package texts;

import java.util.HashMap;
import java.util.Map;

public class ExamTextToBe implements ITexts
{
    /** Значения времени to be, языка Английский */
    private Map<Integer, String> examEnToBe = new HashMap<>();

    /** Значения времени to be, языка Русский */
    private Map<Integer, String> examRuToBe = new HashMap<>();

    @Override
    public Map<Integer, String> getEnglish(){
        getStrEnToBe();
        return examEnToBe;
    }

    /**
     * Функция получения списка значений на Русском языке времени to be
     * @return возвращает значения
     */
    @Override
    public Map<Integer, String> getRussia(){
        getStrRuToBe();
        return examRuToBe;
    }
    /**
     * Функция со значениями на Английском языке времени to be
     * @return возвращает список значений
     */
    private Map<Integer, String> getStrEnToBe(){
        examEnToBe.put(0,"How much is this book?");
        examEnToBe.put(1,"What's there?");
        examEnToBe.put(2,"How is he?");
        examEnToBe.put(3,"He's so clever");
        examEnToBe.put(4,"She's a beautiful girl");
        examEnToBe.put(5,"Are the women at home?");
        examEnToBe.put(6,"When are you busy?");
        examEnToBe.put(7,"Is this method really ineffective?");
        examEnToBe.put(8,"It isn't a difficult rule");
        examEnToBe.put(9,"It isn't boring");
        examEnToBe.put(10,"Is it a good result?");
        examEnToBe.put(11,"He isn't a professional teacher");
        examEnToBe.put(12,"Is it a brilliant result?");
        examEnToBe.put(13,"I have a car. The car is very good");
        examEnToBe.put(14,"How is this exercise?");
        examEnToBe.put(15,"Where is the girl?");
        examEnToBe.put(16,"It's easy");
        examEnToBe.put(17,"What's her name?");
        examEnToBe.put(18,"It's so boring");
        examEnToBe.put(19,"It isn't a very bad situation");
        examEnToBe.put(20,"It's so cheap");
        examEnToBe.put(21,"Is this story so funny?");
        examEnToBe.put(22,"It's the best course");
        examEnToBe.put(23,"He's such a clever person");
        examEnToBe.put(24,"How useful is the lesson?");
        examEnToBe.put(25,"How much is the computer?");
        examEnToBe.put(26,"It isn't his profession");
        examEnToBe.put(27,"How effective are the lessons?");
        examEnToBe.put(28,"It's very easy");
        examEnToBe.put(29,"It's sunny");
        examEnToBe.put(30,"Are they from Spain?");
        examEnToBe.put(31,"It's so difficult");
        examEnToBe.put(32,"Is it expensive?");
        examEnToBe.put(33,"How is she?");
        examEnToBe.put(34,"You're so clever");
        examEnToBe.put(35,"How much is the house?");
        examEnToBe.put(36,"All these videos are very useful");
        examEnToBe.put(37,"I'm not satisfied with this result");
        examEnToBe.put(38,"It's an easy exercise");
        examEnToBe.put(39,"Are you satisfied with their answer?");
        examEnToBe.put(40,"It's a useless lesson");
        examEnToBe.put(41,"It isn't for this level");
        examEnToBe.put(42,"Is it a very simple exercise?");
        examEnToBe.put(43,"Are you sure?");
        examEnToBe.put(44,"It's difficult");
        examEnToBe.put(45,"My memory is bad");
        examEnToBe.put(46,"It's a very ineffective method");
        examEnToBe.put(47,"She isn't free. She's very busy");
        examEnToBe.put(48,"It's cheap");
        examEnToBe.put(49,"Why are these exercises so difficult?");
        examEnToBe.put(50,"How expensive is it?");
        examEnToBe.put(51,"She's very beautiful");
        examEnToBe.put(52,"Is your mother at school?");
        examEnToBe.put(53,"It isn't an easy lesson");
        examEnToBe.put(54,"Is he tired?");
        examEnToBe.put(55,"It's simple");
        examEnToBe.put(56,"Are the videos funny?");
        examEnToBe.put(57,"When is he at work?");
        examEnToBe.put(58,"Is the game interesting?");
        examEnToBe.put(59,"How old are you?");
        examEnToBe.put(60,"Are you really sure?");
        examEnToBe.put(61,"Is it a very important detail?");
        examEnToBe.put(62,"It's easy");
        examEnToBe.put(63,"It's a very low level");
        examEnToBe.put(64,"Where are the children?");
        examEnToBe.put(65,"Why is your boss right?");
        examEnToBe.put(66,"He's such a poor boy");
        examEnToBe.put(67,"They're rich");
        examEnToBe.put(68,"Is he her boss?");
        examEnToBe.put(69,"What's important?");
        examEnToBe.put(70,"Who is she?");
        examEnToBe.put(71,"It's the best playlist");
        examEnToBe.put(72,"It's the best answer");
        examEnToBe.put(73,"Who's in the park?");
        examEnToBe.put(74,"Our manager is very professional");
        examEnToBe.put(75,"Is it cheap?");
        examEnToBe.put(76,"These lessons are really good");
        examEnToBe.put(77,"Are you tired?");
        examEnToBe.put(78,"Is the article in English?");
        examEnToBe.put(79,"It's too expensive");
        examEnToBe.put(80,"I'm so happy");
        examEnToBe.put(81,"How is the channel?");
        examEnToBe.put(82,"Is the computer new?");
        examEnToBe.put(83,"It's better");
        examEnToBe.put(84,"Is it impossible?");
        examEnToBe.put(85,"Is it an excellent result?");
        examEnToBe.put(86,"What's her job?");
        examEnToBe.put(87,"Your help is very important");
        examEnToBe.put(88,"It's so simple");
        examEnToBe.put(89,"Is the airport near?");
        examEnToBe.put(90,"Is this level enough?");
        examEnToBe.put(91,"Is he their client?");
        examEnToBe.put(92,"They aren't pessimistic");
        examEnToBe.put(93,"Is this language difficult?");
        examEnToBe.put(94,"What's the time? What time is it?");
        examEnToBe.put(95,"Am I right?");
        examEnToBe.put(96,"You're right");
        examEnToBe.put(97,"He isn't busy. He's free");
        examEnToBe.put(98,"Is it so effective?");
        examEnToBe.put(99,"All his lessons are free");
        examEnToBe.put(100,"Is his video so fanny?");
        examEnToBe.put(101,"Why is this problem so big?");
        examEnToBe.put(102,"Why are those lessons ineffective?");
        examEnToBe.put(103,"It's a very interesting detail");
        examEnToBe.put(104,"Why is that method ineffective?");
        examEnToBe.put(105,"Are these things so important?");
        examEnToBe.put(106,"It's so easy");
        examEnToBe.put(107,"How old is your sister?");
        examEnToBe.put(108,"Is it only for children?");
        examEnToBe.put(109,"It's so cheap");
        examEnToBe.put(110,"Is he a director?");
        examEnToBe.put(111,"It isn't far");
        examEnToBe.put(112,"It's such a useful video");
        examEnToBe.put(113,"It isn't the best decision for us");
        examEnToBe.put(114,"Is this computer powerful?");
        examEnToBe.put(115,"Are they lazy?");
        examEnToBe.put(116,"This video is very informative");
        examEnToBe.put(117,"It's near");
        examEnToBe.put(118,"It's there");
        examEnToBe.put(119,"It the project so interesting?");
        examEnToBe.put(120,"He's the best teacher in the world");
        examEnToBe.put(121,"It's interesting");
        examEnToBe.put(122,"Is it a good idea?");
        examEnToBe.put(123,"What's your best friend's name?");
        examEnToBe.put(124,"Is this word new for you?");
        examEnToBe.put(125,"It's too cold");
        examEnToBe.put(126,"Is it dangerous?");
        examEnToBe.put(127,"Are these exercises so useful?");
        examEnToBe.put(128,"It's such a cheap thing");
        examEnToBe.put(129,"Is it sunny?");
        examEnToBe.put(130,"What's your boyfriend's name?");
        examEnToBe.put(131,"Is it his own flat?");
        examEnToBe.put(132,"Is your father at work?");
        examEnToBe.put(133,"It's such a simple answer");
        examEnToBe.put(134,"English is easy");
        examEnToBe.put(135,"It's such a boring story");
        examEnToBe.put(136,"Who's that person?");
        examEnToBe.put(137,"How interesting is it?");
        examEnToBe.put(138,"It's a good idea");
        examEnToBe.put(139,"He's a manager");
        examEnToBe.put(140,"What's her father's job?");
        examEnToBe.put(141,"Is this information enough?");
        examEnToBe.put(142,"Is it a big success?");
        examEnToBe.put(143,"How much is this pair of trousers?");
        examEnToBe.put(144,"Is it on the left?");
        examEnToBe.put(145,"All your videos are so interesting");
        examEnToBe.put(146,"Her boyfriend is twenty-two");
        examEnToBe.put(147,"Is it a big problem?");
        examEnToBe.put(148,"How easy is it?");
        examEnToBe.put(149,"It's such an expensive car");
        examEnToBe.put(150,"It's a very good result");
        examEnToBe.put(151,"Is he single?");
        examEnToBe.put(152,"Is it the same?");
        examEnToBe.put(153,"I'm full of ideas");
        examEnToBe.put(154,"Is he talented?");
        examEnToBe.put(155,"Is this test too difficult?");
        examEnToBe.put(156,"Where are our teachers?");
        examEnToBe.put(157,"It isn't so easy");
        examEnToBe.put(158,"It's a very simple method");
        examEnToBe.put(159,"It's very interesting");
        examEnToBe.put(160,"It's an interesting idea");
        examEnToBe.put(161,"The day is hot");
        examEnToBe.put(162,"I'm not at home");
        examEnToBe.put(163,"I'm at work");
        examEnToBe.put(164,"Who's here?");
        examEnToBe.put(165,"Is this test too easy?");
        examEnToBe.put(166,"Is he a rich man?");
        examEnToBe.put(167,"He's a good manager");
        examEnToBe.put(168,"Is this song very popular?");
        examEnToBe.put(169,"This woman isn't so wise");
        examEnToBe.put(170,"Is the game boring?");
        examEnToBe.put(171,"Am I talented?");
        examEnToBe.put(172,"What's your girlfriend's name?");
        examEnToBe.put(173,"How is it?");
        examEnToBe.put(174,"How is her dress?");
        examEnToBe.put(175,"It's such an effective method");
        examEnToBe.put(176,"My friend is sure");
        examEnToBe.put(177,"It isn't such a bad situation");
        examEnToBe.put(178,"It isn't so bad");
        examEnToBe.put(179,"Is her boyfriend?");
        examEnToBe.put(180,"Where is she?");
        examEnToBe.put(181,"Why are the students there?");
        examEnToBe.put(182,"I'm not satisfied with these results at all");
        examEnToBe.put(183,"He's a very professional teacher");
        examEnToBe.put(184,"The students are ready");
        examEnToBe.put(185,"He's a very poor person");
        examEnToBe.put(186,"He isn't in America");
        examEnToBe.put(187,"Is it an important detail?");
        examEnToBe.put(188,"It's a very small mistake");
        examEnToBe.put(189,"Who are these people?");
        examEnToBe.put(190,"It's so interesting");
        examEnToBe.put(191,"Is the problem big?");
        examEnToBe.put(192,"It's such an effective lesson");
        examEnToBe.put(193,"Are the boys at school?");
        examEnToBe.put(194,"It's on the left");
        examEnToBe.put(195,"She's such a kind woman");
        examEnToBe.put(196,"It isn't late now");
        examEnToBe.put(197,"It's so difficult");
        examEnToBe.put(198,"It's a small mistake");
        examEnToBe.put(199,"They aren't successful");
        examEnToBe.put(200,"Is it her own house?");
        examEnToBe.put(201,"How are these exercises?");
        examEnToBe.put(202,"His father is very rich");
        examEnToBe.put(203,"I'm not a manager. I'm a teacher");
        examEnToBe.put(204,"His girlfriend is nineteen");
        examEnToBe.put(205,"Is the idea interesting?");
        examEnToBe.put(206,"The men are here");
        examEnToBe.put(207,"Are we hard-working?");
        examEnToBe.put(208,"Her boyfriend is twenty-four");
        examEnToBe.put(209,"Is the teacher right?");
        examEnToBe.put(210,"These men are managers");
        examEnToBe.put(211,"How much is it?");
        examEnToBe.put(212,"How useful is it?");
        examEnToBe.put(213,"Are your friends online?");
        examEnToBe.put(214,"It's a very important thing");
        examEnToBe.put(215,"Is she his girlfriend?");
        examEnToBe.put(216,"How much is this computer?");
        examEnToBe.put(217,"How difficult is it?");
        examEnToBe.put(218,"The girl is very hard-working");
        examEnToBe.put(219,"Why is that method so ineffective?");
        examEnToBe.put(220,"He isn't my colleague");
        examEnToBe.put(221,"Who is at home?");
        examEnToBe.put(222,"She's so kind");
        examEnToBe.put(223,"He's very rich");
        examEnToBe.put(224,"Is the idea brilliant?");
        examEnToBe.put(225,"It's a very bad method");
        examEnToBe.put(226,"How is this playlist?");
        examEnToBe.put(227,"Her level is very low");
        examEnToBe.put(228,"How is this result?");
        examEnToBe.put(229,"It's so difficult");
        examEnToBe.put(230,"You're a good teacher");
        examEnToBe.put(231,"He's a very strange person");
        examEnToBe.put(232,"What's in your pocket?");
        examEnToBe.put(233,"Is his decision right?");
        examEnToBe.put(234,"How old is your mother?");
        examEnToBe.put(235,"How interesting is the magazine?");
        examEnToBe.put(236,"His wife is thirty-seven");
        examEnToBe.put(237,"That woman is a designer");
        examEnToBe.put(238,"How much is the dress?");
        examEnToBe.put(239,"It's rainy");
        examEnToBe.put(240,"His son is in the zoo");
        examEnToBe.put(241,"It's a very important detail");
        examEnToBe.put(242,"Are you together?");
        examEnToBe.put(243,"It's very boring");
        examEnToBe.put(244,"This thing is very important");
        examEnToBe.put(245,"What's really useful?");
        examEnToBe.put(246,"Why is it useless?");
        examEnToBe.put(247,"It's so easy");
        examEnToBe.put(248,"It isn't the best course");
        examEnToBe.put(249,"It's an expensive car");
        examEnToBe.put(250,"We aren't colleagues");
        examEnToBe.put(251,"We aren't tired at all");
        examEnToBe.put(252,"My brother is sixteen");
        examEnToBe.put(253,"Are the computers new?");
        examEnToBe.put(254,"It's a very bad decision");
        examEnToBe.put(255,"How are you?");
        examEnToBe.put(256,"It isn't on the left");
        examEnToBe.put(257,"What's here?");
        examEnToBe.put(258,"The company is very rich");
        examEnToBe.put(259,"Are we in the first place?");
        examEnToBe.put(260,"Why are her lessons so ineffective?");
        examEnToBe.put(261,"It's obvious");
        examEnToBe.put(262,"They aren't my colleagues");
        examEnToBe.put(263,"Is he the best student?");
        examEnToBe.put(264,"Why is he angry?");
        examEnToBe.put(265,"Is it a boring magazine?");
        examEnToBe.put(266,"Are we in the wrong place?");
        examEnToBe.put(267,"My boss is very busy now");
        examEnToBe.put(268,"It isn't warm. It's cold");
        examEnToBe.put(269,"My mother is at work");
        examEnToBe.put(270,"She's on holiday");
        examEnToBe.put(271,"Who is wrong?");
        examEnToBe.put(272,"It's worse");
        examEnToBe.put(273,"It's an informative lesson");
        examEnToBe.put(274,"Is cold here?");
        examEnToBe.put(275,"He's a professional teacher");
        examEnToBe.put(276,"It isn't rainy. It's sunny");
        examEnToBe.put(277,"Their idea is very interesting");
        examEnToBe.put(278,"It's such a difficult exam");
        examEnToBe.put(279,"Is that thing really important?");
        examEnToBe.put(280,"It's a cold day");
        examEnToBe.put(281,"Is this thing really so important?");
        examEnToBe.put(282,"The day is rainy");
        examEnToBe.put(283,"It isn't on the right");
        examEnToBe.put(284,"It isn't a very big mistake");
        examEnToBe.put(285,"He isn't poor. He's very rich");
        examEnToBe.put(286,"He's on a business trip");
        examEnToBe.put(287,"Are you satisfied with your result?");
        examEnToBe.put(288,"It's so important");
        examEnToBe.put(289,"She's with us now");
        examEnToBe.put(290,"Is your mother a designer?");
        examEnToBe.put(291,"Is the book so interesting?");
        examEnToBe.put(292,"Is it his point of view?");
        examEnToBe.put(293,"He's so smart");
        examEnToBe.put(294,"She's sure");
        examEnToBe.put(295,"It's very important");
        examEnToBe.put(296,"She's very poor");
        examEnToBe.put(297,"It's a very boring book");
        examEnToBe.put(298,"It's so bad");
        examEnToBe.put(299,"He's a young man");
        examEnToBe.put(300,"It's an important detail");
        examEnToBe.put(301,"He's such a talented boy");
        examEnToBe.put(302,"I'm not a student. I work");
        examEnToBe.put(303,"She's such a beautiful girl");
        examEnToBe.put(304,"It's so ineffective");
        examEnToBe.put(305,"It's interesting");
        examEnToBe.put(306,"How is the party?");
        examEnToBe.put(307,"It's a very important thing");
        examEnToBe.put(308,"Are they far?");
        examEnToBe.put(309,"His parents are near");
        examEnToBe.put(310,"It's bad");
        examEnToBe.put(311,"It's an important thing");
        examEnToBe.put(312,"It isn't so");
        examEnToBe.put(313,"What's your girlfriend's name?");
        examEnToBe.put(314,"Are the lessons really useful?");
        examEnToBe.put(315,"Is the food good?");
        examEnToBe.put(316,"Is the university famous?");
        examEnToBe.put(317,"Is the article about politics?");
        examEnToBe.put(318,"It isn't a very low level");
        examEnToBe.put(319,"It's so far");
        examEnToBe.put(320,"What's your brother's name?");
        examEnToBe.put(321,"Is his father a businessman?");
        examEnToBe.put(322,"Are these words new for you?");
        examEnToBe.put(323,"They're my friends");
        examEnToBe.put(324,"Is it in your own flat?");
        examEnToBe.put(325,"It's the best channel");
        examEnToBe.put(326,"How effective is the lesson?");
        examEnToBe.put(327,"It's an easy lesson");
        examEnToBe.put(328,"It's a warm day");
        examEnToBe.put(329,"Is he a successful businessman?");
        examEnToBe.put(330,"Where is it?");
        examEnToBe.put(331,"How good is the lesson?");
        examEnToBe.put(332,"How is the movie?");
        examEnToBe.put(333,"Is it for children?");
        examEnToBe.put(334,"Are the problems so big?");
        examEnToBe.put(335,"It's a simple test");
        examEnToBe.put(336,"It's too hot");
        examEnToBe.put(337,"She's a teacher");
        examEnToBe.put(338,"They're lazy");
        examEnToBe.put(339,"The rule is very important");
        examEnToBe.put(340,"She isn't with him. She's with her");
        examEnToBe.put(341,"Those lessons aren't effective");
        examEnToBe.put(342,"How difficult is the test?");
        examEnToBe.put(343,"He's at school");
        examEnToBe.put(344,"Is it an effective method?");
        examEnToBe.put(345,"How much is this book?");
        examEnToBe.put(346,"She's a very beautiful girl");
        examEnToBe.put(347,"They aren't businessmen");
        examEnToBe.put(348,"They're managers");
        examEnToBe.put(349,"How old is he?");
        examEnToBe.put(350,"The day is windy");
        examEnToBe.put(351,"I'm happy");
        examEnToBe.put(352,"Where is the boy?");
        examEnToBe.put(353,"She's so beautiful");
        examEnToBe.put(354,"Money is important");
        examEnToBe.put(355,"Are those exercises useless?");
        examEnToBe.put(356,"How much is this pair of jeans?");
        examEnToBe.put(357,"I'm not tired");
        examEnToBe.put(358,"It's so cold");
        examEnToBe.put(359,"Is she a poor woman?");
        examEnToBe.put(360,"This method is very simple");
        examEnToBe.put(361,"Where is our teacher?");
        examEnToBe.put(362,"It's too easy");
        examEnToBe.put(363,"When is she at home?");
        examEnToBe.put(364,"Is the boy at home?");
        examEnToBe.put(365,"Are you there?");
        examEnToBe.put(366,"What is it?");
        examEnToBe.put(367,"Is this text simple?");
        examEnToBe.put(368,"Is the hotel expensive?");
        examEnToBe.put(369,"Is it worse?");
        examEnToBe.put(370,"It's such an important meeting");
        examEnToBe.put(371,"I'm sure you're the best teacher in the world");
        examEnToBe.put(372,"Why are you so happy?");
        examEnToBe.put(373,"Is the book boring?");
        examEnToBe.put(374,"Is it the best channel?");
        examEnToBe.put(375,"It's such an interesting question");
        examEnToBe.put(376,"Is the lesson useful?");
        examEnToBe.put(377,"What's your wife's job?");
        examEnToBe.put(378,"We're in the park");
        examEnToBe.put(379,"Who's there?");
        examEnToBe.put(380,"He isn't with them");
        examEnToBe.put(381,"It's so easy");
        examEnToBe.put(382,"It isn't a high level");
        examEnToBe.put(383,"Is his mother a doctor?");
        examEnToBe.put(384,"Is he a lazy boy?");
        examEnToBe.put(385,"Who's that man?");
        examEnToBe.put(386,"It isn't in the first place for me");
        examEnToBe.put(387,"I'm free");
        examEnToBe.put(388,"Who is in the room?");
        examEnToBe.put(389,"You're a happy person");
        examEnToBe.put(390,"Is this university famous?");
        examEnToBe.put(391,"Is it a powerful computer?");
        examEnToBe.put(392,"We aren't sad. We're happy");
        examEnToBe.put(393,"Where is your husband?");
        examEnToBe.put(394,"Who's next?");
        examEnToBe.put(395,"How difficult are these exercises?");
        examEnToBe.put(396,"It's a very expansive thing");
        examEnToBe.put(397,"Is he right?");
        examEnToBe.put(398,"I'm thirty-one. And you?");
        examEnToBe.put(399,"It's a very useful thing");
        examEnToBe.put(400, "Is he really hard-working?");
        examEnToBe.put(401, "It isn't a very good decision");
        examEnToBe.put(402, "Is knowledge power?");
        examEnToBe.put(403, "Where are you?");
        examEnToBe.put(404, "Are his parents abroad?");
        examEnToBe.put(405, "What's your name?");
        examEnToBe.put(406, "What's in your bag?");
        examEnToBe.put(407, "It's a very interesting offer?");
        examEnToBe.put(408, "We aren't stupid. We're clever");
        examEnToBe.put(409, "What's your sister's name?");
        examEnToBe.put(410, "This student is so hard-working");
        examEnToBe.put(411, "It's an expensive thing");
        examEnToBe.put(412, "It's good");
        examEnToBe.put(413, "I'm so tired");
        examEnToBe.put(414, "Are the computers old?");
        examEnToBe.put(415, "You're right");
        examEnToBe.put(416, "The test is easy");
        examEnToBe.put(417, "All these exercises are so easy");
        examEnToBe.put(418, "Is it a funny video?");
        examEnToBe.put(419, "How expensive is this house?");
        examEnToBe.put(420, "Is it sich a big problem?");
        examEnToBe.put(421, "Why are you against it?");
        examEnToBe.put(422, "Is the information useful?");
        examEnToBe.put(423, "He's her hasband");
        examEnToBe.put(424, "Where is your wife?");
        examEnToBe.put(425, "It's a hot day");
        examEnToBe.put(426, "He's a student");
        examEnToBe.put(427, "It isn't better");
        examEnToBe.put(428, "It's so popular");
        examEnToBe.put(429, "It isn't so obvious");
        examEnToBe.put(430, "Is the channel really good?");
        examEnToBe.put(431, "Is the cat in that room?");
        examEnToBe.put(432, "She's here");
        examEnToBe.put(433, "She's a very beautiful girl");
        examEnToBe.put(434, "His result isn't so bad");
        examEnToBe.put(435, "What's your husband's job?");
        examEnToBe.put(436, "It's bad");
        examEnToBe.put(437, "It's a very useful lesson");
        examEnToBe.put(438, "He's a very poor person");
        examEnToBe.put(439, "You aren't in this place");
        examEnToBe.put(440, "The question is simple");
        examEnToBe.put(441, "I'm not tired at all");
        examEnToBe.put(442, "He isn't a director. He's a manager");
        examEnToBe.put(443, "It's dark");
        examEnToBe.put(444, "He's my friend");
        examEnToBe.put(445, "How old is your brother?");
        examEnToBe.put(446, "The woman is very poor");
        examEnToBe.put(447, "Is our teacher right?");
        examEnToBe.put(448, "Is it on the right?");
        examEnToBe.put(449, "She isn't in the kitchen");
        examEnToBe.put(450, "Is this business profitable?");
        examEnToBe.put(451, "How effective are the lessons?");
        examEnToBe.put(452, "What's wrong?");
        examEnToBe.put(453, "Where is your car?");
        examEnToBe.put(454, "His level is very high");
        examEnToBe.put(455, "Is she beautiful?");
        examEnToBe.put(456, "My friend is at home");
        examEnToBe.put(457, "The song is very popular");
        examEnToBe.put(458, "Where is this place?");
        examEnToBe.put(459, "Why are you here?");
        examEnToBe.put(460, "What's your best friend's name?");
        examEnToBe.put(461, "You aren't in the first place. You're in the second place");
        examEnToBe.put(462, "Are you ready?");
        examEnToBe.put(463, "You're a very happy person");
        examEnToBe.put(464, "My brother is in the bathroom");
        examEnToBe.put(465, "It's an interesting idea");
        examEnToBe.put(466, "This lesson is very useful");
        examEnToBe.put(467, "I'm thirty-two");
        examEnToBe.put(468, "It's such a big problem");
        examEnToBe.put(469, "Those women are teachers");
        examEnToBe.put(470, "Is this knowledge enough?");
        examEnToBe.put(471, "Are the problems big?");
        examEnToBe.put(472, "What time is it? What's the time?");
        examEnToBe.put(473, "How effective is the lesson?");
        examEnToBe.put(474, "He's such a clever boy");
        examEnToBe.put(475, "Your videos are very informative");
        examEnToBe.put(476, "The boy is at school");
        examEnToBe.put(477, "What's your brother's name?");
        examEnToBe.put(478, "They're our friends");
        examEnToBe.put(479, "They aren't in Russia now");
        examEnToBe.put(480, "Is she married?");
        examEnToBe.put(481, "Is it a very useful video?");
        examEnToBe.put(482, "How interesting is this magazine?");
        examEnToBe.put(483, "It's hot");
        examEnToBe.put(484, "Is it effective?");
        examEnToBe.put(485, "Is the news important?");
        examEnToBe.put(486, "The channel is really good");
        examEnToBe.put(487, "Why are these exercises so difficult?");
        examEnToBe.put(488, "It's such a difficult situation");
        examEnToBe.put(489, "We aren't tired but I think you're tired");
        examEnToBe.put(490, "The lesson is interesting");
        examEnToBe.put(491, "These things are very important");
        examEnToBe.put(492, "Is his computer new?");
        examEnToBe.put(493, "Is it a very big problem?");
        examEnToBe.put(494, "It isn't a big mistake");
        examEnToBe.put(495, "When are you free?");
        examEnToBe.put(496, "Is he married?");
        examEnToBe.put(497, "It's a brilliant result");
        examEnToBe.put(498, "It's such an intersrting place");
        examEnToBe.put(499, "It's a big mistake");
        examEnToBe.put(500, "What's your fried's name?");
        examEnToBe.put(501, "How difficult is this exercises?");
        examEnToBe.put(502, "She's very optimistic");
        examEnToBe.put(503, "I'm at school");
        examEnToBe.put(504, "You aren't right");
        examEnToBe.put(505, "He's sure");
        examEnToBe.put(506, "She's my girlfriend");
        examEnToBe.put(507, "My girlfriend is twenty-one");
        examEnToBe.put(508, "Is the channel very popular?");
        examEnToBe.put(509, "It's a simple method");
        examEnToBe.put(510, "Your results are excellent");
        examEnToBe.put(511, "These problems are small");
        examEnToBe.put(512, "Is it a special offer?");
        examEnToBe.put(513, "The article isn't about politics");
        examEnToBe.put(514, "It's so easy");
        examEnToBe.put(515, "Am I lucky?");
        examEnToBe.put(516, "She isn't with us");
        examEnToBe.put(517, "They're at work");
        examEnToBe.put(518, "It's such a bad situation");
        examEnToBe.put(519, "Are you in the United States?");
        examEnToBe.put(520, "She isn't here. She's there");
        examEnToBe.put(521, "It's a good manner");
        examEnToBe.put(522, "Are we right?");
        examEnToBe.put(523, "What's he job?");
        examEnToBe.put(524, "My parents are so happy");
        examEnToBe.put(525, "Who is in the first place?");
        examEnToBe.put(526, "It isn't such an important meeting");
        examEnToBe.put(527, "Is their father a businessman?");
        examEnToBe.put(528, "Is he abroad?");
        examEnToBe.put(529, "Is this test so simple?");
        examEnToBe.put(530, "My brother is ready");
        examEnToBe.put(531, "Is it his point of view");
        examEnToBe.put(532, "Is this information really useful?");
        examEnToBe.put(533, "Is this rule impotant?");
        examEnToBe.put(534, "She's too pessimistic");
        examEnToBe.put(535, "Is that decision worse?");
        examEnToBe.put(536, "He's so talented");
        examEnToBe.put(537, "It's such an easy exercise");
        examEnToBe.put(538, "All these details are very important");
        examEnToBe.put(539, "What's next?");
        examEnToBe.put(540, "It's so effective");
        examEnToBe.put(541, "He isn't so hard-working");
        examEnToBe.put(542, "The women are there");
        examEnToBe.put(543, "Is she tired?");
        examEnToBe.put(544, "Time is money");
        examEnToBe.put(545, "It's very easy");
        examEnToBe.put(546, "We aren't angry. We're very kind");
        examEnToBe.put(547, "Is time money?");
        examEnToBe.put(548, "I'm at work");
        examEnToBe.put(549, "You're very kind");
        examEnToBe.put(550, "I'm not married. I'm single");
        examEnToBe.put(551, "It's a very good decision");
        examEnToBe.put(552, "Is it obvious?");
        examEnToBe.put(553, "Is it a famous university?");
        examEnToBe.put(554, "They're poor");
        examEnToBe.put(555, "The day is sunny");
        examEnToBe.put(556, "Her daughter is in the park");
        examEnToBe.put(557, "It's the best example");
        examEnToBe.put(558, "This problem is very big");
        examEnToBe.put(559, "The boys are at home");
        examEnToBe.put(560, "Who is he?");
        examEnToBe.put(561, "Where is your room?");
        examEnToBe.put(562, "The boy is very clever");
        examEnToBe.put(563, "His parents are abroad now");
        examEnToBe.put(564, "Is it such an ineffective method?");
        examEnToBe.put(565, "Who is that woman?");
        examEnToBe.put(566, "She isn't a singer. She's an actress");
        examEnToBe.put(567, "What's your mother's job?");
        examEnToBe.put(568, "It's the best book");
        examEnToBe.put(569, "You aren't optimistic");
        examEnToBe.put(570, "These words are new for me");
        examEnToBe.put(571, "Where is this place?");
        examEnToBe.put(572, "Am I in the right place?");
        examEnToBe.put(573, "Chinese is very difficult");
        examEnToBe.put(574, "Is your brother at home?");
        examEnToBe.put(575, "Are you really tired?");
        examEnToBe.put(576, "Is this news important?");
        examEnToBe.put(577, "How much is this car?");
        examEnToBe.put(578, "It isn't a high level. This level is low");
        examEnToBe.put(579, "How much is one English lesson?");
        examEnToBe.put(580, "It's a very easy lesson");
        examEnToBe.put(581, "The exam is difficult");
        examEnToBe.put(582, "He's my boyfriend");
        examEnToBe.put(583, "All these lessons are free");
        examEnToBe.put(584, "She's beautiful");
        examEnToBe.put(585, "He isn't sure");
        examEnToBe.put(586, "Her mother is in the kitchen");
        examEnToBe.put(587, "What's your sister's name?");
        examEnToBe.put(588, "What's her name?");
        examEnToBe.put(589, "Is this lesson useful for you? It's very useful");
        examEnToBe.put(590, "How is this test?");
        examEnToBe.put(591, "We're full of optimism");
        examEnToBe.put(592, "I'm not satisfied with this decision");
        examEnToBe.put(593, "Is he young?");
        examEnToBe.put(594, "He's a businessman");
        examEnToBe.put(595, "Is your girlfriend nineteen?");
        examEnToBe.put(596, "It's a very interesting idea");
        examEnToBe.put(597, "Hoe old is his son?");
        examEnToBe.put(598, "You're the best teacher in the world");
        examEnToBe.put(599, "She's such a wise woman");

        return examEnToBe;
    }

    /**
     * Функция со значениями на Русском языке времени to be
     * @return возвращает список значений
     */
    private Map<Integer, String> getStrRuToBe(){
        examRuToBe.put(0,"Сколько стоит эта книга?");
        examRuToBe.put(1,"Что там?");
        examRuToBe.put(2,"Как он?");
        examRuToBe.put(3,"Он такой умный");
        examRuToBe.put(4,"Она красивая девушка");
        examRuToBe.put(5,"Женщины дома?");
        examRuToBe.put(6,"Когда ты занят?");
        examRuToBe.put(7,"Этот метод действительно не эффективен?");
        examRuToBe.put(8,"Это не сложное правило");
        examRuToBe.put(9,"Это не скучно");
        examRuToBe.put(10,"Это хороший результат?");
        examRuToBe.put(11,"Он не профессиональный учитель");
        examRuToBe.put(12,"Это блестящий результат?");
        examRuToBe.put(13,"У меня есть машина. Машина очень хорошая");
        examRuToBe.put(14,"Как тебе это упражнение?");
        examRuToBe.put(15,"Где девочка?");
        examRuToBe.put(16,"Это легко");
        examRuToBe.put(17,"Как её зовут?");
        examRuToBe.put(18,"Это так скучно");
        examRuToBe.put(19,"Это не очень плохая ситуация");
        examRuToBe.put(20,"Это так дёшево");
        examRuToBe.put(21,"Эта история такая забавная?");
        examRuToBe.put(22,"Это лучший курс");
        examRuToBe.put(23,"Он такой умный человек");
        examRuToBe.put(24,"На сколько полезный урок?");
        examRuToBe.put(25,"Сколько стоит компьютер?");
        examRuToBe.put(26,"Это не его профессия");
        examRuToBe.put(27,"На сколько эффективные уроки?");
        examRuToBe.put(28,"Это очень легко");
        examRuToBe.put(29,"Солнечно");
        examRuToBe.put(30,"Они из Испании?");
        examRuToBe.put(31,"Это так сложно");
        examRuToBe.put(32,"Это дорого?");
        examRuToBe.put(33,"Как она?");
        examRuToBe.put(34,"Ты такой умный");
        examRuToBe.put(35,"Сколько стоит дом?");
        examRuToBe.put(36,"Все эти видео очень полезные");
        examRuToBe.put(37,"Я не удовлетворен этим результатом");
        examRuToBe.put(38,"Это лёгкое упражнение");
        examRuToBe.put(39,"Ты удовлетворен их ответом?");
        examRuToBe.put(40,"Это бесполезный урок");
        examRuToBe.put(41,"Это не для этого уровня");
        examRuToBe.put(42,"Это очень простое упражнение?");
        examRuToBe.put(43,"Ты уверен?");
        examRuToBe.put(44,"Это сложно");
        examRuToBe.put(45,"Моя память плохая");
        examRuToBe.put(46,"Это очень не эффективный метод");
        examRuToBe.put(47,"Она не свободна. Она очень занята");
        examRuToBe.put(48,"Это дёшево");
        examRuToBe.put(49,"Почему эти упражнения такие сложные?");
        examRuToBe.put(50,"На сколько это дорого?");
        examRuToBe.put(51,"Она очень красивая");
        examRuToBe.put(52,"Твоя мама в школе?");
        examRuToBe.put(53,"Это не легкий урок");
        examRuToBe.put(54,"Он устал?");
        examRuToBe.put(55,"Это просто");
        examRuToBe.put(56,"Видео смешные?");
        examRuToBe.put(57,"Когда он на работе?");
        examRuToBe.put(58,"Игра интересная?");
        examRuToBe.put(59,"Сколько тебе лет?");
        examRuToBe.put(60,"Ты действительно уверен?");
        examRuToBe.put(61,"Это очень важная деталь?");
        examRuToBe.put(62,"Это легко");
        examRuToBe.put(63,"Это очень низкий уровень");
        examRuToBe.put(64,"Где дети?");
        examRuToBe.put(65,"Почему твой босс прав?");
        examRuToBe.put(66,"Он такой бедный мальчик");
        examRuToBe.put(67,"Они богатые");
        examRuToBe.put(68,"Он её босс?");
        examRuToBe.put(69,"Что важно?");
        examRuToBe.put(70,"Кто она?");
        examRuToBe.put(71,"Это лучший плэйлист");
        examRuToBe.put(72,"Это лучший ответ");
        examRuToBe.put(73,"Кто в парке?");
        examRuToBe.put(74,"Наш менеджер очень профессиональный");
        examRuToBe.put(75,"Это дёшево?");
        examRuToBe.put(76,"Эти уроки действительно хорошие");
        examRuToBe.put(77,"Ты устал?");
        examRuToBe.put(78,"Статья на Английском?");
        examRuToBe.put(79,"Это слишком дорого");
        examRuToBe.put(80,"Я так счастлив");
        examRuToBe.put(81,"Как этот канал?");
        examRuToBe.put(82,"Компьютер новый?");
        examRuToBe.put(83,"Это лучше");
        examRuToBe.put(84,"Это не возможно?");
        examRuToBe.put(85,"Это отличный результат?");
        examRuToBe.put(86,"Кем она работает?");
        examRuToBe.put(87,"Твоя помощь очень важна");
        examRuToBe.put(88,"Это так просто");
        examRuToBe.put(89,"Аэропорт рядом?");
        examRuToBe.put(90,"Этого уровня достаточно?");
        examRuToBe.put(91,"Он их клиент?");
        examRuToBe.put(92,"Они не песиместичны");
        examRuToBe.put(93,"Этот язык сложный?");
        examRuToBe.put(94,"Сколько времени? (коротко) Сколько времени? (длинно)");
        examRuToBe.put(95,"Я прав?");
        examRuToBe.put(96,"Ты прав");
        examRuToBe.put(97,"Он не занят. Он свободен");
        examRuToBe.put(98,"Это так эффективно?");
        examRuToBe.put(99,"Все его уроки бесплатные");
        examRuToBe.put(100,"Его видео такое смешное?");
        examRuToBe.put(101,"Почему эта проблема такая большая?");
        examRuToBe.put(102,"Почему те уроки не эффективные?");
        examRuToBe.put(103,"Это очень интересная деталь");
        examRuToBe.put(104,"Почему тот метод не эффективный?");
        examRuToBe.put(105,"Эти вещи такие важные?");
        examRuToBe.put(106,"Это так легко");
        examRuToBe.put(107,"Сколько лет твоей сестре?");
        examRuToBe.put(108,"Это только для детей?");
        examRuToBe.put(109,"Это так дешево");
        examRuToBe.put(110,"Он директор?");
        examRuToBe.put(111,"Это не далеко");
        examRuToBe.put(112,"Это такое полезное видео");
        examRuToBe.put(113,"Это не лучшее решение для нас");
        examRuToBe.put(114,"Этот компьютер мощьный?");
        examRuToBe.put(115,"Они ленивые?");
        examRuToBe.put(116,"Это видео очень информативное");
        examRuToBe.put(117,"Это близко");
        examRuToBe.put(118,"Это там");
        examRuToBe.put(119,"Проект такой интересный?");
        examRuToBe.put(120,"Он лучший учитель в мире");
        examRuToBe.put(121,"Это интересно");
        examRuToBe.put(122,"Это хорошая идея?");
        examRuToBe.put(123,"Как зовут твоего лучшего друга?");
        examRuToBe.put(124,"Это слово новое для тебя?");
        examRuToBe.put(125,"Слишком холодно");
        examRuToBe.put(126,"Это опасно?");
        examRuToBe.put(127,"Эти упражнения такие полезные?");
        examRuToBe.put(128,"Это такая дешевая вещь");
        examRuToBe.put(129,"Солнечно?");
        examRuToBe.put(130,"Как зовут твоего парня?");
        examRuToBe.put(131,"Это его собственная квартира?");
        examRuToBe.put(132,"Твой отец на работе?");
        examRuToBe.put(133,"Это такой простой ответ");
        examRuToBe.put(134,"Английский легкий");
        examRuToBe.put(135,"Это такая скучная история");
        examRuToBe.put(136,"Кто тот человек?");
        examRuToBe.put(137,"На сколько интересно это?");
        examRuToBe.put(138,"Это хорошая идея");
        examRuToBe.put(139,"Он менеджер");
        examRuToBe.put(140,"Кем работает её отец?");
        examRuToBe.put(141,"Этой информации достаточно?");
        examRuToBe.put(142,"Это большой успех?");
        examRuToBe.put(143,"Сколько стоит пара брюк?");
        examRuToBe.put(144,"Это слева?");
        examRuToBe.put(145,"Все твои видео такие интересные");
        examRuToBe.put(146,"Её парню двадцать два");
        examRuToBe.put(147,"Это большая проблема?");
        examRuToBe.put(148,"На сколько это легко?");
        examRuToBe.put(149,"Это такая дорогая машина");
        examRuToBe.put(150,"Это очень хороший результат");
        examRuToBe.put(151,"Он холост?");
        examRuToBe.put(152,"Это тоже самое?");
        examRuToBe.put(153,"Я полон идей");
        examRuToBe.put(154,"Он талантлив?");
        examRuToBe.put(155,"Этот тест слишком сложный?");
        examRuToBe.put(156,"Где наши учителя?");
        examRuToBe.put(157,"Это не так легко");
        examRuToBe.put(158,"Это очень простой метод");
        examRuToBe.put(159,"Это очень интересно");
        examRuToBe.put(160,"Это интересная идея");
        examRuToBe.put(161,"День жаркий");
        examRuToBe.put(162,"Я не дома");
        examRuToBe.put(163,"Я на работе");
        examRuToBe.put(164,"Кто здесь?");
        examRuToBe.put(165,"Этот тест слишком легкий?");
        examRuToBe.put(166,"Он богатый мужчина?");
        examRuToBe.put(167,"Он хороший менеджер");
        examRuToBe.put(168,"Эта песня очень популярная?");
        examRuToBe.put(169,"Эта женщина не такая мудрая");
        examRuToBe.put(170,"Игра скучная?");
        examRuToBe.put(171,"Я талантливый?");
        examRuToBe.put(172,"Как зовут твою девушку?");
        examRuToBe.put(173,"Как тебе это?");
        examRuToBe.put(174,"Как тебе её платье?");
        examRuToBe.put(175,"Это такой эффективный метод");
        examRuToBe.put(176,"Мой друг уверен");
        examRuToBe.put(177,"Это не такая плохая ситуация");
        examRuToBe.put(178,"Это не так плохо");
        examRuToBe.put(179,"Он её парень?");
        examRuToBe.put(180,"Где она?");
        examRuToBe.put(181,"Почему студенты там?");
        examRuToBe.put(182,"Я вовсе не удовлетворён этими результатами");
        examRuToBe.put(183,"Он очень профессиональный учитель");
        examRuToBe.put(184,"Студенты готовы");
        examRuToBe.put(185,"Он очень бедный человек");
        examRuToBe.put(186,"Он не в Америке");
        examRuToBe.put(187,"Это важная деталь?");
        examRuToBe.put(188,"Это очень маленькая ошибка");
        examRuToBe.put(189,"Кто эти люди?");
        examRuToBe.put(190,"Это так интересно");
        examRuToBe.put(191,"Проблема большая?");
        examRuToBe.put(192,"Это такой эффективный урок");
        examRuToBe.put(193,"Мальчики в школе?");
        examRuToBe.put(194,"Это слева");
        examRuToBe.put(195,"Она такая добрая женщина");
        examRuToBe.put(196,"Не поздно сейчас");
        examRuToBe.put(197,"Это так сложно");
        examRuToBe.put(198,"Это маленькая ошибка");
        examRuToBe.put(199,"Они не успешны");
        examRuToBe.put(200,"Это её собственный дом?");
        examRuToBe.put(201,"Как тебе эти упражнения?");
        examRuToBe.put(202,"Его отец очень богат");
        examRuToBe.put(203,"Я не менеджер. Я учитель");
        examRuToBe.put(204,"Его девушке 19");
        examRuToBe.put(205,"Идея интересная?");
        examRuToBe.put(206,"Мужчины здесь");
        examRuToBe.put(207,"Мы трудолюбивые?");
        examRuToBe.put(208,"Её парню 24");
        examRuToBe.put(209,"Учитель прав?");
        examRuToBe.put(210,"Эти мужчины менеджеры");
        examRuToBe.put(211,"Сколько это (стоит)?");
        examRuToBe.put(212,"На сколько это полезно?");
        examRuToBe.put(213,"Твои друзья онлайн?");
        examRuToBe.put(214,"Это очень важная вещь");
        examRuToBe.put(215,"Она его девушка?");
        examRuToBe.put(216,"Сколько (стоит) этот компьютер?");
        examRuToBe.put(217,"На сколько это сложно?");
        examRuToBe.put(218,"Девочка очень трудолюбивая");
        examRuToBe.put(219,"Почему тот метод такой не эффективный?");
        examRuToBe.put(220,"Он не мой коллега");
        examRuToBe.put(221,"Кто дома?");
        examRuToBe.put(222,"Она такая добрая");
        examRuToBe.put(223,"Он очень богатый");
        examRuToBe.put(224,"Идея блестящая?");
        examRuToBe.put(225,"Это очень плохой метод");
        examRuToBe.put(226,"Как тебе плейлист?");
        examRuToBe.put(227,"Её уровень очень низкий");
        examRuToBe.put(228,"Как (тебе) этот результат?");
        examRuToBe.put(229,"Это так сложно");
        examRuToBe.put(230,"Ты хороший учитель");
        examRuToBe.put(231,"Он очень странный человек");
        examRuToBe.put(232,"Что в твоем кормане?");
        examRuToBe.put(233,"Его решение верное?");
        examRuToBe.put(234,"Сколько лет твоей маме?");
        examRuToBe.put(235,"На сколько интересный журнал?");
        examRuToBe.put(236,"Его жене 37");
        examRuToBe.put(237,"Та женщина дизайнер");
        examRuToBe.put(238,"Сколько (стоит) платье?");
        examRuToBe.put(239,"Дождливо");
        examRuToBe.put(240,"Его сын в зоопарке");
        examRuToBe.put(241,"Это очень важная деталь");
        examRuToBe.put(242,"Вы вместе?");
        examRuToBe.put(243,"Это очень скучно");
        examRuToBe.put(244,"Эта вещь очень важная");
        examRuToBe.put(245,"Что действительно полезно?");
        examRuToBe.put(246,"Почему это безполезно?");
        examRuToBe.put(247,"Это так легко");
        examRuToBe.put(248,"Это не лучший курс");
        examRuToBe.put(249,"Это дорогая машина");
        examRuToBe.put(250,"Мы не коллеги");
        examRuToBe.put(251,"Мы вовсе не устали");
        examRuToBe.put(252,"Моему брату 16");
        examRuToBe.put(253,"Компьютеры новые?");
        examRuToBe.put(254,"Это очень плохое решение");
        examRuToBe.put(255,"Как ты?");
        examRuToBe.put(256,"Это не слева");
        examRuToBe.put(257,"Что здесь?");
        examRuToBe.put(258,"Компания очень богатая");
        examRuToBe.put(259,"Мы на первом месте?");
        examRuToBe.put(260,"Почему её уроки такие не эффективные?");
        examRuToBe.put(261,"Это очевидно");
        examRuToBe.put(262,"Они не мои коллеги");
        examRuToBe.put(263,"Он лучший студент?");
        examRuToBe.put(264,"Почему он зол/рассержен?");
        examRuToBe.put(265,"Это скучный журнал?");
        examRuToBe.put(266,"Мы в не правельном месте?");
        examRuToBe.put(267,"Мой босс очень занят сейчас");
        examRuToBe.put(268,"Не тепло. Холодно");
        examRuToBe.put(269,"Моя мама на работе");
        examRuToBe.put(270,"Она в отпуске");
        examRuToBe.put(271,"Кто не прав?");
        examRuToBe.put(272,"Это хуже");
        examRuToBe.put(273,"Это информативный урок");
        examRuToBe.put(274,"Здесь холодно?");
        examRuToBe.put(275,"Он профессиональный учитель");
        examRuToBe.put(276,"Не дождливо. Солнечно");
        examRuToBe.put(277,"Их идея очень интересная");
        examRuToBe.put(278,"Это такой сложный экзамен");
        examRuToBe.put(279,"Та вещь действительно важная?");
        examRuToBe.put(280,"Это холодный день");
        examRuToBe.put(281,"Эта вещь действительно такая важная?");
        examRuToBe.put(282,"День дождливый");
        examRuToBe.put(283,"Это не справа");
        examRuToBe.put(284,"Это не очень большая ошибка");
        examRuToBe.put(285,"Он не бедный. Он очень богатый");
        examRuToBe.put(286,"Он в командировке");
        examRuToBe.put(287,"Ты удовлетворен своим результатом?");
        examRuToBe.put(288,"Это так важно");
        examRuToBe.put(289,"Она с нами сейчас");
        examRuToBe.put(290,"Твоя мама дизайнер?");
        examRuToBe.put(291,"Книга такая интересная?");
        examRuToBe.put(292,"Это его точка зрения?");
        examRuToBe.put(293,"Он такой смышленный");
        examRuToBe.put(294,"Она уверена");
        examRuToBe.put(295,"Это очень важно");
        examRuToBe.put(296,"Она очень бедная");
        examRuToBe.put(297,"Это очень скучная книга");
        examRuToBe.put(298,"Это так плохо");
        examRuToBe.put(299,"Он молодной человек");
        examRuToBe.put(300,"Это важная деталь");
        examRuToBe.put(301,"Он такой талантливый мальчик");
        examRuToBe.put(302,"Я не студент. Я работаю");
        examRuToBe.put(303,"Она такая красивая девушка");
        examRuToBe.put(304,"Это так не эффективно");
        examRuToBe.put(305,"Это интересно");
        examRuToBe.put(306,"Как (тебе) вечеринка?");
        examRuToBe.put(307,"Это очень важная вещь");
        examRuToBe.put(308,"Они далеко?");
        examRuToBe.put(309,"Его родители рядом");
        examRuToBe.put(310,"Это плохо");
        examRuToBe.put(311,"Это важная вещь");
        examRuToBe.put(312,"Это не так");
        examRuToBe.put(313,"Как зовут твою девушку?");
        examRuToBe.put(314,"Уроки действительно полезные?");
        examRuToBe.put(315,"Еда хорошая?");
        examRuToBe.put(316,"Университет знаменитый?");
        examRuToBe.put(317,"Статья о политике?");
        examRuToBe.put(318,"Это не очень низкий уровень");
        examRuToBe.put(319,"Это так далеко");
        examRuToBe.put(320,"Как зовут твоего брата?");
        examRuToBe.put(321,"Его отец бизнесмен?");
        examRuToBe.put(322,"Эти слова новые для тебя?");
        examRuToBe.put(323,"Они мои друзья");
        examRuToBe.put(324,"Это в твоей собственной квартире?");
        examRuToBe.put(325,"Это лучший канал");
        examRuToBe.put(326,"На сколько эффективный урок?");
        examRuToBe.put(327,"Это легкий урок");
        examRuToBe.put(328,"Это теплый день");
        examRuToBe.put(329,"Он успешный бизнесмен?");
        examRuToBe.put(330,"Где это?");
        examRuToBe.put(331,"На сколько хороший урок?");
        examRuToBe.put(332,"Как тебе фильм?");
        examRuToBe.put(333,"Это для детей?");
        examRuToBe.put(334,"Проблемы такие большие?");
        examRuToBe.put(335,"Это простой тест");
        examRuToBe.put(336,"Слишком жарко");
        examRuToBe.put(337,"Она учительница");
        examRuToBe.put(338,"Они ленивые");
        examRuToBe.put(339,"Правила очень важные");
        examRuToBe.put(340,"Она не с ним. Она с ней");
        examRuToBe.put(341,"Те уроки не эффективные (с отрицанием)");
        examRuToBe.put(342,"На сколько сложный тест?");
        examRuToBe.put(343,"Он в школе");
        examRuToBe.put(344,"Это эффективный метод?");
        examRuToBe.put(345,"Скорлько (стоит) эта книга?");
        examRuToBe.put(346,"Она очень красивая девушка");
        examRuToBe.put(347,"Они не бизнесмены. Они менеджеры");
        examRuToBe.put(348,"Я так счастлив");
        examRuToBe.put(349,"Сколько ему лет?");
        examRuToBe.put(350,"День ветренный");
        examRuToBe.put(351,"Я счастлив");
        examRuToBe.put(352,"Где мальчик?");
        examRuToBe.put(353,"Она такая красивая");
        examRuToBe.put(354,"Деньги важны");
        examRuToBe.put(355,"Те упражнения бесполезные?");
        examRuToBe.put(356,"Сколько (стоит) эта пара джинс?");
        examRuToBe.put(357,"Я не устал");
        examRuToBe.put(358,"Так холодно");
        examRuToBe.put(359,"Она бедная женщина?");
        examRuToBe.put(360,"Этот метод очень простой");
        examRuToBe.put(361,"Где наш учитель?");
        examRuToBe.put(362,"Это слишком легко");
        examRuToBe.put(363,"Когда она дома?");
        examRuToBe.put(364,"Мальчик дома?");
        examRuToBe.put(365,"Ты там?");
        examRuToBe.put(366,"Что это?");
        examRuToBe.put(367,"Этот текст простой?");
        examRuToBe.put(368,"Отель дорогой?");
        examRuToBe.put(369,"Это хуже?");
        examRuToBe.put(370,"Это такая важная встреча");
        examRuToBe.put(371,"Я уверен ты лучший учитель в мире");
        examRuToBe.put(372,"Почему ты так счастлив?");
        examRuToBe.put(373,"Книга скучная?");
        examRuToBe.put(374,"Это лучший канал?");
        examRuToBe.put(375,"Это такой интересный вопрос");
        examRuToBe.put(376,"Урок полезный?");
        examRuToBe.put(377,"Кем работает твоя жена?");
        examRuToBe.put(378,"Мы в парке");
        examRuToBe.put(379,"Кто там?");
        examRuToBe.put(380,"Он не с ними");
        examRuToBe.put(381,"Это так легко");
        examRuToBe.put(382,"Это не высокий уровень");
        examRuToBe.put(383,"Его мама врач?");
        examRuToBe.put(384,"Он ленивый мальчик?");
        examRuToBe.put(385,"Кто тот мужчина?");
        examRuToBe.put(386,"Это не на первом месте для меня");
        examRuToBe.put(387,"Я свободен");
        examRuToBe.put(388,"Кто в комнате?");
        examRuToBe.put(389,"Ты счастливый человек");
        examRuToBe.put(390,"Этот универстет известный?");
        examRuToBe.put(391,"Это мощный компьютер?");
        examRuToBe.put(392,"Мы не грустные. Мы счастливые");
        examRuToBe.put(393,"Где твой муж?");
        examRuToBe.put(394,"Кто следующий?");
        examRuToBe.put(395,"На сколько сложные эти упражнения?");
        examRuToBe.put(396,"Это очень дорогая вещь");
        examRuToBe.put(397,"Он прав?");
        examRuToBe.put(398,"Мне 31. А тебе?");
        examRuToBe.put(399,"Это очень полезная вещь");
        examRuToBe.put(400, "Он действительно трудолюбивый?");
        examRuToBe.put(401, "Это не очень хорошее решение");
        examRuToBe.put(402, "Знания сила?");
        examRuToBe.put(403, "Где ты?");
        examRuToBe.put(404, "Его родители за границей?");
        examRuToBe.put(405, "Как тебя зовут?");
        examRuToBe.put(406, "Что в твоей сумке?");
        examRuToBe.put(407, "Это очень интересное предложение?");
        examRuToBe.put(408, "Мы не глупые. Мы умные.");
        examRuToBe.put(409, "Как зовут твою сестру?");
        examRuToBe.put(410, "Этот студент такой трудолюбивый");
        examRuToBe.put(411, "Это дорогая вещь");
        examRuToBe.put(412, "Это хорошо");
        examRuToBe.put(413, "Я так устал");
        examRuToBe.put(414, "Компьютеры старые?");
        examRuToBe.put(415, "Ты прав");
        examRuToBe.put(416, "Тест легкий");
        examRuToBe.put(417, "Все эти упражнения такие легкие");
        examRuToBe.put(418, "Это забавное видео?");
        examRuToBe.put(419, "На сколько дорогой этот дом?");
        examRuToBe.put(420, "Это такая большая проблема?");
        examRuToBe.put(421, "Почему ты против этого?");
        examRuToBe.put(422, "Информация полезная?");
        examRuToBe.put(423, "Он её муж");
        examRuToBe.put(424, "Где твоя жена?");
        examRuToBe.put(425, "Это жаркий день");
        examRuToBe.put(426, "Он студент");
        examRuToBe.put(427, "Это не лучше");
        examRuToBe.put(428, "Это так популярно");
        examRuToBe.put(429, "Это не так очевидно");
        examRuToBe.put(430, "Канал действительно хороший?");
        examRuToBe.put(431, "Кошка в твоей комнате?");
        examRuToBe.put(432, "Она здесь");
        examRuToBe.put(433, "Она очень красивая девушка");
        examRuToBe.put(434, "Его результат не такой плохой");
        examRuToBe.put(435, "Кем работает твой муж?");
        examRuToBe.put(436, "Это плохо");
        examRuToBe.put(437, "Это очень полезный урок");
        examRuToBe.put(438, "Он очень бедный человек");
        examRuToBe.put(439, "Ты не в этом месте");
        examRuToBe.put(440, "Вопрос простой");
        examRuToBe.put(441, "Я вовсе не устал");
        examRuToBe.put(442, "Он не директор. Он менеджер");
        examRuToBe.put(443, "Темно");
        examRuToBe.put(444, "Он мой друг");
        examRuToBe.put(445, "Сколько лет твоему брату?");
        examRuToBe.put(446, "Женщина очень бедная");
        examRuToBe.put(447, "Наш учитель прав?");
        examRuToBe.put(448, "Это справа?");
        examRuToBe.put(449, "Она не на кухне");
        examRuToBe.put(450, "Этот бизнес прибыльный?");
        examRuToBe.put(451, "На сколько эффективные уроки?");
        examRuToBe.put(452, "Что не так?");
        examRuToBe.put(453, "Где твоя машина?");
        examRuToBe.put(454, "Его уровень очень высокий");
        examRuToBe.put(455, "Она красива?");
        examRuToBe.put(456, "Мой друг дома");
        examRuToBe.put(457, "Песня очень популярная");
        examRuToBe.put(458, "Где это место?");
        examRuToBe.put(459, "Почему ты здесь?");
        examRuToBe.put(460, "Как зовут твоего лучшего друга?");
        examRuToBe.put(461, "Ты не на первом месте. Ты на втором месте");
        examRuToBe.put(462, "Ты готов?");
        examRuToBe.put(463, "Ты очень счастливый человек");
        examRuToBe.put(464, "Мой брат в ванной");
        examRuToBe.put(465, "Это интересная идея");
        examRuToBe.put(466, "Этот урок очень полезный");
        examRuToBe.put(467, "Мне 32");
        examRuToBe.put(468, "Это такая большая проблема");
        examRuToBe.put(469, "Те женщины учительницы");
        examRuToBe.put(470, "Этих знаний достаточно?");
        examRuToBe.put(471, "Проблемы большие?");
        examRuToBe.put(472, "Сколько времени? (длинно) Сколько времени? (коротко)");
        examRuToBe.put(473, "На сколько эффективен урок?");
        examRuToBe.put(474, "Он такой умный мальчик");
        examRuToBe.put(475, "Твои видео очень информативные");
        examRuToBe.put(476, "Мальчик в школе");
        examRuToBe.put(477, "Как зовут твоего брата?");
        examRuToBe.put(478, "Они наши друзья");
        examRuToBe.put(479, "Они не в России сейчас");
        examRuToBe.put(480, "Она замужем?");
        examRuToBe.put(481, "Это очень полезное видео?");
        examRuToBe.put(482, "На сколько интересный этот журнал?");
        examRuToBe.put(483, "Жарко");
        examRuToBe.put(484, "Это эффективно?");
        examRuToBe.put(485, "Новости важные?");
        examRuToBe.put(486, "Канал действительно хороший");
        examRuToBe.put(487, "Почему эти упражнения такие сложные?");
        examRuToBe.put(488, "Это такая сложная ситуация");
        examRuToBe.put(489, "Мы не устали, но я думаю ты устал");
        examRuToBe.put(490, "Урок интересный");
        examRuToBe.put(491, "Эти вещи очень важные");
        examRuToBe.put(492, "Его компьютер новый?");
        examRuToBe.put(493, "Это очень большая проблема?");
        examRuToBe.put(494, "Это не большая ошибка");
        examRuToBe.put(495, "Когда ты свободен?");
        examRuToBe.put(496, "Он женат?");
        examRuToBe.put(497, "Это блестящий результат");
        examRuToBe.put(498, "Это такое интересное место");
        examRuToBe.put(499, "Это большая ошибка");
        examRuToBe.put(500, "Как зовут твоего друга?");
        examRuToBe.put(501, "На сколько сложное это упражнение?");
        examRuToBe.put(502, "Она очень оптимистичная");
        examRuToBe.put(503, "Я в школе");
        examRuToBe.put(504, "Ты не прав (с отрицанием)");
        examRuToBe.put(505, "Он уверен");
        examRuToBe.put(506, "Она моя девушка");
        examRuToBe.put(507, "Моей девушке 21");
        examRuToBe.put(508, "Канал очень популярный?");
        examRuToBe.put(509, "Это простой метод");
        examRuToBe.put(510, "Твои результаты отличные");
        examRuToBe.put(511, "Эти проблемы маленькие");
        examRuToBe.put(512, "Это особое предложение?");
        examRuToBe.put(513, "Статья не о политике");
        examRuToBe.put(514, "Это так легко");
        examRuToBe.put(515, "Мне везёт?");
        examRuToBe.put(516, "Она не с нами");
        examRuToBe.put(517, "Они на работе");
        examRuToBe.put(518, "Это такая плохая ситуация");
        examRuToBe.put(519, "Ты в Соединенных Штатах?");
        examRuToBe.put(520, "Она не здесь. Она там");
        examRuToBe.put(521, "Это хорошая манера");
        examRuToBe.put(522, "Мы правы?");
        examRuToBe.put(523, "Кем он работает?");
        examRuToBe.put(524, "Мои родители так счастливы");
        examRuToBe.put(525, "Кто на первом месте?");
        examRuToBe.put(526, "Это не такая важная встреча");
        examRuToBe.put(527, "Их отец бизнесмен?");
        examRuToBe.put(528, "Он за границей?");
        examRuToBe.put(529, "Этот тест такой простой?");
        examRuToBe.put(530, "Мой брат готов");
        examRuToBe.put(531, "Это его точка зрения?");
        examRuToBe.put(532, "Эта информация действительно полезная?");
        examRuToBe.put(533, "Это правило важное?");
        examRuToBe.put(534, "Она слишком пессимистична?");
        examRuToBe.put(535, "То решение хуже?");
        examRuToBe.put(536, "Он такой талантливый");
        examRuToBe.put(537, "Это такое легкое упражнение");
        examRuToBe.put(538, "Все эти детали очень важны");
        examRuToBe.put(539, "Что дальше?");
        examRuToBe.put(540, "Это так эффективно");
        examRuToBe.put(541, "Он не такой трудолюбивый");
        examRuToBe.put(542, "Женщины там");
        examRuToBe.put(543, "Она устала?");
        examRuToBe.put(544, "Время деньги");
        examRuToBe.put(545, "Это очень легко");
        examRuToBe.put(546, "Мы не злые. Мы очень добрые");
        examRuToBe.put(547, "Время деньги?");
        examRuToBe.put(548, "Я на работе");
        examRuToBe.put(549, "Ты очень добрый");
        examRuToBe.put(550, "Я не женат. Я холост");
        examRuToBe.put(551, "Это очень хорошее решение");
        examRuToBe.put(552, "Это очевидно?");
        examRuToBe.put(553, "Это знаменитый университет?");
        examRuToBe.put(554, "Они бедные");
        examRuToBe.put(555, "День солнечный");
        examRuToBe.put(556, "Её дочь в парке");
        examRuToBe.put(557, "Это самый лучший пример");
        examRuToBe.put(558, "Это проблема очень большая");
        examRuToBe.put(559, "Мальчики дома");
        examRuToBe.put(560, "Кто он?");
        examRuToBe.put(561, "Где твоя комната?");
        examRuToBe.put(562, "Мальчик очень умный");
        examRuToBe.put(563, "Его родители за границей сейчас");
        examRuToBe.put(564, "Это такой не эффективный метод?");
        examRuToBe.put(565, "Кто та женщина?");
        examRuToBe.put(566, "Она не певица. Она актриса");
        examRuToBe.put(567, "Кем работает твоя мама?");
        examRuToBe.put(568, "Это лучшая книга");
        examRuToBe.put(569, "Ты не оптимистичен");
        examRuToBe.put(570, "Эти слова новые для меня");
        examRuToBe.put(571, "Где это место?");
        examRuToBe.put(572, "Я в правильном месте?");
        examRuToBe.put(573, "Китайский очень сложный");
        examRuToBe.put(574, "Твой брат дома?");
        examRuToBe.put(575, "Ты действительно устал?");
        examRuToBe.put(576, "Эти новости важные?");
        examRuToBe.put(577, "Сколько стоит эта машина?");
        examRuToBe.put(578, "Это не высокий уровень. Этот уровень низкий");
        examRuToBe.put(579, "Сколько стоит один урок Английского?");
        examRuToBe.put(580, "Это очень легкий урок");
        examRuToBe.put(581, "Экзамен сложный");
        examRuToBe.put(582, "Он мой парень");
        examRuToBe.put(583, "Все эти уроки бесплатные");
        examRuToBe.put(584, "Она красивая");
        examRuToBe.put(585, "Он не уверен");
        examRuToBe.put(586, "Её мама на кухне");
        examRuToBe.put(587, "Как зовут твою сестру?");
        examRuToBe.put(588, "Как её зовут?");
        examRuToBe.put(589, "Этот урок полезный для тебя? Он очень полезный");
        examRuToBe.put(590, "Как (тебе) этот тест?");
        examRuToBe.put(591, "Мы полны оптимизма");
        examRuToBe.put(592, "Я не удовлетворен этим решением");
        examRuToBe.put(593, "Он молодой?");
        examRuToBe.put(594, "Он бизнесмен");
        examRuToBe.put(595, "Твоей девушке 19?");
        examRuToBe.put(596, "Это очень интересная идея");
        examRuToBe.put(597, "Сколько лет его сыну?");
        examRuToBe.put(598, "Ты лучший учитель в мире");
        examRuToBe.put(599, "Она такая мудрая женщина");

        return examRuToBe;
    }
}
