package texts;

import java.util.HashMap;
import java.util.Map;

/**
 * Класс со значениями для
 * Имеет свойства: <b>examEnPS</b>, <b>examRuPS</b>, <b>examEnToBe</b>, <b>examRuToBe</b>
 * @author Загороднев Д.М.
 * @version 2.0
 */
public class ExamTextPS implements ITexts
{
    /** Значения времени PS, языка Английский */
    private Map<Integer, String> examEnPS = new HashMap<>();

    /** Значения времени PS, языка Русский */
    private Map<Integer, String> examRuPS = new HashMap<>();

    /**
     * Функция получения списка значений на Английском языке времени to be
     * @return возвращает значения
     */
    @Override
    public Map<Integer, String> getEnglish(){
        getStrEnPS();
        return examEnPS;
    }

    /**
     * Функция получения списка значений на Русском языке времени to be
     * @return возвращает значения
     */
    @Override
    public Map<Integer, String> getRussia(){
        getStrRuPS();
        return examRuPS;
    }

    /**
     * Функция со значениями на Английском языке времени PS
     * @return возвращает список значений
     */
    private Map<Integer, String> getStrEnPS(){

        examEnPS.put(0,"How often does he test their knowledge?");
        examEnPS.put(1,"I want to know English better");
        examEnPS.put(2,"I really like it");
        examEnPS.put(3,"Do you want to study better?");
        examEnPS.put(4,"He lives there");
        examEnPS.put(5,"This test seems very easy");
        examEnPS.put(6,"I need your advice");
        examEnPS.put(7,"I need to see her");
        examEnPS.put(8,"She'd like to go to another place");
        examEnPS.put(9,"What time do you usually get up?");
        examEnPS.put(10,"She feels happy");
        examEnPS.put(11,"Do you often call him?");
        examEnPS.put(12,"How does he get home?");
        examEnPS.put(13,"What do you think about it?");
        examEnPS.put(14,"He doesn't know it");
        examEnPS.put(15,"What seems useless?");
        examEnPS.put(16,"Do we have enough practice?");
        examEnPS.put(17,"I really like these lessons");
        examEnPS.put(18,"He lives in this country");
        examEnPS.put(19,"She wants to see you right now");
        examEnPS.put(20,"I want to be happy");
        examEnPS.put(21,"She has a car");
        examEnPS.put(22,"Does he want to live abroad?");
        examEnPS.put(23,"What do your friends usually order?");
        examEnPS.put(24,"He works very hard");
        examEnPS.put(25,"It depends on them");
        examEnPS.put(26,"What English books does he have?");
        examEnPS.put(27,"He wants more");
        examEnPS.put(28,"I understand you very well");
        examEnPS.put(29,"She explains all these things very well");
        examEnPS.put(30,"She loves you");
        examEnPS.put(31,"These lessons really help");
        examEnPS.put(32,"She does those exercises regularly");
        examEnPS.put(33,"She always does it on time");
        examEnPS.put(34,"What helps you?");
        examEnPS.put(35,"I want to go abroad");
        examEnPS.put(36,"I need money");
        examEnPS.put(37,"How often does she go to the cinema?");
        examEnPS.put(38,"What does she want to add?");
        examEnPS.put(39,"She works very hard");
        examEnPS.put(40,"My sister studies there");
        examEnPS.put(41,"I like your lessons");
        examEnPS.put(42,"Who love her?");
        examEnPS.put(43,"I remember it");
        examEnPS.put(44,"I want a new computer");
        examEnPS.put(45,"What helps her?");
        examEnPS.put(46,"She lives this place");
        examEnPS.put(47,"I'd like a cup of coffee");
        examEnPS.put(48,"It doesn't seem strange");
        examEnPS.put(49,"What worries you more?");
        examEnPS.put(50,"How does it help you?");
        examEnPS.put(51,"My parents want to do it");
        examEnPS.put(52,"All people do it");
        examEnPS.put(53,"How long does it take him to get to that place?");
        examEnPS.put(54,"He doesn't try to find a good job");
        examEnPS.put(55,"You don't try to learn English");
        examEnPS.put(56,"What kind of examples does his teacher give?");
        examEnPS.put(57,"Does this person seem very good?");
        examEnPS.put(58,"It doesn't seem useful");
        examEnPS.put(59,"I think so");
        examEnPS.put(60,"They go to work");
        examEnPS.put(61,"How does she explain it?");
        examEnPS.put(62,"She needs to correct these mistakes");
        examEnPS.put(63,"What music do you prefer?");
        examEnPS.put(64,"My sister lives these but I live here");
        examEnPS.put(65,"How long does it take his daughter to get to school?");
        examEnPS.put(66,"You need to remember this rule");
        examEnPS.put(67,"I live in this country");
        examEnPS.put(68,"Do you remember it?");
        examEnPS.put(69,"I go to work");
        examEnPS.put(70,"I need to speak English without any mistakes at all");
        examEnPS.put(71,"I understand everything");
        examEnPS.put(72,"It helps me");
        examEnPS.put(73,"I like it");
        examEnPS.put(74,"Which drink does she prefer: tea or coffee?");
        examEnPS.put(75,"Do you support me?");
        examEnPS.put(76,"Why do your parents disagree with you?");
        examEnPS.put(77,"She feels so happy");
        examEnPS.put(78,"He goes to work");
        examEnPS.put(79,"It depends on us");
        examEnPS.put(80,"Does he hate this thing?");
        examEnPS.put(81,"How often do you go there?");
        examEnPS.put(82,"I like this idea");
        examEnPS.put(83,"I don't want to study there");
        examEnPS.put(84,"When do you have free time?");
        examEnPS.put(85,"She watches different movies");
        examEnPS.put(86,"Do you often listen to music?");
        examEnPS.put(87,"I like this method");
        examEnPS.put(88,"She tries to understand it");
        examEnPS.put(89,"It doesn't inspire me");
        examEnPS.put(90,"I want it");
        examEnPS.put(91,"How often do you think about it?");
        examEnPS.put(92,"Where do they spend time together?");
        examEnPS.put(93,"I'd like to drink a cup of coffee");
        examEnPS.put(94,"When does he feel happy?");
        examEnPS.put(95,"I don't want to live in that city");
        examEnPS.put(96,"Who wants to live abroad?");
        examEnPS.put(97,"She doesn't want to discuss it");
        examEnPS.put(98,"Your lessons really help");
        examEnPS.put(99,"He misses you");
        examEnPS.put(100,"I do it with great pleasure");
        examEnPS.put(101,"It attracts me");
        examEnPS.put(102,"Why does she refuse to pay?");
        examEnPS.put(103,"This lesson seems interesting");
        examEnPS.put(104,"How do you get home?");
        examEnPS.put(105,"He wants more practice");
        examEnPS.put(106,"Does that test seem very easy?");
        examEnPS.put(107,"Do we have enough knowledge?");
        examEnPS.put(108,"How do you spend your free time?");
        examEnPS.put(109,"Does she remember all these rules?");
        examEnPS.put(110,"Why does it happen again and again?");
        examEnPS.put(111,"Do they do business?");
        examEnPS.put(112,"Does she teach English?");
        examEnPS.put(113,"She reads in English");
        examEnPS.put(114,"She speaks English very well");
        examEnPS.put(115,"Do they support us?");
        examEnPS.put(116,"These lessons seem very useful");
        examEnPS.put(117,"He often plays computer games");
        examEnPS.put(118,"I practice English every day");
        examEnPS.put(119,"My parents know it");
        examEnPS.put(120,"Who corrects your mistakes?");
        examEnPS.put(121,"Does her boyfriend want to go abroad?");
        examEnPS.put(122,"Why does he say these things again and again?");
        examEnPS.put(123,"He has a cat");
        examEnPS.put(124,"Who sees these mistakes?");
        examEnPS.put(125,"These things attract them");
        examEnPS.put(126,"I see you really like English");
        examEnPS.put(127,"I want more practice");
        examEnPS.put(128,"Does he often think about it?");
        examEnPS.put(129,"Why do you think so?");
        examEnPS.put(130,"We speak English");
        examEnPS.put(131,"Do you go to work?");
        examEnPS.put(132,"Do you work on your mistakes?");
        examEnPS.put(133,"Do these things seem unimportant?");
        examEnPS.put(134,"What does your boss usually answer?");
        examEnPS.put(135,"I need to study harder");
        examEnPS.put(136,"Where do you work?");
        examEnPS.put(137,"How regularly do you practice English?");
        examEnPS.put(138,"He also works here");
        examEnPS.put(139,"Does this student show brilliant results?");
        examEnPS.put(140,"He understand you very well");
        examEnPS.put(141,"What seems strange?");
        examEnPS.put(142,"I live in Russia");
        examEnPS.put(143,"My friend doesn't think so");
        examEnPS.put(144,"He has an offer");
        examEnPS.put(145,"Why does he always complain about it?");
        examEnPS.put(146,"He knows more");
        examEnPS.put(147,"I see everything");
        examEnPS.put(148,"He doesn't want to read these books");
        examEnPS.put(149,"Does he often watch TV?");
        examEnPS.put(150,"He thinks so");
        examEnPS.put(151,"I like this thing");
        examEnPS.put(152,"He teaches English");
        examEnPS.put(153,"It doesn't help me");
        examEnPS.put(154,"I don't want to play computer games");
        examEnPS.put(155,"Do you remember everything?");
        examEnPS.put(156,"Do you need my advice?");
        examEnPS.put(157,"My boss reads all the documents");
        examEnPS.put(158,"She does it very well");
        examEnPS.put(159,"How much money do you have with you?");
        examEnPS.put(160,"He sees that mistake");
        examEnPS.put(161,"Does this lesson seem useful?");
        examEnPS.put(162,"Who supports you?");
        examEnPS.put(163,"It seems interesting");
        examEnPS.put(164,"I don't agree with you / I disagree with you");
        examEnPS.put(165,"She misses you");
        examEnPS.put(166,"Do they support this decision?");
        examEnPS.put(167,"She really remembers it");
        examEnPS.put(168,"I want to thank you");
        examEnPS.put(169,"I want to know it");
        examEnPS.put(170,"We live in this country");
        examEnPS.put(171,"I really need English");
        examEnPS.put(172,"How does he support you?");
        examEnPS.put(173,"I need to correct this mistake");
        examEnPS.put(174,"He also knows it");
        examEnPS.put(175,"How regularly does your boss check it?");
        examEnPS.put(176,"How does your sister feel?");
        examEnPS.put(177,"How regularly does he do these exercises?");
        examEnPS.put(178,"I want to go to another place");
        examEnPS.put(179,"Who do you know?");
        examEnPS.put(180,"This thing seems unimportant");
        examEnPS.put(181,"How long does it take her to get to this place?");
        examEnPS.put(182,"What does he remember?");
        examEnPS.put(183,"Why do you agree with him?");
        examEnPS.put(184,"It really happens");
        examEnPS.put(185,"I'd like a cup of tea");
        examEnPS.put(186,"I need this thing");
        examEnPS.put(187,"He often goes to the cinema");
        examEnPS.put(188,"I want to train my memory");
        examEnPS.put(189,"They don't do business");
        examEnPS.put(190,"I don't want to talk/speak about it");
        examEnPS.put(191,"She doesn't want to think about it");
        examEnPS.put(192,"She wants to do it right now");
        examEnPS.put(193,"My friend needs your help");
        examEnPS.put(194,"Does he ignore her words?");
        examEnPS.put(195,"Does your father need it?");
        examEnPS.put(196,"Why does it attract you?");
        examEnPS.put(197,"I know they like it");
        examEnPS.put(198,"He does it every day");
        examEnPS.put(199,"How regularly do you learn English?");
        examEnPS.put(200,"Does it seem interesting?");
        examEnPS.put(201,"How many dollars does he have with him?");
        examEnPS.put(202,"They go to school");
        examEnPS.put(203,"Do I have enough money?");
        examEnPS.put(204,"I want to do it");
        examEnPS.put(205,"My brother tries to do it");
        examEnPS.put(206,"She doesn't remember it");
        examEnPS.put(207,"I speak English");
        examEnPS.put(208,"His lessons seem very useful");
        examEnPS.put(209,"What does he want to add?");
        examEnPS.put(210,"Why do your friends disagree with you?");
        examEnPS.put(211,"We understand you");
        examEnPS.put(212,"What do you want to say?");
        examEnPS.put(213,"It looks interesting");
        examEnPS.put(214,"He doesn't have a car");
        examEnPS.put(215,"We need to solve this problem");
        examEnPS.put(216,"Does your mother tell him all the truth?");
        examEnPS.put(217,"It inspires me");
        examEnPS.put(218,"What inspires you?");
        examEnPS.put(219,"Who does she love?");
        examEnPS.put(220,"Does she often listen to the radio?");
        examEnPS.put(221,"I don't want to tell you about this problem");
        examEnPS.put(222,"What do you like here?");
        examEnPS.put(223,"Their ideas seem very interesting");
        examEnPS.put(224,"What does he need to change?");
        examEnPS.put(225,"Does his girlfriend understand it?");
        examEnPS.put(226,"I find all these lessons really useful");
        examEnPS.put(227,"Why do you depend on him?");
        examEnPS.put(228,"She also works there");
        examEnPS.put(229,"How does she train her memory?");
        examEnPS.put(230,"Do your parents understand it?");
        examEnPS.put(231,"You know it");
        examEnPS.put(232,"Why does your boss criticize it?");
        examEnPS.put(233,"I see he really likes it");
        examEnPS.put(234,"I don't want to know it");
        examEnPS.put(235,"Does that lesson seem boring?");
        examEnPS.put(236,"Does she ignore it sometimes?");
        examEnPS.put(237,"It attracts him");
        examEnPS.put(238,"Does she want to go abroad?");
        examEnPS.put(239,"I want to speak English fluently and correctly");
        examEnPS.put(240,"Where do you go?");
        examEnPS.put(241,"This lesson helps me");
        examEnPS.put(242,"They often criticize him");
        examEnPS.put(243,"Her brother often says it");
        examEnPS.put(244,"Do you like that offer?");
        examEnPS.put(245,"She tries to learn English");
        examEnPS.put(246,"Do they see their mistakes?");
        examEnPS.put(247,"Do you like it?");
        examEnPS.put(248,"Does your friend agree with you?");
        examEnPS.put(249,"My sister lives in this place");
        examEnPS.put(250,"I have an idea");
        examEnPS.put(251,"How do you usually get to that place?");
        examEnPS.put(252,"I don't understand these people");
        examEnPS.put(253,"How regularly do you speak English?");
        examEnPS.put(254,"He has dollars");
        examEnPS.put(255,"I know it");
        examEnPS.put(256,"This thing attracts me");
        examEnPS.put(257,"What time does she leave home?");
        examEnPS.put(258,"When do you feel happy?");
        examEnPS.put(259,"He'd like to become a doctor");
        examEnPS.put(260,"He makes so many mistakes");
        examEnPS.put(261,"What books do you read?");
        examEnPS.put(262,"She goes to school");
        examEnPS.put(263,"I support this decision");
        examEnPS.put(264,"Who does it motivate?");
        examEnPS.put(265,"It seems useless");
        examEnPS.put(266,"Do you have free time?");
        examEnPS.put(267,"Do you agree with him?");
        examEnPS.put(268,"What channels does he watch?");
        examEnPS.put(269,"I'd like to visit this place");
        examEnPS.put(270,"We like it");
        examEnPS.put(271,"I love you");
        examEnPS.put(272,"What time does your mother come to work?");
        examEnPS.put(273,"She watches TV");
        examEnPS.put(274,"Why do you want to visit this place?");
        examEnPS.put(275,"Who does he support?");
        examEnPS.put(276,"He wants to buy this thing");
        examEnPS.put(277,"She wants more practice");
        examEnPS.put(278,"I don't want to say it");
        examEnPS.put(279,"Does this thing seem important?");
        examEnPS.put(280,"Does he often speak English?");
        examEnPS.put(281,"My friend likes this hotel");
        examEnPS.put(282,"I really want it");
        examEnPS.put(283,"Does it seem boring?");
        examEnPS.put(284,"I feel it");
        examEnPS.put(285,"It happens");
        examEnPS.put(286,"What kind of computer games do they play?");
        examEnPS.put(287,"I need to solve these problems");
        examEnPS.put(288,"I like this channel");
        examEnPS.put(289,"Those lessons don't help me at all");
        examEnPS.put(290,"Why does it look strange?");
        examEnPS.put(291,"How often do you go to the gym?");
        examEnPS.put(292,"Does this information seem unimportant?");
        examEnPS.put(293,"Do you agree with her?");
        examEnPS.put(294,"I work here");
        examEnPS.put(295,"What does she want to add?");
        examEnPS.put(296,"I'd like to know English very well");
        examEnPS.put(297,"Our mother thinks the same");
        examEnPS.put(298,"That offer seems strange");
        examEnPS.put(299,"This project seems very interesting");
        examEnPS.put(300,"How does he usually spend his free time?");
        examEnPS.put(301,"How does she get home?");
        examEnPS.put(302,"He has a house");
        examEnPS.put(303,"She needs your advice");
        examEnPS.put(304,"What do they want to tell you?");
        examEnPS.put(305,"We don't want to live in another place");
        examEnPS.put(306,"I really need it");
        examEnPS.put(307,"What worries you?");
        examEnPS.put(308,"What do you want to do?");
        examEnPS.put(309,"His father has a car");
        examEnPS.put(310,"She'd like to become a teacher");
        examEnPS.put(311,"What does he try to do?");
        examEnPS.put(312,"I want this thing");
        examEnPS.put(313,"My boss always says it");
        examEnPS.put(314,"When does it happen?");
        examEnPS.put(315,"This company has money");
        examEnPS.put(316,"He has a company. Its profit seems so big");
        examEnPS.put(317,"She remember it");
        examEnPS.put(318,"I really need your lessons");
        examEnPS.put(319,"Do those students speak English correctly?");
        examEnPS.put(320,"I want to speak English correctly");
        examEnPS.put(321,"I want a good car");
        examEnPS.put(322,"Where does he work?");
        examEnPS.put(323,"How often do these things happen?");
        examEnPS.put(324,"Who knows it?");
        examEnPS.put(325,"She sees this mistake");
        examEnPS.put(326,"I want to improve my English");
        examEnPS.put(327,"My parents want to live in another place");
        examEnPS.put(328,"Do your friends agree with you?");
        examEnPS.put(329,"Does he ignore everything?");
        examEnPS.put(330,"Do these results motivate you?");
        examEnPS.put(331,"Do you want to to know your mistakes?");
        examEnPS.put(332,"Do you agree with them?");
        examEnPS.put(333,"I need to call him");
        examEnPS.put(334,"What interests you?");
        examEnPS.put(335,"I really want to improve my grammar");
        examEnPS.put(336,"I want to go there one more time");
        examEnPS.put(337,"I study here");
        examEnPS.put(338,"I want this computer");
        examEnPS.put(339,"Does she often say it?");
        examEnPS.put(340,"I don't know");
        examEnPS.put(341,"Does that student make mistakes?");
        examEnPS.put(342,"We need more information");
        examEnPS.put(343,"They show brilliant results");
        examEnPS.put(344,"We remember it");
        examEnPS.put(345,"Do you often visit this place?");
        examEnPS.put(346,"What advice does she give you?");
        examEnPS.put(347,"Do you often do it?");
        examEnPS.put(348,"I'd like to go abroad");
        examEnPS.put(349,"Why does it interest him?");
        examEnPS.put(350,"I have a sister");
        examEnPS.put(351,"He needs it");
        examEnPS.put(352,"Do you support him?");
        examEnPS.put(353,"What attracts him there?");
        examEnPS.put(354,"What does she usually say?");
        examEnPS.put(355,"How do you solve these problems?");
        examEnPS.put(356,"What seems important?");
        examEnPS.put(357,"He lives in this house");
        examEnPS.put(358,"I need it");
        examEnPS.put(359,"What really helps you?");
        examEnPS.put(360,"I see it");
        examEnPS.put(361,"What time do you go to bed?");
        examEnPS.put(362,"He helps me");
        examEnPS.put(363,"How many friends do you have?");
        examEnPS.put(364,"She needs it");
        examEnPS.put(365,"Does it really motivate you?");
        examEnPS.put(366,"Who supports you?");
        examEnPS.put(367,"Do you often use the Internet?");
        examEnPS.put(368,"Do you have enough money with you?");
        examEnPS.put(369,"Do you often go to the gym?");
        examEnPS.put(370,"They study very hard");
        examEnPS.put(371,"He always promises it");
        examEnPS.put(372,"I want to have a good job");
        examEnPS.put(373,"Hoe many mistakes do you usually make?");
        examEnPS.put(374,"I really need you");
        examEnPS.put(375,"He feels happy");
        examEnPS.put(376,"I don't like it");
        examEnPS.put(377,"How many English words do you know?");
        examEnPS.put(378,"Where do your parents live?");
        examEnPS.put(379,"I need to improve my English");
        examEnPS.put(380,"Who checks all this information?");
        examEnPS.put(381,"What does your boss usually promise?");
        examEnPS.put(382,"I want to go there one more time");
        examEnPS.put(383,"I think he needs to change his life");
        examEnPS.put(384,"Does she try to find a new job?");
        examEnPS.put(385,"I do business");
        examEnPS.put(386,"Where does your father work?");
        examEnPS.put(387,"She lives in that place");
        examEnPS.put(388,"Where does she usually go?");
        examEnPS.put(389,"We want it");
        examEnPS.put(390,"He tries to help me");
        examEnPS.put(391,"What do you know?");
        examEnPS.put(392,"I think you need to work less");
        examEnPS.put(393,"What drinks does she prefer?");
        examEnPS.put(394,"Does your friend like this idea?");
        examEnPS.put(395,"It really inspires me");
        examEnPS.put(396,"Does this information seem useless?");
        examEnPS.put(397,"Do you support me?");
        examEnPS.put(398,"Do you need help?");
        examEnPS.put(399,"He doesn't need this money now");
        examEnPS.put(400,"He likes this dress");
        examEnPS.put(401,"What books does she prefer to read?");
        examEnPS.put(402,"Why do you like this channel?");
        examEnPS.put(403,"He tries to find more time for English");
        examEnPS.put(404,"It really helps me");
        examEnPS.put(405,"I need to train my memory");
        examEnPS.put(406,"You need it");
        examEnPS.put(407,"My mother comes home early");
        examEnPS.put(408,"I really like this place");
        examEnPS.put(409,"Does it sometimes happen?");
        examEnPS.put(410,"Does she like this profession?");
        examEnPS.put(411,"Who checks all the information?");
        examEnPS.put(412,"What advice do your teachers give you?");
        examEnPS.put(413,"My father comes home late");
        examEnPS.put(414,"We don't understand it");
        examEnPS.put(415,"We live in Russia");
        examEnPS.put(416,"Your mother needs to work less");
        examEnPS.put(417,"I'd like to become a businessman");
        examEnPS.put(418,"I want to go there again");
        examEnPS.put(419,"I know it very well");
        examEnPS.put(420,"Where does she study?");
        examEnPS.put(421,"How regularly do your teachers tell you these things?");
        examEnPS.put(422,"It doesn't work");
        examEnPS.put(423,"I want to learn English fast");
        examEnPS.put(424,"What channels does he usually watch?");
        examEnPS.put(425,"I work there");
        examEnPS.put(426,"What motivates you more?");
        examEnPS.put(427,"My friend wants to check it one more time");
        examEnPS.put(428,"Do you often go there?");
        examEnPS.put(429,"I like this video");
        examEnPS.put(430,"That method seems useless");
        examEnPS.put(431,"Does she really like it?");
        examEnPS.put(432,"He'd like to order it online");
        examEnPS.put(433,"Who do you support?");
        examEnPS.put(434,"How long does it take you to get to school?");
        examEnPS.put(435,"I don't want to live in this country");
        examEnPS.put(436,"These students show brilliant results");
        examEnPS.put(437,"Do they agree with us?");
        examEnPS.put(438,"He explains everything very well");
        examEnPS.put(439,"How often does he go to the zoo?");
        examEnPS.put(440,"I go to school");
        examEnPS.put(441,"My friend has a car");
        examEnPS.put(442,"I need to solve that problem");
        examEnPS.put(443,"They like it");
        examEnPS.put(444,"I don’t want to discuss it");
        examEnPS.put(445,"I really want to know it");
        examEnPS.put(446,"He has a dog");
        examEnPS.put(447,"How do you get there?");
        examEnPS.put(448,"Does he live there?");
        examEnPS.put(449,"He'd like to become a businessman");
        examEnPS.put(450,"Does he like it?");
        examEnPS.put(451,"I want to practice English now");
        examEnPS.put(452,"She goes to scholl with great pleasure");
        examEnPS.put(453,"I want to speak English without mistakes");
        examEnPS.put(454,"You need to remember it");
        examEnPS.put(455,"We need it");
        examEnPS.put(456,"You need to change it");
        examEnPS.put(457,"She doesn't want to think about it");
        examEnPS.put(458,"When do you go to work?");
        examEnPS.put(459,"I understand you");
        examEnPS.put(460,"Does she need to come to that place?");
        examEnPS.put(461,"Why do they depend on you?");
        examEnPS.put(462,"How long does it take your friend to get there?");
        examEnPS.put(463,"What kind of books do you read?");
        examEnPS.put(464,"Why does your mother think so?");
        examEnPS.put(465,"He wants to do it");
        examEnPS.put(466,"I like this advice");
        examEnPS.put(467,"What advice do your friends give you?");
        examEnPS.put(468,"I'd like to do it");
        examEnPS.put(469,"He sometimes plays computer games");
        examEnPS.put(470,"Does he pay for it?");
        examEnPS.put(471,"I have a car");
        examEnPS.put(472,"I work very hard");
        examEnPS.put(473,"They don’t help me");
        examEnPS.put(474,"Does he like this project?");
        examEnPS.put(475,"Does this exam seem very difficult?");
        examEnPS.put(476,"You help me");
        examEnPS.put(477,"I'd like to practice English");
        examEnPS.put(478,"I understand");
        examEnPS.put(479,"We live here");
        examEnPS.put(480,"How often do these things happen?");
        examEnPS.put(481,"My father leaves home very early");
        examEnPS.put(482,"He doesn't work there");
        examEnPS.put(483,"He works here");
        examEnPS.put(484,"Do these lessons help you?");
        examEnPS.put(485,"I need to check it");
        examEnPS.put(486,"She also thinks so");
        examEnPS.put(487,"She has interesting ideas");
        examEnPS.put(488,"Why do those things happen?");
        examEnPS.put(489,"He really hates it");
        examEnPS.put(490,"It looks strange");
        examEnPS.put(491,"What lessons does your teacher find really useful?");
        examEnPS.put(492,"He needs more money");
        examEnPS.put(493,"What seems so interesting?");
        examEnPS.put(494,"She likes it");
        examEnPS.put(495,"Does he work in another place?");
        examEnPS.put(496,"He sometimes wants to do it");
        examEnPS.put(497,"Do we show good results?");
        examEnPS.put(498,"You see it");
        examEnPS.put(499,"His father needs money");
        examEnPS.put(500,"It doesn't interest me at all");
        examEnPS.put(501,"You speak English very well");
        examEnPS.put(502,"He needs to find a good job");
        examEnPS.put(503,"What does she usually tell him?");
        examEnPS.put(504,"I want to speak English better");
        examEnPS.put(505,"He really thinks so");
        examEnPS.put(506,"He doesn't have this information");
        examEnPS.put(507,"Does his father do business?");
        examEnPS.put(508,"They want to solve these problems right now");
        examEnPS.put(509,"I don't want to drink");
        examEnPS.put(510,"Where do you live?");
        examEnPS.put(511,"Why do you need to do it now?");
        examEnPS.put(512,"Why does he complain so often?");
        examEnPS.put(513,"It depends on him");
        examEnPS.put(514,"How long does it take his son to get to work?");
        examEnPS.put(515,"I like this channel, too");
        examEnPS.put(516,"My friend needs your advice right now");
        examEnPS.put(517,"I need to call them");
        examEnPS.put(518,"How often do you listen to the radio?");
        examEnPS.put(519,"Does he often hear it?");
        examEnPS.put(520,"She teaches it");
        examEnPS.put(521,"Do you need more money?");
        examEnPS.put(522,"Why does your friend want to look for a new job?");
        examEnPS.put(523,"I have a brother");
        examEnPS.put(524,"How does she test their knowledge?");
        examEnPS.put(525,"He doesn't share your point of view");
        examEnPS.put(526,"I need this information");
        examEnPS.put(527,"He reads in English");
        examEnPS.put(528,"How regularly does your teacher say it?");
        examEnPS.put(529,"She wants to go to the park");
        examEnPS.put(530,"My brother wants it");
        examEnPS.put(531,"I like this playlist");
        examEnPS.put(532,"She wants more");
        examEnPS.put(533,"They need it");
        examEnPS.put(534,"I don't want to tell you this thing");
        examEnPS.put(535,"He also works here");
        examEnPS.put(536,"How do you usually spend your free time?");
        examEnPS.put(537,"How does he solve these problems?");
        examEnPS.put(538,"Who controls it");
        examEnPS.put(539,"Who does he control?");
        examEnPS.put(540,"She wants to do it");
        examEnPS.put(541,"He tries to do it");
        examEnPS.put(542,"What kind of movies does she watch?");
        examEnPS.put(543,"Do you need to solve this problem right now?");
        examEnPS.put(544,"We really like this channel");
        examEnPS.put(545,"Do you go to school?");
        examEnPS.put(546,"My father does business");
        examEnPS.put(547,"I need to learn English");
        examEnPS.put(548,"I really like these exercises");
        examEnPS.put(549,"Do I make mistakes?");
        examEnPS.put(550,"Do you know about this problem?");
        examEnPS.put(551,"How often does this thing happen?");
        examEnPS.put(552,"How much free time does your business partner have?");
        examEnPS.put(553,"I'd like to drink a cup of tea");
        examEnPS.put(554,"We want to know English");
        examEnPS.put(555,"He also remembers it");
        examEnPS.put(556,"She helps me");
        examEnPS.put(557,"Does their know all the truth?");
        examEnPS.put(558,"I study there");
        examEnPS.put(559,"Does it really help you?");
        examEnPS.put(560,"I'd like to thank you for everything");
        examEnPS.put(561,"I want a new flat");
        examEnPS.put(562,"Does he often tell you these things?");
        examEnPS.put(563,"Who usually checks it?");
        examEnPS.put(564,"I live in this city");
        examEnPS.put(565,"All people know it");
        examEnPS.put(566,"I share your point of view");
        examEnPS.put(567,"These lessons help me");
        examEnPS.put(568,"I need to do it");
        examEnPS.put(569,"How much money does she pay?");
        examEnPS.put(570,"These students show very good results");
        examEnPS.put(571,"I really need to know it");
        examEnPS.put(572,"Who goes to work?");
        examEnPS.put(573,"Does she need to call him?");
        examEnPS.put(574,"Who do you usually see there?");
        examEnPS.put(575,"Does your teacher see it?");
        examEnPS.put(576,"What seems unimportant?");
        examEnPS.put(577,"I remember it very well");
        examEnPS.put(578,"What time does he come to work?");
        examEnPS.put(579,"What looks strange?");
        examEnPS.put(580,"I want this dress");
        examEnPS.put(581,"Why does it seem useless?");
        examEnPS.put(582,"I need to speak English without mistakes");
        examEnPS.put(583,"Does it often happen?");
        examEnPS.put(584,"She sometimes goes to the cinema");
        examEnPS.put(585,"Do these students show excellent results?");
        examEnPS.put(586,"I really like this playlist");
        examEnPS.put(587,"How often do you use the Internet?");
        examEnPS.put(588,"I think you need to work more");
        examEnPS.put(589,"I like English");
        examEnPS.put(590,"I need to stpeak English correctly");
        examEnPS.put(591,"I often listen to the radio");
        examEnPS.put(592,"Does this result motivate you?");
        examEnPS.put(593,"Do you like this dress?");
        examEnPS.put(594,"Which channel does he usually watch?");
        examEnPS.put(595,"I want it");
        examEnPS.put(596,"How does your brother control it?");
        examEnPS.put(597,"How regularly do you check it");
        examEnPS.put(598,"She reads English books");
        examEnPS.put(599,"I learn English with you with great pleasure");
        examEnPS.put(600,"It seems unimportant");
        examEnPS.put(601,"Why does he refuse to do it?");
        examEnPS.put(602,"I don't want to do it right now");
        examEnPS.put(603,"She wants to live in another place");
        examEnPS.put(604,"Who does it worry?");
        examEnPS.put(605,"Do your friends always support you?");
        examEnPS.put(606,"She always does it with great pleasure");
        examEnPS.put(607,"I don't know this person");
        examEnPS.put(608,"My boss know everything");
        examEnPS.put(609,"My partner needs to solve this problem");
        examEnPS.put(610,"Does this channel help you?");
        examEnPS.put(611,"Do you agree with me?");
        examEnPS.put(612,"How many English words does your friend want to know?");
        examEnPS.put(613,"Does your teacher explain everything very well?");
        examEnPS.put(614,"Why do you want to know English?");
        examEnPS.put(615,"I also like channel");
        examEnPS.put(616,"It depends on her");
        examEnPS.put(617,"I live in this city");
        examEnPS.put(618,"He loves you");
        examEnPS.put(619,"I want to buy a new flat");
        examEnPS.put(620,"I'd like to become a manager");
        examEnPS.put(621,"What works so well?");
        examEnPS.put(622,"You work very hard");
        examEnPS.put(623,"Do you understand me?");
        examEnPS.put(624,"They do business");
        examEnPS.put(625,"Who checks everything?");
        examEnPS.put(626,"Does she often use it?");
        examEnPS.put(627,"All your ideas seem very interesting");
        examEnPS.put(628,"These lessons don't seem boring");
        examEnPS.put(629,"I feel happy");
        examEnPS.put(630,"I want to have a good car");
        examEnPS.put(631,"We don't share your point view");
        examEnPS.put(632,"They know everything");
        examEnPS.put(633,"He often complains about it");
        examEnPS.put(634,"Does she tell him everything?");
        examEnPS.put(635,"They don't want to listen to her");
        examEnPS.put(636,"He doesn't try to find a good job. It seems strange");
        examEnPS.put(637,"Do you try to improve you result?");
        examEnPS.put(638,"They help me");
        examEnPS.put(639,"I disagree with you");
        examEnPS.put(640,"Does she need to come here?");
        examEnPS.put(641,"Do they support this decision?");
        examEnPS.put(642,"What English books do you read?");
        examEnPS.put(643,"How do you get this place?");
        examEnPS.put(644,"We think so");
        examEnPS.put(645,"We want much more practice");
        examEnPS.put(646,"She lives in that city");
        examEnPS.put(647,"How long does it take you to get to work?");
        examEnPS.put(648,"He tries to find a job");
        examEnPS.put(649,"Does he look for a job?");
        examEnPS.put(650,"He knows it");
        examEnPS.put(651,"Hoe many English words does he want to know?");
        examEnPS.put(652,"How do you get to work?");
        examEnPS.put(653,"I see you like it");
        examEnPS.put(654,"I do these exercises regularly");
        examEnPS.put(655,"She often goes to the park");
        examEnPS.put(656,"How often do you watch TV?");
        examEnPS.put(657,"Does this channel seem very interesting?");
        examEnPS.put(658,"Does he always pay for her?");
        examEnPS.put(659,"How do you find this idea?");
        examEnPS.put(660,"Who motivates you?");
        examEnPS.put(661,"How much free time do you have?");
        examEnPS.put(662,"Does it look strange?");
        examEnPS.put(663,"My friend wants to live abroad");
        examEnPS.put(664,"I like this question");
        examEnPS.put(665,"She always criticizes him");
        examEnPS.put(666,"I usually get up early");
        examEnPS.put(667,"I really want to speak English fluently");
        examEnPS.put(668,"I prefer tea");
        examEnPS.put(669,"She prefers coffee");
        examEnPS.put(670,"Do you remember this rule?");
        examEnPS.put(671,"We see its success");
        examEnPS.put(672,"Her words inspire us");
        examEnPS.put(673,"This result motivates me");
        examEnPS.put(674,"It depends on our boss");
        examEnPS.put(675,"What motivates you more?");
        examEnPS.put(676,"I want to thank you for your advice");
        examEnPS.put(677,"I'd like to thank you for your help");
        examEnPS.put(678,"How do you find these lessons?");
        examEnPS.put(679,"How do you find this place?");
        examEnPS.put(680,"Do you want more practice?");
        examEnPS.put(681,"Do you want to improve your result?");
        examEnPS.put(682,"How often do you go to the zoo?");
        examEnPS.put(683,"Who do you usually call?");
        examEnPS.put(684,"Who usually calls you?");
        examEnPS.put(685,"What does he refuse to do?");
        examEnPS.put(686,"I need to train my memory more");
        examEnPS.put(687,"She often asks these questions");
        examEnPS.put(688,"He sometimes answers");
        examEnPS.put(689,"I like your decision");
        examEnPS.put(690,"I share your point of view");
        examEnPS.put(691,"He always promises it");
        examEnPS.put(692,"What do you want to add?");
        examEnPS.put(693,"I want to correct it");
        examEnPS.put(694,"You need to correct this mistake");
        examEnPS.put(695,"Who says these things?");
        examEnPS.put(696,"Do your friends like this channel?");
        examEnPS.put(697,"My friends really like it");
        examEnPS.put(698,"I find these videos very useful");
        examEnPS.put(699,"I'd like to thank our teacher for everything");

        return examEnPS;
    }

    /**
     * Функция со значениями на Русском языке времени PS
     * @return возвращает список значений
     */
    private Map<Integer, String> getStrRuPS(){
        examRuPS.put(0,"Как часто он тестирует их знания?");
        examRuPS.put(1,"Я хочу знать Английский лучше");
        examRuPS.put(2,"Мне действительно это нравится");
        examRuPS.put(3,"Ты хочешь учиться лучше?");
        examRuPS.put(4,"Он живет там");
        examRuPS.put(5,"Этот тест кажется очень легким");
        examRuPS.put(6,"Мне нужен твой совет");
        examRuPS.put(7,"Мне нужно увидеть её");
        examRuPS.put(8,"Она хотела бы поехать в другое место");
        examRuPS.put(9,"В какое время ты обычно встаешь?");
        examRuPS.put(10,"Она чувствует себя счастливой");
        examRuPS.put(11,"Ты часто звонишь ему?");
        examRuPS.put(12,"Как он добирается домой?");
        examRuPS.put(13,"Что ты думаешь об этом?");
        examRuPS.put(14,"Он не знает это");
        examRuPS.put(15,"Что кажется бесполезным?");
        examRuPS.put(16,"У нас достаточно практики?");
        examRuPS.put(17,"Мне действительно нравятся эти уроки");
        examRuPS.put(18,"Он живет в этой стране");
        examRuPS.put(19,"Она хочет увидеть тебя прямо сейчас");
        examRuPS.put(20,"Я хочу быть счастливым");
        examRuPS.put(21,"У неё есть машина");
        examRuPS.put(22,"Он хочет жить за границей?");
        examRuPS.put(23,"Что твои друзья обычно заказывают?");
        examRuPS.put(24,"Он работает очень усердно");
        examRuPS.put(25,"Это зависит от них");
        examRuPS.put(26,"Какие у него есть Английские книги?");
        examRuPS.put(27,"Он хочет больше");
        examRuPS.put(28,"Я очень хорошо тебя понимаю");
        examRuPS.put(29,"Она объясняет все эти вещи очень хорошо");
        examRuPS.put(30,"Она любит тебя");
        examRuPS.put(31,"Эти уроки реально помогают");
        examRuPS.put(32,"Она делает те упражнения регулярно");
        examRuPS.put(33,"Она всегда делает это вовремя");
        examRuPS.put(34,"Что помогает тебе?");
        examRuPS.put(35,"Я хочу поехать за границу");
        examRuPS.put(36,"Мне нужны деньги");
        examRuPS.put(37,"Как часто она ходит в кино?");
        examRuPS.put(38,"Что она хочет добавить?");
        examRuPS.put(39,"Она работает очень усердно");
        examRuPS.put(40,"Моя сестра учится там");
        examRuPS.put(41,"Мне нравятся твои уроки");
        examRuPS.put(42,"Кто любит её?");
        examRuPS.put(43,"Я помню это");
        examRuPS.put(44,"Я хочу новый компьютер");
        examRuPS.put(45,"Что помогает ей?");
        examRuPS.put(46,"Она живет в этом месте");
        examRuPS.put(47,"Я хотел бы чашку коффе");
        examRuPS.put(48,"Это не кажется странным");
        examRuPS.put(49,"Что волнует тебя больше?");
        examRuPS.put(50,"Как это помогает тебе?");
        examRuPS.put(51,"Мои родители хотят сделать это");
        examRuPS.put(52,"Все люди делают это");
        examRuPS.put(53,"Сколько у него занимает по времени добраться до того места?");
        examRuPS.put(54,"Он не пытается найти хорошую работу");
        examRuPS.put(55,"Ты не пытаешся выучить Английский");
        examRuPS.put(56,"Какого рода примеры его учитель дает?");
        examRuPS.put(57,"Этот человек кажется очень хорошим?");
        examRuPS.put(58,"Это не кажется полезным");
        examRuPS.put(59,"Я думаю так");
        examRuPS.put(60,"Они ходят на работу");
        examRuPS.put(61,"Как она объясняет это?");
        examRuPS.put(62,"Ей нужно исправить эти ошибки");
        examRuPS.put(63,"Какую музыку ты предпочитаешь?");
        examRuPS.put(64,"Моя сестра живет там, но я живу сдесь");
        examRuPS.put(65,"Сколько по времени занимает у его дочери добраться в школу?");
        examRuPS.put(66,"Тебе нужно запомнить это правило");
        examRuPS.put(67,"Я живу в этой стране");
        examRuPS.put(68,"Ты помнишь это");
        examRuPS.put(69,"Я хожу на работу");
        examRuPS.put(70,"Мне нужно говорить по Английски вовсе без каких-либо ошибок");
        examRuPS.put(71,"Я все понимаю");
        examRuPS.put(72,"Это помогает мне");
        examRuPS.put(73,"Мне нравиться это");
        examRuPS.put(74,"Который напиток она предпочитает: чай или коффе?");
        examRuPS.put(75,"Ты поддерживаешь меня?");
        examRuPS.put(76,"Почему твои родители не согласны с тобой?");
        examRuPS.put(77,"Она чувствует себя такой счастливой");
        examRuPS.put(78,"Он ходит на работу");
        examRuPS.put(79,"Это зависит от нас");
        examRuPS.put(80,"Он не навидит эту вещь?");
        examRuPS.put(81,"Как часто ты ходишь туда?");
        examRuPS.put(82,"Мне нравиться эта идея");
        examRuPS.put(83,"Я не хочу учиться там");
        examRuPS.put(84,"Когда у тебя есть свободное время?");
        examRuPS.put(85,"Она смотрит различные фильмы");
        examRuPS.put(86,"Ты часто слушаешь музыку?");
        examRuPS.put(87,"Мне нравиться этот метод");
        examRuPS.put(88,"Она пытается понять это");
        examRuPS.put(89,"Это не вдохновляет меня");
        examRuPS.put(90,"Я хочу это");
        examRuPS.put(91,"Как часто ты думаешь об этом?");
        examRuPS.put(92,"Где они проводят время вместе?");
        examRuPS.put(93,"Я хотелбы выпить чашку коффе");
        examRuPS.put(94,"Когда он чувствует себя счастливым?");
        examRuPS.put(95,"Я не хочу жить в том городе");
        examRuPS.put(96,"Кто хочет жить за границей?");
        examRuPS.put(97,"Она не хочет обсуждать это");
        examRuPS.put(98,"Твои уроки реально помогают");
        examRuPS.put(99,"Он скучает по тебе");
        examRuPS.put(100,"Я делаю это с большим удовольствием");
        examRuPS.put(101,"Это привлекает меня");
        examRuPS.put(102,"Почему она отказывается платить?");
        examRuPS.put(103,"Этот урок кажется интересным");
        examRuPS.put(104,"Как ты добираешься домой?");
        examRuPS.put(105,"Он хочет больше практики");
        examRuPS.put(106,"Тот тест кажется очень легким?");
        examRuPS.put(107,"У нас достаточно знаний?");
        examRuPS.put(108,"Как ты проводишь своё свободное время?");
        examRuPS.put(109,"Она помнит все эти правила?");
        examRuPS.put(110,"Почему это происходит снова и снова?");
        examRuPS.put(111,"Они занимаются бизнесом?");
        examRuPS.put(112,"Она припадаёт Английский?");
        examRuPS.put(113,"Она читает на Английском");
        examRuPS.put(114,"Она очень хорошо говорит по Английски");
        examRuPS.put(115,"Они поддерживают нас?");
        examRuPS.put(116,"Эти кажутся очень полезными");
        examRuPS.put(117,"Он часто играет в компьютерные игры");
        examRuPS.put(118,"Я практикую Английский каждый день");
        examRuPS.put(119,"Мои родители знают это");
        examRuPS.put(120,"Кто исправляет твои ошибки?");
        examRuPS.put(121,"Её парень хочет поехать за границу?");
        examRuPS.put(122,"Почему он говорит эти вещи снова и снова?");
        examRuPS.put(123,"У него есть кот");
        examRuPS.put(124,"Кто видит эти ошибки?");
        examRuPS.put(125,"Эти вещи привлекают их");
        examRuPS.put(126,"Я вижу тебе реально нравится Английский");
        examRuPS.put(127,"Я хочу больше практики");
        examRuPS.put(128,"Он часто думает об этом?");
        examRuPS.put(129,"Почему ты думаешь так?");
        examRuPS.put(130,"Мы говорим по Английски");
        examRuPS.put(131,"Ты ходишь на работу?");
        examRuPS.put(132,"Ты работаешь над своими ошибками?");
        examRuPS.put(133,"Эти вещи кажутся не важными?");
        examRuPS.put(134,"Что твой босс обычно отвечает?");
        examRuPS.put(135,"Мне нужно учиться усерднее");
        examRuPS.put(136,"Где ты работаешь?");
        examRuPS.put(137,"Как регулярно ты практикуешь Английский?");
        examRuPS.put(138,"Он так же работает сдесь");
        examRuPS.put(139,"Этот студент показывает блестящие результаты?");
        examRuPS.put(140,"Он очень хорошо понимает тебя");
        examRuPS.put(141,"Что кажется странным?");
        examRuPS.put(142,"Я живу в России");
        examRuPS.put(143,"Мой друг не думает так");
        examRuPS.put(144,"У него есть предложение");
        examRuPS.put(145,"Почему он всегда жалуется об этом?");
        examRuPS.put(146,"Он знает больше");
        examRuPS.put(147,"Я все вижу");
        examRuPS.put(148,"Он не хочет читать эти книги");
        examRuPS.put(149,"Он часто смотрит телевизор?");
        examRuPS.put(150,"Он думает так");
        examRuPS.put(151,"Мне нравиться эта вещь");
        examRuPS.put(152,"Он припадает Английский");
        examRuPS.put(153,"Это не помогает мне");
        examRuPS.put(154,"Я не хочу играть в компьютерные игры");
        examRuPS.put(155,"Ты все помнишь?");
        examRuPS.put(156,"Тебе нужен мой совет?");
        examRuPS.put(157,"Мой босс читает все документы");
        examRuPS.put(158,"Она делает это очень хорошо");
        examRuPS.put(159,"Сколько денег у тебя с собой?");
        examRuPS.put(160,"Он видит ту ошибку");
        examRuPS.put(161,"Этот урок кажется полезным?");
        examRuPS.put(162,"Кто поддерживает тебя?");
        examRuPS.put(163,"Это кажется интересным");
        examRuPS.put(164,"Я не согласен с тобой");
        examRuPS.put(165,"Она скучает по тебе");
        examRuPS.put(166,"Они поддерживают это решение?");
        examRuPS.put(167,"Она действительно помнит это");
        examRuPS.put(168,"Я хочу поблагодарить тебя");
        examRuPS.put(169,"Я хочу знать это");
        examRuPS.put(170,"Мы живем в этой стране");
        examRuPS.put(171,"Мне действительно нужен Английский");
        examRuPS.put(172,"Как он поддерживает тебя?");
        examRuPS.put(173,"Мне нужно исправить эту ошибку");
        examRuPS.put(174,"Он так же знает это");
        examRuPS.put(175,"Как регулярно твой босс проверяет это?");
        examRuPS.put(176,"Как чувствует твоя сестра?");
        examRuPS.put(177,"Как регулярно он делает эти упражнения?");
        examRuPS.put(178,"Я хочу поехать в другое место");
        examRuPS.put(179,"Кого ты знаешь?");
        examRuPS.put(180,"Эта вещь кажется не важной");
        examRuPS.put(181,"Сколько у неё  занимает по времени добрать до этого места?");
        examRuPS.put(182,"Что он помнит?");
        examRuPS.put(183,"Почему ты согласен с ним?");
        examRuPS.put(184,"Это реально происходит");
        examRuPS.put(185,"Я хотел бы чашку чая");
        examRuPS.put(186,"Мне нужна эта вещь");
        examRuPS.put(187,"Он часто ходит в кино");
        examRuPS.put(188,"Я хочу тренировать свою память");
        examRuPS.put(189,"Они не занимаются бизнесом");
        examRuPS.put(190,"Я не хочу говорить об этом");
        examRuPS.put(191,"Она не хочет думать об этом");
        examRuPS.put(192,"Она хочет сделать это прямо сейчас");
        examRuPS.put(193,"Моему другу нужна твоя помощь");
        examRuPS.put(194,"Он игнорирует её слова?");
        examRuPS.put(195,"Твоему отцу нужно это?");
        examRuPS.put(196,"Почему это привлекает тебя?");
        examRuPS.put(197,"Я знаю им нравится это");
        examRuPS.put(198,"Он делает это каждый день");
        examRuPS.put(199,"Как регулярно ты занимаешься Английским?");
        examRuPS.put(200,"Это кажется интересным?");
        examRuPS.put(201,"Сколько долларов у него с собой?");
        examRuPS.put(202,"Они ходят в школу");
        examRuPS.put(203,"У меня достаточно денег?");
        examRuPS.put(204,"Я хочу сделать это");
        examRuPS.put(205,"Мой брат пытается делать это");
        examRuPS.put(206,"Она не помнит это");
        examRuPS.put(207,"Я говорю по Английски");
        examRuPS.put(208,"Его уроки кажутся очень полезными");
        examRuPS.put(209,"Что он хочет добавить?");
        examRuPS.put(210,"Почему твои друзья не согласны с тобой?");
        examRuPS.put(211,"Мы понимаем тебя");
        examRuPS.put(212,"Что ты хочешь сказать?");
        examRuPS.put(213,"Это выглядит интересным");
        examRuPS.put(214,"У него нет машины");
        examRuPS.put(215,"Нам нужно решить эту проблему");
        examRuPS.put(216,"Твоя мама говорит ему всю правду?");
        examRuPS.put(217,"Это вдохновляет меня");
        examRuPS.put(218,"Что вдохновляет тебя?");
        examRuPS.put(219,"Кого она любит?");
        examRuPS.put(220,"Она часто слушает радио?");
        examRuPS.put(221,"Я не хочу говорить тебе об этой проблеме");
        examRuPS.put(222,"Что тебе нравиться сдесь?");
        examRuPS.put(223,"Их идеи кажутся очень интересными");
        examRuPS.put(224,"Что ему нужно изменить?");
        examRuPS.put(225,"Его девушка понимает это?");
        examRuPS.put(226,"Я нахожу все эти уроки реально полезными");
        examRuPS.put(227,"Почему ты зависишь от него?");
        examRuPS.put(228,"Она так же работает там");
        examRuPS.put(229,"Как она тренирует свою память?");
        examRuPS.put(230,"Твои родители понимают это?");
        examRuPS.put(231,"Ты знаешь это");
        examRuPS.put(232,"Почему твой босс критикует это?");
        examRuPS.put(233,"Я вижу ему реально это нравится");
        examRuPS.put(234,"Я не хочу знать это");
        examRuPS.put(235,"Тот урок кажется скучным?");
        examRuPS.put(236,"Она игнорирует это иногда?");
        examRuPS.put(237,"Это привлекает его");
        examRuPS.put(238,"Она хочет поехать за границу?");
        examRuPS.put(239,"Я хочу говорить по Английски свободно и правильно");
        examRuPS.put(240,"Куда ты ходишь?");
        examRuPS.put(241,"Этот урок помогает мне");
        examRuPS.put(242,"Они часто критикуют его");
        examRuPS.put(243,"Её брат часто говорит это");
        examRuPS.put(244,"Тебе нравится то предложение?");
        examRuPS.put(245,"Она пытается выучить Английский");
        examRuPS.put(246,"Они видят свои ошибки?");
        examRuPS.put(247,"Тебе нравится это?");
        examRuPS.put(248,"Твой друг согласен с тобой?");
        examRuPS.put(249,"Моя сестра живет в этом месте");
        examRuPS.put(250,"У меня есть идея");
        examRuPS.put(251,"Как ты обычно добираешся до того места?");
        examRuPS.put(252,"Я не понимаю этих людей");
        examRuPS.put(253,"Как регулярно ты говоришь по Английски");
        examRuPS.put(254,"У него есть доллары");
        examRuPS.put(255,"Я знаю это");
        examRuPS.put(256,"Эта вещь привлекает меня");
        examRuPS.put(257,"В какое время она уходит из дома?");
        examRuPS.put(258,"Когда ты чувствуешь себя счастливой?");
        examRuPS.put(259,"Он хотел бы стать врачем");
        examRuPS.put(260,"Он делает так много ошибок");
        examRuPS.put(261,"Какие книги ты читаешь?");
        examRuPS.put(262,"Она ходит в школу");
        examRuPS.put(263,"Я поддерживаю это решение");
        examRuPS.put(264,"Кого это мотевирует?");
        examRuPS.put(265,"Это кажется бесполезным");
        examRuPS.put(266,"У тебя есть свободное время?");
        examRuPS.put(267,"Ты согласен с ним?");
        examRuPS.put(268,"Какие каналы он смотрит?");
        examRuPS.put(269,"Я хотел бы посетить это место");
        examRuPS.put(270,"Нам наравиться это");
        examRuPS.put(271,"Я люблю тебя");
        examRuPS.put(272,"В какое время твоя мама приходит на работу?");
        examRuPS.put(273,"Она смотрит ТВ");
        examRuPS.put(274,"Почему ты хочешь посетить это место?");
        examRuPS.put(275,"Кого он поддерживает?");
        examRuPS.put(276,"Он хочет купить эту вещь");
        examRuPS.put(277,"Она хочет больше практики");
        examRuPS.put(278,"Я не хочу сказать это");
        examRuPS.put(279,"Эта вещь кажется важной?");
        examRuPS.put(280,"Он часто говорит по Английски?");
        examRuPS.put(281,"Моему другу нравиться этот отель");
        examRuPS.put(282,"Я действительно хочу это");
        examRuPS.put(283,"Это кажется скучным?");
        examRuPS.put(284,"Я чувствую это");
        examRuPS.put(285,"Это происходит");
        examRuPS.put(286,"Какого рода компьютерные игры они играют?");
        examRuPS.put(287,"Мне нужно решить эти проблемы");
        examRuPS.put(288,"Мне нравиться этот канал");
        examRuPS.put(289,"Те уроки мне вовсе не помогают");
        examRuPS.put(290,"Почему это выглядит странным?");
        examRuPS.put(291,"Как часто ты ходишь в зал?");
        examRuPS.put(292,"Эта информация кажется не важной?");
        examRuPS.put(293,"Ты согласен с ней?");
        examRuPS.put(294,"Я работаю сдесь");
        examRuPS.put(295,"Что она хочет добавить?");
        examRuPS.put(296,"Я хотел бы очень хорошо знать Английский");
        examRuPS.put(297,"Наша мама думает так же");
        examRuPS.put(298,"То предложение кажется странным");
        examRuPS.put(299,"Этот проект кажется очень интересным");
        examRuPS.put(300,"Как он обычно проводит своё свободное время?");
        examRuPS.put(301,"Как она добирается домой?");
        examRuPS.put(302,"У него есть дом");
        examRuPS.put(303,"Её нужен твой совет");
        examRuPS.put(304,"Что они хотят сказать тебе?");
        examRuPS.put(305,"Мы не хотим жить в другом месте");
        examRuPS.put(306,"Мне действительно это нужно");
        examRuPS.put(307,"Что беспокоит тебя?");
        examRuPS.put(308,"Что ты хочешь сделать?");
        examRuPS.put(309,"У его отца есть машина");
        examRuPS.put(310,"Она хотела бы стать учительницей");
        examRuPS.put(311,"Что он пытается делать?");
        examRuPS.put(312,"Я хочу эту вещь");
        examRuPS.put(313,"Мой босс всегда говорит это");
        examRuPS.put(314,"Когда это происходит?");
        examRuPS.put(315,"У этой компании есть деньги");
        examRuPS.put(316,"У него есть компания. Её прибыль кажется такой большой");
        examRuPS.put(317,"Она помнит это");
        examRuPS.put(318,"Мне реально нужны твои уроки");
        examRuPS.put(319,"Те студенты говорят по Английски правильно?");
        examRuPS.put(320,"Я хочу говорить по Английски правильно");
        examRuPS.put(321,"Я хочу хорошую машину");
        examRuPS.put(322,"Где он работает?");
        examRuPS.put(323,"Как часто происходят эти вещи?");
        examRuPS.put(324,"Кто знает это?");
        examRuPS.put(325,"Она видит эту ошибку");
        examRuPS.put(326,"Я хочу улучшить свой Английский");
        examRuPS.put(327,"Мои родители хотят жить в другом месте");
        examRuPS.put(328,"Твои друзь согласны с тобой?");
        examRuPS.put(329,"Он игнорирует всё?");
        examRuPS.put(330,"Эти результаты мотивируют тебя?");
        examRuPS.put(331,"Ты хочешь знать свои ошибки?");
        examRuPS.put(332,"Ты согласен с ними?");
        examRuPS.put(333,"Мне нужно позвонить ему");
        examRuPS.put(334,"Что интересует тебя?");
        examRuPS.put(335,"Я действительно хочу улучшить свою граматику");
        examRuPS.put(336,"Я хочу поехать туда ещё один раз");
        examRuPS.put(337,"Я учусь здесь");
        examRuPS.put(338,"Я хочу этот компьютер");
        examRuPS.put(339,"Она часто говорит это?");
        examRuPS.put(340,"Я не знаю");
        examRuPS.put(341,"Тот студент делает ошибки?");
        examRuPS.put(342,"Нам нужно больше информации");
        examRuPS.put(343,"Они показывают блестящие результаты");
        examRuPS.put(344,"Мы помним это");
        examRuPS.put(345,"Ты часто посещаешь это место?");
        examRuPS.put(346,"Какие советы она даёт тебе?");
        examRuPS.put(347,"Ты часто делаешь это?");
        examRuPS.put(348,"Я хотел бы поехать за границу");
        examRuPS.put(349,"Почему это интересует его?");
        examRuPS.put(350,"У меня есть сестра");
        examRuPS.put(351,"Ему нужно это");
        examRuPS.put(352,"Ты поддерживаешь его?");
        examRuPS.put(353,"Что привлкает его там?");
        examRuPS.put(354,"Что она обычно говорит?");
        examRuPS.put(355,"Как ты решаешь эти проблемы?");
        examRuPS.put(356,"Что кажется важным?");
        examRuPS.put(357,"Он живет в этом доме");
        examRuPS.put(358,"Мне нужно это");
        examRuPS.put(359,"Что реально помогает тебе?");
        examRuPS.put(360,"Я вижу это");
        examRuPS.put(361,"В какое время ты ложишся спать?");
        examRuPS.put(362,"Он помогает мне");
        examRuPS.put(363,"Сколько у тебя друзей?");
        examRuPS.put(364,"Ей нужно это");
        examRuPS.put(365,"Это действительно мотивирует тебя?");
        examRuPS.put(366,"Кто поддерживает тебя?");
        examRuPS.put(367,"Ты часто пользуешься интернетом?");
        examRuPS.put(368,"У тебя достаточно денег с собой?");
        examRuPS.put(369,"Ты часто ходишь в зал?");
        examRuPS.put(370,"Они учатся очень усердно");
        examRuPS.put(371,"Он всегда обещает это");
        examRuPS.put(372,"Я хочу иметь хорошую работу");
        examRuPS.put(373,"Сколько ошибок ты обычно делаешь?");
        examRuPS.put(374,"Ты мне действительно нужна");
        examRuPS.put(375,"Он чувствет себя счастливым");
        examRuPS.put(376,"Мне не нравиться это");
        examRuPS.put(377,"Сколько Английских слов ты знаешь?");
        examRuPS.put(378,"Где живут твои родители?");
        examRuPS.put(379,"Мне нужно улучшить свой Английский");
        examRuPS.put(380,"Кто проверяет всю эту информацию?");
        examRuPS.put(381,"Что твой босс обычно обещает?");
        examRuPS.put(382,"Я хочу поехать туда ещё один раз");
        examRuPS.put(383,"Я думаю ему нужно изменить свою жизнь");
        examRuPS.put(384,"Она пытается найти новую работу?");
        examRuPS.put(385,"Я занимаюсь бизнесом");
        examRuPS.put(386,"Где работает твой отец?");
        examRuPS.put(387,"Она живет в том месте");
        examRuPS.put(388,"Куда она обычно ходит?");
        examRuPS.put(389,"Мы хотим это");
        examRuPS.put(390,"Он пытается помочь мне");
        examRuPS.put(391,"Что ты знаешь?");
        examRuPS.put(392,"Я думаю тебе нужно работать меньше");
        examRuPS.put(393,"Какие напитки она предпочитает?");
        examRuPS.put(394,"Твоему другу нравиться эта идея?");
        examRuPS.put(395,"Это действительно вдохновляет меня");
        examRuPS.put(396,"Эта информация кажется бесполезной?");
        examRuPS.put(397,"Ты поддерживаешь меня?");
        examRuPS.put(398,"Тебе нужна помощь?");
        examRuPS.put(399,"Ему не нужны эти деньги сейчас");
        examRuPS.put(400,"Ему нравится это платье");
        examRuPS.put(401,"Какие книги она предпочитает читать?");
        examRuPS.put(402,"Почему тебе нравиться этот канал?");
        examRuPS.put(403,"Он пытается найти больше времени для Английского");
        examRuPS.put(404,"Это реально помогает мне");
        examRuPS.put(405,"Мне нужно тренировать свою память");
        examRuPS.put(406,"Тебе нужно это");
        examRuPS.put(407,"Моя мама приходит домой рано");
        examRuPS.put(408,"Мне действительно нравится это место");
        examRuPS.put(409,"Это иногда происходит?");
        examRuPS.put(410,"Ей нравится эта профессия?");
        examRuPS.put(411,"Кто проверят всю информацию?");
        examRuPS.put(412,"Какой совет твои учителя дают тебе?");
        examRuPS.put(413,"Мой отец приходит домой поздно");
        examRuPS.put(414,"Мы не понимаем это");
        examRuPS.put(415,"Мы живем в России");
        examRuPS.put(416,"Твоей маме нужно работать меньше");
        examRuPS.put(417,"Я хотел бы стать бизнесменом");
        examRuPS.put(418,"Я хочу поехать туда снова");
        examRuPS.put(419,"Я очень хорошо знаю это");
        examRuPS.put(420,"Где она учится?");
        examRuPS.put(421,"Как регулярно твои учителя говорят тебе эти вещи?");
        examRuPS.put(422,"Это не работает");
        examRuPS.put(423,"Я хочу выучить Английский быстро");
        examRuPS.put(424,"Какие каналы он обычно смотрит?");
        examRuPS.put(425,"Я работаю там");
        examRuPS.put(426,"Что мотивирует тебя больше?");
        examRuPS.put(427,"Мой друг хочет проверить это ещё один раз");
        examRuPS.put(428,"Ты часто ходишь туда?");
        examRuPS.put(429,"Мне нравится это видео");
        examRuPS.put(430,"Тот метод кажется бесполезным");
        examRuPS.put(431,"Ей реально нравится это?");
        examRuPS.put(432,"Он хотел бы заказать это он-лайн");
        examRuPS.put(433,"Кого ты поддерживаешь?");
        examRuPS.put(434,"Сколько занимает у тебя по времени добраться до школы?");
        examRuPS.put(435,"Я не хочу жить в этой стране");
        examRuPS.put(436,"Эти студенты показывают блестящие результаты");
        examRuPS.put(437,"Они согласны с нами?");
        examRuPS.put(438,"Он объясняет все очень хорошо");
        examRuPS.put(439,"Как часто он ходит в зоопарк?");
        examRuPS.put(440,"Я хожу в школу");
        examRuPS.put(441,"У моего друга есть машина");
        examRuPS.put(442,"Мне нужно решить ту проблему");
        examRuPS.put(443,"Им нравится это");
        examRuPS.put(444,"Я не хочу обсуждать это");
        examRuPS.put(445,"Я действительно хочу это знать");
        examRuPS.put(446,"У него есть собака");
        examRuPS.put(447,"Как ты добираешься туда?");
        examRuPS.put(448,"Он живет там?");
        examRuPS.put(449,"Он хотел бы стать бизнесменом");
        examRuPS.put(450,"Ему нравиться это?");
        examRuPS.put(451,"Я хочу практиковать Английский сейчас");
        examRuPS.put(452,"Она ходит в школу с большим удовольствием");
        examRuPS.put(453,"Я хочу говорить по Английски без ощибок");
        examRuPS.put(454,"Тебе нужно запомнить это");
        examRuPS.put(455,"Нам нужно это");
        examRuPS.put(456,"Тебе нужно изменить это");
        examRuPS.put(457,"Она не хочет об этом думать");
        examRuPS.put(458,"Когда ты ходишь на работу?");
        examRuPS.put(459,"Я понимаю тебя");
        examRuPS.put(460,"Ей нужно прийти в то место?");
        examRuPS.put(461,"Почему они зависят от тебя?");
        examRuPS.put(462,"Сколько занимает у твоего по времени добраться туда?");
        examRuPS.put(463,"Какого рода книги ты читаешь?");
        examRuPS.put(464,"Почему твоя мама думает так?");
        examRuPS.put(465,"Он хочет сделать это");
        examRuPS.put(466,"Мне нравится этот совет");
        examRuPS.put(467,"Какой совет твои друзья дают тебе?");
        examRuPS.put(468,"Я хотел бы сделать это");
        examRuPS.put(469,"Он иногда играет в компьютерные игры");
        examRuPS.put(470,"Он платит за это?");
        examRuPS.put(471,"У меня есть машина");
        examRuPS.put(472,"Я работаю очень усердно");
        examRuPS.put(473,"Они не помогают мне");
        examRuPS.put(474,"Ему нравится этот проект?");
        examRuPS.put(475,"Этот экзамен кажется очень сложным?");
        examRuPS.put(476,"Ты помогаешь мне");
        examRuPS.put(477,"Я хотел бы попрактиковать Английский");
        examRuPS.put(478,"Я помню");
        examRuPS.put(479,"Мы живем здесь");
        examRuPS.put(480,"Как часто происходят эти вещи?");
        examRuPS.put(481,"Мой отец уходит из дома очень рано");
        examRuPS.put(482,"Он не работает там");
        examRuPS.put(483,"Он работает здесь");
        examRuPS.put(484,"Эти уроки помогают тебе?");
        examRuPS.put(485,"Мне нужно проверить это");
        examRuPS.put(486,"Она так же думает так");
        examRuPS.put(487,"У неё есть интресные идеи");
        examRuPS.put(488,"Почему те вещи происходят?");
        examRuPS.put(489,"Он действительно не навидит это");
        examRuPS.put(490,"Это выглядет странным");
        examRuPS.put(491,"Какие уроки твой учитель находит реально полезными?");
        examRuPS.put(492,"Ему нужно больше денег");
        examRuPS.put(493,"Что кажется таким интересным?");
        examRuPS.put(494,"Ей нравится это");
        examRuPS.put(495,"Он работает в другом месте?");
        examRuPS.put(496,"Он иногда хочет сделать это");
        examRuPS.put(497,"Мы показываем хорошие результаты?");
        examRuPS.put(498,"Ты видишь это");
        examRuPS.put(499,"Его отцу нужны деньги");
        examRuPS.put(500,"Это вовсе не интересует меня");
        examRuPS.put(501,"Ты говоришь по Английски очень хорошо");
        examRuPS.put(502,"Ему нужно найти хорошую работу");
        examRuPS.put(503,"Что она обычно говорит ему?");
        examRuPS.put(504,"Я хочу говорить по Английски лучше");
        examRuPS.put(505,"Он реально думает так");
        examRuPS.put(506,"У него нет этой информации");
        examRuPS.put(507,"Его отец занимается бизнесом?");
        examRuPS.put(508,"Они хотят решить эти проблемы прямо сейчас");
        examRuPS.put(509,"Я не хочу пить");
        examRuPS.put(510,"Где ты живешь?");
        examRuPS.put(511,"Почему тебе нужно сделать это сейчас?");
        examRuPS.put(512,"Почему он жалуется так часто?");
        examRuPS.put(513,"Это зависит от него");
        examRuPS.put(514,"Сколько по времени занимает у его сына добраться до работы?");
        examRuPS.put(515,"Мне нравится этот канал, так же");
        examRuPS.put(516,"Моему другу нужен твой совет прямо сейчас");
        examRuPS.put(517,"Мне нужно позвонить им");
        examRuPS.put(518,"Как часто ты слушаешь радио?");
        examRuPS.put(519,"Он часто слышит это?");
        examRuPS.put(520,"Она препадает это");
        examRuPS.put(521,"Тебе нужно больше денег?");
        examRuPS.put(522,"Почему твой друг хочет искать новую работу?");
        examRuPS.put(523,"У меня есть брат");
        examRuPS.put(524,"Как она тестирует их знания?");
        examRuPS.put(525,"Он не разделяет твою точку зрения");
        examRuPS.put(526,"Мне нужна эта информация");
        examRuPS.put(527,"Он читает на Английском");
        examRuPS.put(528,"Как регулярно твой учитель говорит это?");
        examRuPS.put(529,"Она хочет пойти в парк");
        examRuPS.put(530,"Мой брат хочет это");
        examRuPS.put(531,"Мне нравится этот плей лист");
        examRuPS.put(532,"Она хочет большего");
        examRuPS.put(533,"Им нужно это");
        examRuPS.put(534,"Я не хочу говорить тебе эту вещь");
        examRuPS.put(535,"Он также работат здесь");
        examRuPS.put(536,"Как ты обычно проводишь своё свободное время?");
        examRuPS.put(537,"Как он решает эти проблемы?");
        examRuPS.put(538,"Кто контролирует это?");
        examRuPS.put(539,"Кого он контролирует?");
        examRuPS.put(540,"Она хочет сделать это");
        examRuPS.put(541,"Он пытается делать это");
        examRuPS.put(542,"Какого рода фильмы она смотрит?");
        examRuPS.put(543,"Тебе нужно решить эту проблему прямо сейчас?");
        examRuPS.put(544,"Нам действительно нравится этот канал");
        examRuPS.put(545,"Ты ходишь в школу?");
        examRuPS.put(546,"Мой отец занимается бизнесом");
        examRuPS.put(547,"Мне нужно выучить Английский");
        examRuPS.put(548,"Мне действительно нравятся эти упражнения");
        examRuPS.put(549,"Я делаю ошибки?");
        examRuPS.put(550,"Ты знаешь об этой проблеме?");
        examRuPS.put(551,"Как часто происходит эта вещь?");
        examRuPS.put(552,"Сколько свободного вреимени у твоего бизнес партнера?");
        examRuPS.put(553,"Я хотел бы выпить чашку чая");
        examRuPS.put(554,"Мы хотим знать Английский");
        examRuPS.put(555,"Он так же помнит это");
        examRuPS.put(556,"Она помогает мне");
        examRuPS.put(557,"Их босс знает всю правду?");
        examRuPS.put(558,"Я учусь там");
        examRuPS.put(559,"Это реально помогает тебе?");
        examRuPS.put(560,"Я хотел бы поблагадарить тебя за всё");
        examRuPS.put(561,"Я хочу новую квартиру");
        examRuPS.put(562,"Он часто говорит тебе эти вещи?");
        examRuPS.put(563,"Кто обычно проверяет это?");
        examRuPS.put(564,"Я живу в этом городе");
        examRuPS.put(565,"Все люди знают это");
        examRuPS.put(566,"Я разделяю твою точку зрения");
        examRuPS.put(567,"Эти уроки помогают мне");
        examRuPS.put(568,"Мне нужно сделать это");
        examRuPS.put(569,"Сколько денег она платит?");
        examRuPS.put(570,"Эти студенты показывают очень хорошие результаты");
        examRuPS.put(571,"Мне действительно нужно это знать");
        examRuPS.put(572,"Кто ходит на работу?");
        examRuPS.put(573,"Её нужно позвонить ему?");
        examRuPS.put(574,"Кого ты обычно видишь там?");
        examRuPS.put(575,"Твой учитель видит это?");
        examRuPS.put(576,"Что кажется важным?");
        examRuPS.put(577,"Я очень хорошо помню это");
        examRuPS.put(578,"В какое время он приходит на работу?");
        examRuPS.put(579,"Что выглядит странным?");
        examRuPS.put(580,"Я хочу это платье");
        examRuPS.put(581,"Почему это кажется бесполезным?");
        examRuPS.put(582,"Мне нужно говорить по Английски без ошибок");
        examRuPS.put(583,"Это часто происходит?");
        examRuPS.put(584,"Она иногда ходит в кино");
        examRuPS.put(585,"Эти студенты показывают отличные результаты?");
        examRuPS.put(586,"Мне действительно нравиться этот плей лист");
        examRuPS.put(587,"Как часто ты пользуешся интернетом?");
        examRuPS.put(588,"Я думаю тебе нужно работать больше");
        examRuPS.put(589,"Мне нравиться Английский");
        examRuPS.put(590,"Мне нужно говорить по Английски правильно");
        examRuPS.put(591,"Я часто слушаю радио");
        examRuPS.put(592,"Этот результат мотивирует тебя?");
        examRuPS.put(593,"Тебе нравится это платье?");
        examRuPS.put(594,"Который канал он обычно смотрит?");
        examRuPS.put(595,"Я хочу это");
        examRuPS.put(596,"Как твой брат контролирует это?");
        examRuPS.put(597,"Как регулярно ты проверяешь это?");
        examRuPS.put(598,"Она читает Английские книги");
        examRuPS.put(599,"Я изучаю Ангилйский с тобой с огромным удовольствием");
        examRuPS.put(600,"Это кажется важным");
        examRuPS.put(601,"Почему он отказывается делать это?");
        examRuPS.put(602,"Я не хочу делать это прямо сейчас");
        examRuPS.put(603,"Она хочет жить в другом месте");
        examRuPS.put(604,"Кого это беспокоит?");
        examRuPS.put(605,"Твои друзья всегда поддерживают тебя?");
        examRuPS.put(606,"Она всегда делает это с огромным удовольствием");
        examRuPS.put(607,"Я не знаю этого человека");
        examRuPS.put(608,"Мой босс все знает");
        examRuPS.put(609,"Моему партнёру нужно решить эту проблему");
        examRuPS.put(610,"Этот канал помогает тебе?");
        examRuPS.put(611,"Ты согласна со мной?");
        examRuPS.put(612,"Сколько Английских слов твой друг хочет знать?");
        examRuPS.put(613,"Твой учитель объясняет всё очень хорошо?");
        examRuPS.put(614,"Почему ты хочешь знать Ангилйский?");
        examRuPS.put(615,"Мне так же нравится этот канал");
        examRuPS.put(616,"Это зависит от неё");
        examRuPS.put(617,"Я живу в этом городе");
        examRuPS.put(618,"Он любит тебя");
        examRuPS.put(619,"Я хочу купить новую квартиру");
        examRuPS.put(620,"Я хотел бы стать менеджером");
        examRuPS.put(621,"Что работает так хорошо?");
        examRuPS.put(622,"Ты работаешь очень усердно");
        examRuPS.put(623,"Ты понимаешь меня?");
        examRuPS.put(624,"Они занимаются бизнесом");
        examRuPS.put(625,"Кто всё проверяет?");
        examRuPS.put(626,"Она часто пользуется этим?");
        examRuPS.put(627,"Все твои идеи кажутся очень интересными");
        examRuPS.put(628,"Эти уроки не кажутся скучными");
        examRuPS.put(629,"Я чувствую себя счастливым");
        examRuPS.put(630,"Я хочу иметь хорошую машину");
        examRuPS.put(631,"Мы не разделяем твою точку зрения");
        examRuPS.put(632,"Они все знают");
        examRuPS.put(633,"Он часто жалуется об этом");
        examRuPS.put(634,"Она всё ему говорит?");
        examRuPS.put(635,"Они не хотят слушать её");
        examRuPS.put(636,"Он не пытается найти хорошую работу. Это кажется странным");
        examRuPS.put(637,"Ты пытаешься улучшить свой результат?");
        examRuPS.put(638,"Они помогают мне ");
        examRuPS.put(639,"Я не согалсен с тобой");
        examRuPS.put(640,"Ей нужно приходить сюда?");
        examRuPS.put(641,"Они поддерживают это решение?");
        examRuPS.put(642,"Какие Английские книги ты читаешь?");
        examRuPS.put(643,"Как ты добираешься до этого места?");
        examRuPS.put(644,"Мы думаем так");
        examRuPS.put(645,"Мы хотим намного больше практики");
        examRuPS.put(646,"Она живет в этом городе");
        examRuPS.put(647,"Сколько у тебя занимает это по времени добраться до работы?");
        examRuPS.put(648,"Он пытается найти работу");
        examRuPS.put(649,"Он ищет работу?");
        examRuPS.put(650,"Он знает это");
        examRuPS.put(651,"Сколько английских слов он хочет знать?");
        examRuPS.put(652,"Как ты добираешься до работы?");
        examRuPS.put(653,"Я вижу тебе это нравится");
        examRuPS.put(654,"Я делаю эти упражнения регулярно");
        examRuPS.put(655,"Она часто ходит в парк");
        examRuPS.put(656,"Как часто ты смотришь телевизор?");
        examRuPS.put(657,"Этот канал кажется очень интересным?");
        examRuPS.put(658,"Он всегда прлатит за неё?");
        examRuPS.put(659,"Как ты находишь эту идею?");
        examRuPS.put(660,"Кто мотивирует тебя?");
        examRuPS.put(661,"Сколько у тебя есть свободного времени?");
        examRuPS.put(662,"Это выгядит странным?");
        examRuPS.put(663,"Мой друг хочет жить за границей");
        examRuPS.put(664,"Мне нравитсся этот вопрос");
        examRuPS.put(665,"Она всегда критикует его");
        examRuPS.put(666,"Я обычно встаю рано");
        examRuPS.put(667,"Я действительно хочу говорит по английски свободно");
        examRuPS.put(668,"Я предпочитаю чай");
        examRuPS.put(669,"Она предпочитает коффе");
        examRuPS.put(670,"Ты помнишь это правило?");
        examRuPS.put(671,"Мы видим её успех (компании)");
        examRuPS.put(672,"Её слова вдохновляют нас");
        examRuPS.put(673,"Этот результат мотивирует меня");
        examRuPS.put(674,"Это зависит от нашего босса");
        examRuPS.put(675,"Что мотивирует тебя больше?");
        examRuPS.put(676,"Я хочу поблагадарить тебя за твой совет");
        examRuPS.put(677,"Я хотел бы поблагадарить тебя за твою помощь");
        examRuPS.put(678,"Как ты находишь эти уроки?");
        examRuPS.put(679,"Как ты находишь это место?");
        examRuPS.put(680,"Ты хочешь больше практики?");
        examRuPS.put(681,"Ты хочешь улучшить свой результат?");
        examRuPS.put(682,"Как часто ты ходишь в зоопарк?");
        examRuPS.put(683,"Кому ты обычно звонишь?");
        examRuPS.put(684,"Кто обычно звонит тебе?");
        examRuPS.put(685,"Что он отказывается сделать?");
        examRuPS.put(686,"Мне нужно тренировать свою память больше");
        examRuPS.put(687,"Она часто задаёт эти вопросы");
        examRuPS.put(688,"Он иногда отвечает");
        examRuPS.put(689,"Мне нравится твоё решение");
        examRuPS.put(690,"Я разделяю твою точку зрения");
        examRuPS.put(691,"Он всегда обещает это");
        examRuPS.put(692,"Что ты хочешь добавить?");
        examRuPS.put(693,"Я хочу иправить это");
        examRuPS.put(694,"Тебе нужно исправить эту ошибку");
        examRuPS.put(695,"Кто говорит эти вещи?");
        examRuPS.put(696,"Твоим друзьям нравится этот кнал?");
        examRuPS.put(697,"Моим друзьям реально это нравится");
        examRuPS.put(698,"Я нахожу эти видео очень полезными");
        examRuPS.put(699,"Я хотел бы полагадарить нашего учителя за всё");

        return examRuPS;
    }
}