package texts;

import java.util.HashMap;
import java.util.Map;

public class ExerciseTextToBe implements ITexts {

    /** Значения времени to be, языка Английский */
    private Map<Integer, String> toBeFileEn = new HashMap<>();

    /** Значения времени to be, языка Русский */
    private Map<Integer, String> toBeFileRu = new HashMap<>();

    /**
     * Функция получения списка значений на Английском языке времени to be
     * @return возвращает значения
     */
    @Override
    public Map<Integer, String> getEnglish() {
        getStrEnToBe();
        return toBeFileEn;
    }

    @Override
    public Map<Integer, String> getRussia() {
        getStrRuToBe();
        return toBeFileRu;
    }

    /**
     * Функция со значениями на Английском языке времени to be
     * @return возвращает список значений
     */
    private Map<Integer, String> getStrEnToBe(){
        toBeFileEn.put(0,"It's interesting");
        toBeFileEn.put(1,"I'm at home");
        toBeFileEn.put(2,"We're at home");
        toBeFileEn.put(3,"You're at home");
        toBeFileEn.put(4,"They're at home");
        toBeFileEn.put(5,"He's at home");
        toBeFileEn.put(6,"I'm happy");
        toBeFileEn.put(7,"You're right");
        toBeFileEn.put(8,"They're at work");
        toBeFileEn.put(9,"He's at school");
        toBeFileEn.put(10,"She's here");
        toBeFileEn.put(11,"It's there");
        toBeFileEn.put(12,"I'm sure");
        toBeFileEn.put(13,"We're in the park");
        toBeFileEn.put(14,"We're so happy");
        toBeFileEn.put(15,"We're friends");
        toBeFileEn.put(16,"He's right");
        toBeFileEn.put(17,"You're very kind");
        toBeFileEn.put(18,"You're a good person");
        toBeFileEn.put(19,"They're our friends");
        toBeFileEn.put(20,"They're rich");
        toBeFileEn.put(21,"They're poor");
        toBeFileEn.put(22,"They're lazy");
        toBeFileEn.put(23,"He's a doctor");
        toBeFileEn.put(24,"He's a manager");
        toBeFileEn.put(25,"He's my friend");
        toBeFileEn.put(26,"He's my boyfriend");
        toBeFileEn.put(27,"He's a businessman");
        toBeFileEn.put(28,"She's a teacher");
        toBeFileEn.put(29,"She's my girlfriend");
        toBeFileEn.put(30,"She's my teacher");
        toBeFileEn.put(31,"She's a student");
        toBeFileEn.put(32,"He's her husband");
        toBeFileEn.put(33,"She's his wife");
        toBeFileEn.put(34,"It's important");
        toBeFileEn.put(35,"It's very important");
        toBeFileEn.put(36,"It's so important");
        toBeFileEn.put(37,"It's difficult");
        toBeFileEn.put(38,"It's so difficult");
        toBeFileEn.put(39,"It's easy");
        toBeFileEn.put(40,"It's very easy");
        toBeFileEn.put(41,"It's good");
        toBeFileEn.put(42,"It's so bad");
        toBeFileEn.put(43,"It's a good result");
        toBeFileEn.put(44,"It's a very good result");
        toBeFileEn.put(45,"It's an interesting idea");
        toBeFileEn.put(46,"It's a very interesting idea");
        toBeFileEn.put(47,"It's a useful lesson");
        toBeFileEn.put(48,"It's a very useful lesson");
        toBeFileEn.put(49,"It's an easy lesson");
        toBeFileEn.put(50,"It's a very easy lesson");
        toBeFileEn.put(51,"It's a big success");
        toBeFileEn.put(52,"It's a very big success");
        toBeFileEn.put(53,"It's a high level");
        toBeFileEn.put(54,"It's a very high level");
        toBeFileEn.put(55,"It's a low level");
        toBeFileEn.put(56,"It's a very low level");
        toBeFileEn.put(57,"It's an important detail");
        toBeFileEn.put(58,"It's an informative lesson");
        toBeFileEn.put(59,"It's a very informative lesson");
        toBeFileEn.put(60,"It's a big mistake");
        toBeFileEn.put(61,"It's a very big mistake");
        toBeFileEn.put(62,"It's a small mistake");
        toBeFileEn.put(63,"It's a very small mistake");
        toBeFileEn.put(64,"It's a very important detail");
        toBeFileEn.put(65,"It's a brilliant result");
        toBeFileEn.put(66,"It's the best channel");
        toBeFileEn.put(67,"You're the best teacher");
        toBeFileEn.put(68,"You're the best teacher in the world");
        toBeFileEn.put(69,"It's the best example");
        toBeFileEn.put(70,"It's so boring");
        toBeFileEn.put(71,"It's very boring");
        toBeFileEn.put(72,"It's too boring");
        toBeFileEn.put(73,"It's too easy");
        toBeFileEn.put(74,"It's too difficult");
        toBeFileEn.put(75,"It's too expensive");
        toBeFileEn.put(76,"It's cheap");
        toBeFileEn.put(77,"It's the best course");
        toBeFileEn.put(78,"It's cold!");
        toBeFileEn.put(79,"It's warm!");
        toBeFileEn.put(80,"It's hot!");
        toBeFileEn.put(81,"It's rainy!");
        toBeFileEn.put(82,"It's sunny!");
        toBeFileEn.put(83,"It's dark!");
        toBeFileEn.put(84,"It's a cold day");
        toBeFileEn.put(85,"It's a warm day");
        toBeFileEn.put(86,"It's a hot day");
        toBeFileEn.put(87,"It's too hot");
        toBeFileEn.put(88,"It's too cold");
        toBeFileEn.put(89,"It's obvious");
        toBeFileEn.put(90,"She's a very beautiful girl");
        toBeFileEn.put(91,"It's simple");
        toBeFileEn.put(92,"It's possible");
        toBeFileEn.put(93,"It's impossible");
        toBeFileEn.put(94,"I'm ready");
        toBeFileEn.put(95,"It's on the right");
        toBeFileEn.put(96,"It's on the left");
        toBeFileEn.put(97,"I'm fine");
        toBeFileEn.put(98,"It's better");
        toBeFileEn.put(99,"It's worse");
        toBeFileEn.put(100,"He's a young man");
        toBeFileEn.put(101,"It's such an interesting story");
        toBeFileEn.put(102,"It's such an important meeting");
        toBeFileEn.put(103,"It's so popular");
        toBeFileEn.put(104,"It's such a popular song");
        toBeFileEn.put(105,"It's such a difficult exam");
        toBeFileEn.put(106,"It's such an easy test");
        toBeFileEn.put(107,"He's a professional teacher");
        toBeFileEn.put(108,"He's such a professional teacher");
        toBeFileEn.put(109,"It's an expensive car");
        toBeFileEn.put(110,"It's such an expensive car");
        toBeFileEn.put(111,"She's beautiful");
        toBeFileEn.put(112,"She's so beautiful");
        toBeFileEn.put(113,"She's very beautiful");
        toBeFileEn.put(114,"She's a beautiful girl");
        toBeFileEn.put(115,"She's such a beautiful girl");
        toBeFileEn.put(116,"It's an easy exerciseT");
        toBeFileEn.put(117,"It's such an easy exerciseT");
        toBeFileEn.put(118,"It's so useful");
        toBeFileEn.put(119,"It's such a useful video");
        toBeFileEn.put(120,"It's such a bad situation");
        toBeFileEn.put(121,"It's so cheap");
        toBeFileEn.put(122,"It's such a cheap thing");
        toBeFileEn.put(123,"He's so strange");
        toBeFileEn.put(124,"He's such a strange person");
        toBeFileEn.put(125,"He's so clever");
        toBeFileEn.put(126,"He's such a clever man");
        toBeFileEn.put(127,"He's talented");
        toBeFileEn.put(128,"He's such a talented boy");
        toBeFileEn.put(129,"He's such a poor boy");
        toBeFileEn.put(130,"It's so effective");
        toBeFileEn.put(131,"It's such an effective method");
        toBeFileEn.put(132,"She's such a smart girl");
        toBeFileEn.put(133,"She's so kind");
        toBeFileEn.put(134,"She's such a kind woman");
        toBeFileEn.put(135,"She's such a wise woman");
        toBeFileEn.put(136,"It's such a simple answer");
        toBeFileEn.put(137,"My friend is at home");
        toBeFileEn.put(138,"My mother is at work");
        toBeFileEn.put(139,"Their idea is very interesting");
        toBeFileEn.put(140,"This lesson is very useful");
        toBeFileEn.put(141,"These lessons are very useful");
        toBeFileEn.put(142,"This year is very difficult");
        toBeFileEn.put(143,"This video is very informative");
        toBeFileEn.put(144,"These videos are very informative");
        toBeFileEn.put(145,"All these videos are very useful");
        toBeFileEn.put(146,"All your videos are so interesting");
        toBeFileEn.put(147,"This student is so hard-working");
        toBeFileEn.put(148,"These students are very lazy");
        toBeFileEn.put(149,"My boss is very busy now");
        toBeFileEn.put(150,"Her boss is very busy at the moment");
        toBeFileEn.put(151,"I have a computer! The computer is new!");
        toBeFileEn.put(152,"I have a car! The car is very good!");
        toBeFileEn.put(153,"This boy is very clever");
        toBeFileEn.put(154,"The boy is very clever");
        toBeFileEn.put(155,"The exam is difficult");
        toBeFileEn.put(156,"The addText is easy");
        toBeFileEn.put(157,"The lesson is useful");
        toBeFileEn.put(158,"The lesson is interesting");
        toBeFileEn.put(159,"The rule is very important");
        toBeFileEn.put(160,"This man is a doctor");
        toBeFileEn.put(161,"These men are managers");
        toBeFileEn.put(162,"That woman is a designer");
        toBeFileEn.put(163,"Those women are teachers");
        toBeFileEn.put(164,"These lessons are so effective");
        toBeFileEn.put(165,"Those lessons are ineffective");
        toBeFileEn.put(166,"This problem is very big");
        toBeFileEn.put(167,"These problems are small");
        toBeFileEn.put(168,"These lessons are really good");
        toBeFileEn.put(169,"This information is really useful");
        toBeFileEn.put(170,"This thing is very important");
        toBeFileEn.put(171,"These things are very important");
        toBeFileEn.put(172,"Time is money");
        toBeFileEn.put(173,"Money is important");
        toBeFileEn.put(174,"English is easy");
        toBeFileEn.put(175,"Chinese is very difficult");
        toBeFileEn.put(176,"Love is a wonderful feeling");
        toBeFileEn.put(177,"Knowledge is power");
        toBeFileEn.put(178,"This place is very beautiful");
        toBeFileEn.put(179,"This company is very rich");
        toBeFileEn.put(180,"I'm Russia");
        toBeFileEn.put(181,"He's American");
        toBeFileEn.put(182,"I'm twenty");
        toBeFileEn.put(183,"She's thirty");
        toBeFileEn.put(184,"My mother is a doctor! She's forty");
        toBeFileEn.put(185,"I'm twenty-one");
        toBeFileEn.put(186,"My brother is 21");
        toBeFileEn.put(187,"His wife is 32");
        //Отрицания
        toBeFileEn.put(188,"The day is windy");
        toBeFileEn.put(189,"This word is new for me");
        toBeFileEn.put(190,"I'm not at home");
        toBeFileEn.put(191,"We aren't at home");
        toBeFileEn.put(192,"He isn't at home");
        toBeFileEn.put(193,"I'm not married");
        toBeFileEn.put(194,"I'm single");
        toBeFileEn.put(195,"I'm not a manager. I'm a teacher");
        toBeFileEn.put(196,"I'm not at home. I'm at work.");
        toBeFileEn.put(197,"I'm not a student. I work");
        toBeFileEn.put(198,"We aren't tired");
        toBeFileEn.put(199,"We're full of energy");
        toBeFileEn.put(200,"We aren't stupid. We're clever");
        toBeFileEn.put(201,"We aren't angry. We're very kind");
        toBeFileEn.put(202,"We aren't sad. We're happy");
        toBeFileEn.put(203,"You aren't right / You are wrong");
        toBeFileEn.put(204,"You aren't in this place");
        toBeFileEn.put(205,"You aren't in the first place");
        toBeFileEn.put(206,"You're in the second place");
        toBeFileEn.put(207,"They aren't together");
        toBeFileEn.put(208,"They aren't my colleagues");
        toBeFileEn.put(209,"They aren't successful / They're unsuccessful");
        toBeFileEn.put(210,"They aren't businessmen");
        toBeFileEn.put(211,"He isn't old");
        toBeFileEn.put(212,"He isn't poor");
        toBeFileEn.put(213,"He isn't a director");
        toBeFileEn.put(214,"He isn't in the city");
        toBeFileEn.put(215,"She isn't here");
        toBeFileEn.put(216,"She isn't a singer. She's an actress");
        toBeFileEn.put(217,"She isn't free");
        toBeFileEn.put(218,"She isn't with him");
        toBeFileEn.put(219,"It isn't warm");
        toBeFileEn.put(220,"It isn't rainy");
        toBeFileEn.put(221,"It isn't the same");
        toBeFileEn.put(222,"It isn't so easy");
        toBeFileEn.put(223,"It isn't far");
        toBeFileEn.put(224,"It isn't near");
        toBeFileEn.put(225,"It isn't a good method");
        toBeFileEn.put(226,"It's such a bad method");
        toBeFileEn.put(227,"I prefer these lessons");
        // Вопросы
        toBeFileEn.put(228,"You're happy");
        toBeFileEn.put(229,"Are you happy?");
        toBeFileEn.put(230,"You're with her");
        toBeFileEn.put(231,"Are you with her?");
        toBeFileEn.put(232,"Am I right?");
        toBeFileEn.put(233,"Are we in the first place?");
        toBeFileEn.put(234,"Are you together?");
        toBeFileEn.put(235,"Are they at work?");
        toBeFileEn.put(236,"Is he her boyfriend?");
        toBeFileEn.put(237,"Is she his girlfriend?");
        toBeFileEn.put(238,"Is it a special offer?");
        toBeFileEn.put(239,"Am I in the right place?");
        toBeFileEn.put(240,"Am I talented?");
        toBeFileEn.put(241,"Am I lucky?");
        toBeFileEn.put(242,"Are we in the wrong place?");
        toBeFileEn.put(243,"Are we the best students?");
        toBeFileEn.put(244,"Are we hard-working?");
        toBeFileEn.put(245,"Are you from the United States?");
        toBeFileEn.put(246,"Are you here?");
        toBeFileEn.put(247,"Are you there?");
        toBeFileEn.put(248,"Are you sure?");
        toBeFileEn.put(249,"Are you really sure?");
        toBeFileEn.put(250,"Are they from Spain?");
        toBeFileEn.put(251,"Are they far?");
        toBeFileEn.put(252,"Are they in another country?");
        toBeFileEn.put(253,"Is he from Russia?");
        toBeFileEn.put(254,"Is he their client?");
        toBeFileEn.put(255,"Is he her boss?");
        toBeFileEn.put(256,"Is he a successful businessman?");
        toBeFileEn.put(257,"Is he in the building?");
        toBeFileEn.put(258,"Is she from Italy?");
        toBeFileEn.put(259,"Is she in her room?");
        toBeFileEn.put(260,"Is she abroad?");
        toBeFileEn.put(261,"Is he young?");
        toBeFileEn.put(262,"Is he a director?");
        toBeFileEn.put(263,"Is it effective?");
        toBeFileEn.put(264,"Is it an effective method?");
        toBeFileEn.put(265,"Is it so effective?");
        toBeFileEn.put(266,"Is it such an effective method?");
        toBeFileEn.put(267,"Is it his version?");
        toBeFileEn.put(268,"Is it her opinion?");
        toBeFileEn.put(269,"Is it his point of view?");
        toBeFileEn.put(270,"Is it your decision?");
        toBeFileEn.put(271,"Is it his own flat?");
        toBeFileEn.put(272,"Is it her own house?");
        toBeFileEn.put(273,"Is it a global problem?");
        toBeFileEn.put(274,"Is it a funny video?");
        toBeFileEn.put(275,"Is it an interesting newspaper?");
        toBeFileEn.put(276,"Is it a boring magazine?");
        toBeFileEn.put(277,"Is it dangerous?");
        toBeFileEn.put(278,"Is it for children?");
        toBeFileEn.put(279,"Is it expensive?");
        toBeFileEn.put(280,"Is it cheap?");
        toBeFileEn.put(281,"Is he a student?");
        toBeFileEn.put(282,"Is she a student?");
        toBeFileEn.put(283,"Is it the same?");
        toBeFileEn.put(284,"Is it a problem?");
        toBeFileEn.put(285,"Is it a big problem?");
        toBeFileEn.put(286,"Is it such a big problem?");
        toBeFileEn.put(287,"Is it a very big problem?");
        toBeFileEn.put(288,"Is it a good answer?");
        toBeFileEn.put(289,"Is it only for children?");
        toBeFileEn.put(290,"Is it a good result?");
        toBeFileEn.put(291,"Is it an excellent result?");
        toBeFileEn.put(292,"Is it a brilliant result?");
        toBeFileEn.put(293,"Is it a very useful video?");
        toBeFileEn.put(294,"Is it not here?");
        toBeFileEn.put(295,"Is it cold here?");
        toBeFileEn.put(296,"Is it warm here?");
        toBeFileEn.put(297,"Is his video funny?");
        toBeFileEn.put(298,"Is this project so interesting?");
        toBeFileEn.put(299,"Is this information really useful?");
        toBeFileEn.put(300,"Is his computer new?");
        toBeFileEn.put(301,"Is it a powerful computer?");
        toBeFileEn.put(302,"Is this knowledge enough?");
        toBeFileEn.put(303,"Is this story so funny?");
        toBeFileEn.put(304,"Is his father a businessman?");
        toBeFileEn.put(305,"Is his mother a doctor?");
        toBeFileEn.put(306,"Are his parents abroad?");
        toBeFileEn.put(307,"Is your girlfriend nineteen?");
        toBeFileEn.put(308,"Is your boyfriend twenty-too?");
        toBeFileEn.put(309,"Is this thing so important?");
        toBeFileEn.put(310,"Are these things so important?");
        toBeFileEn.put(311,"Is this business profitable?");
        toBeFileEn.put(312,"Is your father at work?");
        toBeFileEn.put(313,"Is your mother at school?");
        toBeFileEn.put(314,"Are your friends online?");
        toBeFileEn.put(315,"Is this practice really important?");
        toBeFileEn.put(316,"Is this language difficult?");
        toBeFileEn.put(317,"Is this addText too easy?");
        toBeFileEn.put(318,"Is this addText too difficult?");
        toBeFileEn.put(319,"Are these exercisesT so useful?");
        toBeFileEn.put(320,"Are those exercisesT useless?");
        toBeFileEn.put(321,"Is this word new for you?");
        toBeFileEn.put(322,"Are these words new for you?");
        toBeFileEn.put(323,"Is this text simple?");
        toBeFileEn.put(324,"Are these texts too difficult?");
        toBeFileEn.put(325,"Is the boy at home?");
        toBeFileEn.put(326,"Are the boys at school?");
        toBeFileEn.put(327,"Is the book so interesting?");
        toBeFileEn.put(328,"Is the book boring?");
        toBeFileEn.put(329,"Is the lesson useful?");
        toBeFileEn.put(330,"Are the lessons really useful?");
        toBeFileEn.put(331,"Is the channel very popular?");
        toBeFileEn.put(332,"Is the university famous?");
        toBeFileEn.put(333,"Is the teacher right?");
        toBeFileEn.put(334,"Is his decision right?");
        toBeFileEn.put(335,"Is the article in English?");
        toBeFileEn.put(336,"Are the articles in Russian?");
        toBeFileEn.put(337,"Is the article about politics?");
        toBeFileEn.put(338,"Is the game interesting?");
        toBeFileEn.put(339,"Is the food good?");
        toBeFileEn.put(340,"Is the airport near?");
        toBeFileEn.put(341,"Is time money?");
        toBeFileEn.put(342,"Is money important?");
        toBeFileEn.put(343,"Is knowledge power?");
        toBeFileEn.put(344,"Is this information enough?");
        toBeFileEn.put(345,"Is this level enough?");
        toBeFileEn.put(346,"Is this money enough?");
        toBeFileEn.put(347,"Is the news interesting?");
        toBeFileEn.put(348,"Is the news important?");
        toBeFileEn.put(349,"It this news interesting?");
        toBeFileEn.put(350,"Is this news important?");
        toBeFileEn.put(351,"Where is it?");
        toBeFileEn.put(352,"Where are you?");
        toBeFileEn.put(353,"Where is she?");
        toBeFileEn.put(354,"Where is he?");
        toBeFileEn.put(355,"What is it?");
        toBeFileEn.put(356,"What is there?");
        toBeFileEn.put(357,"What is here?");
        toBeFileEn.put(358,"What's in this box?");
        toBeFileEn.put(359,"What's in your bag?");
        toBeFileEn.put(360,"What's in your pocket?");
        toBeFileEn.put(361,"What's interesting?");
        toBeFileEn.put(362,"What's strange?");
        toBeFileEn.put(363,"What's important?");
        toBeFileEn.put(364,"What's really important?");
        toBeFileEn.put(365,"What's really useful?");
        toBeFileEn.put(366,"What's normal?");
        toBeFileEn.put(367,"What's next?");
        toBeFileEn.put(368,"Why are you here?");
        toBeFileEn.put(369,"Why is he at work now?");
        toBeFileEn.put(370,"Why are you so happy?");
        toBeFileEn.put(371,"Why is he angry?");
        toBeFileEn.put(372,"Why are you against it?");
        toBeFileEn.put(373,"How are you?");
        toBeFileEn.put(374,"How is he?");
        toBeFileEn.put(375,"How is she?");
        toBeFileEn.put(376,"How is it?");
        toBeFileEn.put(377,"When are you free?");
        toBeFileEn.put(378,"When are you busy?");
        toBeFileEn.put(379,"When is he at work?");
        toBeFileEn.put(380,"When is she at home?");
        toBeFileEn.put(381,"Who is there?");
        toBeFileEn.put(382,"Who is here?");
        toBeFileEn.put(383,"Who is in the room?");
        toBeFileEn.put(384,"Who is at home?");
        toBeFileEn.put(385,"Who is at work?");
        toBeFileEn.put(386,"Who is in the park?");
        toBeFileEn.put(387,"Who is right?");
        toBeFileEn.put(388,"Who is wrong?");
        toBeFileEn.put(389,"Who is in the first place?");
        toBeFileEn.put(390,"Who is in the second place?");
        toBeFileEn.put(391,"Who is he?");
        toBeFileEn.put(392,"Who is she?");
        toBeFileEn.put(393,"Who's next?");
        toBeFileEn.put(394,"How far is it?");
        toBeFileEn.put(395,"How expensive is it?");
        toBeFileEn.put(396,"How interesting is it?");
        toBeFileEn.put(397,"How useful is it?");
        toBeFileEn.put(398,"How difficult is it?");
        toBeFileEn.put(399,"How good is it?");
        toBeFileEn.put(400,"How old are you?");
        toBeFileEn.put(401,"How old is he?");
        toBeFileEn.put(402,"How old is she?");
        toBeFileEn.put(403,"What time is it?/What's the time?");
        toBeFileEn.put(404,"How much is it?");
        toBeFileEn.put(405,"What's your name?");
        toBeFileEn.put(406,"What's her name?");
        toBeFileEn.put(407,"What's his name?");
        toBeFileEn.put(408,"What's your girlfriend's name?");
        toBeFileEn.put(409,"What's your boyfriend's name?");
        toBeFileEn.put(410,"What's your friend's name?");
        toBeFileEn.put(411,"What's your best friend's name?");
        toBeFileEn.put(412,"How is this playlist?");
        toBeFileEn.put(413,"How is the channel?");
        toBeFileEn.put(414,"How is the party?");
        toBeFileEn.put(415,"How is the movie?");
        toBeFileEn.put(416,"How is this addText?");
        toBeFileEn.put(417,"How is this exerciseT?");
        toBeFileEn.put(418,"How are these exercisesT?");
        toBeFileEn.put(419,"Where is this place?");
        toBeFileEn.put(420,"Where is the nearest supermarket?");
        toBeFileEn.put(421,"Where is your room?");
        toBeFileEn.put(422,"Where is your husband?");
        toBeFileEn.put(423,"Where is your wife?");
        toBeFileEn.put(424,"Who is that woman?");
        toBeFileEn.put(425,"Who is that man?");
        toBeFileEn.put(426,"Who are these people?");
        toBeFileEn.put(427,"Who are those people?");
        toBeFileEn.put(428,"Why is this video so interesting?");
        toBeFileEn.put(429,"Why is this channel so popular?");
        toBeFileEn.put(430,"Why is this rule so important?");
        toBeFileEn.put(431,"Why are these rules so important?");
        toBeFileEn.put(432,"Why is that lesson so ineffective?");
        toBeFileEn.put(433,"Why are those lessons so ineffective?");
        toBeFileEn.put(434,"How old is your mother?");
        toBeFileEn.put(435,"How old is your father?");
        toBeFileEn.put(436,"How old is your brother?");
        toBeFileEn.put(437,"How old is your sister?");
        toBeFileEn.put(438,"What's your job?");
        toBeFileEn.put(439,"What's his job?");
        toBeFileEn.put(440,"What's her job?");
        toBeFileEn.put(441,"What's your mother's job?");
        toBeFileEn.put(442,"What's your father's job?");
        toBeFileEn.put(443,"What's your wife's job?");
        toBeFileEn.put(444,"What's your husband is job?");
        toBeFileEn.put(445,"How interesting is this magazine?");
        toBeFileEn.put(446,"How good is this lesson?");
        toBeFileEn.put(447,"How good is the lesson?");
        toBeFileEn.put(448,"How useful is the lesson?");
        toBeFileEn.put(449,"How difficult is the addText?");
        toBeFileEn.put(450,"How difficult is this exerciseT?");
        toBeFileEn.put(451,"How difficult are these exercisesT?");
        toBeFileEn.put(452,"How much is this dress?");
        toBeFileEn.put(453,"How much is the dress?");
        toBeFileEn.put(454,"How much is this computer?");
        toBeFileEn.put(455,"How much is the computer?");
        toBeFileEn.put(456,"How much does the computer cost?");
        toBeFileEn.put(457,"How much are these trousers?");
        toBeFileEn.put(458,"How much is this pair of trousers?");
        toBeFileEn.put(459,"How much are these jeans?");
        toBeFileEn.put(460,"How much is this pair of jeans?");
        toBeFileEn.put(461,"How much is one English lesson?");


        return toBeFileEn;
    }

    /**
     * Функция со значениями на Русском языке времени to be
     * @return возвращает список значений
     */
    private Map<Integer, String> getStrRuToBe(){
        toBeFileRu.put(0,"Это интересно");
        toBeFileRu.put(1,"Я дома");
        toBeFileRu.put(2,"Мы дома");
        toBeFileRu.put(3,"Ты дома");
        toBeFileRu.put(4,"Они дома");
        toBeFileRu.put(5,"Он дома");
        toBeFileRu.put(6,"Я счастлив");
        toBeFileRu.put(7,"Ты прав");
        toBeFileRu.put(8,"Они на работе");
        toBeFileRu.put(9,"Он в школе");
        toBeFileRu.put(10,"Она сдесь");
        toBeFileRu.put(11,"Это там");
        toBeFileRu.put(12,"Я уверен");
        toBeFileRu.put(13,"Мы в парке");
        toBeFileRu.put(14,"Мы так счастливы");
        toBeFileRu.put(15,"Мы друзья");
        toBeFileRu.put(16,"Он прав");
        toBeFileRu.put(17,"Ты очень добрый");
        toBeFileRu.put(18,"Ты хороший человек");
        toBeFileRu.put(19,"Они наши друзья");
        toBeFileRu.put(20,"Они богатые");
        toBeFileRu.put(21,"Они бедные");
        toBeFileRu.put(22,"Они ленивые");
        toBeFileRu.put(23,"Он врач");
        toBeFileRu.put(24,"Он менеджер");
        toBeFileRu.put(25,"Он мой друг");
        toBeFileRu.put(26,"Он мой парень");
        toBeFileRu.put(27,"Он бизнесмен");
        toBeFileRu.put(28,"Она учительница");
        toBeFileRu.put(29,"Она моя девушка");
        toBeFileRu.put(30,"Она моя учительница");
        toBeFileRu.put(31,"Она студентка");
        toBeFileRu.put(32,"Он её муж");
        toBeFileRu.put(33,"Она его жена");
        toBeFileRu.put(34,"Это важно");
        toBeFileRu.put(35,"Это очень важно");
        toBeFileRu.put(36,"Это так важно");
        toBeFileRu.put(37,"Это сложно");
        toBeFileRu.put(38,"Это так сложно");
        toBeFileRu.put(39,"Это легко");
        toBeFileRu.put(40,"Это очень легко");
        toBeFileRu.put(41,"Это хорошо");
        toBeFileRu.put(42,"Это так плохо");
        toBeFileRu.put(43,"Это хороший результат");
        toBeFileRu.put(44,"Это очень хороший результат");
        toBeFileRu.put(45,"Это интересная идея");
        toBeFileRu.put(46,"Это очень интересная идея");
        toBeFileRu.put(47,"Это полезный урок");
        toBeFileRu.put(48,"Это очень полезный урок");
        toBeFileRu.put(49,"Это легкий урок");
        toBeFileRu.put(50,"Это очень легий урок");
        toBeFileRu.put(51,"Это большой упех");
        toBeFileRu.put(52,"Это очень большой успех");
        toBeFileRu.put(53,"Это высокий уровень");
        toBeFileRu.put(54,"Это очень высокий уровень");
        toBeFileRu.put(55,"Это низкий уровень");
        toBeFileRu.put(56,"Это очень низкий уровень");
        toBeFileRu.put(57,"Это важная деталь");
        toBeFileRu.put(58,"Это информативный урок");
        toBeFileRu.put(59,"Это очень информативный урок");
        toBeFileRu.put(60,"Это большая ошибка");
        toBeFileRu.put(61,"Это очень большая ошибка");
        toBeFileRu.put(62,"Это маленькая ошибка");
        toBeFileRu.put(63,"Это очень маленькая ошибка");
        toBeFileRu.put(64,"Это очень важная деталь");
        toBeFileRu.put(65,"Это блестящий результат");
        toBeFileRu.put(66,"Это лучший канал");
        toBeFileRu.put(67,"Ты лучший учитель");
        toBeFileRu.put(68,"Ты лучший учитель в мире");
        toBeFileRu.put(69,"Это лучший пример");
        toBeFileRu.put(70,"Это так скучно");
        toBeFileRu.put(71,"Это очень скучно");
        toBeFileRu.put(72,"Это слишком скучно");
        toBeFileRu.put(73,"Это слишком легко");
        toBeFileRu.put(74,"Это слишком сложно");
        toBeFileRu.put(75,"Это слишком дорого");
        toBeFileRu.put(76,"Это дешево");
        toBeFileRu.put(77,"Это самый лучший курс");
        toBeFileRu.put(78,"Холодно!");
        toBeFileRu.put(79,"Тепло!");
        toBeFileRu.put(80,"Жарко!");
        toBeFileRu.put(81,"Дождливо!");
        toBeFileRu.put(82,"Солнечно!");
        toBeFileRu.put(83,"Темно!");
        toBeFileRu.put(84,"Это холодный день");
        toBeFileRu.put(85,"Это теплый день");
        toBeFileRu.put(86,"Это жаркий день");
        toBeFileRu.put(87,"Слишком жарко");
        toBeFileRu.put(88,"Слишком холодно");
        toBeFileRu.put(89,"Это очевидно");
        toBeFileRu.put(90,"Она очень красивая девушка");
        toBeFileRu.put(91,"Это просто");
        toBeFileRu.put(92,"Это возможно");
        toBeFileRu.put(93,"Это не возможно");
        toBeFileRu.put(94,"Я готов");
        toBeFileRu.put(95,"Это справа");
        toBeFileRu.put(96,"Это слева");
        toBeFileRu.put(97,"Я в порядке");
        toBeFileRu.put(98,"Это лучше");
        toBeFileRu.put(99,"Это хуже");
        toBeFileRu.put(100,"Он молодой человек");
        toBeFileRu.put(101,"Это такая интересная история");
        toBeFileRu.put(102,"Это такая важная встреча");
        toBeFileRu.put(103,"Это так популярно");
        toBeFileRu.put(104,"Это такая популярная песня");
        toBeFileRu.put(105,"Это такой сложный экзамен");
        toBeFileRu.put(106,"Это такой легкий тест");
        toBeFileRu.put(107,"Он професиональный учитель");
        toBeFileRu.put(108,"Он такой профессиональный учитель");
        toBeFileRu.put(109,"Это дорогая машина");
        toBeFileRu.put(110,"Это такая дорогая машина");
        toBeFileRu.put(111,"Она красивая");
        toBeFileRu.put(112,"Она такая красивая");
        toBeFileRu.put(113,"Она очень красивая");
        toBeFileRu.put(114,"Она красивая девушка");
        toBeFileRu.put(115,"Она такая красивая девушка");
        toBeFileRu.put(116,"Это легкое упражнение");
        toBeFileRu.put(117,"Это такое легкое упражнение");
        toBeFileRu.put(118,"Это так полезно");
        toBeFileRu.put(119,"Это такое полезно видео");
        toBeFileRu.put(120,"Это такая плохая ситуация");
        toBeFileRu.put(121,"Это так дешево");
        toBeFileRu.put(122,"Это такая дешевая вещь");
        toBeFileRu.put(123,"Он такой странный");
        toBeFileRu.put(124,"Он такой странный человек");
        toBeFileRu.put(125,"Он такой умный");
        toBeFileRu.put(126,"Он такой умный мужчина");
        toBeFileRu.put(127,"Он талантливый");
        toBeFileRu.put(128,"Он такой талантливый мальчик");
        toBeFileRu.put(129,"Он такой бедный мальчик");
        toBeFileRu.put(130,"Это так эффективно");
        toBeFileRu.put(131,"Это такой эффективный метод");
        toBeFileRu.put(132,"Она такая смышленая девочка");
        toBeFileRu.put(133,"Она такая добрая");
        toBeFileRu.put(134,"Она такая добрая женщина");
        toBeFileRu.put(135,"Она такая мудрая женщина");
        toBeFileRu.put(136,"Это такой простой ответ");
        toBeFileRu.put(137,"Мой друг дома");
        toBeFileRu.put(138,"Моя мама на работе");
        toBeFileRu.put(139,"Их идея очень интересная");
        toBeFileRu.put(140,"Этот урок очень полезный");
        toBeFileRu.put(141,"Эти уроки очень полезные");
        toBeFileRu.put(142,"Этот год очень сложный");
        toBeFileRu.put(143,"Это видео очень информативное");
        toBeFileRu.put(144,"Эти видео очень информативные");
        toBeFileRu.put(145,"Все эти видео очень полезные");
        toBeFileRu.put(146,"Все твои видео такие интересные");
        toBeFileRu.put(147,"Этот студент такой трудолюбивый");
        toBeFileRu.put(148,"Эти суденты очень ленивые");
        toBeFileRu.put(149,"Мой босс очень занят сейчас");
        toBeFileRu.put(150,"Её босс очень занят в настоящий момент");
        toBeFileRu.put(151,"У меня есть компьютер! Компьютер новый!");
        toBeFileRu.put(152,"У меня есть машина! Машина очень хорошая!");
        toBeFileRu.put(153,"Этот мальчик очень умный ");
        toBeFileRu.put(154,"Мальчик очень умный");
        toBeFileRu.put(155,"Экзамен сложный");
        toBeFileRu.put(156,"Тест легкий");
        toBeFileRu.put(157,"Урок полезный");
        toBeFileRu.put(158,"Урок интересный");
        toBeFileRu.put(159,"Правило очень важное");
        toBeFileRu.put(160,"Этот мужчина врач");
        toBeFileRu.put(161,"Эти мужчины менеджеры");
        toBeFileRu.put(162,"Та женщина дизайнер");
        toBeFileRu.put(163,"Те женщины учителя");
        toBeFileRu.put(164,"Эти уроки такие эффективные");
        toBeFileRu.put(165,"Те уроки не эффективные");
        toBeFileRu.put(166,"Эта проблема очень большая");
        toBeFileRu.put(167,"Эти проблемы маленькие");
        toBeFileRu.put(168,"Эти уроки реально хорошие");
        toBeFileRu.put(169,"Эта информация реально полезная");
        toBeFileRu.put(170,"Эта вещь очень важная");
        toBeFileRu.put(171,"Эти вещи очень важные");
        toBeFileRu.put(172,"Время деньги");
        toBeFileRu.put(173,"Деньги важны");
        toBeFileRu.put(174,"Английский легкий");
        toBeFileRu.put(175,"Китайский очень сложный");
        toBeFileRu.put(176,"Любовь прекрасное чувство");
        toBeFileRu.put(177,"Знание сила");
        toBeFileRu.put(178,"Это место очень красивое");
        toBeFileRu.put(179,"Эта компания очень богатая");
        toBeFileRu.put(180,"Я русский");
        toBeFileRu.put(181,"Он американец");
        toBeFileRu.put(182,"Мне 20");
        toBeFileRu.put(183,"Ей 30");
        toBeFileRu.put(184,"Моя мама врач! Ей 40");
        toBeFileRu.put(185,"Мне 21");
        toBeFileRu.put(186,"Моему брату 21");
        toBeFileRu.put(187,"Его жене 32");
        //Отрицания
        toBeFileRu.put(188,"День ветренный");
        toBeFileRu.put(189,"Это слово новое для меня");
        toBeFileRu.put(190,"Я не дома");
        toBeFileRu.put(191,"Мы не дома");
        toBeFileRu.put(192,"Он не дома");
        toBeFileRu.put(193,"Я не женат");
        toBeFileRu.put(194,"Я холост");
        toBeFileRu.put(195,"Я не менеджер. Я учитель");
        toBeFileRu.put(196,"Я не дома. Я на работе");
        toBeFileRu.put(197,"Я не студент. Я работаю");
        toBeFileRu.put(198,"Мы не устали");
        toBeFileRu.put(199,"Мы полны энергии");
        toBeFileRu.put(200,"Мы не тупые. Мы умные");
        toBeFileRu.put(201,"Мы не злые. Мы очень добрые");
        toBeFileRu.put(202,"Мы не грустные. Мы счастливые");
        toBeFileRu.put(203,"Ты не прав");
        toBeFileRu.put(204,"Ты не в этом месте");
        toBeFileRu.put(205,"Ты не на первом месте");
        toBeFileRu.put(206,"Ты на втором месте");
        toBeFileRu.put(207,"Они не вместе");
        toBeFileRu.put(208,"Они не мои коллеги");
        toBeFileRu.put(209,"Они не успешны");
        toBeFileRu.put(210,"Они не бизнесмены");
        toBeFileRu.put(211,"Он не старый");
        toBeFileRu.put(212,"Он не бедный");
        toBeFileRu.put(213,"Он не директор");
        toBeFileRu.put(214,"Его нет в городе");
        toBeFileRu.put(215,"Её нет сдесь");
        toBeFileRu.put(216,"Она не певица. Она актриса");
        toBeFileRu.put(217,"Она не свободна");
        toBeFileRu.put(218,"Она не с ним");
        toBeFileRu.put(219,"Не тепло");
        toBeFileRu.put(220,"Не дождливо");
        toBeFileRu.put(221,"Это не тоже самое");
        toBeFileRu.put(222,"Это не так легко");
        toBeFileRu.put(223,"Это не далеко");
        toBeFileRu.put(224,"Это не близко");
        toBeFileRu.put(225,"Это не хороший метод");
        toBeFileRu.put(226,"Это такой плохой метод");
        toBeFileRu.put(227,"Я предпочитаю эти уроки");
        //Вопросы
        toBeFileRu.put(228,"Ты счастлив");
        toBeFileRu.put(229,"Ты счастлив?");
        toBeFileRu.put(230,"Ты с ней");
        toBeFileRu.put(231,"Ты с ней?");
        toBeFileRu.put(232,"Я прав?");
        toBeFileRu.put(233,"Мы на первом месте?");
        toBeFileRu.put(234,"Вы вместе?");
        toBeFileRu.put(235,"Они на работе?");
        toBeFileRu.put(236,"Он её парень?");
        toBeFileRu.put(237,"Она его девушка?");
        toBeFileRu.put(238,"Это особое предложение?");
        toBeFileRu.put(239,"Я в правельном месте?");
        toBeFileRu.put(240,"Я талантливый?");
        toBeFileRu.put(241,"Я визучий?");
        toBeFileRu.put(242,"Мы не в правельном месте?");
        toBeFileRu.put(243,"Мы лучшие студенты?");
        toBeFileRu.put(244,"Мы трудолюбивые?");
        toBeFileRu.put(245,"Ты из Соединенных Штатов?");
        toBeFileRu.put(246,"Ты здесь?");
        toBeFileRu.put(247,"Ты там?");
        toBeFileRu.put(248,"Ты уверен?");
        toBeFileRu.put(249,"Ты действительно уверен?");
        toBeFileRu.put(250,"Они из Испании?");
        toBeFileRu.put(251,"Они далеко?");
        toBeFileRu.put(252,"Они в другой стране?");
        toBeFileRu.put(253,"Он из России?");
        toBeFileRu.put(254,"Он их клиент?");
        toBeFileRu.put(255,"Он её босс?");
        toBeFileRu.put(256,"Он усппешный бизнесмен?");
        toBeFileRu.put(257,"Он в здании?");
        toBeFileRu.put(258,"Она из Италии?");
        toBeFileRu.put(259,"Она в своей комнате?");
        toBeFileRu.put(260,"Она за границей?");
        toBeFileRu.put(261,"Он молодой?");
        toBeFileRu.put(262,"Он директор?");
        toBeFileRu.put(263,"Это эффективно?");
        toBeFileRu.put(264,"Это эффективный метод?");
        toBeFileRu.put(265,"Это так эффективно?");
        toBeFileRu.put(266,"Это такой эффективный метод?");
        toBeFileRu.put(267,"Это его версия?");
        toBeFileRu.put(268,"Это её мнение?");
        toBeFileRu.put(269,"Это его точка зрения?");
        toBeFileRu.put(270,"Это твоё решение?");
        toBeFileRu.put(271,"Это его собственная квартира?");
        toBeFileRu.put(272,"Это её собственный дом?");
        toBeFileRu.put(273,"Это глобальная проблема?");
        toBeFileRu.put(274,"Это забавное/смешное видео?");
        toBeFileRu.put(275,"Это интересная газета?");
        toBeFileRu.put(276,"Это скучный журнал?");
        toBeFileRu.put(277,"Это опасно?");
        toBeFileRu.put(278,"Это для детей?");
        toBeFileRu.put(279,"Это дорого?");
        toBeFileRu.put(280,"Это дешево?");
        toBeFileRu.put(281,"Он студент?");
        toBeFileRu.put(282,"Она студентка?");
        toBeFileRu.put(283,"Это тоже самое?");
        toBeFileRu.put(284,"Это проблема?");
        toBeFileRu.put(285,"Это большая проблема?");
        toBeFileRu.put(286,"Это такая большая проблема?");
        toBeFileRu.put(287,"Это очень большая проблема?");
        toBeFileRu.put(288,"Это хороший ответ?");
        toBeFileRu.put(289,"Это только для детей?");
        toBeFileRu.put(290,"Это хороший результат?");
        toBeFileRu.put(291,"Это отличный результат?");
        toBeFileRu.put(292,"Это блестящий результат?");
        toBeFileRu.put(293,"Это очень полезное видео?");
        toBeFileRu.put(294,"Жарко здесь?");
        toBeFileRu.put(295,"Холодно здесь?");
        toBeFileRu.put(296,"Тепло здесь?");
        toBeFileRu.put(297,"Его видео такое забавное?");
        toBeFileRu.put(298,"Этот проект такой интересный?");
        toBeFileRu.put(299,"Эта информация действительно полезная?");
        toBeFileRu.put(300,"Его компьютер новый?");
        toBeFileRu.put(301,"Это мощьный компьютер?");
        toBeFileRu.put(302,"Этих знаний достаточно?");
        toBeFileRu.put(303,"Эта история такая смешная?");
        toBeFileRu.put(304,"Его отец бизнесмен?");
        toBeFileRu.put(305,"Его мама врач?");
        toBeFileRu.put(306,"Его родители за границей?");
        toBeFileRu.put(307,"Твоей девушке 19?");
        toBeFileRu.put(308,"Твоему парню 22?");
        toBeFileRu.put(309,"Эта вещь такая важная?");
        toBeFileRu.put(310,"Эти вещи такие важные?");
        toBeFileRu.put(311,"Этот бизнес прибыльный?");
        toBeFileRu.put(312,"Твой папа на работе?");
        toBeFileRu.put(313,"Твоя мама в школе?");
        toBeFileRu.put(314,"Твои друзья онлайн?");
        toBeFileRu.put(315,"Эта практика действительно важная?");
        toBeFileRu.put(316,"Этот язык сложный?");
        toBeFileRu.put(317,"Этот тест слишком легкий?");
        toBeFileRu.put(318,"Этот тест слишком сложный?");
        toBeFileRu.put(319,"Эти упражнения такие полезные?");
        toBeFileRu.put(320,"Те упражнения песполезные?");
        toBeFileRu.put(321,"Это слово новое для тебя?");
        toBeFileRu.put(322,"Эти слова новые для тебя?");
        toBeFileRu.put(323,"Этот текст простой?");
        toBeFileRu.put(324,"Эти тексты слишком сложные?");
        toBeFileRu.put(325,"Мальчик дома?");
        toBeFileRu.put(326,"Мальчики в школе?");
        toBeFileRu.put(327,"Книга такая интересная?");
        toBeFileRu.put(328,"Книга скучная?");
        toBeFileRu.put(329,"Урок полезный?");
        toBeFileRu.put(330,"Уроки действительно полезные?");
        toBeFileRu.put(331,"Канал очень популярный?");
        toBeFileRu.put(332,"Университет знаменитый?");
        toBeFileRu.put(333,"Учитель прав?");
        toBeFileRu.put(334,"Его решение правильное?");
        toBeFileRu.put(335,"Статья на Английском?");
        toBeFileRu.put(336,"Статьи на Русском?");
        toBeFileRu.put(337,"Статья о политике?");
        toBeFileRu.put(338,"Игра интересная?");
        toBeFileRu.put(339,"Еда хорошая?");
        toBeFileRu.put(340,"Аэропорт близко?");
        toBeFileRu.put(341,"Время деньги?");
        toBeFileRu.put(342,"Деньги важны?");
        toBeFileRu.put(343,"Знания сила?");
        toBeFileRu.put(344,"Этой информации достаточно?");
        toBeFileRu.put(345,"Этого уровня достаточно?");
        toBeFileRu.put(346,"Этих денег достаточно?");
        toBeFileRu.put(347,"Новости интересные?");
        toBeFileRu.put(348,"Новости важные?");
        toBeFileRu.put(349,"Эти новости интересные?");
        toBeFileRu.put(350,"Эти новости важные?");
        toBeFileRu.put(351,"Где это?");
        toBeFileRu.put(352,"Где ты?");
        toBeFileRu.put(353,"Где она?");
        toBeFileRu.put(354,"Где он?");
        toBeFileRu.put(355,"Что это?");
        toBeFileRu.put(356,"Что там?");
        toBeFileRu.put(357,"Что здесь?");
        toBeFileRu.put(358,"Что в этой коробке?");
        toBeFileRu.put(359,"Что в твоей сумке?");
        toBeFileRu.put(360,"Что в твоем кормане?");
        toBeFileRu.put(361,"Что интересно?");
        toBeFileRu.put(362,"Что странно?");
        toBeFileRu.put(363,"Что важно?");
        toBeFileRu.put(364,"Что действительно важно?");
        toBeFileRu.put(365,"Что действительно полезно?");
        toBeFileRu.put(366,"Что нормально?");
        toBeFileRu.put(367,"Что дальше?");
        toBeFileRu.put(368,"Почему ты здесь?");
        toBeFileRu.put(369,"Почему он на работе сейчас?");
        toBeFileRu.put(370,"Почему ты так счастлив?");
        toBeFileRu.put(371,"Почему он зол?");
        toBeFileRu.put(372,"Почему ты против этого?");
        toBeFileRu.put(373,"Как ты?");
        toBeFileRu.put(374,"Как у него дела?");
        toBeFileRu.put(375,"Как она?");
        toBeFileRu.put(376,"Как это?");
        toBeFileRu.put(377,"Когда ты свободен?");
        toBeFileRu.put(378,"Когда ты занят?");
        toBeFileRu.put(379,"Когда он на работе?");
        toBeFileRu.put(380,"Когда он дома?");
        toBeFileRu.put(381,"Кто там?");
        toBeFileRu.put(382,"Кто здесь?");
        toBeFileRu.put(383,"Кто в комнате?");
        toBeFileRu.put(384,"Кто дома?");
        toBeFileRu.put(385,"Кто на работе?");
        toBeFileRu.put(386,"Кто в парке?");
        toBeFileRu.put(387,"Кто прав?");
        toBeFileRu.put(388,"Кто не прав?");
        toBeFileRu.put(389,"Кто на первом месте?");
        toBeFileRu.put(390,"Кто на втором месте?");
        toBeFileRu.put(391,"Кто он?");
        toBeFileRu.put(392,"Кто она?");
        toBeFileRu.put(393,"Кто следующий?");
        toBeFileRu.put(394,"Как далеко это?");
        toBeFileRu.put(395,"На сколько дорого это?");
        toBeFileRu.put(396,"На сколько интересно это?");
        toBeFileRu.put(397,"На сколько полезно это?");
        toBeFileRu.put(398,"На сколько сложно это?");
        toBeFileRu.put(399,"На сколько хорошее это?");
        toBeFileRu.put(400,"Сколько тебе лет?");
        toBeFileRu.put(401,"Сколько ему лет?");
        toBeFileRu.put(402,"Сколько ей лет?");
        toBeFileRu.put(403,"Сколько времени?");
        toBeFileRu.put(404,"Сколько это стоит?");
        toBeFileRu.put(405,"Как тебя зовут?");
        toBeFileRu.put(406,"Как её имя?");
        toBeFileRu.put(407,"Какое его имя?");
        toBeFileRu.put(408,"Какое имя твоей девушки?");
        toBeFileRu.put(409,"Как зовут твоего парня?");
        toBeFileRu.put(410,"Как зовут твоего друга?");
        toBeFileRu.put(411,"Какое имя твоего лучшего друга?");
        toBeFileRu.put(412,"Как тебя этот плэйлист?");
        toBeFileRu.put(413,"Как тебе канал?");
        toBeFileRu.put(414,"Как тебе вечеринка?");
        toBeFileRu.put(415,"Как тебе фильм?");
        toBeFileRu.put(416,"Как тебе этот тест?");
        toBeFileRu.put(417,"Как тебе это упражнение?");
        toBeFileRu.put(418,"Как тебе эти упражнения?");
        toBeFileRu.put(419,"Где это место?");
        toBeFileRu.put(420,"Где ближайший супермаркет?");
        toBeFileRu.put(421,"Где твоя комната?");
        toBeFileRu.put(422,"Где твой муж?");
        toBeFileRu.put(423,"Где твоя жена?");
        toBeFileRu.put(424,"Кто та женщина?");
        toBeFileRu.put(425,"Кто тот мужчина?");
        toBeFileRu.put(426,"Кто эти люди?");
        toBeFileRu.put(427,"Кто те люди?");
        toBeFileRu.put(428,"Почему это видео такое интересное?");
        toBeFileRu.put(429,"Почему этот канал такой популярный?");
        toBeFileRu.put(430,"Почему это правило такое важное?");
        toBeFileRu.put(431,"Почему эти правила такие важные?");
        toBeFileRu.put(432,"Почему тот урок такой не эффективный?");
        toBeFileRu.put(433,"Почему те уроки такие не эффективные?");
        toBeFileRu.put(434,"Сколько лет твоей маме?");
        toBeFileRu.put(435,"Сколько лет твоему отцу?");
        toBeFileRu.put(436,"Сколько лет твоему брату?");
        toBeFileRu.put(437,"Сколько лет твоей сестре?");
        toBeFileRu.put(438,"Кем ты работаешь?");
        toBeFileRu.put(439,"Какая его работа?");
        toBeFileRu.put(440,"Какая её работа?");
        toBeFileRu.put(441,"Кем работает твоя мама?");
        toBeFileRu.put(442,"Кем работает твой папа?");
        toBeFileRu.put(443,"Кем работает твоя жена?");
        toBeFileRu.put(444,"кем работает твой муж?");
        toBeFileRu.put(445,"На сколько интересный этот журнал?");
        toBeFileRu.put(446,"На сколько хороший этот урок?");
        toBeFileRu.put(447,"На сколько хороший урок?");
        toBeFileRu.put(448,"На сколько полезный урок?");
        toBeFileRu.put(449,"На сколько сложный тест?");
        toBeFileRu.put(450,"На сколько сложное упражнение?");
        toBeFileRu.put(451,"На сколько сложные эти упражнения?");
        toBeFileRu.put(452,"Сколько это платье?");
        toBeFileRu.put(453,"Сколько платье?");
        toBeFileRu.put(454,"Сколько этот компьютер?");
        toBeFileRu.put(455,"Сколько компьютер?");
        toBeFileRu.put(456,"Сколько стоит компьютер?");
        toBeFileRu.put(457,"Сколько эти брюки?");
        toBeFileRu.put(458,"Сколько эта пара брюк?");
        toBeFileRu.put(459,"Сколько эти джинсы?");
        toBeFileRu.put(460,"Сколько пара джинс?");
        toBeFileRu.put(461,"Сколько один урок Английского?");
        return toBeFileRu;
    }
}