package texts;

import java.util.HashMap;
import java.util.Map;

public class ExerciseTextPS implements ITexts
{
    /** Значения времени PS, языка Английский */
    private Map<Integer, String> psFileEn = new HashMap<>();

    /** Значения времени PS, языка Русский */
    private Map<Integer, String> psFileRu = new HashMap<>();
    /**
     * Функция получения списка значений на Английском языке времени PS
     * @return возвращает значения
     */
    @Override
    public Map<Integer, String> getEnglish() {
        getStrEnPS();
        return psFileEn;
    }

    /**
     * Функция получения списка значений на Русском языке времени PS
     * @return возвращает значения
     */
    @Override
    public Map<Integer, String> getRussia() {
        getStrRuPS();
        return psFileRu;
    }

    /**
     * Функция со значениями на Английском языке времени PS
     * @return возвращает список значений
     */
    private Map<Integer, String> getStrEnPS(){

        psFileEn.put(0,"I work here");
        psFileEn.put(1,"I study");
        psFileEn.put(2,"I understand");
        psFileEn.put(3,"I understand you");
        psFileEn.put(4,"I know it");
        psFileEn.put(5,"I know it very well");
        psFileEn.put(6,"I live in Russia");
        psFileEn.put(7,"I speak English");
        psFileEn.put(8,"I go to school");
        psFileEn.put(9,"I go to work");
        psFileEn.put(10,"I have a brother");
        psFileEn.put(11,"I have an idea");
        psFileEn.put(12,"I have a sister");
        psFileEn.put(13,"We understand you");
        psFileEn.put(14,"I have a car");
        psFileEn.put(15,"I think so");
        psFileEn.put(16,"I see it");
        psFileEn.put(17,"I want it");
        psFileEn.put(18,"I remember it");
        psFileEn.put(19,"I remember it very well");
        psFileEn.put(20,"We speak English");
        psFileEn.put(21,"You know it");
        psFileEn.put(22,"You see it");
        psFileEn.put(23,"They help me");
        psFileEn.put(24,"They go to work");
        psFileEn.put(25,"We remember it");
        psFileEn.put(26,"You speak English very well");
        psFileEn.put(27,"We live here");
        psFileEn.put(28,"I live in this city");
        psFileEn.put(29,"We live in this county");
        psFileEn.put(30,"I study there");
        psFileEn.put(31,"It really happens");
        psFileEn.put(32,"We want it");
        psFileEn.put(33,"You work very hard");
        psFileEn.put(34,"They study very hard");
        psFileEn.put(35,"I feel happy");
        psFileEn.put(36,"He lives there");
        psFileEn.put(37,"She feels happy");
        psFileEn.put(38,"It helps me");
        psFileEn.put(39,"He also works here");
        psFileEn.put(40,"He thinks so");
        psFileEn.put(41,"He lives in this house");
        psFileEn.put(42,"She remembers it");
        psFileEn.put(43,"She lives in this place");
        psFileEn.put(44,"She lives in that place");
        psFileEn.put(45,"She speaks English very well");
        psFileEn.put(46,"It really helps me");
        psFileEn.put(47,"It looks interesting");
        psFileEn.put(48,"It seems interesting");
        psFileEn.put(49,"He reads in English");
        psFileEn.put(50,"She reads English books");
        psFileEn.put(51,"It looks strange");
        psFileEn.put(52,"He knows it");
        psFileEn.put(53,"She sees this mistake");
        psFileEn.put(54,"He sees that mistake");
        psFileEn.put(55,"It happens");
        psFileEn.put(56,"He wants more");
        psFileEn.put(57,"She wants more practice");
        psFileEn.put(58,"He often plays computer games");
        psFileEn.put(59,"She feels so happy");
        psFileEn.put(60,"He does it every day");
        psFileEn.put(61,"She goes to school");
        psFileEn.put(62,"He goes to work");
        psFileEn.put(63,"He often goes to the cinema");
        psFileEn.put(64,"She often goes to the park");
        psFileEn.put(65,"She does it very well");
        psFileEn.put(66,"He has a house");
        psFileEn.put(67,"She has a car");
        psFileEn.put(68,"He has a dog");
        psFileEn.put(69,"She has a cat");
        psFileEn.put(70,"He has money");
        psFileEn.put(71,"He has an offer");
        psFileEn.put(72,"She watches TV");
        psFileEn.put(73,"He teaches English");
        psFileEn.put(74,"He misses you");
        psFileEn.put(75,"He always finishes his work on time");
        psFileEn.put(76,"She usually relaxes at home");
        psFileEn.put(77,"He tries to do it");
        psFileEn.put(78,"She tries to learn English");
        psFileEn.put(79,"He tries to find a job");
        psFileEn.put(80,"He sometimes plays computer games");
        psFileEn.put(81,"She has interesting ideas");
        psFileEn.put(82,"This lesson seems interesting");
        psFileEn.put(83,"These lessons seem very useful");
        psFileEn.put(84,"This lesson helps me");
        psFileEn.put(85,"These lessons help me");
        psFileEn.put(86,"Your lessons really help");
        psFileEn.put(87,"My brother wants it");
        psFileEn.put(88,"My sister lives there");
        psFileEn.put(89,"My parents know it");
        psFileEn.put(90,"My friend has a car");
        psFileEn.put(91,"My boss knows everything");
        psFileEn.put(92,"My boss usually reads all the documents");
        psFileEn.put(93,"My boss usually checks all the information");
        psFileEn.put(94,"I understand everything");
        psFileEn.put(95,"Our mother thinks the same");
        psFileEn.put(96,"Their ideas seem so interesting");
        psFileEn.put(97,"His father has a car");
        psFileEn.put(98,"Her brother often says it");
        psFileEn.put(99,"He has a company");
        psFileEn.put(100,"Its profit seems so big");
        psFileEn.put(101,"My girlfriend feels happy");
        psFileEn.put(102,"My girlfriend loves me very much");
        psFileEn.put(103,"My friend always supports me");
        psFileEn.put(104,"My friends always support me");
        psFileEn.put(105,"My friends sometimes say it");
        psFileEn.put(106,"My best friend always helps me");
        psFileEn.put(107,"My teacher usually comes to work early");
        psFileEn.put(108,"My father usually comes home late");
        psFileEn.put(109,"I see its success");
        psFileEn.put(110,"I have a family");
        psFileEn.put(111,"We often do it");
        psFileEn.put(112,"You always say it");
        psFileEn.put(113,"They often go to the cinema");
        psFileEn.put(114,"He knows this thing");
        psFileEn.put(115,"She sees this mistake");
        psFileEn.put(116,"It looks so interesting");
        psFileEn.put(117,"I see this mistake");
        psFileEn.put(118,"I see these mistakes");
        psFileEn.put(119,"I understand that person");
        psFileEn.put(120,"I understand those people");
        psFileEn.put(121,"He goes to school");
        psFileEn.put(122,"My friend thinks so");
        psFileEn.put(123,"My friend thinks the same");
        psFileEn.put(124,"Our boss knows it");
        psFileEn.put(125,"All your ideas seem very interesting");
        psFileEn.put(126,"Their offer seems really strange");
        psFileEn.put(127,"His idea seems very interesting");
        psFileEn.put(128,"Her words seem strange");
        psFileEn.put(129,"I want to be happy");
        psFileEn.put(130,"I want this thing");
        psFileEn.put(131,"I want this computer");
        psFileEn.put(132,"I want this dress");
        psFileEn.put(133,"I want a new computer");
        psFileEn.put(134,"I want a good car");
        psFileEn.put(135,"I want a new flat/apartment");
        psFileEn.put(136,"I really want it");
        psFileEn.put(137,"I want to do it");
        psFileEn.put(138,"She wants to do it");
        psFileEn.put(139,"I want to know it");
        psFileEn.put(140,"I really want to know it");
        psFileEn.put(141,"I want to improve my English");
        psFileEn.put(142,"I want to speak English better");
        psFileEn.put(143,"I want to speak English without mistakes");
        psFileEn.put(144,"I want to improve my grammar");
        psFileEn.put(145,"I want to speak English correctly");
        psFileEn.put(146,"I want to learn English fast");
        psFileEn.put(147,"I want to have a good job");
        psFileEn.put(148,"I want to have a good car");
        psFileEn.put(149,"She wants to do it right now");
        psFileEn.put(150,"He wants to buy this thing");
        psFileEn.put(151,"I want to speak English fluently");
        psFileEn.put(152,"My friend wants to check it one more time");
        psFileEn.put(153,"My friend wants to check it again");
        psFileEn.put(154,"My friend wants to live abroad");
        psFileEn.put(155,"I want to go abroad");
        psFileEn.put(156,"My parents want to live in another place");
        psFileEn.put(157,"I really want to thank you");
        psFileEn.put(158,"Thanks a lot");
        psFileEn.put(159,"I like it");
        psFileEn.put(160,"I like English");
        psFileEn.put(161,"I like your lessons");
        psFileEn.put(162,"I like this idea");
        psFileEn.put(163,"I like this thing");
        psFileEn.put(164,"I like this video");
        psFileEn.put(165,"I like this playlist");
        psFileEn.put(166,"I like this channel");
        psFileEn.put(167,"I like this method");
        psFileEn.put(168,"I really like it");
        psFileEn.put(169,"I really like these lessons");
        psFileEn.put(170,"I also like it");
        psFileEn.put(171,"I also like this channel");
        psFileEn.put(172,"I like it, too");
        psFileEn.put(173,"I like this channel, too");
        psFileEn.put(174,"We like");
        psFileEn.put(175,"You like it");
        psFileEn.put(176,"They like it");
        psFileEn.put(177,"He likes it");
        psFileEn.put(178,"She likes it");
        psFileEn.put(179,"I see you like it");
        psFileEn.put(180,"I know they like it");
        psFileEn.put(181,"She likes this place");
        psFileEn.put(182,"He likes this dress");
        psFileEn.put(183,"My friend likes this hotel");
        psFileEn.put(184,"I would like");
        psFileEn.put(185,"I would like a cup of coffee");
        psFileEn.put(186,"I'd like to become a businessman");
        psFileEn.put(187,"I'd like a cup of tea");
        psFileEn.put(188,"I'd like to drink a cup of coffee");
        psFileEn.put(189,"I'd like to drink a cup of tea");
        psFileEn.put(190,"I'd like to do it");
        psFileEn.put(191,"I'd like to know English very well");
        psFileEn.put(192,"I'd like to visit this place");
        //Отрицания
        psFileEn.put(193,"I don't know");
        psFileEn.put(194,"We don't understand");
        psFileEn.put(195,"You don't try to learn English");
        psFileEn.put(196,"They don't help me");
        psFileEn.put(197,"I agree with you");
        psFileEn.put(198,"I don't agree with you");
        psFileEn.put(199,"I don't like it");
        psFileEn.put(200,"I don't want to study there");
        psFileEn.put(201,"I want to discuss it");
        psFileEn.put(202,"I don't want to discuss it");
        psFileEn.put(203,"I don't want to do it right now");
        psFileEn.put(204,"I don't want to do it later");
        psFileEn.put(205,"I don't want to say it");
        psFileEn.put(206,"I don't want to tell you this thing");
        psFileEn.put(207,"I don't want to tell you about this problem");
        psFileEn.put(208,"I don't want to think about it");
        psFileEn.put(209,"He doesn't know it");
        psFileEn.put(210,"She doesn't want to discuss it");
        psFileEn.put(211,"It doesn't help me");
        psFileEn.put(212,"It doesn't seem strange");
        psFileEn.put(213,"It doesn't work");
        psFileEn.put(214,"I don't want to know it");
        psFileEn.put(215,"He doesn't work there");
        psFileEn.put(216,"He doesn't work here");
        psFileEn.put(217,"She doesn't remember it");
        psFileEn.put(218,"He doesn't want to read these books");
        psFileEn.put(219,"He wants to read those books");
        psFileEn.put(220,"He doesn't have this information");
        psFileEn.put(221,"I don't want to play computer games");
        psFileEn.put(222,"He doesn't know this person");
        psFileEn.put(223,"He doesn't want to try to find a good job");
        psFileEn.put(224,"He doesn't try to find a good job");
        psFileEn.put(225,"I don't want to live in this country");
        psFileEn.put(226,"My friend doesn't think so");
        psFileEn.put(227,"We don't want to live in another place");
        psFileEn.put(228,"It doesn't seem useful");
        psFileEn.put(229,"I don't want to think about it");
        psFileEn.put(230,"I don't understand these people");
        psFileEn.put(231,"He doesn't have a car");
        psFileEn.put(232,"I don't want to drink");
        psFileEn.put(233,"I don't want to live in this city");
        psFileEn.put(234,"This thing doesn't interest me");
        psFileEn.put(235,"These things don't attract me");
        psFileEn.put(236,"That thing doesn't seem interesting");
        psFileEn.put(237,"Those things don't seem strange");
        psFileEn.put(238,"Those lessons don't seem useful");
        psFileEn.put(239,"These lessons seem very useful");
        psFileEn.put(240,"That method doesn't help");
        psFileEn.put(241,"This method really helps");
        psFileEn.put(242,"My brother doesn't want to think about his future");
        psFileEn.put(243,"My sister doesn't know this person");
        psFileEn.put(244,"My friends don't recommend this hotel");
        psFileEn.put(245,"His son doesn't want to become a doctor");
        psFileEn.put(246,"Her daughter doesn't want to study there");
        psFileEn.put(247,"His parents don't feel happy");
        psFileEn.put(248,"This person doesn't try to change his life");
        psFileEn.put(249,"My boss doesn't see her");
        psFileEn.put(250,"My partner doesn't know him");
        psFileEn.put(251,"My friend and I don't call them");
        psFileEn.put(252,"Our teacher doesn't believe us");
        psFileEn.put(253,"He thinks money doesn't bring people happiness");
        psFileEn.put(254,"She thinks money doesn't make people happy");
        psFileEn.put(255,"I want to make you happy");
        psFileEn.put(256,"I need this information");
        psFileEn.put(257,"I need to do it");
        psFileEn.put(258,"I need to check it");
        psFileEn.put(259,"I need to study harder");
        psFileEn.put(260,"I need to learn English");
        psFileEn.put(261,"I need to correct this mistake");
        psFileEn.put(262,"I need to see her");
        psFileEn.put(263,"I need to call him");
        psFileEn.put(264,"I need to call them");
        psFileEn.put(265,"I need it");
        psFileEn.put(266,"We need it");
        psFileEn.put(267,"You need it");
        psFileEn.put(268,"They need it");
        psFileEn.put(269,"He needs it");
        psFileEn.put(270,"She needs it");
        psFileEn.put(271,"I really need English");
        psFileEn.put(272,"I really need it");
        psFileEn.put(273,"I really need to know English");
        psFileEn.put(274,"I really need your lessons");
        psFileEn.put(275,"I need to solve this problem");
        psFileEn.put(276,"I really need you");
        psFileEn.put(277,"She needs to correct these mistakes");
        psFileEn.put(278,"He needs to find a good job");
        psFileEn.put(279,"You need to remember this rule");
        psFileEn.put(280,"You need to remember it");
        psFileEn.put(281,"I need to improve my English");
        psFileEn.put(282,"I need to speak English without mistake");
        psFileEn.put(283,"I need to speak English without any mistakes at all");
        psFileEn.put(284,"My friend needs your help");
        psFileEn.put(285,"My friend needs your advice");
        psFileEn.put(286,"I need your advice");
        psFileEn.put(287,"His father needs money");
        psFileEn.put(288,"Your mother needs to work less");
        psFileEn.put(289,"I need this thing");
        psFileEn.put(290,"I agree with you");
        psFileEn.put(291,"We support you");
        psFileEn.put(292,"You know it better");
        psFileEn.put(293,"They live in another country");
        psFileEn.put(294,"He always pays for her");
        psFileEn.put(295,"She agrees with you");
        psFileEn.put(296,"It happens from time to time");
        psFileEn.put(297,"He often goes to the cinema");
        psFileEn.put(298,"She goes to work");
        psFileEn.put(299,"He has so many problems");
        psFileEn.put(300,"He has an interesting idea");
        psFileEn.put(301,"She teaches Spanish");
        psFileEn.put(302,"I don't order food there");
        psFileEn.put(303,"We don't have any questions");
        psFileEn.put(304,"You don't understand us");
        psFileEn.put(305,"They don't believe him");
        psFileEn.put(306,"She doesn't tell me these things");
        psFileEn.put(307,"He doesn't speak Spanish");
        psFileEn.put(308,"It doesn't motivate me");
        psFileEn.put(309,"His girlfriend know everything");
        psFileEn.put(310,"Our teachers don't explain it");
        psFileEn.put(311,"Her boyfriend doesn't know about this problem");
        //Вопросы
        psFileEn.put(312,"Do you know it?");
        psFileEn.put(313,"Do I make mistakes?");
        psFileEn.put(314,"Do we show good results?");
        psFileEn.put(315,"Do you understand me?");
        psFileEn.put(316,"Do they agree with us?");
        psFileEn.put(317,"Do you try to improve this result?");
        psFileEn.put(318,"Do you work on your mistakes?");
        psFileEn.put(319,"Do you have free time?");
        psFileEn.put(320,"Do you support me?");
        psFileEn.put(321,"Do you agree with me?");
        psFileEn.put(322,"Do you remember it?");
        psFileEn.put(323,"Do you remember everything?");
        psFileEn.put(324,"Do you know about this problem?");
        psFileEn.put(325,"Do you need help?");
        psFileEn.put(326,"Do you need more money?");
        psFileEn.put(327,"Do you need my advice?");
        psFileEn.put(328,"Do you support this decision?");
        psFileEn.put(329,"Do you want to study better?");
        psFileEn.put(330,"Do you want to know your mistakes?");
        psFileEn.put(331,"Do you need to solve this problem right now?");
        psFileEn.put(332,"Do you like it?");
        psFileEn.put(333,"Do you like this channel?");
        psFileEn.put(334,"Do you like this song?");
        psFileEn.put(335,"Do you like this idea?");
        psFileEn.put(336,"Do you like classical music?");
        psFileEn.put(337,"Do you often do it?");
        psFileEn.put(338,"Do you often listen to music?");
        psFileEn.put(339,"Do you often go there?");
        psFileEn.put(340,"Do you often use the Internet?");
        psFileEn.put(341,"Do you often go to the gym?");
        psFileEn.put(342,"Do you often visit this place?");
        psFileEn.put(343,"Do they often discuss it?");
        psFileEn.put(344,"Do they do the same?");
        psFileEn.put(345,"Do we have enough practice?");
        psFileEn.put(346,"Do we have enough knowledge?");
        psFileEn.put(347,"Does she think about it?");
        psFileEn.put(348,"Does he live there?");
        psFileEn.put(349,"Does it help you?");
        psFileEn.put(350,"Does she teach English?");
        psFileEn.put(351,"Does she tell him everything?");
        psFileEn.put(352,"Does she ignore it?");
        psFileEn.put(353,"Does he hate it?");
        psFileEn.put(354,"Does he hate this thing?");
        psFileEn.put(355,"Does he pay for it?");
        psFileEn.put(356,"Does he look for a job?");
        psFileEn.put(357,"Does he try to find a new job?");
        psFileEn.put(358,"Does he want to work in another place?");
        psFileEn.put(359,"Does she need to call him?");
        psFileEn.put(360,"Does she need to come there?");
        psFileEn.put(361,"Does she need to come to this place?");
        psFileEn.put(362,"Does she often say it?");
        psFileEn.put(363,"Does he often hear it?");
        psFileEn.put(364,"Does she often listen to the radio?");
        psFileEn.put(365,"Does he often watch TV?");
        psFileEn.put(366,"Does she often use it?");
        psFileEn.put(367,"Does it often happen?");
        psFileEn.put(368,"Does it sometimes happen?");
        psFileEn.put(369,"Does he like it?");
        psFileEn.put(370,"Does she like it?");
        psFileEn.put(371,"Does he like this project?");
        psFileEn.put(372,"Does she like this profession?");
        psFileEn.put(373,"Does it look strange?");
        psFileEn.put(374,"Does it seem interesting?");
        psFileEn.put(375,"Does it seem boring?");
        psFileEn.put(376,"Does this lesson seem useful?");
        psFileEn.put(377,"Do these lessons help you?");
        psFileEn.put(378,"Does this channel seem very interesting?");
        psFileEn.put(379,"Does this teacher explain everything very well?");
        psFileEn.put(380,"Does this information seem useless?");
        psFileEn.put(381,"Does this thing seem important?");
        psFileEn.put(382,"Do these things seem unimportant?");
        psFileEn.put(383,"Does this exam seem very difficult?");
        psFileEn.put(384,"Does that addText seem very easy?");
        psFileEn.put(385,"Does his girlfriend understand it?");
        psFileEn.put(386,"Does their boss know all the truth?");
        psFileEn.put(387,"Do these students show excellent results?");
        psFileEn.put(388,"Does this student show brilliant results?");
        psFileEn.put(389,"Does that student make mistakes?");
        psFileEn.put(390,"Do those students speak English correctly?");
        psFileEn.put(391,"Does your friend like this idea?");
        psFileEn.put(392,"Do your friends support you?");
        psFileEn.put(393,"Does this exerciseT seem too easy?");
        psFileEn.put(394,"Does this result depend on you?");
        psFileEn.put(395,"Where do you live?");
        psFileEn.put(396,"Where do you work?");
        psFileEn.put(397,"Where do you go?");
        psFileEn.put(398,"Where do they spend time together?");
        psFileEn.put(399,"Why do you think so?");
        psFileEn.put(400,"Why do you agree with him?");
        psFileEn.put(401,"Why do you learn English?");
        psFileEn.put(402,"What do you think about it?");
        psFileEn.put(403,"What do you know?");
        psFileEn.put(404,"What do you want to do? ");
        psFileEn.put(405,"What do you need to do?");
        psFileEn.put(406,"How do you find this idea?");
        psFileEn.put(407,"How do you get to work?");
        psFileEn.put(408,"How do you get there?");
        psFileEn.put(409,"When do you feel happy?");
        psFileEn.put(410,"When do you go to work?");
        psFileEn.put(411,"When do you have free time?");
        psFileEn.put(412,"What do you want to say?");
        psFileEn.put(413,"What seems strange?");
        psFileEn.put(414,"What do they want to tell you?");
        psFileEn.put(415,"What helps you?");
        psFileEn.put(416,"What really helps you?");
        psFileEn.put(417,"Who do you know?");
        psFileEn.put(418,"Who knows it?");
        psFileEn.put(419,"Who do you support?");
        psFileEn.put(420,"Who supports you?");
        psFileEn.put(421,"What books do you read?");
        psFileEn.put(422,"What English books do you read?");
        psFileEn.put(423,"What music do you prefer?");
        psFileEn.put(424,"What kind of books do you read?");
        psFileEn.put(425,"What kind of computer games do they play?");
        psFileEn.put(426,"What time do you get up?");
        psFileEn.put(427,"What time do you go to bed?");
        psFileEn.put(428,"How much money do you have with you?");
        psFileEn.put(429,"How many friends do you have?");
        psFileEn.put(430,"How often do you go there?");
        psFileEn.put(431,"How often do you go to the gym?");
        psFileEn.put(432,"How regularly do you learn English?");
        psFileEn.put(433,"Where does he work?");
        psFileEn.put(434,"Where does she study?");
        psFileEn.put(435,"Where does she go?");
        psFileEn.put(436,"Why does he complain so often?");
        psFileEn.put(437,"Why does she refuse to pay?");
        psFileEn.put(438,"Why does it happen again and again?");
        psFileEn.put(439,"What does she say?");
        psFileEn.put(440,"What does she tell him?");
        psFileEn.put(441,"What does he want to add?");
        psFileEn.put(442,"What does she try to do?");
        psFileEn.put(443,"What does he need to change?");
        psFileEn.put(444,"How does she addText their knowledge?");
        psFileEn.put(445,"How does it help you?");
        psFileEn.put(446,"How does he support you?");
        psFileEn.put(447,"When does it happen?");
        psFileEn.put(448,"When does he feel happy?");
        psFileEn.put(449,"What does he remember?");
        psFileEn.put(450,"What does she want to add?");
        psFileEn.put(451,"What helps you?");
        psFileEn.put(452,"What interests you?");
        psFileEn.put(453,"What worries you?");
        psFileEn.put(454,"Who does it motivate?");
        psFileEn.put(455,"Who motivates you?");
        psFileEn.put(456,"Who does she love?");
        psFileEn.put(457,"Who loves her?");
        psFileEn.put(458,"Who does he support?");
        psFileEn.put(459,"Who supports him?");
        psFileEn.put(460,"What English books does he have?");
        psFileEn.put(461,"What channels does he watch?");
        psFileEn.put(462,"What kind of movies (films) does she watch?");
        psFileEn.put(463,"She watches different movies!");
        psFileEn.put(464,"What books does she prefer to read?");
        psFileEn.put(465,"Which channel do you usually watch?");
        psFileEn.put(466,"What channels does he usually watch?");
        psFileEn.put(467,"Which drink does she prefer: tea or coffee?");
        psFileEn.put(468,"What drinks does she prefer?");
        psFileEn.put(469,"What time does he come to work?");
        psFileEn.put(470,"What time does she leave home?");
        psFileEn.put(471,"How much money does she pay?");
        psFileEn.put(472,"How many dollars does he have?");
        psFileEn.put(473,"How often does she go to the cinema?");
        psFileEn.put(474,"How often does he go to the zoo?");
        psFileEn.put(475,"How regularly does he do these exercisesT?");
        psFileEn.put(476,"What do you do?");
        psFileEn.put(477,"How long does it take you to get to work?");
        psFileEn.put(478,"How long does it take him to get to this place?");
        psFileEn.put(479,"What advice does she give you?");
        psFileEn.put(480,"Where?");
        psFileEn.put(481,"Why?");
        psFileEn.put(482,"Who?");
        psFileEn.put(483,"How?");
        psFileEn.put(484,"When?");
        psFileEn.put(485,"What?");
        psFileEn.put(486,"Which?");
        psFileEn.put(487,"Where does your father work?");
        psFileEn.put(488,"Where do your parents live?");
        psFileEn.put(489,"Why does your boss criticize it?");
        psFileEn.put(490,"Why does your mother think so?");
        psFileEn.put(491,"Why do your friends disagree with you?");
        psFileEn.put(492,"How does your sister feel?");
        psFileEn.put(493,"How does your brother control it?");
        psFileEn.put(494,"When does your father leave home?");
        psFileEn.put(495,"When does this thing happen?");
        psFileEn.put(496,"When do these things happen?");
        psFileEn.put(497,"What do your friends usually order?");
        psFileEn.put(498,"What does your boss usually promise?");
        psFileEn.put(499,"What advice does your teacher give you?");
        psFileEn.put(500,"What advice do your teachers give you?");
        psFileEn.put(501,"What kind of examples does his teacher give?");
        psFileEn.put(502,"How much free time does your business partner have?");
        psFileEn.put(503,"How many English words does your friend want to know?");
        psFileEn.put(504,"How often does this thing happen?");
        psFileEn.put(505,"How often do these things happen?");
        psFileEn.put(506,"How regularly does your boss check it?");
        psFileEn.put(507,"How long does it take his son to get to work?");
        psFileEn.put(508,"How long does it take his daughter to get to school?");
        psFileEn.put(509,"What does your boss usually answer?");
        psFileEn.put(510,"Does he do it with great pleasure?");
        psFileEn.put(511,"Do you share his point of view?");
        psFileEn.put(512,"What inspires you?");
        psFileEn.put(513,"How often does your girlfriend mention it?");
        psFileEn.put(514,"She often asks me about it!");
        psFileEn.put(515,"Let's talk/speak about it!");

        return psFileEn;
    }

    /**
     * Функция со значениями на Русском языке времени PS
     * @return возвращает список значений
     */
    private Map<Integer, String> getStrRuPS(){
        psFileRu.put(0,"Я работаю здесь");
        psFileRu.put(1,"Я учусь");
        psFileRu.put(2,"Я понимаю");
        psFileRu.put(3,"Я понимаю тебя");
        psFileRu.put(4,"Я знаю это");
        psFileRu.put(5,"Я знаю это очень хорошо");
        psFileRu.put(6,"Я живу в России");
        psFileRu.put(7,"Я говорю по-английски");
        psFileRu.put(8,"Я хожу в школу");
        psFileRu.put(9,"Я хожу на работу");
        psFileRu.put(10,"У меня есть брат");
        psFileRu.put(11,"У меня есть идея");
        psFileRu.put(12,"У меня есть сестра");
        psFileRu.put(13,"Мы понимаем тебя");
        psFileRu.put(14,"У меня есть машина");
        psFileRu.put(15,"Я думаю так");
        psFileRu.put(16,"Я вижу это");
        psFileRu.put(17,"Я хочу это");
        psFileRu.put(18,"Я помню это");
        psFileRu.put(19,"Я помню это очень хорошо");
        psFileRu.put(20,"Мы говорим по-английски");
        psFileRu.put(21,"Ты знаешь это");
        psFileRu.put(22,"Ты видишь это");
        psFileRu.put(23,"Они помогают мне");
        psFileRu.put(24,"Они ходят на работу");
        psFileRu.put(25,"Мы помним это");
        psFileRu.put(26,"Ты говоришь по-английски очень хорошо");
        psFileRu.put(27,"Мы живем здесь");
        psFileRu.put(28,"Я живу в этом городе");
        psFileRu.put(29,"Мы живем в этой стране");
        psFileRu.put(30,"Я учусь там");
        psFileRu.put(31,"Это реально происходит");
        psFileRu.put(32,"Мы хотим это");
        psFileRu.put(33,"Ты работаешь очень усердно");
        psFileRu.put(34,"Они учатся очень усердно");
        psFileRu.put(35,"Я чувствую себя счастливым");
        psFileRu.put(36,"Он живет там");
        psFileRu.put(37,"Она чувствует себя счастливой");
        psFileRu.put(38,"Это помогает мне");
        psFileRu.put(39,"Он также работает здесь");
        psFileRu.put(40,"Он думает так");
        psFileRu.put(41,"Он живет в этом доме");
        psFileRu.put(42,"Она помнит это");
        psFileRu.put(43,"Она живет в этом месте");
        psFileRu.put(44,"Она живет в том месте");
        psFileRu.put(45,"Она говорит по-английски очень хорошо");
        psFileRu.put(46,"Это реально помогает мне");
        psFileRu.put(47,"Это выглядит интересно");
        psFileRu.put(48,"Это кажется интересным");
        psFileRu.put(49,"Он читает на Английском");
        psFileRu.put(50,"Она читает Английские книги");
        psFileRu.put(51,"Это выглядит странно");
        psFileRu.put(52,"Он знает это");
        psFileRu.put(53,"Она видит эту ошибку");
        psFileRu.put(54,"Он видит ту ошибку");
        psFileRu.put(55,"Это случается");
        psFileRu.put(56,"Он хочет большего");
        psFileRu.put(57,"Она хочет больше практики");
        psFileRu.put(58,"Он часто играет в компьютерные игры");
        psFileRu.put(59,"Она чувствует себя такой счастливой");
        psFileRu.put(60,"Он делает это каждый день");
        psFileRu.put(61,"Она ходит в школу");
        psFileRu.put(62,"Он ходит на работу");
        psFileRu.put(63,"Он часто ходит в кино");
        psFileRu.put(64,"Она часто ходит в парк");
        psFileRu.put(65,"Она делает это очень хорошо");
        psFileRu.put(66,"У него есть дом");
        psFileRu.put(67,"У нее есть машина");
        psFileRu.put(68,"У него есть собака");
        psFileRu.put(69,"У нее есть кошка");
        psFileRu.put(70,"У него есть деньги");
        psFileRu.put(71,"У него есть предложение");
        psFileRu.put(72,"Она смотрит ТВ");
        psFileRu.put(73,"Он припадает Английский");
        psFileRu.put(74,"Он скучает по тебе");
        psFileRu.put(75,"Он всегда заканчивает свою работу вовремя");
        psFileRu.put(76,"Она обычно отдыхает дома");
        psFileRu.put(77,"Он пытается сделать это");
        psFileRu.put(78,"Она пытается выучить Английский");
        psFileRu.put(79,"Он пытается найти работу");
        psFileRu.put(80,"Он иногда играет в компьютерные игры");
        psFileRu.put(81,"У нее есть интересные идеи");
        psFileRu.put(82,"Этот урок кажется интересным");
        psFileRu.put(83,"Эти уроки кажутся очень полезными");
        psFileRu.put(84,"Этот урок помогает мне");
        psFileRu.put(85,"Эти уроки помогают мне");
        psFileRu.put(86,"Твои уроки реально помогают");
        psFileRu.put(87,"Мой брат хочет это");
        psFileRu.put(88,"Моя сестра живет там");
        psFileRu.put(89,"Мои родители знают это");
        psFileRu.put(90,"У моего друга есть машина");
        psFileRu.put(91,"Мой босс знает все");
        psFileRu.put(92,"Мой босс обычно читает все документы");
        psFileRu.put(93,"Мой босс обычно проверяет всю информацию");
        psFileRu.put(94,"Я понимаю все");
        psFileRu.put(95,"Наша мама думает также");
        psFileRu.put(96,"Их идеи кажутся такими интересными");
        psFileRu.put(97,"У его отца есть машина");
        psFileRu.put(98,"Её брат часто говорит это");
        psFileRu.put(99,"У него есть компания");
        psFileRu.put(100,"Её прибыль кажется такой большой");
        psFileRu.put(101,"Моя девушка чувствует себя счастливой");
        psFileRu.put(102,"Моя девушка любит меня очень сильно");
        psFileRu.put(103,"Мой друг всегда поддерживает меня");
        psFileRu.put(104,"Мои друзья всегда поддерживают меня");
        psFileRu.put(105,"Мои друзья иногда говорят это");
        psFileRu.put(106,"Мой лучший друг всегда помогает мне");
        psFileRu.put(107,"Мой учитель обычно приходит на работу рано");
        psFileRu.put(108,"Мой отец обычно приходит домой поздно");
        psFileRu.put(109,"Я вижу её успех");
        psFileRu.put(110,"У меня есть семья");
        psFileRu.put(111,"Мы часто делаем это");
        psFileRu.put(112,"Ты всегда говоришь это");
        psFileRu.put(113,"Они часто ходят в кино");
        psFileRu.put(114,"Он знает эту вещь");
        psFileRu.put(115,"Она видит эту ошибку");
        psFileRu.put(116,"Это выглядит таким интересным");
        psFileRu.put(117,"Я вижу эту ошибку");
        psFileRu.put(118,"Я вижу эти ошибки");
        psFileRu.put(119,"Я понимаю того человека");
        psFileRu.put(120,"Я понимаю тех людей");
        psFileRu.put(121,"Он ходит в школу");
        psFileRu.put(122,"Мой друг думает так");
        psFileRu.put(123,"Мой друг думает так же");
        psFileRu.put(124,"Наш босс знает это");
        psFileRu.put(125,"Все твои идеи кажутся очень интересными");
        psFileRu.put(126,"Их предложение кажется действительно странным");
        psFileRu.put(127,"Его идея кажется очень интересной");
        psFileRu.put(128,"Её слова кажутся странными");
        psFileRu.put(129,"Я хочу быть счастливым");
        psFileRu.put(130,"Я хочу эту вещь");
        psFileRu.put(131,"Я хочу этот компьютер");
        psFileRu.put(132,"Я хочу это платье");
        psFileRu.put(133,"Я хочу новый компьютер");
        psFileRu.put(134,"Я хочу хорошую машину");
        psFileRu.put(135,"Я хочу новую квартиру");
        psFileRu.put(136,"Я действительно хочу это");
        psFileRu.put(137,"Я хочу сделать это");
        psFileRu.put(138,"Она хочет сделать это");
        psFileRu.put(139,"Я хочу знать это");
        psFileRu.put(140,"Я реально хочу знать это");
        psFileRu.put(141,"Я хочу улучшить свой английский");
        psFileRu.put(142,"Я хочу говорить по-английски лучше");
        psFileRu.put(143,"Я хочу говорить по-английски без ошибок");
        psFileRu.put(144,"Я хочу улучшить свою грамматику");
        psFileRu.put(145,"Я хочу говорить по-английски правильно");
        psFileRu.put(146,"Я хочу выучить английский быстро");
        psFileRu.put(147,"Я хочу иметь хорошую работу");
        psFileRu.put(148,"Я хочу иметь хорошую машину");
        psFileRu.put(149,"Она хочет сделать это прямо сейчас");
        psFileRu.put(150,"Он хочет купить эту вещь");
        psFileRu.put(151,"Я хочу говорить по-английски свободно");
        psFileRu.put(152,"Мой друг хочет проверить это еще один раз");
        psFileRu.put(153,"Мой друг хочет проверить это снова");
        psFileRu.put(154,"Мой друг хочет жить за границей");
        psFileRu.put(155,"Я хочу поехать за границу");
        psFileRu.put(156,"Мои родители хотят жить в другом месте");
        psFileRu.put(157,"Я действительно хочу поблагодарить тебя");
        psFileRu.put(158,"Спасибо большое");
        psFileRu.put(159,"Мне нравится это");
        psFileRu.put(160,"Мне нравится Английский");
        psFileRu.put(161,"Мне нравятся твои уроки");
        psFileRu.put(162,"Мне нравится эта идея");
        psFileRu.put(163,"Мне нравится эта вещь");
        psFileRu.put(164,"Мне нравится это видео");
        psFileRu.put(165,"Мне нравится этот плейлист");
        psFileRu.put(166,"Мне нравится этот канал");
        psFileRu.put(167,"Мне нравится этот метод");
        psFileRu.put(168,"Мне реально нравится это");
        psFileRu.put(169,"Мне действительно нравятся эти уроки");
        psFileRu.put(170,"Мне также нравится это");
        psFileRu.put(171,"Мне также нравится этот канал");
        psFileRu.put(172,"Мне нравится это, так же");
        psFileRu.put(173,"Мне нравится этот канал, так же");
        psFileRu.put(174,"Нам нравится");
        psFileRu.put(175,"Тебе нравится это");
        psFileRu.put(176,"Им нравится это");
        psFileRu.put(177,"Ему нравится это");
        psFileRu.put(178,"Ей нравится это");
        psFileRu.put(179,"Я вижу, тебе нравится это");
        psFileRu.put(180,"Я знаю, им нравится это");
        psFileRu.put(181,"Ей нравится это место");
        psFileRu.put(182,"Ему нравится это платье");
        psFileRu.put(183,"Моему другу нравится этот отель");
        psFileRu.put(184,"Я хотел бы");
        psFileRu.put(185,"Я хотел бы чашку кофе");
        psFileRu.put(186,"Я хотел бы стать бизнесменом");
        psFileRu.put(187,"Я хотел бы чашку чая");
        psFileRu.put(188,"Я хотел бы выпить чашку кофе");
        psFileRu.put(189,"Я хотел бы выпить чашку чая");
        psFileRu.put(190,"Я хотел бы сделать это");
        psFileRu.put(191,"Я хотел бы знать английский очень хорошо");
        psFileRu.put(192,"Я хотел бы посетить это место");
        //Отрицания
        psFileRu.put(193,"Я не знаю");
        psFileRu.put(194,"Мы не понимаем");
        psFileRu.put(195,"Ты не пытаешься выучить Английский");
        psFileRu.put(196,"Они не помогают мне");
        psFileRu.put(197,"Я согласен с тобой");
        psFileRu.put(198,"Я не согласен с тобой");
        psFileRu.put(199,"Мне не нравится это");
        psFileRu.put(200,"Я не хочу учиться там");
        psFileRu.put(201,"Я хочу обсудить это");
        psFileRu.put(202,"Я не хочу обсуждать это");
        psFileRu.put(203,"Я не хочу делать это прямо сейчас");
        psFileRu.put(204,"Я не хочу делать это позже");
        psFileRu.put(205,"Я не хочу говорить это");
        psFileRu.put(206,"Я не хочу говорить тебе эту вещь");
        psFileRu.put(207,"Я не хочу говорить тебе об этой проблеме");
        psFileRu.put(208,"Я не хочу думать об этом");
        psFileRu.put(209,"Он не знает это");
        psFileRu.put(210,"Она не хочет обсуждать это");
        psFileRu.put(211,"Это не помогает мне");
        psFileRu.put(212,"Это не кажется странным");
        psFileRu.put(213,"Это не работает");
        psFileRu.put(214,"Я не хочу это знать");
        psFileRu.put(215,"Он не работает там");
        psFileRu.put(216,"Он не работает здесь");
        psFileRu.put(217,"Она не помнит это");
        psFileRu.put(218,"Он не хочет читать эти книги");
        psFileRu.put(219,"Он хочет читать те книги");
        psFileRu.put(220,"У него нет этой информации");
        psFileRu.put(221,"Он не хочет играть в компьютерные игры");
        psFileRu.put(222,"Он не знает этого человека");
        psFileRu.put(223,"Он не хочет пытаться найти хорошую работу");
        psFileRu.put(224,"Он не пытается найти хорошую работу");
        psFileRu.put(225,"Я не хочу жить в этой стране");
        psFileRu.put(226,"Мой друг не думает так");
        psFileRu.put(227,"Мы не хотим жить в другом месте");
        psFileRu.put(228,"Это не кажется полезным");
        psFileRu.put(229,"Я не хочу думать об этом");
        psFileRu.put(230,"Я не понимаю этих людей");
        psFileRu.put(231,"У него нет машины");
        psFileRu.put(232,"Я не хочу пить");
        psFileRu.put(233,"Я не хочу жить в этом городе");
        psFileRu.put(234,"Эта вещь не интересует меня");
        psFileRu.put(235,"Эти вещи не привлекают меня");
        psFileRu.put(236,"Та вещь не кажется интересной");
        psFileRu.put(237,"Те вещи не кажутся странными");
        psFileRu.put(238,"Те уроки не кажутся полезными");
        psFileRu.put(239,"Эти уроки кажутся очень полезными");
        psFileRu.put(240,"Тот метод не помогает");
        psFileRu.put(241,"Этот метод реально помогает");
        psFileRu.put(242,"Мой брат не хочет думать о своем будущем");
        psFileRu.put(243,"Моя сестра не знает этого человека");
        psFileRu.put(244,"Мои друзья не рекомендуют этот отель");
        psFileRu.put(245,"Его сын не хочет стать доктором");
        psFileRu.put(246,"Её дочь не хочет учиться там");
        psFileRu.put(247,"Его родители не чувствуют себя счастливыми");
        psFileRu.put(248,"Этот человек не пытается изменить свою жизнь");
        psFileRu.put(249,"Мой босс не видит её");
        psFileRu.put(250,"Мой партнер не знает его");
        psFileRu.put(251,"Мы с моим другом не звоним им");
        psFileRu.put(252,"Наш учитель не верит нам");
        psFileRu.put(253,"Он думает деньги не приносят людям счастья");
        psFileRu.put(254,"Она думает деньги не делают людей счастливыми");
        psFileRu.put(255,"Я хочу сделать вас счастливыми");
        psFileRu.put(256,"Мне нужна эта информация");
        psFileRu.put(257,"Мне нужно сделать это");
        psFileRu.put(258,"Мне нужно проверить это");
        psFileRu.put(259,"Мне нужно учиться усердней");
        psFileRu.put(260,"Мне нужно выучить Английский");
        psFileRu.put(261,"Мне нужно исправить эту ошибку");
        psFileRu.put(262,"Мне нужно увидеть её");
        psFileRu.put(263,"Мне нужно позвонить ему");
        psFileRu.put(264,"Мне нужно позвонить им");
        psFileRu.put(265,"Мне нужно это");
        psFileRu.put(266,"Нам нужно это");
        psFileRu.put(267,"Тебе нужно это");
        psFileRu.put(268,"Им нужно это");
        psFileRu.put(269,"Ему нужно это");
        psFileRu.put(270,"Ей нужно это");
        psFileRu.put(271,"Мне реально нужен английский");
        psFileRu.put(272,"Мне реально это нужно");
        psFileRu.put(273,"Мне реально нужно знать Английский");
        psFileRu.put(274,"Мне реально нужны твои уроки");
        psFileRu.put(275,"Мне нужно решить эту проблему");
        psFileRu.put(276,"Ты мне реально нужна");
        psFileRu.put(277,"Ей нужно исправить эти ошибки");
        psFileRu.put(278,"Ему нужно найти хорошую работу");
        psFileRu.put(279,"Тебе нужно запомнить это правило");
        psFileRu.put(280,"Тебе нужно запомнить это");
        psFileRu.put(281,"Мне нужно улучшить свой Английский");
        psFileRu.put(282,"Мне нужно говорить по-английски без ошибок");
        psFileRu.put(283,"Мне нужно говорить по-английски вовсе без каких-либо ошибок");
        psFileRu.put(284,"Моему другу нужна твоя помощь");
        psFileRu.put(285,"Моему другу нужен твой совет");
        psFileRu.put(286,"Мне нужен твой совет");
        psFileRu.put(287,"Его отцу нужны деньги");
        psFileRu.put(288,"Твоей маме нужно работать меньше");
        psFileRu.put(289,"Мне нужна эта вещь");
        psFileRu.put(290,"Я согласен с тобой");
        psFileRu.put(291,"Мы поддерживаем тебя");
        psFileRu.put(292,"Ты знаешь это лучше");
        psFileRu.put(293,"Они живут в другой стране");
        psFileRu.put(294,"Он всегда платит за неё");
        psFileRu.put(295,"Она согласна с тобой");
        psFileRu.put(296,"Это происходит время от времени");
        psFileRu.put(297,"Он часто ходит в кино");
        psFileRu.put(298,"Она ходит на работу");
        psFileRu.put(299,"У него так много проблем");
        psFileRu.put(300,"У него есть интересная идея");
        psFileRu.put(301,"Она припадает Испанский");
        psFileRu.put(302,"Я не заказываю еду там");
        psFileRu.put(303,"У нас нет каких-либо вопросов");
        psFileRu.put(304,"Ты не понимаешь нас");
        psFileRu.put(305,"Они не верят ему");
        psFileRu.put(306,"Она не говорит мне эти вещи");
        psFileRu.put(307,"Он не говорит по-испански");
        psFileRu.put(308,"Это не мотивирует меня");
        psFileRu.put(309,"Его девушка все знает");
        psFileRu.put(310,"Наши учителя не объясняют это");
        psFileRu.put(311,"Её парень не знает об этой проблеме");
        //Вопросы
        psFileRu.put(312,"Ты знаешь это?");
        psFileRu.put(313,"Я делаю ошибки?");
        psFileRu.put(314,"Мы показываем хорошие результаты?");
        psFileRu.put(315,"Ты понимаешь меня?");
        psFileRu.put(316,"Они согласны с нами?");
        psFileRu.put(317,"Ты пытаешься улучшить этот результат?");
        psFileRu.put(318,"Ты работаешь над своими ошибками?");
        psFileRu.put(319,"У тебя есть свободное время?");
        psFileRu.put(320,"Ты поддерживаешь меня?");
        psFileRu.put(321,"Ты согласен со мной?");
        psFileRu.put(322,"Ты помнишь это?");
        psFileRu.put(323,"Ты все помнишь?");
        psFileRu.put(324,"Ты знаешь об этой проблеме?");
        psFileRu.put(325,"Тебе нужна помощь?");
        psFileRu.put(326,"Тебе нужно больше денег?");
        psFileRu.put(327,"Тебе нужен мой совет?");
        psFileRu.put(328,"Ты поддерживаешь это решение?");
        psFileRu.put(329,"Ты хочешь учиться лучше?");
        psFileRu.put(330,"Ты хочешь знать свои ошибки?");
        psFileRu.put(331,"Тебе нужно решить эту проблему прямо сейчас?");
        psFileRu.put(332,"Тебе нравится это?");
        psFileRu.put(333,"Тебе нравится этот канал?");
        psFileRu.put(334,"Тебе нравится эта песня?");
        psFileRu.put(335,"Тебе нравится эта идея?");
        psFileRu.put(336,"Тебе нравится класическая музыка?");
        psFileRu.put(337,"Ты часто делаешь это?");
        psFileRu.put(338,"Ты часто слушаешь музыку?");
        psFileRu.put(339,"Ты часто ходишь туда?");
        psFileRu.put(340,"Ты часто пользуешся интернетом?");
        psFileRu.put(341,"Ты часто ходишь в зал?");
        psFileRu.put(342,"Ты часто посещаешь это место?");
        psFileRu.put(343,"Они часто обсуждают это?");
        psFileRu.put(344,"Они делают тоже самое?");
        psFileRu.put(345,"У нас достаточно практики?");
        psFileRu.put(346,"У нас достаточно знаний?");
        psFileRu.put(347,"Она думает об этом?");
        psFileRu.put(348,"Он живет там?");
        psFileRu.put(349,"Это помогает тебе?");
        psFileRu.put(350,"Она припадает английский?");
        psFileRu.put(351,"Она говорит ему все?");
        psFileRu.put(352,"Она игнорирует это?");
        psFileRu.put(353,"Он ненавидит это?");
        psFileRu.put(354,"Он ненавидит эту вещь?");
        psFileRu.put(355,"Он платит за это?");
        psFileRu.put(356,"Он ищет работу?");
        psFileRu.put(357,"Он пытается найти новую работу?");
        psFileRu.put(358,"Он хочет работать в другом месте?");
        psFileRu.put(359,"Ей нужно позвонить ему?");
        psFileRu.put(360,"Её нужно прийти туда?");
        psFileRu.put(361,"Её нужно прийти в это место?");
        psFileRu.put(362,"Она часто говорит это?");
        psFileRu.put(363,"Он часто слышит это?");
        psFileRu.put(364,"Она часто слушает радио?");
        psFileRu.put(365,"Он часто смотрит ТВ?");
        psFileRu.put(366,"Она часто пользуется этим?");
        psFileRu.put(367,"Это часто происходит?");
        psFileRu.put(368,"Это иногда случается? / Это случается иногда?");
        psFileRu.put(369,"Ему нравится это?");
        psFileRu.put(370,"Ей нравится это?");
        psFileRu.put(371,"Ему нравится этот проект?");
        psFileRu.put(372,"Ей нравится эта профессия?");
        psFileRu.put(373,"Это выглядет странным?");
        psFileRu.put(374,"Это кажется интересным?");
        psFileRu.put(375,"Это кажется скучным?");
        psFileRu.put(376,"Этот урок кажется полезным?");
        psFileRu.put(377,"Эти уроки помогают тебе?");
        psFileRu.put(378,"Этот канал кажется очень интересным?");
        psFileRu.put(379,"Этот учитель очень хорошо объясняет все?");
        psFileRu.put(380,"Эта информация кажется бесполезной?");
        psFileRu.put(381,"Эта вещь кажется важной?");
        psFileRu.put(382,"Эти вещи кажутся не важными?");
        psFileRu.put(383,"Этот экзамен кажется очень сложным?");
        psFileRu.put(384,"Тот тест кажется очень легким?");
        psFileRu.put(385,"Его девушка понимает это?");
        psFileRu.put(386,"Их босс знает всю правду?");
        psFileRu.put(387,"Эти студенты показывают отличные результаты?");
        psFileRu.put(388,"Этот студент показывает блестящие результаты?");
        psFileRu.put(389,"Тот студент делает ошибки?");
        psFileRu.put(390,"Те студенты говорят по-английски правильно?");
        psFileRu.put(391,"Твоему другу нравиться эта идея?");
        psFileRu.put(392,"Твои друзья поддерживают тебя?");
        psFileRu.put(393,"Это упражнение кажется слишком легким?");
        psFileRu.put(394,"Этот результат зависит от тебя?");
        psFileRu.put(395,"Где ты живешь?");
        psFileRu.put(396,"Где ты работаешь?");
        psFileRu.put(397,"Куда ты идешь?");
        psFileRu.put(398,"Где они проводят время вместе?");
        psFileRu.put(399,"Почему ты думаешь так?");
        psFileRu.put(400,"Почему ты согласен с ним?");
        psFileRu.put(401,"Почему ты изучаешь английский?");
        psFileRu.put(402,"Что ты думаешь об этом?");
        psFileRu.put(403,"Что ты знаешь?");
        psFileRu.put(404,"Что ты хочешь сделать?");
        psFileRu.put(405,"Что тебе нужно сделать?");
        psFileRu.put(406,"Как ты находишь эту идею?");
        psFileRu.put(407,"Как ты добираешься на работу?");
        psFileRu.put(408,"Как ты добираешься до туда?");
        psFileRu.put(409,"Когда ты чувствуешь себя счастливой?");
        psFileRu.put(410,"Когда ты идешь на работу?");
        psFileRu.put(411,"Когда у тебя есть свободное время?");
        psFileRu.put(412,"Что ты хочешь сказать?");
        psFileRu.put(413,"Что кажется странным?");
        psFileRu.put(414,"Что они хотят сказать тебе?");
        psFileRu.put(415,"Что помогает тебе?");
        psFileRu.put(416,"Что реально помогает тебе?");
        psFileRu.put(417,"Кого ты знаешь?");
        psFileRu.put(418,"Кто знает это?");
        psFileRu.put(419,"Кого ты поддерживаешь?");
        psFileRu.put(420,"Кто поддерживает тебя?");
        psFileRu.put(421,"Какие книги ты читаешь?");
        psFileRu.put(422,"Какие английские книги ты читаешь?");
        psFileRu.put(423,"Какую музыку ты предпочитаешь?");
        psFileRu.put(424,"Какого рода книги ты читаешь?");
        psFileRu.put(425,"Какого рода компьютерные игры они играют?");
        psFileRu.put(426,"В какое время ты встаешь?");
        psFileRu.put(427,"В какое время ты ложишся спать?");
        psFileRu.put(428,"Сколько денег у тебя с собой?");
        psFileRu.put(429,"Сколько друзей у тебя?");
        psFileRu.put(430,"Как часто ты ходишь туда?");
        psFileRu.put(431,"Как часто ты ходишь в зал?");
        psFileRu.put(432,"Как регулярно ты занимаешся английским?");
        psFileRu.put(433,"Где он работает?");
        psFileRu.put(434,"Где она учится?");
        psFileRu.put(435,"Куда она ходит?");
        psFileRu.put(436,"Почему он жалуется так часто?");
        psFileRu.put(437,"Почему она отказывается платить?");
        psFileRu.put(438,"Почему это происходит снова и снова?");
        psFileRu.put(439,"Что она говорит?");
        psFileRu.put(440,"Что она говорит ему?");
        psFileRu.put(441,"Что он хочет добавить?");
        psFileRu.put(442,"Что она пытается делать?");
        psFileRu.put(443,"Что ему нужно изменить?");
        psFileRu.put(444,"Как она тестирует их знания?");
        psFileRu.put(445,"Как это помогает тебе?");
        psFileRu.put(446,"Как он поддерживает тебя?");
        psFileRu.put(447,"Когда это происходит?");
        psFileRu.put(448,"Когда он чувствует себя счастливым?");
        psFileRu.put(449,"Что он помнит?");
        psFileRu.put(450,"Что она хочет добавить?");
        psFileRu.put(451,"Что помогает тебе?");
        psFileRu.put(452,"Что интересует тебя?");
        psFileRu.put(453,"Что беспокоит тебя?");
        psFileRu.put(454,"Кого это мотивирует?");
        psFileRu.put(455,"Кто мотивирует тебя?");
        psFileRu.put(456,"Кого она любит?");
        psFileRu.put(457,"Кто любит её?");
        psFileRu.put(458,"Кого он поддерживает?");
        psFileRu.put(459,"Кто поддерживает его?");
        psFileRu.put(460,"Какие Английские книги у него есть?");
        psFileRu.put(461,"Какие каналы он смотрит?");
        psFileRu.put(462,"Какого рода фильмы он смотрит?");
        psFileRu.put(463,"Она смотрит различные фильмы!");
        psFileRu.put(464,"Какие книги она предпочитает читать?");
        psFileRu.put(465,"Какой канал ты обычно смотришь?");
        psFileRu.put(466,"Какие каналы ты обычно смотришь?");
        psFileRu.put(467,"Какой напиток она предпочитает: чай или коффе?");
        psFileRu.put(468,"Какие напитки она предпочитает?");
        psFileRu.put(469,"В какое время он приходит на работу?");
        psFileRu.put(470,"В какое время она уходит из дома?");
        psFileRu.put(471,"Сколько денег она платит?");
        psFileRu.put(472,"Сколько у него долларов?");
        psFileRu.put(473,"Как часто она ходит в кино?");
        psFileRu.put(474,"Как часто он ходит в зоопарк?");
        psFileRu.put(475,"Как регулярно он делает эти упражнения?");
        psFileRu.put(476,"Что ты делаешь?");
        psFileRu.put(477,"Как долго это знаимает у тебя добраться до работы?");
        psFileRu.put(478,"Сколько по времени он добирается до этого места?");
        psFileRu.put(479,"Какой совет она дает тебе?");
        psFileRu.put(480,"Где? Куда?");
        psFileRu.put(481,"Почему?");
        psFileRu.put(482,"Кто? Кого?");
        psFileRu.put(483,"Как?");
        psFileRu.put(484,"Когда?");
        psFileRu.put(485,"Что? Какой? Какая? Какие?");
        psFileRu.put(486,"Какой? Какая? Какие? - ограниченый выбор 1-3");
        psFileRu.put(487,"Где работает твой отец?");
        psFileRu.put(488,"Где живут твои родители?");
        psFileRu.put(489,"Почему твой босс критекует это?");
        psFileRu.put(490,"Почему твоя мама думает так?");
        psFileRu.put(491,"Почему твои друзья не соглашаются с тобой?");
        psFileRu.put(492,"Как чувствует твоя сестра?");
        psFileRu.put(493,"Как твой брат контролирует это?");
        psFileRu.put(494,"Когда твой отец уходит из дома?");
        psFileRu.put(495,"Когда эта вещь происходит?");
        psFileRu.put(496,"Когда эти вещи происходят?");
        psFileRu.put(497,"Что твои друзья обычно заказывают?");
        psFileRu.put(498,"Что обычно обещает твой босс?");
        psFileRu.put(499,"Какой совет твоя учительница дает тебе?");
        psFileRu.put(500,"Какие советы твои учителя дают тебе?");
        psFileRu.put(501,"Какого рода примеры его учитель дает?");
        psFileRu.put(502,"Как много совободного времени есть у твоего бизнес партнера?");
        psFileRu.put(503,"Как много английских слов твой друг хочет знать?");
        psFileRu.put(504,"Как часто эта вещь происходит?");
        psFileRu.put(505,"Как часто происходят эти вещи?");
        psFileRu.put(506,"Как регулярно твой босс проверяет это?");
        psFileRu.put(507,"Сколько по времени занимает у его сына добраться до работы?");
        psFileRu.put(508,"Сколько по времени занимает у его дочери добраться до школы?");
        psFileRu.put(509,"Что твой босс обычно отвечает?");
        psFileRu.put(510,"Он делает это с огромным удовольствием?");
        psFileRu.put(511,"Ты разделяешь его точку зрения?");
        psFileRu.put(512,"Что вдохновляет тебя?");
        psFileRu.put(513,"Как часто твоя девушка упоминает это?");
        psFileRu.put(514,"Она часто спрашивает меня об этом!");
        psFileRu.put(515,"Давай поговорим об этом!");

        return psFileRu;
    }
}
