package texts;

import java.util.HashMap;
import java.util.Map;

public class WordsText implements ITexts
{
    private Map<Integer, String> wordEn = new HashMap<>();
    private Map<Integer, String> wordRu = new HashMap<>();

    @Override
    public Map<Integer, String> getEnglish(){
        getStrWordsEn();
        return wordEn;
    }

    @Override
    public Map<Integer, String> getRussia(){
        getStrWordsRu();
        return wordRu;
    }

    private Map<Integer, String> getStrWordsEn(){
        wordEn.put(0,"hi");
        wordEn.put(1,"hello");
        wordEn.put(2,"sorry");
        wordEn.put(3,"please");
        wordEn.put(4,"thank you");
        wordEn.put(5,"you are welcome");
        wordEn.put(6,"what a pity");
        wordEn.put(7,"(good)bye");
        wordEn.put(8,"people");
        wordEn.put(9,"man");
        wordEn.put(10,"woman");
        wordEn.put(11,"child");
        wordEn.put(12,"boy");
        wordEn.put(13,"girl");
        wordEn.put(14,"guy");
        wordEn.put(15,"friend");
        wordEn.put(16,"acquaintance");
        wordEn.put(17,"neighbor");
        wordEn.put(18,"guest");
        wordEn.put(19,"chief");
        wordEn.put(20,"boss");
        wordEn.put(21,"competitor");
        wordEn.put(22,"client");
        wordEn.put(23,"colleague");
        wordEn.put(24,"family ");
        wordEn.put(25,"parents");
        wordEn.put(26,"father");
        wordEn.put(27,"dad(dy)");
        wordEn.put(28,"mother");
        wordEn.put(29,"mum(my)");
        wordEn.put(30,"husband");
        wordEn.put(31,"wife");
        wordEn.put(32,"son");
        wordEn.put(33,"daughter");
        wordEn.put(34,"brother");
        wordEn.put(35,"sister");
        wordEn.put(36,"grandfather");
        wordEn.put(37,"father-in-law");
        wordEn.put(38,"uncle");
        wordEn.put(39,"aunt");
        wordEn.put(40,"cousin");
        wordEn.put(41,"nephew");
        wordEn.put(42,"niece");
        wordEn.put(43,"job");
        wordEn.put(44,"businessman");
        wordEn.put(45,"teacher");
        wordEn.put(46,"driver");
        wordEn.put(47,"worker");
        wordEn.put(48,"engineer");
        wordEn.put(49,"doctor");
        wordEn.put(50,"lawyer");
        wordEn.put(51,"journalist");
        wordEn.put(52,"nurse");
        wordEn.put(53,"shop assistant");
        wordEn.put(54,"waiter");
        wordEn.put(55,"accountant");
        wordEn.put(56,"artist");
        wordEn.put(57,"musician");
        wordEn.put(58,"actor");
        wordEn.put(59,"student");
        wordEn.put(60,"pupil");
        wordEn.put(61,"animal");
        wordEn.put(62,"cat");
        wordEn.put(63,"dog");
        wordEn.put(64,"bird");
        wordEn.put(65,"squirrel");
        wordEn.put(66,"wolf");
        wordEn.put(67,"goose");
        wordEn.put(68,"giraffe");
        wordEn.put(69,"rabbit");
        wordEn.put(70,"cow");
        wordEn.put(71,"rat");
        wordEn.put(72,"fox");
        wordEn.put(73,"horse");
        wordEn.put(74,"frog");
        wordEn.put(75,"bear");
        wordEn.put(76,"mouse");
        wordEn.put(77,"monkey");
        wordEn.put(78,"pig");
        wordEn.put(79,"elephant");
        wordEn.put(80,"duck");
        wordEn.put(81,"country");
        wordEn.put(82,"Russia");
        wordEn.put(83,"Great Britain");
        wordEn.put(84,"England");
        wordEn.put(85,"city");
        wordEn.put(86,"house");
        wordEn.put(87,"home");
        wordEn.put(88,"building");
        wordEn.put(89,"place");
        wordEn.put(90,"entrance");
        wordEn.put(91,"exit");
        wordEn.put(92,"center");
        wordEn.put(93,"yard");
        wordEn.put(94,"roof");
        wordEn.put(95,"fence");
        wordEn.put(96,"land");
        wordEn.put(97,"village");
        wordEn.put(98,"school");
        wordEn.put(99,"university");
        wordEn.put(100,"theater");
        wordEn.put(101,"church");
        wordEn.put(102,"restaurant");
        wordEn.put(103,"cafe");
        wordEn.put(104,"hotel");
        wordEn.put(105,"bank");
        wordEn.put(106,"cinema");
        wordEn.put(107,"hospital");
        wordEn.put(108,"police");
        wordEn.put(109,"post office");
        wordEn.put(110,"station");
        wordEn.put(111,"airport");
        wordEn.put(112,"shop");
        wordEn.put(113,"pharmacy");
        wordEn.put(114,"market");
        wordEn.put(115,"office");
        wordEn.put(116,"company");
        wordEn.put(117,"factory");
        wordEn.put(118,"square");
        wordEn.put(119,"street");
        wordEn.put(120,"road");
        wordEn.put(121,"crossroads");
        wordEn.put(122,"stop");
        wordEn.put(123,"sidewalk");
        wordEn.put(124,"path");
        wordEn.put(125,"garden");
        wordEn.put(126,"park");
        wordEn.put(127,"bridge");
        wordEn.put(128,"river");
        wordEn.put(129,"forest");
        wordEn.put(130,"field");
        wordEn.put(131,"mountain");
        wordEn.put(132,"lake");
        wordEn.put(133,"sea");
        wordEn.put(134,"ocean");
        wordEn.put(135,"coast");
        wordEn.put(136,"beach");
        wordEn.put(137,"sand");
        wordEn.put(138,"island");
        wordEn.put(139,"border");
        wordEn.put(140,"customs");
        wordEn.put(141,"garbage");
        wordEn.put(142,"waste");
        wordEn.put(143,"stone");
        wordEn.put(144,"plant");
        wordEn.put(145,"tree");
        wordEn.put(146,"grass");
        wordEn.put(147,"flower");
        wordEn.put(148,"leaf");
        wordEn.put(149,"flat");
        wordEn.put(150,"room");
        wordEn.put(151,"living room");
        wordEn.put(152,"bedroom");
        wordEn.put(153,"bathroom");
        wordEn.put(154,"shower");
        wordEn.put(155,"toilet");
        wordEn.put(156,"kitchen");
        wordEn.put(157,"hall");
        wordEn.put(158,"balcony");
        wordEn.put(159,"floor");
        wordEn.put(160,"ceiling");
        wordEn.put(161,"wall");
        wordEn.put(162,"stairs");
        wordEn.put(163,"door");
        wordEn.put(164,"window");
        wordEn.put(165,"windowsill");
        wordEn.put(166,"curtain");
        wordEn.put(167,"switch");
        wordEn.put(168,"socket");
        wordEn.put(169,"faucet");
        wordEn.put(170,"pipe");
        wordEn.put(171,"chimney");
        wordEn.put(172,"furniture");
        wordEn.put(173,"table");
        wordEn.put(174,"chair");
        wordEn.put(175,"armchair");
        wordEn.put(176,"sofa");
        wordEn.put(177,"bed");
        wordEn.put(178,"wardrobe");
        wordEn.put(179,"cabinet");
        wordEn.put(180,"shelf");
        wordEn.put(181,"mirror");
        wordEn.put(182,"carpet");
        wordEn.put(183,"fridge");
        wordEn.put(184,"microwave");
        wordEn.put(185,"oven");
        wordEn.put(186,"stove");
        wordEn.put(187,"food");
        wordEn.put(188,"bread");
        wordEn.put(189,"butter");
        wordEn.put(190,"oil");
        wordEn.put(191,"cheese");
        wordEn.put(192,"sausage");
        wordEn.put(193,"ham");
        wordEn.put(194,"meat");
        wordEn.put(195,"beef");
        wordEn.put(196,"pork");
        wordEn.put(197,"lamb");
        wordEn.put(198,"chicken");
        wordEn.put(199,"cutlet");
        wordEn.put(200,"fish");
        wordEn.put(201,"egg");
        wordEn.put(202,"salad");
        wordEn.put(203,"mushroom");
        wordEn.put(204,"corn");
        wordEn.put(205,"porridge");
        wordEn.put(206,"oatmeal");
        wordEn.put(207,"soup");
        wordEn.put(208,"sandwich");
        wordEn.put(209,"rice");
        wordEn.put(210,"noodles");
        wordEn.put(211,"flour");
        wordEn.put(212,"spice");
        wordEn.put(213,"pepper");
        wordEn.put(214,"salt");
        wordEn.put(215,"onion");
        wordEn.put(216,"garlic");
        wordEn.put(217,"sauce");
        wordEn.put(218,"vegetables");
        wordEn.put(219,"potatoes");
        wordEn.put(220,"carrot");
        wordEn.put(221,"beet");
        wordEn.put(222,"tomato");
        wordEn.put(223,"cucumber");
        wordEn.put(224,"cabbage");
        wordEn.put(225,"squash");
        wordEn.put(226,"eggplant");
        wordEn.put(227,"beans");
        wordEn.put(228,"pea");
        wordEn.put(229,"nut");
        wordEn.put(230,"fruit");
        wordEn.put(231,"apple");
        wordEn.put(232,"pear");
        wordEn.put(233,"banana");
        wordEn.put(234,"berry");
        wordEn.put(235,"strawberry");
        wordEn.put(236,"raspberry");
        wordEn.put(237,"cherry");
        wordEn.put(238,"plum");
        wordEn.put(239,"grape");
        wordEn.put(240,"apricot");
        wordEn.put(241,"peach");
        wordEn.put(242,"melon");
        wordEn.put(243,"watermelon");
        wordEn.put(244,"pumpkin");
        wordEn.put(245,"orange");
        wordEn.put(246,"mandarin");
        wordEn.put(247,"lemon");
        wordEn.put(248,"pineapple");
        wordEn.put(249,"sugar");
        wordEn.put(250,"honey");
        wordEn.put(251,"jam");
        wordEn.put(252,"cake");
        wordEn.put(253,"bun");
        wordEn.put(254,"cookie");
        wordEn.put(255,"pie");
        wordEn.put(256,"sweet");
        wordEn.put(257,"ice-cream");
        wordEn.put(258,"chocolate");
        wordEn.put(259,"water");
        wordEn.put(260,"soda");
        wordEn.put(261,"juice");
        wordEn.put(262,"wine");
        wordEn.put(263,"tea");
        wordEn.put(264,"coffee");
        wordEn.put(265,"milk");
        wordEn.put(266,"cream");
        wordEn.put(267,"yogurt");
        wordEn.put(268,"curd");
        wordEn.put(269,"dish ");
        wordEn.put(270,"cup");
        wordEn.put(271,"glass");
        wordEn.put(272,"mug");
        wordEn.put(273,"plate");
        wordEn.put(274,"spoon");
        wordEn.put(275,"fork");
        wordEn.put(276,"knife");
        wordEn.put(277,"saucer");
        wordEn.put(278,"bottle");
        wordEn.put(279,"napkin");
        wordEn.put(280,"pan");
        wordEn.put(281,"frying pan");
        wordEn.put(282,"kettle");
        wordEn.put(283,"meal ");
        wordEn.put(284,"breakfast");
        wordEn.put(285,"lunch");
        wordEn.put(286,"dinner");
        wordEn.put(287,"transport ");
        wordEn.put(288,"plane");
        wordEn.put(289,"car");
        wordEn.put(290,"tram");
        wordEn.put(291,"bus");
        wordEn.put(292,"train");
        wordEn.put(293,"ship");
        wordEn.put(294,"bicycle");
        wordEn.put(295,"time ");
        wordEn.put(296,"minute");
        wordEn.put(297,"hour");
        wordEn.put(298,"week");
        wordEn.put(299,"year");
        wordEn.put(300,"century");
        wordEn.put(301,"the day before yesterday");
        wordEn.put(302,"yesterday");
        wordEn.put(303,"today");
        wordEn.put(304,"tonight");
        wordEn.put(305,"tomorrow");
        wordEn.put(306,"the day after tomorrow");
        wordEn.put(307,"day");
        wordEn.put(308,"morning");
        wordEn.put(309,"afternoon");
        wordEn.put(310,"evening");
        wordEn.put(311,"night");
        wordEn.put(312,"Monday");
        wordEn.put(313,"Tuesday");
        wordEn.put(314,"Wednesday");
        wordEn.put(315,"Thursday");
        wordEn.put(316,"Friday");
        wordEn.put(317,"Saturday");
        wordEn.put(318,"Sunday");
        wordEn.put(319,"month");
        wordEn.put(320,"January");
        wordEn.put(321,"February");
        wordEn.put(322,"March");
        wordEn.put(323,"April");
        wordEn.put(324,"May");
        wordEn.put(325,"June");
        wordEn.put(326,"July");
        wordEn.put(327,"August");
        wordEn.put(328,"September");
        wordEn.put(329,"October");
        wordEn.put(330,"November");
        wordEn.put(331,"December");
        wordEn.put(332,"season");
        wordEn.put(333,"spring");
        wordEn.put(334,"summer");
        wordEn.put(335,"autumn");
        wordEn.put(336,"winter");
        wordEn.put(337,"holiday");
        wordEn.put(338,"Christmas");
        wordEn.put(339,"Easter");
        wordEn.put(340,"birthday");
        wordEn.put(341,"form");
        wordEn.put(342,"name");
        wordEn.put(343,"first name");
        wordEn.put(344,"surname");
        wordEn.put(345,"maiden name");
        wordEn.put(346,"birth date");
        wordEn.put(347,"place of birth");
        wordEn.put(348,"address");
        wordEn.put(349,"marital status");
        wordEn.put(350,"single");
        wordEn.put(351,"married");
        wordEn.put(352,"divorced");
        wordEn.put(353,"widowed");
        wordEn.put(354,"thing");
        wordEn.put(355,"pen");
        wordEn.put(356,"pencil");
        wordEn.put(357,"book");
        wordEn.put(358,"copybook");
        wordEn.put(359,"notebook");
        wordEn.put(360,"note");
        wordEn.put(361,"dictionary");
        wordEn.put(362,"letter");
        wordEn.put(363,"envelope");
        wordEn.put(364,"paper");
        wordEn.put(365,"newspaper");
        wordEn.put(366,"magazine");
        wordEn.put(367,"(tele)phone");
        wordEn.put(368,"clock");
        wordEn.put(369,"comb");
        wordEn.put(370,"TV");
        wordEn.put(371,"iron");
        wordEn.put(372,"soap");
        wordEn.put(373,"radio");
        wordEn.put(374,"bag");
        wordEn.put(375,"backpack");
        wordEn.put(376,"map");
        wordEn.put(377,"card");
        wordEn.put(378,"suitcase");
        wordEn.put(379,"present");
        wordEn.put(380,"camera");
        wordEn.put(381,"vase");
        wordEn.put(382,"handkerchief");
        wordEn.put(383,"ball");
        wordEn.put(384,"balloon");
        wordEn.put(385,"toy");
        wordEn.put(386,"ticket");
        wordEn.put(387,"luggage");
        wordEn.put(388,"battery");
        wordEn.put(389,"bucket");
        wordEn.put(390,"rope");
        wordEn.put(391,"board");
        wordEn.put(392,"calendar");
        wordEn.put(393,"laptop");
        wordEn.put(394,"brush");
        wordEn.put(395,"keyboard");
        wordEn.put(396,"key");
        wordEn.put(397,"wheel");
        wordEn.put(398,"steering wheel");
        wordEn.put(399,"trunk");
        wordEn.put(400,"gas(oline)");
        wordEn.put(401,"purse");
        wordEn.put(402,"wallet");
        wordEn.put(403,"lamp");
        wordEn.put(404,"ruler");
        wordEn.put(405,"shovel");
        wordEn.put(406,"machine");
        wordEn.put(407,"hammer");
        wordEn.put(408,"scissors");
        wordEn.put(409,"glasses");
        wordEn.put(410,"package");
        wordEn.put(411,"stick");
        wordEn.put(412,"glue");
        wordEn.put(413,"gift");
        wordEn.put(414,"towel");
        wordEn.put(415,"mail");
        wordEn.put(416,"wire");
        wordEn.put(417,"page");
        wordEn.put(418,"torch");
        wordEn.put(419,"box");
        wordEn.put(420,"blanket");
        wordEn.put(421,"sheet");
        wordEn.put(422,"pillow");
        wordEn.put(423,"сlothes");
        wordEn.put(424,"shoes");
        wordEn.put(425,"boot");
        wordEn.put(426,"sneakers");
        wordEn.put(427,"coat");
        wordEn.put(428,"dress");
        wordEn.put(429,"suit");
        wordEn.put(430,"shirt");
        wordEn.put(431,"blouse");
        wordEn.put(432,"skirt");
        wordEn.put(433,"glove");
        wordEn.put(434,"mitten");
        wordEn.put(435,"hat");
        wordEn.put(436,"cap");
        wordEn.put(437,"jacket");
        wordEn.put(438,"cardigan");
        wordEn.put(439,"scarf");
        wordEn.put(440,"sock");
        wordEn.put(441,"sweater");
        wordEn.put(442,"Invoc-shirt");
        wordEn.put(443,"tie");
        wordEn.put(444,"trousers");
        wordEn.put(445,"shorts");
        wordEn.put(446,"tights");
        wordEn.put(447,"stockings");
        wordEn.put(448,"jeans");
        wordEn.put(449,"hood");
        wordEn.put(450,"belt");
        wordEn.put(451,"underwear ");
        wordEn.put(452,"briefs");
        wordEn.put(453,"panties");
        wordEn.put(454,"bra ");
        wordEn.put(455,"body ");
        wordEn.put(456,"head");
        wordEn.put(457,"face");
        wordEn.put(458,"forehead ");
        wordEn.put(459,"nose");
        wordEn.put(460,"ear");
        wordEn.put(461,"mouth");
        wordEn.put(462,"throat");
        wordEn.put(463,"eye");
        wordEn.put(464,"eyebrow");
        wordEn.put(465,"lips");
        wordEn.put(466,"tooth");
        wordEn.put(467,"hair");
        wordEn.put(468,"mustache");
        wordEn.put(469,"cheek");
        wordEn.put(470,"chin");
        wordEn.put(471,"neck");
        wordEn.put(472,"shoulder");
        wordEn.put(473,"chest");
        wordEn.put(474,"heart");
        wordEn.put(475,"stomach");
        wordEn.put(476,"back");
        wordEn.put(477,"wrist");
        wordEn.put(478,"hand");
        wordEn.put(479,"finger");
        wordEn.put(480,"nail");
        wordEn.put(481,"elbow");
        wordEn.put(482,"leg");
        wordEn.put(483,"knee");
        wordEn.put(484,"foot");
        wordEn.put(485,"heel");
        wordEn.put(486,"toe");
        wordEn.put(487,"beard");
        wordEn.put(488,"bone");
        wordEn.put(489,"health ");
        wordEn.put(490,"healthy");
        wordEn.put(491,"sick");
        wordEn.put(492,"sickness");
        wordEn.put(493,"fever  ");
        wordEn.put(494,"cough");
        wordEn.put(495,"running nose");
        wordEn.put(496,"sneeze");
        wordEn.put(497,"pain");
        wordEn.put(498,"headache");
        wordEn.put(499,"flu");
        wordEn.put(500,"bruise");
        wordEn.put(501,"event ");
        wordEn.put(502,"birth");
        wordEn.put(503,"game");
        wordEn.put(504,"lesson");
        wordEn.put(505,"vacation");
        wordEn.put(506,"party");
        wordEn.put(507,"meeting");
        wordEn.put(508,"wedding");
        wordEn.put(509,"negotiation");
        wordEn.put(510,"trip");
        wordEn.put(511,"death");
        wordEn.put(512,"weather ");
        wordEn.put(513,"sun");
        wordEn.put(514,"moon");
        wordEn.put(515,"wind");
        wordEn.put(516,"fog");
        wordEn.put(517,"rain");
        wordEn.put(518,"snow");
        wordEn.put(519,"sky");
        wordEn.put(520,"cloud");
        wordEn.put(521,"air");
        wordEn.put(522,"temperature");
        wordEn.put(523,"degree");
        wordEn.put(524,"art ");
        wordEn.put(525,"music");
        wordEn.put(526,"song");
        wordEn.put(527,"literature");
        wordEn.put(528,"story");
        wordEn.put(529,"movie");
        wordEn.put(530,"film");
        wordEn.put(531,"sculpture");
        wordEn.put(532,"picture");
        wordEn.put(533,"photo");
        wordEn.put(534,"advertising");
        wordEn.put(535,"purchase ");
        wordEn.put(536,"size");
        wordEn.put(537,"price");
        wordEn.put(538,"money");
        wordEn.put(539,"cash");
        wordEn.put(540,"discount");
        wordEn.put(541,"account");
        wordEn.put(542,"bill");
        wordEn.put(543,"tip");
        wordEn.put(544,"measure ");
        wordEn.put(545,"distance");
        wordEn.put(546,"length");
        wordEn.put(547,"height");
        wordEn.put(548,"depth");
        wordEn.put(549,"strength");
        wordEn.put(550,"speed");
        wordEn.put(551,"kilometer");
        wordEn.put(552,"kilogram");
        wordEn.put(553,"pound");
        wordEn.put(554,"feeling ");
        wordEn.put(555,"fun");
        wordEn.put(556,"joy");
        wordEn.put(557,"fear");
        wordEn.put(558,"sadness");
        wordEn.put(559,"passion");
        wordEn.put(560,"pleasure");
        wordEn.put(561,"happiness");
        wordEn.put(562,"peace");
        wordEn.put(563,"love");
        wordEn.put(564,"hate");
        wordEn.put(565,"world");
        wordEn.put(566,"soul");
        wordEn.put(567,"life");
        wordEn.put(568,"knowledge");
        wordEn.put(569,"task");
        wordEn.put(570,"exercise");
        wordEn.put(571,"luck");
        wordEn.put(572,"problem");
        wordEn.put(573,"opportunity");
        wordEn.put(574,"ability");
        wordEn.put(575,"beauty");
        wordEn.put(576,"danger");
        wordEn.put(577,"experience");
        wordEn.put(578,"memory");
        wordEn.put(579,"benefit");
        wordEn.put(580,"advantage");
        wordEn.put(581,"profit");
        wordEn.put(582,"habit");
        wordEn.put(583,"reason");
        wordEn.put(584,"consequence");
        wordEn.put(585,"meaning");
        wordEn.put(586,"means");
        wordEn.put(587,"effort");
        wordEn.put(588,"success");
        wordEn.put(589,"goal");
        wordEn.put(590,"miracle");
        wordEn.put(591,"science");
        wordEn.put(592,"language");
        wordEn.put(593,"word");
        wordEn.put(594,"fire");
        wordEn.put(595,"case");
        wordEn.put(596,"circumstance");
        wordEn.put(597,"thought");
        wordEn.put(598,"choice");
        wordEn.put(599,"permit");
        wordEn.put(600,"delivery");
        wordEn.put(601,"achievement");
        wordEn.put(602,"duty");
        wordEn.put(603,"delay");
        wordEn.put(604,"relationship");
        wordEn.put(605,"mark");
        wordEn.put(606,"mistake");
        wordEn.put(607,"behavior");
        wordEn.put(608,"invitation");
        wordEn.put(609,"development");
        wordEn.put(610,"decision");
        wordEn.put(611,"solution");
        wordEn.put(612,"advice");
        wordEn.put(613,"agreement");
        wordEn.put(614,"list");
        wordEn.put(615,"argument");
        wordEn.put(616,"test");
        wordEn.put(617,"step");
        wordEn.put(618,"piece");
        wordEn.put(619,"area");
        wordEn.put(620,"pair");
        wordEn.put(621,"couple");
        wordEn.put(622,"surface");
        wordEn.put(623,"mess");
        wordEn.put(624,"question ");
        wordEn.put(625,"what");
        wordEn.put(626,"who");
        wordEn.put(627,"where");
        wordEn.put(628,"how");
        wordEn.put(629,"why");
        wordEn.put(630,"when");
        wordEn.put(631,"how many");
        wordEn.put(632,"how much");
        wordEn.put(633,"I");
        wordEn.put(634,"you");
        wordEn.put(635,"he");
        wordEn.put(636,"she");
        wordEn.put(637,"it");
        wordEn.put(638,"we");
        wordEn.put(639,"they");
        wordEn.put(640,"my");
        wordEn.put(641,"your");
        wordEn.put(642,"his");
        wordEn.put(643,"her");
        wordEn.put(644,"its");
        wordEn.put(645,"our");
        wordEn.put(646,"their");
        wordEn.put(647,"from");
        wordEn.put(648,"of");
        wordEn.put(649,"to");
        wordEn.put(650,"in");
        wordEn.put(651,"on");
        wordEn.put(652,"under");
        wordEn.put(653,"behind");
        wordEn.put(654,"with");
        wordEn.put(655,"without");
        wordEn.put(656,"in front of");
        wordEn.put(657,"before");
        wordEn.put(658,"after");
        wordEn.put(659,"between");
        wordEn.put(660,"near");
        wordEn.put(661,"for");
        wordEn.put(662,"since");
        wordEn.put(663,"during");
        wordEn.put(664,"around");
        wordEn.put(665,"because of");
        wordEn.put(666,"about");
        wordEn.put(667,"against");
        wordEn.put(668,"among");
        wordEn.put(669,"through");
        wordEn.put(670,"per");
        wordEn.put(671,"above");
        wordEn.put(672,"below");
        wordEn.put(673,"number ");
        wordEn.put(674,"zero");
        wordEn.put(675,"one");
        wordEn.put(676,"two");
        wordEn.put(677,"three");
        wordEn.put(678,"four");
        wordEn.put(679,"five");
        wordEn.put(680,"six");
        wordEn.put(681,"seven");
        wordEn.put(682,"eight");
        wordEn.put(683,"nine");
        wordEn.put(684,"ten");
        wordEn.put(685,"eleven");
        wordEn.put(686,"twelve  ");
        wordEn.put(687,"thirteen");
        wordEn.put(688,"fourteen");
        wordEn.put(689,"fifteen");
        wordEn.put(690,"sixteen");
        wordEn.put(691,"seventeen [");
        wordEn.put(692,"eighteen");
        wordEn.put(693,"nineteen");
        wordEn.put(694,"twenty");
        wordEn.put(695,"thirty");
        wordEn.put(696,"forty");
        wordEn.put(697,"fifty");
        wordEn.put(698,"sixty");
        wordEn.put(699,"seventy");
        wordEn.put(700,"eighty");
        wordEn.put(701,"ninety");
        wordEn.put(702,"hundred");
        wordEn.put(703,"thousand");
        wordEn.put(704,"first");
        wordEn.put(705,"second");
        wordEn.put(706,"third");
        wordEn.put(707,"fourth");
        wordEn.put(708,"fifth");
        wordEn.put(709,"color ");
        wordEn.put(710,"black");
        wordEn.put(711,"blue");
        wordEn.put(712,"brown");
        wordEn.put(713,"green");
        wordEn.put(714,"grey");
        wordEn.put(715,"red");
        wordEn.put(716,"white");
        wordEn.put(717,"yellow");
        wordEn.put(718,"pink");
        wordEn.put(719,"purple");
        wordEn.put(720,"old");
        wordEn.put(721,"young");
        wordEn.put(722,"new");
        wordEn.put(723,"big");
        wordEn.put(724,"large");
        wordEn.put(725,"huge");
        wordEn.put(726,"small");
        wordEn.put(727,"fat");
        wordEn.put(728,"slim");
        wordEn.put(729,"thick");
        wordEn.put(730,"thin");
        wordEn.put(731,"hungry");
        wordEn.put(732,"full");
        wordEn.put(733,"good");
        wordEn.put(734,"excellent");
        wordEn.put(735,"amazing");
        wordEn.put(736,"fine");
        wordEn.put(737,"bad");
        wordEn.put(738,"terrible");
        wordEn.put(739,"nasty");
        wordEn.put(740,"early");
        wordEn.put(741,"late");
        wordEn.put(742,"last  ");
        wordEn.put(743,"next");
        wordEn.put(744,"free");
        wordEn.put(745,"busy");
        wordEn.put(746,"hot");
        wordEn.put(747,"warm");
        wordEn.put(748,"cold");
        wordEn.put(749,"cool");
        wordEn.put(750,"spicy");
        wordEn.put(751,"sharp");
        wordEn.put(752,"blunt");
        wordEn.put(753,"stupid");
        wordEn.put(754,"clever");
        wordEn.put(755,"smart");
        wordEn.put(756,"nice");
        wordEn.put(757,"beautiful");
        wordEn.put(758,"handsome");
        wordEn.put(759,"attractive");
        wordEn.put(760,"pretty");
        wordEn.put(761,"ugly");
        wordEn.put(762,"high");
        wordEn.put(763,"tall");
        wordEn.put(764,"short");
        wordEn.put(765,"low");
        wordEn.put(766,"long");
        wordEn.put(767,"heavy");
        wordEn.put(768,"light");
        wordEn.put(769,"difficult");
        wordEn.put(770,"easy");
        wordEn.put(771,"simple");
        wordEn.put(772,"dark");
        wordEn.put(773,"expensive");
        wordEn.put(774,"dear");
        wordEn.put(775,"cheap");
        wordEn.put(776,"poor");
        wordEn.put(777,"rich");
        wordEn.put(778,"straight");
        wordEn.put(779,"left");
        wordEn.put(780,"right");
        wordEn.put(781,"wrong");
        wordEn.put(782,"fast");
        wordEn.put(783,"quick");
        wordEn.put(784,"slow");
        wordEn.put(785,"soft");
        wordEn.put(786,"hard");
        wordEn.put(787,"sad");
        wordEn.put(788,"glad");
        wordEn.put(789,"happy");
        wordEn.put(790,"merry");
        wordEn.put(791,"kind");
        wordEn.put(792,"angry");
        wordEn.put(793,"evil");
        wordEn.put(794,"polite");
        wordEn.put(795,"rude");
        wordEn.put(796,"gentle");
        wordEn.put(797,"brave");
        wordEn.put(798,"coward");
        wordEn.put(799,"shy");
        wordEn.put(800,"hard-working");
        wordEn.put(801,"lazy");
        wordEn.put(802,"useful");
        wordEn.put(803,"useless");
        wordEn.put(804,"strong");
        wordEn.put(805,"weak ");
        wordEn.put(806,"loud");
        wordEn.put(807,"noisy");
        wordEn.put(808,"quiet");
        wordEn.put(809,"calm");
        wordEn.put(810,"narrow");
        wordEn.put(811,"wide");
        wordEn.put(812,"clean");
        wordEn.put(813,"dirty");
        wordEn.put(814,"tired");
        wordEn.put(815,"honest");
        wordEn.put(816,"comfortable");
        wordEn.put(817,"strange");
        wordEn.put(818,"weird");
        wordEn.put(819,"own");
        wordEn.put(820,"tasty");
        wordEn.put(821,"delicious");
        wordEn.put(822,"bitter");
        wordEn.put(823,"sour");
        wordEn.put(824,"salty");
        wordEn.put(825,"ready");
        wordEn.put(826,"careful");
        wordEn.put(827,"main");
        wordEn.put(828,"able");
        wordEn.put(829,"necessary");
        wordEn.put(830,"important");
        wordEn.put(831,"sure");
        wordEn.put(832,"fit");
        wordEn.put(833,"better");
        wordEn.put(834,"best");
        wordEn.put(835,"worse");
        wordEn.put(836,"worst");
        wordEn.put(837,"more");
        wordEn.put(838,"most");
        wordEn.put(839,"less");
        wordEn.put(840,"least");
        wordEn.put(841,"sometimes");
        wordEn.put(842,"never");
        wordEn.put(843,"seldom");
        wordEn.put(844,"usually");
        wordEn.put(845,"often");
        wordEn.put(846,"always");
        wordEn.put(847,"soon");
        wordEn.put(848,"recently");
        wordEn.put(849,"well");
        wordEn.put(850,"far");
        wordEn.put(851,"exactly");
        wordEn.put(852,"probably");
        wordEn.put(853,"maybe");
        wordEn.put(854,"perhaps");
        wordEn.put(855,"really");
        wordEn.put(856,"of course");
        wordEn.put(857,"certainly");
        wordEn.put(858,"obviously");
        wordEn.put(859,"especially");
        wordEn.put(860,"yes");
        wordEn.put(861,"no");
        wordEn.put(862,"not");
        wordEn.put(863,"this");
        wordEn.put(864,"that");
        wordEn.put(865,"these");
        wordEn.put(866,"those");
        wordEn.put(867,"and");
        wordEn.put(868,"or");
        wordEn.put(869,"but");
        wordEn.put(870,"however");
        wordEn.put(871,"because");
        wordEn.put(872,"if");
        wordEn.put(873,"(al)though");
        wordEn.put(874,"be");
        wordEn.put(875,"do");
        wordEn.put(876,"have");
        wordEn.put(877,"can");
        wordEn.put(878,"may");
        wordEn.put(879,"go");
        wordEn.put(880,"find");
        wordEn.put(881,"hold");
        wordEn.put(882,"stand");
        wordEn.put(883,"sit");
        wordEn.put(884,"hear");
        wordEn.put(885,"win");
        wordEn.put(886,"get");
        wordEn.put(887,"make");
        wordEn.put(888,"come");
        wordEn.put(889,"become");
        wordEn.put(890,"run");
        wordEn.put(891,"see");
        wordEn.put(892,"write");
        wordEn.put(893,"fall");
        wordEn.put(894,"wear");
        wordEn.put(895,"take");
        wordEn.put(896,"give");
        wordEn.put(897,"forgive");
        wordEn.put(898,"forget");
        wordEn.put(899,"eat");
        wordEn.put(900,"lie");
        wordEn.put(901,"lead");
        wordEn.put(902,"feed");
        wordEn.put(903,"say");
        wordEn.put(904,"pay");
        wordEn.put(905,"lay");
        wordEn.put(906,"drink");
        wordEn.put(907,"swim");
        wordEn.put(908,"sing");
        wordEn.put(909,"begin");
        wordEn.put(910,"ring");
        wordEn.put(911,"sink");
        wordEn.put(912,"stink");
        wordEn.put(913,"fly");
        wordEn.put(914,"know");
        wordEn.put(915,"draw");
        wordEn.put(916,"throw");
        wordEn.put(917,"grow");
        wordEn.put(918,"blow");
        wordEn.put(919,"speak");
        wordEn.put(920,"choose");
        wordEn.put(921,"wake");
        wordEn.put(922,"break");
        wordEn.put(923,"show");
        wordEn.put(924,"cut");
        wordEn.put(925,"put");
        wordEn.put(926,"cost");
        wordEn.put(927,"let");
        wordEn.put(928,"shut");
        wordEn.put(929,"hit");
        wordEn.put(930,"read");
        wordEn.put(931,"send");
        wordEn.put(932,"spend");
        wordEn.put(933,"lend");
        wordEn.put(934,"build");
        wordEn.put(935,"feel");
        wordEn.put(936,"meet");
        wordEn.put(937,"sleep");
        wordEn.put(938,"keep");
        wordEn.put(939,"leave");
        wordEn.put(940,"buy");
        wordEn.put(941,"bring");
        wordEn.put(942,"teach");
        wordEn.put(943,"think");
        wordEn.put(944,"fight");
        wordEn.put(945,"catch");
        wordEn.put(946,"must");
        wordEn.put(947,"should");
        wordEn.put(948,"will");
        wordEn.put(949,"be afraid of");
        wordEn.put(950,"be interested in");
        wordEn.put(951,"be surprised");
        wordEn.put(952,"have to");
        wordEn.put(953,"get up");
        wordEn.put(954,"put on");
        wordEn.put(955,"take off");
        wordEn.put(956,"live");
        wordEn.put(957,"work");
        wordEn.put(958,"watch");
        wordEn.put(959,"wash");
        wordEn.put(960,"shave");
        wordEn.put(961,"try");
        wordEn.put(962,"celebrate");
        wordEn.put(963,"smile");
        wordEn.put(964,"laugh");
        wordEn.put(965,"cry");
        wordEn.put(966,"learn");
        wordEn.put(967,"study");
        wordEn.put(968,"change");
        wordEn.put(969,"listen");
        wordEn.put(970,"close");
        wordEn.put(971,"open");
        wordEn.put(972,"dance");
        wordEn.put(973,"ask");
        wordEn.put(974,"answer");
        wordEn.put(975,"collect");
        wordEn.put(976,"want");
        wordEn.put(977,"like");
        wordEn.put(978,"cook");
        wordEn.put(979,"bake");
        wordEn.put(980,"smell");
        wordEn.put(981,"wait");
        wordEn.put(982,"expect");
        wordEn.put(983,"thank");
        wordEn.put(984,"play");
        wordEn.put(985,"call");
        wordEn.put(986,"walk");
        wordEn.put(987,"smoke");
        wordEn.put(988,"wish");
        wordEn.put(989,"excuse");
        wordEn.put(990,"shout");
        wordEn.put(991,"dream");
        wordEn.put(992,"hope");
        wordEn.put(993,"remember");
        wordEn.put(994,"remind");
        wordEn.put(995,"enjoy");
        wordEn.put(996,"carry");
        wordEn.put(997,"explain");
        wordEn.put(998,"stay");
        wordEn.put(999,"rest");
        wordEn.put(1000,"turn");
        wordEn.put(1001,"lift");
        wordEn.put(1002,"believe");
        wordEn.put(1003,"receive");
        wordEn.put(1004,"help");
        wordEn.put(1005,"order");
        wordEn.put(1006,"visit");
        wordEn.put(1007,"check");
        wordEn.put(1008,"jump");
        wordEn.put(1009,"travel");
        wordEn.put(1010,"talk");
        wordEn.put(1011,"decide");
        wordEn.put(1012,"solve");
        wordEn.put(1013,"drop");
        wordEn.put(1014,"agree");
        wordEn.put(1015,"save");
        wordEn.put(1016,"argue");
        wordEn.put(1017,"count");
        wordEn.put(1018,"surprise");
        wordEn.put(1019,"worry");
        wordEn.put(1020,"joke");
        wordEn.put(1021,"move");
        wordEn.put(1022,"match");
        wordEn.put(1023,"die");
        wordEn.put(1024,"influence");
        wordEn.put(1025,"support  ");
        wordEn.put(1026,"describe");
        wordEn.put(1027,"punish");
        wordEn.put(1028,"intend");
        wordEn.put(1029,"complain");
        wordEn.put(1030,"avoid");
        wordEn.put(1031,"return");
        wordEn.put(1032,"disturb");
        wordEn.put(1033,"provide");
        wordEn.put(1034,"offer");
        wordEn.put(1035,"introduce");
        wordEn.put(1036,"persuade");
        wordEn.put(1037,"approve");
        wordEn.put(1038,"appreciate ");

        return wordEn;
    }

    private Map<Integer, String> getStrWordsRu(){
        wordRu.put(0,"привет");
        wordRu.put(1,"здравствуйте, привет");
        wordRu.put(2,"извини(те)");
        wordRu.put(3,"пожалуйста (прошу); угождать");
        wordRu.put(4,"спасибо");
        wordRu.put(5,"пожалуйста, не за что");
        wordRu.put(6,"как жаль");
        wordRu.put(7,"до свидания");
        wordRu.put(8,"люди");
        wordRu.put(9,"мужчина");
        wordRu.put(10,"женщина");
        wordRu.put(11,"ребенок");
        wordRu.put(12,"мальчик");
        wordRu.put(13,"девочка");
        wordRu.put(14,"парень");
        wordRu.put(15,"друг");
        wordRu.put(16,"знакомый; знакомство");
        wordRu.put(17,"сосед");
        wordRu.put(18,"гость");
        wordRu.put(19,"начальник; шеф; главный; вождь");
        wordRu.put(20,"босс");
        wordRu.put(21,"конкурент, соперник");
        wordRu.put(22,"клиент");
        wordRu.put(23,"коллега");
        wordRu.put(24,"семья");
        wordRu.put(25,"родители");
        wordRu.put(26,"отец");
        wordRu.put(27,"папа");
        wordRu.put(28,"мать");
        wordRu.put(29,"мама");
        wordRu.put(30,"муж");
        wordRu.put(31,"жена");
        wordRu.put(32,"сын");
        wordRu.put(33,"дочь");
        wordRu.put(34,"брат");
        wordRu.put(35,"сестра");
        wordRu.put(36,"дед");
        wordRu.put(37,"тесть, свекор");
        wordRu.put(38,"дядя");
        wordRu.put(39,"тетя");
        wordRu.put(40,"двоюродный брат, двоюродная сестра");
        wordRu.put(41,"племянник");
        wordRu.put(42,"племянница");
        wordRu.put(43,"работа");
        wordRu.put(44,"бизнесмен");
        wordRu.put(45,"учитель");
        wordRu.put(46,"водитель");
        wordRu.put(47,"рабочий");
        wordRu.put(48,"инженер");
        wordRu.put(49,"врач");
        wordRu.put(50,"адвокат, юрист");
        wordRu.put(51,"журналист");
        wordRu.put(52,"медсестра");
        wordRu.put(53,"продавец");
        wordRu.put(54,"официант");
        wordRu.put(55,"бухгалтер");
        wordRu.put(56,"художник");
        wordRu.put(57,"музыкант");
        wordRu.put(58,"актер");
        wordRu.put(59,"студент");
        wordRu.put(60,"школьник, ученик");
        wordRu.put(61,"животное");
        wordRu.put(62,"кошка");
        wordRu.put(63,"собака");
        wordRu.put(64,"птица");
        wordRu.put(65,"белка");
        wordRu.put(66,"волк");
        wordRu.put(67,"гусь");
        wordRu.put(68,"жираф");
        wordRu.put(69,"кролик; заяц");
        wordRu.put(70,"корова");
        wordRu.put(71,"крыса");
        wordRu.put(72,"лиса");
        wordRu.put(73,"лошадь");
        wordRu.put(74,"лягушка");
        wordRu.put(75,"медведь");
        wordRu.put(76,"мышь");
        wordRu.put(77,"обезьяна");
        wordRu.put(78,"свинья");
        wordRu.put(79,"слон");
        wordRu.put(80,"утка");
        wordRu.put(81,"страна; сельская местность");
        wordRu.put(82,"Россия");
        wordRu.put(83,"Великобритания");
        wordRu.put(84,"Англия");
        wordRu.put(85,"город");
        wordRu.put(86,"дом (здание)");
        wordRu.put(87,"дом (место проживания)");
        wordRu.put(88,"здание; строительство");
        wordRu.put(89,"место; помещать");
        wordRu.put(90,"вход");
        wordRu.put(91,"выход");
        wordRu.put(92,"центр");
        wordRu.put(93,"двор");
        wordRu.put(94,"крыша");
        wordRu.put(95,"забор");
        wordRu.put(96,"земля, участок");
        wordRu.put(97,"деревня, поселок");
        wordRu.put(98,"школа");
        wordRu.put(99,"университет");
        wordRu.put(100,"театр");
        wordRu.put(101,"церковь");
        wordRu.put(102,"ресторан");
        wordRu.put(103,"кафе");
        wordRu.put(104,"гостиница");
        wordRu.put(105,"банк");
        wordRu.put(106,"кинотеатр");
        wordRu.put(107,"больница");
        wordRu.put(108,"полиция");
        wordRu.put(109,"почта");
        wordRu.put(110,"станция, вокзал");
        wordRu.put(111,"аэропорт");
        wordRu.put(112,"магазин");
        wordRu.put(113,"аптека");
        wordRu.put(114,"рынок");
        wordRu.put(115,"офис");
        wordRu.put(116,"компания, фирма");
        wordRu.put(117,"предприятие, завод, фабрика");
        wordRu.put(118,"площадь");
        wordRu.put(119,"улица");
        wordRu.put(120,"дорога");
        wordRu.put(121,"перекрёсток");
        wordRu.put(122,"остановка; останавливаться");
        wordRu.put(123,"тротуар");
        wordRu.put(124,"тропа, тропинка");
        wordRu.put(125,"сад");
        wordRu.put(126,"парк");
        wordRu.put(127,"мост");
        wordRu.put(128,"река");
        wordRu.put(129,"лес");
        wordRu.put(130,"поле");
        wordRu.put(131,"гора");
        wordRu.put(132,"озеро");
        wordRu.put(133,"море");
        wordRu.put(134,"океан");
        wordRu.put(135,"морской берег, побережье");
        wordRu.put(136,"пляж");
        wordRu.put(137,"песок");
        wordRu.put(138,"остров");
        wordRu.put(139,"граница");
        wordRu.put(140,"таможня");
        wordRu.put(141,"мусор");
        wordRu.put(142,"отходы; тратить впустую");
        wordRu.put(143,"камень");
        wordRu.put(144,"растение; завод; сажать");
        wordRu.put(145,"дерево");
        wordRu.put(146,"трава");
        wordRu.put(147,"цветок");
        wordRu.put(148,"лист (дерева)");
        wordRu.put(149,"квартира");
        wordRu.put(150,"комната");
        wordRu.put(151,"зал");
        wordRu.put(152,"спальня");
        wordRu.put(153,"ванная");
        wordRu.put(154,"душ");
        wordRu.put(155,"туалет");
        wordRu.put(156,"кухня");
        wordRu.put(157,"коридор");
        wordRu.put(158,"балкон");
        wordRu.put(159,"пол; этаж");
        wordRu.put(160,"потолок");
        wordRu.put(161,"стена");
        wordRu.put(162,"ступеньки; лестница");
        wordRu.put(163,"дверь");
        wordRu.put(164,"окно");
        wordRu.put(165,"подоконник");
        wordRu.put(166,"занавес(ка), штора");
        wordRu.put(167,"выключатель; переключать");
        wordRu.put(168,"розетка");
        wordRu.put(169,"(водопроводный) кран");
        wordRu.put(170,"труба; трубка");
        wordRu.put(171,"дымовая труба");
        wordRu.put(172,"мебель");
        wordRu.put(173,"стол");
        wordRu.put(174,"стул");
        wordRu.put(175,"кресло");
        wordRu.put(176,"диван");
        wordRu.put(177,"кровать");
        wordRu.put(178,"(платяной) шкаф");
        wordRu.put(179,"шкаф(чик)");
        wordRu.put(180,"полка");
        wordRu.put(181,"зеркало");
        wordRu.put(182,"ковер");
        wordRu.put(183,"холодильник");
        wordRu.put(184,"микроволновка");
        wordRu.put(185,"печь, духовка");
        wordRu.put(186,"кухонная плита");
        wordRu.put(187,"еда");
        wordRu.put(188,"хлеб");
        wordRu.put(189,"масло");
        wordRu.put(190,"растительное масло; нефть");
        wordRu.put(191,"сыр");
        wordRu.put(192,"колбаса, сосиска");
        wordRu.put(193,"ветчина");
        wordRu.put(194,"мясо");
        wordRu.put(195,"говядина");
        wordRu.put(196,"свинина");
        wordRu.put(197,"баранина; ягненок");
        wordRu.put(198,"цыпленок; курица");
        wordRu.put(199,"котлета");
        wordRu.put(200,"рыба; рыбачить");
        wordRu.put(201,"яйцо");
        wordRu.put(202,"салат");
        wordRu.put(203,"гриб");
        wordRu.put(204,"кукуруза; зерно");
        wordRu.put(205,"каша");
        wordRu.put(206,"овсянка");
        wordRu.put(207,"суп");
        wordRu.put(208,"бутерброд");
        wordRu.put(209,"рис");
        wordRu.put(210,"лапша");
        wordRu.put(211,"мука");
        wordRu.put(212,"специя, пряность");
        wordRu.put(213,"перец; поперчить");
        wordRu.put(214,"соль; посолить");
        wordRu.put(215,"лук (репчатый)");
        wordRu.put(216,"чеснок");
        wordRu.put(217,"соус");
        wordRu.put(218,"овощи");
        wordRu.put(219,"картофель");
        wordRu.put(220,"морковь");
        wordRu.put(221,"свекла");
        wordRu.put(222,"помидор");
        wordRu.put(223,"огурец");
        wordRu.put(224,"капуста");
        wordRu.put(225,"кабачок");
        wordRu.put(226,"баклажан");
        wordRu.put(227," бобы");
        wordRu.put(228,"горох");
        wordRu.put(229,"орех");
        wordRu.put(230,"фрукт(ы); плод");
        wordRu.put(231,"яблоко");
        wordRu.put(232,"груша");
        wordRu.put(233,"банан");
        wordRu.put(234,"ягода");
        wordRu.put(235,"клубника, земляника");
        wordRu.put(236,"малина");
        wordRu.put(237,"вишня");
        wordRu.put(238,"слива");
        wordRu.put(239,"виноград");
        wordRu.put(240,"абрикос");
        wordRu.put(241,"персик");
        wordRu.put(242,"дыня");
        wordRu.put(243,"арбуз");
        wordRu.put(244,"тыква");
        wordRu.put(245,"апельсин; оранжевый");
        wordRu.put(246,"мандарин");
        wordRu.put(247,"лимон");
        wordRu.put(248,"ананас");
        wordRu.put(249,"сахар");
        wordRu.put(250,"мёд");
        wordRu.put(251,"варенье");
        wordRu.put(252,"торт");
        wordRu.put(253,"булочка");
        wordRu.put(254,"печенье");
        wordRu.put(255,"пирог, пирожок");
        wordRu.put(256,"конфета; сладкий");
        wordRu.put(257,"мороженое");
        wordRu.put(258,"шоколад");
        wordRu.put(259,"вода; поливать");
        wordRu.put(260,"газировка");
        wordRu.put(261,"сок");
        wordRu.put(262,"вино");
        wordRu.put(263,"чай");
        wordRu.put(264,"кофе");
        wordRu.put(265,"молоко");
        wordRu.put(266,"сливки; крем");
        wordRu.put(267,"йогурт");
        wordRu.put(268,"творог");
        wordRu.put(269,"блюдо  ");
        wordRu.put(270," чашка");
        wordRu.put(271,"стакан; стекло");
        wordRu.put(272,"кружка");
        wordRu.put(273,"тарелка");
        wordRu.put(274,"ложка");
        wordRu.put(275,"вилка");
        wordRu.put(276,"нож");
        wordRu.put(277,"блюдце");
        wordRu.put(278,"бутылка");
        wordRu.put(279,"салфетка");
        wordRu.put(280,"кастрюля");
        wordRu.put(281,"сковородка");
        wordRu.put(282,"чайник; котел");
        wordRu.put(283,"принятие пищи, еда");
        wordRu.put(284,"завтрак");
        wordRu.put(285,"обед");
        wordRu.put(286,"ужин");
        wordRu.put(287,"транспорт");
        wordRu.put(288,"самолет");
        wordRu.put(289,"автомобиль");
        wordRu.put(290,"трамвай");
        wordRu.put(291,"автобус");
        wordRu.put(292,"поезд");
        wordRu.put(293,"корабль");
        wordRu.put(294,"велосипед");
        wordRu.put(295,"время; раз");
        wordRu.put(296,"минута");
        wordRu.put(297,"час");
        wordRu.put(298,"неделя");
        wordRu.put(299,"год");
        wordRu.put(300,"век, столетие");
        wordRu.put(301,"позавчера");
        wordRu.put(302,"вчера");
        wordRu.put(303,"сегодня (днем)");
        wordRu.put(304,"сегодня вечером (ночью)");
        wordRu.put(305,"завтра");
        wordRu.put(306,"послезавтра");
        wordRu.put(307,"день");
        wordRu.put(308,"утро");
        wordRu.put(309,"день (после полудня)");
        wordRu.put(310,"вечер");
        wordRu.put(311,"ночь");
        wordRu.put(312,"понедельник");
        wordRu.put(313,"вторник");
        wordRu.put(314,"среда");
        wordRu.put(315,"четверг");
        wordRu.put(316,"пятница");
        wordRu.put(317,"суббота");
        wordRu.put(318,"воскресенье");
        wordRu.put(319,"месяц");
        wordRu.put(320,"январь");
        wordRu.put(321,"февраль");
        wordRu.put(322,"март");
        wordRu.put(323,"апрель");
        wordRu.put(324,"май");
        wordRu.put(325,"июнь");
        wordRu.put(326,"июль");
        wordRu.put(327,"август");
        wordRu.put(328,"сентябрь");
        wordRu.put(329,"октябрь");
        wordRu.put(330,"ноябрь");
        wordRu.put(331,"декабрь");
        wordRu.put(332,"время года; сезон");
        wordRu.put(333,"весна");
        wordRu.put(334,"лето");
        wordRu.put(335,"осень");
        wordRu.put(336,"зима");
        wordRu.put(337,"праздник; отпуск; каникулы");
        wordRu.put(338,"Рождество");
        wordRu.put(339,"Пасха");
        wordRu.put(340,"день рождения");
        wordRu.put(341,"анкета; форма; бланк; класс; формировать, образовывать");
        wordRu.put(342,"имя, фамилия; название; называть");
        wordRu.put(343,"имя");
        wordRu.put(344,"фамилия");
        wordRu.put(345,"девичья фамилия");
        wordRu.put(346,"дата рождения");
        wordRu.put(347,"место рождения");
        wordRu.put(348,"адрес");
        wordRu.put(349,"семейное положение");
        wordRu.put(350,"холостой, незамужняя; один(окий); в один конец (о билете)");
        wordRu.put(351,"женатый/замужняя");
        wordRu.put(352,"разведенный");
        wordRu.put(353,"овдовевший");
        wordRu.put(354,"вещь");
        wordRu.put(355,"ручка");
        wordRu.put(356,"карандаш");
        wordRu.put(357,"книга");
        wordRu.put(358,"тетрадь");
        wordRu.put(359,"блокнот");
        wordRu.put(360,"записка, запись");
        wordRu.put(361,"словарь");
        wordRu.put(362,"письмо; буква");
        wordRu.put(363,"конверт");
        wordRu.put(364,"бумага");
        wordRu.put(365,"газета");
        wordRu.put(366,"журнал");
        wordRu.put(367,"телефон; разговаривать по телефону");
        wordRu.put(368,"часы");
        wordRu.put(369,"расчёска; расчесывать");
        wordRu.put(370,"телевизор");
        wordRu.put(371,"утюг; железо; гладить (утюгом)");
        wordRu.put(372,"мыло; намыливать");
        wordRu.put(373,"радио");
        wordRu.put(374,"сумка");
        wordRu.put(375,"рюкзак");
        wordRu.put(376,"карта (географическая)");
        wordRu.put(377,"открытка; карта (игральная); карточка");
        wordRu.put(378,"чемодан");
        wordRu.put(379,"подарок");
        wordRu.put(380,"фотоаппарат; видеокамера");
        wordRu.put(381,"ваза");
        wordRu.put(382,"носовой платок");
        wordRu.put(383,"мяч");
        wordRu.put(384,"воздушный шар(ик)");
        wordRu.put(385,"игрушка");
        wordRu.put(386,"билет");
        wordRu.put(387,"багаж");
        wordRu.put(388,"батарейка, аккумулятор");
        wordRu.put(389,"ведро");
        wordRu.put(390,"веревка");
        wordRu.put(391,"доска; борт; совет (правление)");
        wordRu.put(392,"календарь");
        wordRu.put(393,"ноутбук");
        wordRu.put(394,"щетка; кисть, кисточка; чистить щеткой");
        wordRu.put(395,"клавиатура");
        wordRu.put(396,"ключ; клавиша");
        wordRu.put(397,"колесо");
        wordRu.put(398,"руль");
        wordRu.put(399,"багажник; ствол; хобот");
        wordRu.put(400,"бензин");
        wordRu.put(401,"дамская сумка; кошелек");
        wordRu.put(402,"бумажник");
        wordRu.put(403,"лампа");
        wordRu.put(404,"линейка; правитель");
        wordRu.put(405,"лопата; рыть");
        wordRu.put(406,"машина; механизм; аппарат; станок");
        wordRu.put(407,"молоток; вбивать молотком");
        wordRu.put(408,"ножницы");
        wordRu.put(409,"очки");
        wordRu.put(410,"посылка; упаковка");
        wordRu.put(411,"палка; придерживаться; втыкать");
        wordRu.put(412,"клей; приклеивать");
        wordRu.put(413,"подарок; дар");
        wordRu.put(414,"полотенце");
        wordRu.put(415,"почта (корреспонденция); отправлять по почте");
        wordRu.put(416,"проволока; провод");
        wordRu.put(417,"страница");
        wordRu.put(418,"карманный фонарь; горелка; факел");
        wordRu.put(419,"коробка, ящик; боксировать");
        wordRu.put(420,"одеяло");
        wordRu.put(421,"простыня; лист(ок)");
        wordRu.put(422,"подушка");
        wordRu.put(423,"одежда");
        wordRu.put(424,"обувь");
        wordRu.put(425,"ботинок; сапог");
        wordRu.put(426,"кроссовки");
        wordRu.put(427,"пальто");
        wordRu.put(428,"платье; одевать(ся)");
        wordRu.put(429,"костюм; иск; подходить, быть к лицу, соответствовать");
        wordRu.put(430,"рубашка");
        wordRu.put(431,"блузка");
        wordRu.put(432,"юбка");
        wordRu.put(433,"перчатка");
        wordRu.put(434,"варежка");
        wordRu.put(435,"шляпа");
        wordRu.put(436,"шапка; кепка; колпачок");
        wordRu.put(437,"пиджак; куртка");
        wordRu.put(438,"кофта");
        wordRu.put(439,"шарф");
        wordRu.put(440,"носок");
        wordRu.put(441,"свитер");
        wordRu.put(442,"футболка");
        wordRu.put(443,"галстук; привязывать");
        wordRu.put(444,"брюки, штаны");
        wordRu.put(445,"шорты");
        wordRu.put(446,"колготки");
        wordRu.put(447,"чулки");
        wordRu.put(448,"джинсы");
        wordRu.put(449,"капюшон; капот");
        wordRu.put(450,"ремень, пояс");
        wordRu.put(451,"нижнее белье");
        wordRu.put(452,"трусы мужские");
        wordRu.put(453,"трусы женские");
        wordRu.put(454,"бюстгальтер");
        wordRu.put(455,"тело; кузов");
        wordRu.put(456,"голова; глава, руководитель");
        wordRu.put(457,"лицо");
        wordRu.put(458,"лоб");
        wordRu.put(459,"нос");
        wordRu.put(460,"ухо; ушко; колос");
        wordRu.put(461,"рот");
        wordRu.put(462,"горло");
        wordRu.put(463,"глаз");
        wordRu.put(464,"бровь");
        wordRu.put(465,"губы");
        wordRu.put(466,"зуб");
        wordRu.put(467,"волос(ы)");
        wordRu.put(468,"усы");
        wordRu.put(469,"щека; наглость, нахальство");
        wordRu.put(470,"подбородок");
        wordRu.put(471,"шея");
        wordRu.put(472,"плечо");
        wordRu.put(473,"грудь");
        wordRu.put(474,"сердце");
        wordRu.put(475,"желудок; живот");
        wordRu.put(476,"спина; назад");
        wordRu.put(477,"запястье");
        wordRu.put(478,"рука, кисть (руки)");
        wordRu.put(479,"палец (руки)");
        wordRu.put(480,"ноготь; гвоздь; прибивать");
        wordRu.put(481,"локоть");
        wordRu.put(482,"нога; ножка");
        wordRu.put(483,"колено");
        wordRu.put(484,"нога, ступня; подножие;");
        wordRu.put(485,"пятка; каблук");
        wordRu.put(486,"палец (ноги)");
        wordRu.put(487,"борода");
        wordRu.put(488,"кость");
        wordRu.put(489,"здоровье");
        wordRu.put(490,"здоровый");
        wordRu.put(491,"больной");
        wordRu.put(492,"болезнь");
        wordRu.put(493,"жар, (высокая) температура");
        wordRu.put(494,"кашель; кашлять");
        wordRu.put(495,"насморк");
        wordRu.put(496,"чихать");
        wordRu.put(497,"боль");
        wordRu.put(498,"головная боль");
        wordRu.put(499,"грипп");
        wordRu.put(500,"синяк, ушиб; ушибить");
        wordRu.put(501,"событие");
        wordRu.put(502,"рождение");
        wordRu.put(503,"игра");
        wordRu.put(504,"урок");
        wordRu.put(505,"отпуск, каникулы");
        wordRu.put(506,"вечеринка");
        wordRu.put(507,"встреча; собрание");
        wordRu.put(508,"свадьба");
        wordRu.put(509,"переговоры");
        wordRu.put(510,"поездка, путешествие");
        wordRu.put(511,"смерть");
        wordRu.put(512,"погода");
        wordRu.put(513,"солнце");
        wordRu.put(514,"луна");
        wordRu.put(515,"ветер");
        wordRu.put(516,"туман");
        wordRu.put(517,"дождь");
        wordRu.put(518,"снег");
        wordRu.put(519,"небо");
        wordRu.put(520,"облако");
        wordRu.put(521,"воздух");
        wordRu.put(522,"температура");
        wordRu.put(523,"градус; степень");
        wordRu.put(524,"искусство");
        wordRu.put(525,"музыка");
        wordRu.put(526,"песня");
        wordRu.put(527,"литература");
        wordRu.put(528,"рассказ, история");
        wordRu.put(529,"кино(фильм)");
        wordRu.put(530,"фильм; пленка");
        wordRu.put(531,"скульптура; статуя");
        wordRu.put(532,"картина; фотография");
        wordRu.put(533,"фото");
        wordRu.put(534,"реклама");
        wordRu.put(535,"покупка, приобретение; покупать, приобретать");
        wordRu.put(536,"размер");
        wordRu.put(537,"цена");
        wordRu.put(538,"деньги");
        wordRu.put(539,"наличные (деньги)");
        wordRu.put(540,"скидка");
        wordRu.put(541,"счет (банковский)");
        wordRu.put(542,"счёт");
        wordRu.put(543,"чаевые; кончик, верхушка; совет");
        wordRu.put(544,"измерение; мера; измерять");
        wordRu.put(545,"расстояние; дистанция");
        wordRu.put(546,"длина");
        wordRu.put(547,"высота");
        wordRu.put(548,"глубина");
        wordRu.put(549,"сила; прочность");
        wordRu.put(550,"скорость");
        wordRu.put(551,"километр");
        wordRu.put(552,"килограмм");
        wordRu.put(553,"фунт");
        wordRu.put(554,"чувство");
        wordRu.put(555,"веселье");
        wordRu.put(556,"радость");
        wordRu.put(557,"страх; бояться");
        wordRu.put(558,"печаль");
        wordRu.put(559,"страсть, страстность");
        wordRu.put(560,"удовольствие");
        wordRu.put(561,"счастье");
        wordRu.put(562,"мир (покой)");
        wordRu.put(563,"любовь; любить");
        wordRu.put(564,"ненависть; ненавидеть");
        wordRu.put(565,"мир (планета)");
        wordRu.put(566,"душа");
        wordRu.put(567,"жизнь");
        wordRu.put(568,"знание");
        wordRu.put(569,"задача, задание");
        wordRu.put(570,"упражнение; упражняться; осуществлять");
        wordRu.put(571,"удача");
        wordRu.put(572,"проблема");
        wordRu.put(573,"(благоприятная) возможность");
        wordRu.put(574,"способность");
        wordRu.put(575,"красота; красавица");
        wordRu.put(576,"опасность");
        wordRu.put(577,"опыт, переживание");
        wordRu.put(578,"память; воспоминание");
        wordRu.put(579,"польза, выгода; приносить (извлекать) пользу");
        wordRu.put(580,"преимущество");
        wordRu.put(581,"прибыль, доход; польза, выгода; извлекать пользу, выгоду");
        wordRu.put(582,"привычка");
        wordRu.put(583,"причина; размышлять");
        wordRu.put(584,"(по)следствие");
        wordRu.put(585,"значение, смысл");
        wordRu.put(586,"средство, способ");
        wordRu.put(587,"усилие");
        wordRu.put(588,"успех; успешный человек");
        wordRu.put(589,"цель; гол");
        wordRu.put(590,"чудо");
        wordRu.put(591,"наука");
        wordRu.put(592,"язык");
        wordRu.put(593,"слово");
        wordRu.put(594,"огонь; пожар; стрелять");
        wordRu.put(595,"случай; дело; чехол");
        wordRu.put(596,"обстоятельство");
        wordRu.put(597,"мысль");
        wordRu.put(598,"выбор");
        wordRu.put(599,"разрешение; разрешать");
        wordRu.put(600,"доставка; поставка");
        wordRu.put(601,"достижение");
        wordRu.put(602,"обязанность; дежурный");
        wordRu.put(603,"задержка, промедление, отсрочка; откладывать, задерживать, промедлять");
        wordRu.put(604,"отношение");
        wordRu.put(605,"оценка, отметка, знак; отметить");
        wordRu.put(606,"ошибка");
        wordRu.put(607,"поведение");
        wordRu.put(608,"приглашение");
        wordRu.put(609,"развитие");
        wordRu.put(610,"решение, принятие решения");
        wordRu.put(611,"решение; раствор");
        wordRu.put(612,"совет");
        wordRu.put(613,"соглашение; согласие; договор");
        wordRu.put(614,"список; перечислять");
        wordRu.put(615,"спор; аргумент");
        wordRu.put(616,"тест, испытание; тестировать, испытывать");
        wordRu.put(617,"шаг; ступать");
        wordRu.put(618,"кусок; часть; пьеса");
        wordRu.put(619,"область, сфера, район; площадь (фигуры)");
        wordRu.put(620,"пара");
        wordRu.put(621,"пара; чета");
        wordRu.put(622,"поверхность; всплывать");
        wordRu.put(623,"беспорядок; привести в беспорядок");
        wordRu.put(624,"вопрос");
        wordRu.put(625,"что; какой");
        wordRu.put(626,"кто");
        wordRu.put(627,"где; куда");
        wordRu.put(628,"как");
        wordRu.put(629,"почему, зачем");
        wordRu.put(630,"когда");
        wordRu.put(631,"сколько (+ слово во множественном числе)");
        wordRu.put(632,"сколько (+ слово в единственном числе)");
        wordRu.put(633,"я");
        wordRu.put(634,"ты; вы; Вы");
        wordRu.put(635,"он");
        wordRu.put(636,"она;");
        wordRu.put(637,"оно");
        wordRu.put(638,"мы");
        wordRu.put(639,"они");
        wordRu.put(640,"мой");
        wordRu.put(641,"твой; ваш");
        wordRu.put(642,"его (одуш.)");
        wordRu.put(643,"её");
        wordRu.put(644,"его (неодуш.)");
        wordRu.put(645,"наш");
        wordRu.put(646,"их");
        wordRu.put(647,"из");
        wordRu.put(648,"передает род. падеж");
        wordRu.put(649,"к; в (куда)");
        wordRu.put(650,"в (где)");
        wordRu.put(651,"на");
        wordRu.put(652,"под");
        wordRu.put(653,"позади");
        wordRu.put(654,"с");
        wordRu.put(655,"без");
        wordRu.put(656,"перед");
        wordRu.put(657,"до");
        wordRu.put(658,"после");
        wordRu.put(659,"между");
        wordRu.put(660,"возле, около; близко");
        wordRu.put(661,"для; в течение; на (такое-то время)");
        wordRu.put(662,"с (такого-то времени и поныне)");
        wordRu.put(663,"во время");
        wordRu.put(664,"вокруг");
        wordRu.put(665,"из-за");
        wordRu.put(666,"о; около, приблизительно");
        wordRu.put(667,"против");
        wordRu.put(668,"среди");
        wordRu.put(669,"через");
        wordRu.put(670,"(километров) в (час)");
        wordRu.put(671,"над, выше");
        wordRu.put(672,"под, ниже");
        wordRu.put(673,"число; количество; номер");
        wordRu.put(674,"ноль");
        wordRu.put(675,"один; (заменяет предыдущее названное существительное, во мн.ч. - ones)");
        wordRu.put(676,"два");
        wordRu.put(677,"три");
        wordRu.put(678,"четыре");
        wordRu.put(679,"пять");
        wordRu.put(680,"шесть");
        wordRu.put(681,"семь");
        wordRu.put(682,"восемь");
        wordRu.put(683,"девять");
        wordRu.put(684,"десять");
        wordRu.put(685,"одиннадцать");
        wordRu.put(686,"двенадцать");
        wordRu.put(687,"тринадцать");
        wordRu.put(688,"четырнадцать");
        wordRu.put(689,"пятнадцать");
        wordRu.put(690,"шестнадцать");
        wordRu.put(691,"семнадцать");
        wordRu.put(692,"восемнадцать");
        wordRu.put(693,"девятнадцать");
        wordRu.put(694,"двадцать");
        wordRu.put(695,"тридцать");
        wordRu.put(696,"сорок");
        wordRu.put(697,"пятьдесят");
        wordRu.put(698,"шестьдесят");
        wordRu.put(699,"семьдесят");
        wordRu.put(700,"восемьдесят");
        wordRu.put(701,"девяносто");
        wordRu.put(702,"сто");
        wordRu.put(703,"тысяча");
        wordRu.put(704,"первый; сначала");
        wordRu.put(705,"второй; секунда");
        wordRu.put(706,"третий");
        wordRu.put(707,"четвертый");
        wordRu.put(708,"пятый");
        wordRu.put(709,"цвет");
        wordRu.put(710,"чёрный");
        wordRu.put(711,"голубой; синий");
        wordRu.put(712,"коричневый");
        wordRu.put(713,"зелёный");
        wordRu.put(714,"серый");
        wordRu.put(715,"красный");
        wordRu.put(716,"белый");
        wordRu.put(717,"жёлтый");
        wordRu.put(718,"розовый");
        wordRu.put(719,"фиолетовый; пурпурный");
        wordRu.put(720,"старый");
        wordRu.put(721,"молодой");
        wordRu.put(722,"новый");
        wordRu.put(723,"большой");
        wordRu.put(724,"большой, просторный");
        wordRu.put(725,"огромный");
        wordRu.put(726,"маленький");
        wordRu.put(727,"толстый, жирный; жир");
        wordRu.put(728,"тонкий, стройный");
        wordRu.put(729,"толстый; густой");
        wordRu.put(730,"тонкий");
        wordRu.put(731,"голодный");
        wordRu.put(732,"сытый; полный");
        wordRu.put(733,"хороший; добрый");
        wordRu.put(734,"отличный, превосходный, великолепный");
        wordRu.put(735,"удивительный");
        wordRu.put(736,"прекрасный; прекрасно; утонченный; штраф; штрафовать");
        wordRu.put(737,"плохой");
        wordRu.put(738,"ужасный");
        wordRu.put(739,"противный");
        wordRu.put(740,"ранний; рано");
        wordRu.put(741,"поздний; поздно");
        wordRu.put(742,"последний, прошлый");
        wordRu.put(743,"следующий");
        wordRu.put(744,"свободный; бесплатный");
        wordRu.put(745,"занятый");
        wordRu.put(746,"жаркий; горячий; острый (по вкусу); жарко; горячо");
        wordRu.put(747,"тёплый; тепло");
        wordRu.put(748,"холодный; холодно; холод; простуда");
        wordRu.put(749,"прохладный; прохладно; круто; охлаждать(ся)");
        wordRu.put(750,"острый (по вкусу)");
        wordRu.put(751,"острый (не тупой)");
        wordRu.put(752,"тупой (нож, человек)");
        wordRu.put(753,"глупый");
        wordRu.put(754,"умный");
        wordRu.put(755,"умный; нарядный");
        wordRu.put(756,"красивый, хороший, приятный");
        wordRu.put(757,"красивая (о женщине)");
        wordRu.put(758,"красивый (о мужчине)");
        wordRu.put(759,"привлекательный");
        wordRu.put(760,"симпатичный; довольно");
        wordRu.put(761,"уродливый, безобразный");
        wordRu.put(762,"высокий");
        wordRu.put(763,"высокий (о росте)");
        wordRu.put(764,"короткий; низкий (о росте)");
        wordRu.put(765,"низкий; низко");
        wordRu.put(766,"длинный; долгий");
        wordRu.put(767,"тяжёлый");
        wordRu.put(768,"лёгкий; светлый; свет");
        wordRu.put(769,"трудный, тяжелый");
        wordRu.put(770,"легкий, нетрудный");
        wordRu.put(771,"простой");
        wordRu.put(772,"тёмный");
        wordRu.put(773,"дорогой (по цене)");
        wordRu.put(774,"дорогой, милый");
        wordRu.put(775,"дешёвый");
        wordRu.put(776,"бедный; плохой");
        wordRu.put(777,"богатый");
        wordRu.put(778,"прямой; прямо");
        wordRu.put(779,"левый; cлева; налево");
        wordRu.put(780,"правый; правильный; справа; направо; право; прямо (напр., прямо сейчас)");
        wordRu.put(781,"неправильный");
        wordRu.put(782,"быстрый, быстро");
        wordRu.put(783,"быстрый, скорый");
        wordRu.put(784,"медленный");
        wordRu.put(785,"мягкий; нежный");
        wordRu.put(786,"твёрдый; жесткий; трудный; усердно, упорно");
        wordRu.put(787,"печальный");
        wordRu.put(788,"радостный");
        wordRu.put(789,"счастливый");
        wordRu.put(790,"веселый");
        wordRu.put(791,"добрый; вид, тип");
        wordRu.put(792,"сердитый");
        wordRu.put(793,"злой; зло");
        wordRu.put(794,"вежливый");
        wordRu.put(795,"грубый");
        wordRu.put(796,"нежный");
        wordRu.put(797,"смелый");
        wordRu.put(798,"трусливый; трус");
        wordRu.put(799,"застенчивый");
        wordRu.put(800,"трудолюбивый, прилежный");
        wordRu.put(801,"ленивый");
        wordRu.put(802,"полезный");
        wordRu.put(803,"бесполезный");
        wordRu.put(804,"сильный; крепкий");
        wordRu.put(805,"слабый");
        wordRu.put(806,"громкий");
        wordRu.put(807,"шумный");
        wordRu.put(808,"тихий");
        wordRu.put(809,"спокойный; спокойствие; успокаивать");
        wordRu.put(810,"узкий");
        wordRu.put(811,"широкий");
        wordRu.put(812,"чистый; чистить, прибираться");
        wordRu.put(813,"грязный");
        wordRu.put(814,"усталый");
        wordRu.put(815,"честный");
        wordRu.put(816,"удобный, комфортабельный, уютный");
        wordRu.put(817,"странный; чужой; незнакомый");
        wordRu.put(818,"странный");
        wordRu.put(819,"собственный; владеть");
        wordRu.put(820,"вкусный");
        wordRu.put(821,"очень вкусный");
        wordRu.put(822,"горький");
        wordRu.put(823,"кислый");
        wordRu.put(824,"соленый");
        wordRu.put(825,"готовый");
        wordRu.put(826,"внимательный; осторожный");
        wordRu.put(827,"основной, главный");
        wordRu.put(828,"способный");
        wordRu.put(829,"необходимый");
        wordRu.put(830,"важный");
        wordRu.put(831,"уверенный");
        wordRu.put(832,"в хорошей форме; подходить, соответствовать");
        wordRu.put(833,"лучше; более хороший");
        wordRu.put(834,"лучший");
        wordRu.put(835,"хуже; более плохой");
        wordRu.put(836,"худший");
        wordRu.put(837,"больше (по количеству); более; еще (больше)");
        wordRu.put(838,"наибольший; больше всего; большинство");
        wordRu.put(839,"меньше (по количеству); менее");
        wordRu.put(840,"наименьший; наименее; меньше всего");
        wordRu.put(841,"иногда");
        wordRu.put(842,"никогда");
        wordRu.put(843,"редко");
        wordRu.put(844,"обычно");
        wordRu.put(845,"часто");
        wordRu.put(846,"всегда");
        wordRu.put(847,"скоро");
        wordRu.put(848,"недавно");
        wordRu.put(849,"хорошо; колодец");
        wordRu.put(850,"далеко");
        wordRu.put(851,"точно");
        wordRu.put(852,"вероятно");
        wordRu.put(853,"может быть");
        wordRu.put(854,"возможно, может быть");
        wordRu.put(855,"действительно, правда?");
        wordRu.put(856,"конечно!");
        wordRu.put(857,"конечно, безусловно");
        wordRu.put(858,"очевидно");
        wordRu.put(859,"особенно");
        wordRu.put(860,"да");
        wordRu.put(861,"нет");
        wordRu.put(862,"не");
        wordRu.put(863,"этот");
        wordRu.put(864,"тот; что (союз); который");
        wordRu.put(865,"эти");
        wordRu.put(866,"те");
        wordRu.put(867,"и");
        wordRu.put(868,"или");
        wordRu.put(869,"но");
        wordRu.put(870,"однако");
        wordRu.put(871,"потому что, так как");
        wordRu.put(872,"если; ли");
        wordRu.put(873,"хотя");
        wordRu.put(874," быть, являться");
        wordRu.put(875,"делать (действовать)");
        wordRu.put(876,"иметь");
        wordRu.put(877,"мочь (быть в состоянии)");
        wordRu.put(878,"мочь (иметь разрешение)");
        wordRu.put(879,"идти; ехать; уходить; уезжать");
        wordRu.put(880,"находить");
        wordRu.put(881,"держать");
        wordRu.put(882,"стоять; стенд  ");
        wordRu.put(883,"сидеть  ");
        wordRu.put(884,"слышать  ");
        wordRu.put(885,"побеждать  ");
        wordRu.put(886,"получать; добираться; становиться");
        wordRu.put(887,"делать (изготовлять)  ");
        wordRu.put(888,"приходить, приезжать  ");
        wordRu.put(889,"становиться  ");
        wordRu.put(890,"бежать  ");
        wordRu.put(891,"видеть  ");
        wordRu.put(892,"писать");
        wordRu.put(893,"падать");
        wordRu.put(894,"носить (одежду);");
        wordRu.put(895,"брать  ");
        wordRu.put(896,"давать; дарить");
        wordRu.put(897,"прощать  ");
        wordRu.put(898,"забывать  ");
        wordRu.put(899,"кушать");
        wordRu.put(900,"лежать; лгать; ложь");
        wordRu.put(901,"вести  ");
        wordRu.put(902,"кормить");
        wordRu.put(903,"сказать  ");
        wordRu.put(904,"платить");
        wordRu.put(905,"класть; накрывать (на стол)");
        wordRu.put(906,"пить  ");
        wordRu.put(907,"плавать");
        wordRu.put(908,"петь  ");
        wordRu.put(909,"начинать  ");
        wordRu.put(910,"звонить (в звонок), звенеть; кольцо");
        wordRu.put(911,"тонуть; опускаться; погружаться; раковина  ");
        wordRu.put(912,"вонять; вонь  ");
        wordRu.put(913,"летать; муха  ");
        wordRu.put(914,"знать  ");
        wordRu.put(915,"рисовать, чертить; тащить, тянуть  ");
        wordRu.put(916,"кидать, бросать");
        wordRu.put(917,"расти, выращивать  ");
        wordRu.put(918,"дуть; взрывать; удар");
        wordRu.put(919,"разговаривать");
        wordRu.put(920,"выбирать  ");
        wordRu.put(921,"будить  ");
        wordRu.put(922,"ломать  ");
        wordRu.put(923,"показывать  ");
        wordRu.put(924,"резать  ");
        wordRu.put(925,"помещать, ставить, класть");
        wordRu.put(926,"стоить  ");
        wordRu.put(927,"позволять");
        wordRu.put(928,"закрывать");
        wordRu.put(929,"ударять  ");
        wordRu.put(930,"читать  ");
        wordRu.put(931,"посылать  ");
        wordRu.put(932,"проводить (время); тратить");
        wordRu.put(933,"одолжить");
        wordRu.put(934,"строить  ");
        wordRu.put(935,"чувствовать  ");
        wordRu.put(936,"встречать  ");
        wordRu.put(937,"спать  ");
        wordRu.put(938,"хранить, держать");
        wordRu.put(939,"покидать; оставлять; уходить; уезжать");
        wordRu.put(940,"покупать  ");
        wordRu.put(941,"приносить, привозить  ");
        wordRu.put(942,"учить, обучать");
        wordRu.put(943,"думать  ");
        wordRu.put(944,"бороться, драться; борьба, драка  ");
        wordRu.put(945,"ловить; подхватить (болезнь)");
        wordRu.put(946,"быть должным");
        wordRu.put(947,"быть должным (следует)");
        wordRu.put(948,"для образования буд. времени");
        wordRu.put(949,"бояться");
        wordRu.put(950,"интересоваться");
        wordRu.put(951,"удивляться");
        wordRu.put(952,"быть должным, вынужденным");
        wordRu.put(953,"вставать");
        wordRu.put(954,"надевать");
        wordRu.put(955,"снимать (одежду)");
        wordRu.put(956,"жить");
        wordRu.put(957,"работать; работа");
        wordRu.put(958,"смотреть; наблюдать; наручные часы");
        wordRu.put(959,"мыть, cтирать");
        wordRu.put(960,"брить");
        wordRu.put(961,"пытаться, пробовать; попытка");
        wordRu.put(962,"праздновать");
        wordRu.put(963,"улыбаться; улыбка");
        wordRu.put(964,"смеяться");
        wordRu.put(965,"плакать, кричать; плач, крик");
        wordRu.put(966,"учить(ся)");
        wordRu.put(967,"учиться (в вузе); изучать; изучение");
        wordRu.put(968,"(из)менять; переодеваться; изменение; сдача, мелочь");
        wordRu.put(969,"слушать");
        wordRu.put(970,"закрывать");
        wordRu.put(971,"открывать; открытый");
        wordRu.put(972,"танцевать");
        wordRu.put(973,"спрашивать; просить");
        wordRu.put(974,"отвечать; ответ");
        wordRu.put(975,"собирать");
        wordRu.put(976,"хотеть");
        wordRu.put(977,"нравиться, любить; подобно, как");
        wordRu.put(978,"варить; готовить");
        wordRu.put(979,"печь");
        wordRu.put(980,"пахнуть; нюхать; запах; нюх");
        wordRu.put(981,"ждать");
        wordRu.put(982,"ожидать");
        wordRu.put(983,"благодарить");
        wordRu.put(984,"играть; спектакль, пьеса");
        wordRu.put(985,"звать; звонить");
        wordRu.put(986,"гулять; идти пешком; прогулка");
        wordRu.put(987,"курить; дым");
        wordRu.put(988,"желать; желание");
        wordRu.put(989,"извинять; извинение; отговорка");
        wordRu.put(990,"кричать; крик");
        wordRu.put(991,"мечтать; видеть сон; мечта; сон");
        wordRu.put(992,"надеяться; надежда");
        wordRu.put(993,"(за)помнить; вспомнить");
        wordRu.put(994,"напоминать");
        wordRu.put(995,"наслаждаться, нравиться");
        wordRu.put(996,"нести");
        wordRu.put(997,"объяснять");
        wordRu.put(998,"оставаться; останавливаться (в гостинице)");
        wordRu.put(999,"отдыхать; отдых; остальные/ое");
        wordRu.put(1000,"повернуть; поворот; очередь, черед");
        wordRu.put(1001,"поднимать(ся); лифт");
        wordRu.put(1002,"верить, полагать");
        wordRu.put(1003,"получать");
        wordRu.put(1004,"помогать; помощь");
        wordRu.put(1005,"заказывать; приказывать; заказ; приказ; порядок");
        wordRu.put(1006,"посещать; посещение, визит");
        wordRu.put(1007,"проверять; проверка; чек");
        wordRu.put(1008,"прыгать; прыжок");
        wordRu.put(1009,"путешествовать; путешествие");
        wordRu.put(1010,"разговаривать; разговор");
        wordRu.put(1011,"решать, принимать решение");
        wordRu.put(1012,"решать (проблему); растворять");
        wordRu.put(1013,"ронять; падение, снижение");
        wordRu.put(1014,"соглашаться");
        wordRu.put(1015,"спасать; сохранять; экономить");
        wordRu.put(1016,"спорить");
        wordRu.put(1017,"считать, подсчитывать");
        wordRu.put(1018,"удивлять; удивление; сюрприз");
        wordRu.put(1019,"беспокоить(ся); беспокойство");
        wordRu.put(1020,"шутить; шутка");
        wordRu.put(1021,"двигать(ся); переезжать; движение");
        wordRu.put(1022,"соответствовать, подходить; матч; спичка");
        wordRu.put(1023,"умирать");
        wordRu.put(1024,"влиять; влияние; воздействие");
        wordRu.put(1025,"поддерживать; поддержка");
        wordRu.put(1026,"описывать");
        wordRu.put(1027,"наказывать");
        wordRu.put(1028,"намереваться");
        wordRu.put(1029,"жаловаться");
        wordRu.put(1030,"избегать");
        wordRu.put(1031,"возвращать(ся); возврат, возвращение");
        wordRu.put(1032,"беспокоить, мешать");
        wordRu.put(1033,"обеспечивать");
        wordRu.put(1034,"предлагать; предложение");
        wordRu.put(1035,"представлять, знакомить");
        wordRu.put(1036,"убеждать");
        wordRu.put(1037,"одобрять");
        wordRu.put(1038,"ценить; быть признательным");

        return wordRu;
    }
}