package texts;

import java.util.HashMap;
import java.util.Map;

public class WordsText implements ITexts
{
    private Map<Integer, String> wordEn = new HashMap<>();
    private Map<Integer, String> wordRu = new HashMap<>();

    @Override
    public Map<Integer, String> getEnglish(){
        getStrWordsEn();
        return wordEn;
    }

    @Override
    public Map<Integer, String> getRussia(){
        getStrWordsRu();
        return wordRu;
    }

    private Map<Integer, String> getStrWordsEn(){
        wordEn.put(0,"hello");
        wordEn.put(1,"sorry");
        wordEn.put(2,"please");
        wordEn.put(3,"thank you");
        wordEn.put(4,"what a pity");
        wordEn.put(5,"(good)bye");
        wordEn.put(6,"people");
        wordEn.put(7,"man");
        wordEn.put(8,"woman");
        wordEn.put(9,"child");
        wordEn.put(10,"boy");
        wordEn.put(11,"girl");
        wordEn.put(12,"guy");
        wordEn.put(13,"friend");
        wordEn.put(14,"acquaintance");
        wordEn.put(15,"neighbor");
        wordEn.put(16,"guest");
        wordEn.put(17,"chief");
        wordEn.put(18,"competitor");
        wordEn.put(19,"client");
        wordEn.put(20,"colleague");
        wordEn.put(21,"family");
        wordEn.put(22,"parents");
        wordEn.put(23,"father");
        wordEn.put(24,"dad(dy)");
        wordEn.put(25,"mother");
        wordEn.put(26,"mum(my)");
        wordEn.put(27,"husband");
        wordEn.put(28,"wife");
        wordEn.put(29,"son");
        wordEn.put(30,"daughter");
        wordEn.put(31,"brother");
        wordEn.put(32,"sister");
        wordEn.put(33,"grandfather");
        wordEn.put(34,"father-in-law");
        wordEn.put(35,"uncle");
        wordEn.put(36,"aunt");
        wordEn.put(37,"cousin");
        wordEn.put(38,"nephew");
        wordEn.put(39,"niece");
        wordEn.put(40,"job");
        wordEn.put(41,"businessman");
        wordEn.put(42,"teacher");
        wordEn.put(43,"driver");
        wordEn.put(44,"worker");
        wordEn.put(45,"engineer");
        wordEn.put(46,"doctor");
        wordEn.put(47,"lawyer");
        wordEn.put(48,"journalist");
        wordEn.put(49,"nurse");
        wordEn.put(50,"shop assistant");
        wordEn.put(51,"waiter");
        wordEn.put(52,"accountant");
        wordEn.put(53,"artist");
        wordEn.put(54,"musician");
        wordEn.put(55,"actor");
        wordEn.put(56,"student");
        wordEn.put(57,"pupil");
        wordEn.put(58,"animal");
        wordEn.put(59,"cat");
        wordEn.put(60,"dog");
        wordEn.put(61,"bird");
        wordEn.put(62,"squirrel");
        wordEn.put(63,"wolf");
        wordEn.put(64,"goose");
        wordEn.put(65,"giraffe");
        wordEn.put(66,"rabbit");
        wordEn.put(67,"cow");
        wordEn.put(68,"rat");
        wordEn.put(69,"fox");
        wordEn.put(70,"horse");
        wordEn.put(71,"frog");
        wordEn.put(72,"bear");
        wordEn.put(73,"mouse");
        wordEn.put(74,"monkey");
        wordEn.put(75,"pig");
        wordEn.put(76,"elephant");
        wordEn.put(77,"duck");
        wordEn.put(78,"country");
        wordEn.put(79,"city");
        wordEn.put(80,"house");
        wordEn.put(81,"home");
        wordEn.put(82,"building");
        wordEn.put(83,"place");
        wordEn.put(84,"entrance");
        wordEn.put(85,"exit");
        wordEn.put(86,"center");
        wordEn.put(87,"yard");
        wordEn.put(88,"roof");
        wordEn.put(89,"fence");
        wordEn.put(90,"land");
        wordEn.put(91,"village");
        wordEn.put(92,"school");
        wordEn.put(93,"university");
        wordEn.put(94,"theater");
        wordEn.put(95,"church");
        wordEn.put(96,"restaurant");
        wordEn.put(97,"cafe");
        wordEn.put(98,"hotel");
        wordEn.put(99,"bank");
        wordEn.put(100,"cinema");
        wordEn.put(101,"hospital");
        wordEn.put(102,"police");
        wordEn.put(103,"post office");
        wordEn.put(104,"station");
        wordEn.put(105,"airport");
        wordEn.put(106,"shop");
        wordEn.put(107,"pharmacy");
        wordEn.put(108,"market");
        wordEn.put(109,"office");
        wordEn.put(110,"company");
        wordEn.put(111,"factory");
        wordEn.put(112,"square");
        wordEn.put(113,"street");
        wordEn.put(114,"road");
        wordEn.put(115,"crossroads");
        wordEn.put(116,"stop");
        wordEn.put(117,"sidewalk");
        wordEn.put(118,"path");
        wordEn.put(119,"garden");
        wordEn.put(120,"park");
        wordEn.put(121,"bridge");
        wordEn.put(122,"river");
        wordEn.put(123,"forest");
        wordEn.put(124,"field");
        wordEn.put(125,"mountain");
        wordEn.put(126,"lake");
        wordEn.put(127,"sea");
        wordEn.put(128,"ocean");
        wordEn.put(129,"coast");
        wordEn.put(130,"beach");
        wordEn.put(131,"sand");
        wordEn.put(132,"island");
        wordEn.put(133,"border");
        wordEn.put(134,"customs");
        wordEn.put(135,"garbage");
        wordEn.put(136,"waste");
        wordEn.put(137,"stone");
        wordEn.put(138,"plant");
        wordEn.put(139,"tree");
        wordEn.put(140,"grass");
        wordEn.put(141,"flower");
        wordEn.put(142,"leaf");
        wordEn.put(143,"flat");
        wordEn.put(144,"room");
        wordEn.put(145,"living room");
        wordEn.put(146,"bedroom");
        wordEn.put(147,"bathroom");
        wordEn.put(148,"shower");
        wordEn.put(149,"toilet");
        wordEn.put(150,"kitchen");
        wordEn.put(151,"hall");
        wordEn.put(152,"balcony");
        wordEn.put(153,"floor");
        wordEn.put(154,"ceiling");
        wordEn.put(155,"wall");
        wordEn.put(156,"stairs");
        wordEn.put(157,"door");
        wordEn.put(158,"window");
        wordEn.put(159,"windowsill");
        wordEn.put(160,"curtain");
        wordEn.put(161,"switch");
        wordEn.put(162,"socket");
        wordEn.put(163,"faucet");
        wordEn.put(164,"pipe");
        wordEn.put(165,"chimney");
        wordEn.put(166,"furniture");
        wordEn.put(167,"table");
        wordEn.put(168,"chair");
        wordEn.put(169,"armchair");
        wordEn.put(170,"sofa");
        wordEn.put(171,"bed");
        wordEn.put(172,"wardrobe");
        wordEn.put(173,"cabinet");
        wordEn.put(174,"shelf");
        wordEn.put(175,"mirror");
        wordEn.put(176,"carpet");
        wordEn.put(177,"fridge");
        wordEn.put(178,"microwave");
        wordEn.put(179,"oven");
        wordEn.put(180,"stove");
        wordEn.put(181,"food");
        wordEn.put(182,"bread");
        wordEn.put(183,"butter");
        wordEn.put(184,"oil");
        wordEn.put(185,"cheese");
        wordEn.put(186,"sausage");
        wordEn.put(187,"ham");
        wordEn.put(188,"meat");
        wordEn.put(189,"beef");
        wordEn.put(190,"pork");
        wordEn.put(191,"lamb");
        wordEn.put(192,"chicken");
        wordEn.put(193,"cutlet");
        wordEn.put(194,"fish");
        wordEn.put(195,"egg");
        wordEn.put(196,"salad");
        wordEn.put(197,"mushroom");
        wordEn.put(198,"corn");
        wordEn.put(199,"porridge");
        wordEn.put(200,"oatmeal");
        wordEn.put(201,"soup");
        wordEn.put(202,"sandwich");
        wordEn.put(203,"rice");
        wordEn.put(204,"noodles");
        wordEn.put(205,"flour");
        wordEn.put(206,"spice");
        wordEn.put(207,"pepper");
        wordEn.put(208,"salt");
        wordEn.put(209,"onion");
        wordEn.put(210,"garlic");
        wordEn.put(211,"sauce");
        wordEn.put(212,"vegetables");
        wordEn.put(213,"potatoes");
        wordEn.put(214,"carrot");
        wordEn.put(215,"beet");
        wordEn.put(216,"tomato");
        wordEn.put(217,"cucumber");
        wordEn.put(218,"cabbage");
        wordEn.put(219,"squash");
        wordEn.put(220,"eggplant");
        wordEn.put(221,"beans");
        wordEn.put(222,"pea");
        wordEn.put(223,"nut");
        wordEn.put(224,"fruit");
        wordEn.put(225,"apple");
        wordEn.put(226,"pear");
        wordEn.put(227,"banana");
        wordEn.put(228,"berry");
        wordEn.put(229,"strawberry");
        wordEn.put(230,"raspberry");
        wordEn.put(231,"cherry");
        wordEn.put(232,"plum");
        wordEn.put(233,"grape");
        wordEn.put(234,"apricot");
        wordEn.put(235,"peach");
        wordEn.put(236,"melon");
        wordEn.put(237,"watermelon");
        wordEn.put(238,"pumpkin");
        wordEn.put(239,"orange");
        wordEn.put(240,"mandarin");
        wordEn.put(241,"lemon");
        wordEn.put(242,"pineapple");
        wordEn.put(243,"sugar");
        wordEn.put(244,"honey");
        wordEn.put(245,"jam");
        wordEn.put(246,"cake");
        wordEn.put(247,"bun");
        wordEn.put(248,"cookie");
        wordEn.put(249,"pie");
        wordEn.put(250,"sweet");
        wordEn.put(251,"ice-cream");
        wordEn.put(252,"chocolate");
        wordEn.put(253,"water");
        wordEn.put(254,"soda");
        wordEn.put(255,"juice");
        wordEn.put(256,"wine");
        wordEn.put(257,"tea");
        wordEn.put(258,"coffee");
        wordEn.put(259,"milk");
        wordEn.put(260,"cream");
        wordEn.put(261,"yogurt");
        wordEn.put(262,"curd");
        wordEn.put(263,"dish");
        wordEn.put(264,"cup");
        wordEn.put(265,"glass");
        wordEn.put(266,"mug");
        wordEn.put(267,"plate");
        wordEn.put(268,"spoon");
        wordEn.put(269,"fork");
        wordEn.put(270,"knife");
        wordEn.put(271,"saucer");
        wordEn.put(272,"bottle");
        wordEn.put(273,"napkin");
        wordEn.put(274,"pan");
        wordEn.put(275,"frying pan");
        wordEn.put(276,"kettle");
        wordEn.put(277,"meal");
        wordEn.put(278,"breakfast");
        wordEn.put(279,"lunch");
        wordEn.put(280,"dinner");
        wordEn.put(281,"transport");
        wordEn.put(282,"plane");
        wordEn.put(283,"car");
        wordEn.put(284,"tram");
        wordEn.put(285,"bus");
        wordEn.put(286,"train");
        wordEn.put(287,"ship");
        wordEn.put(288,"bicycle");
        wordEn.put(289,"time");
        wordEn.put(290,"minute");
        wordEn.put(291,"hour");
        wordEn.put(292,"week");
        wordEn.put(293,"year");
        wordEn.put(294,"century");
        wordEn.put(295,"the day before yesterday");
        wordEn.put(296,"yesterday");
        wordEn.put(297,"today");
        wordEn.put(298,"tonight");
        wordEn.put(299,"tomorrow");
        wordEn.put(300,"the day after tomorrow");
        wordEn.put(301,"day");
        wordEn.put(302,"morning");
        wordEn.put(303,"afternoon");
        wordEn.put(304,"evening");
        wordEn.put(305,"night");
        wordEn.put(306,"Monday");
        wordEn.put(307,"Tuesday");
        wordEn.put(308,"Wednesday");
        wordEn.put(309,"Thursday");
        wordEn.put(310,"Friday");
        wordEn.put(311,"Saturday");
        wordEn.put(312,"Sunday");
        wordEn.put(313,"month");
        wordEn.put(314,"season");
        wordEn.put(315,"spring");
        wordEn.put(316,"summer");
        wordEn.put(317,"autumn");
        wordEn.put(318,"winter");
        wordEn.put(319,"holiday");
        wordEn.put(320,"Christmas");
        wordEn.put(321,"Easter");
        wordEn.put(322,"birthday");
        wordEn.put(323,"form");
        wordEn.put(324,"name");
        wordEn.put(325,"first name");
        wordEn.put(326,"surname");
        wordEn.put(327,"maiden name");
        wordEn.put(328,"birth date");
        wordEn.put(329,"place of birth");
        wordEn.put(330,"address");
        wordEn.put(331,"marital status");
        wordEn.put(332,"single");
        wordEn.put(333,"married");
        wordEn.put(334,"divorced");
        wordEn.put(335,"widowed");
        wordEn.put(336,"thing");
        wordEn.put(337,"pen");
        wordEn.put(338,"pencil");
        wordEn.put(339,"book");
        wordEn.put(340,"copybook");
        wordEn.put(341,"notebook");
        wordEn.put(342,"note");
        wordEn.put(343,"dictionary");
        wordEn.put(344,"letter");
        wordEn.put(345,"envelope");
        wordEn.put(346,"paper");
        wordEn.put(347,"newspaper");
        wordEn.put(348,"magazine");
        wordEn.put(349,"(tele)phone");
        wordEn.put(350,"clock");
        wordEn.put(351,"comb");
        wordEn.put(352,"TV");
        wordEn.put(353,"iron");
        wordEn.put(354,"soap");
        wordEn.put(355,"radio");
        wordEn.put(356,"bag");
        wordEn.put(357,"backpack");
        wordEn.put(358,"map");
        wordEn.put(359,"card");
        wordEn.put(360,"suitcase");
        wordEn.put(361,"present");
        wordEn.put(362,"camera");
        wordEn.put(363,"vase");
        wordEn.put(364,"handkerchief");
        wordEn.put(365,"ball");
        wordEn.put(366,"balloon");
        wordEn.put(367,"toy");
        wordEn.put(368,"ticket");
        wordEn.put(369,"luggage");
        wordEn.put(370,"battery");
        wordEn.put(371,"bucket");
        wordEn.put(372,"rope");
        wordEn.put(373,"board");
        wordEn.put(374,"calendar");
        wordEn.put(375,"laptop");
        wordEn.put(376,"brush");
        wordEn.put(377,"keyboard");
        wordEn.put(378,"key");
        wordEn.put(379,"wheel");
        wordEn.put(380,"steering wheel");
        wordEn.put(381,"trunk");
        wordEn.put(382,"gas(oline)");
        wordEn.put(383,"purse");
        wordEn.put(384,"wallet");
        wordEn.put(385,"lamp");
        wordEn.put(386,"ruler");
        wordEn.put(387,"shovel");
        wordEn.put(388,"machine");
        wordEn.put(389,"hammer");
        wordEn.put(390,"scissors");
        wordEn.put(391,"glasses");
        wordEn.put(392,"package");
        wordEn.put(393,"stick");
        wordEn.put(394,"glue");
        wordEn.put(395,"gift");
        wordEn.put(396,"towel");
        wordEn.put(397,"mail");
        wordEn.put(398,"wire");
        wordEn.put(399,"page");
        wordEn.put(400,"torch");
        wordEn.put(401,"box");
        wordEn.put(402,"blanket");
        wordEn.put(403,"sheet");
        wordEn.put(404,"pillow");
        wordEn.put(405,"сlothes");
        wordEn.put(406,"shoes");
        wordEn.put(407,"boot");
        wordEn.put(408,"sneakers");
        wordEn.put(409,"coat");
        wordEn.put(410,"dress");
        wordEn.put(411,"suit");
        wordEn.put(412,"shirt");
        wordEn.put(413,"blouse");
        wordEn.put(414,"skirt");
        wordEn.put(415,"glove");
        wordEn.put(416,"mitten");
        wordEn.put(417,"hat");
        wordEn.put(418,"cap");
        wordEn.put(419,"jacket");
        wordEn.put(420,"cardigan");
        wordEn.put(421,"scarf");
        wordEn.put(422,"sock");
        wordEn.put(423,"sweater");
        wordEn.put(424,"Invocation-shirt");
        wordEn.put(425,"tie");
        wordEn.put(426,"trousers");
        wordEn.put(427,"shorts");
        wordEn.put(428,"tights");
        wordEn.put(429,"stockings");
        wordEn.put(430,"jeans");
        wordEn.put(431,"hood");
        wordEn.put(432,"belt");
        wordEn.put(433,"underwear");
        wordEn.put(434,"briefs");
        wordEn.put(435,"panties");
        wordEn.put(436,"bra");
        wordEn.put(437,"body");
        wordEn.put(438,"head");
        wordEn.put(439,"face");
        wordEn.put(440,"forehead");
        wordEn.put(441,"nose");
        wordEn.put(442,"ear");
        wordEn.put(443,"mouth");
        wordEn.put(444,"throat");
        wordEn.put(445,"eye");
        wordEn.put(446,"eyebrow");
        wordEn.put(447,"lips");
        wordEn.put(448,"tooth");
        wordEn.put(449,"hair");
        wordEn.put(450,"mustache");
        wordEn.put(451,"cheek");
        wordEn.put(452,"chin");
        wordEn.put(453,"neck");
        wordEn.put(454,"shoulder");
        wordEn.put(455,"chest");
        wordEn.put(456,"heart");
        wordEn.put(457,"stomach");
        wordEn.put(458,"back");
        wordEn.put(459,"wrist");
        wordEn.put(460,"hand");
        wordEn.put(461,"finger");
        wordEn.put(462,"nail");
        wordEn.put(463,"elbow");
        wordEn.put(464,"leg");
        wordEn.put(465,"knee");
        wordEn.put(466,"foot");
        wordEn.put(467,"heel");
        wordEn.put(468,"toe");
        wordEn.put(469,"beard");
        wordEn.put(470,"bone");
        wordEn.put(471,"health");
        wordEn.put(472,"healthy");
        wordEn.put(473,"sick");
        wordEn.put(474,"sickness");
        wordEn.put(475,"fever ");
        wordEn.put(476,"cough");
        wordEn.put(477,"running nose");
        wordEn.put(478,"sneeze");
        wordEn.put(479,"pain");
        wordEn.put(480,"headache");
        wordEn.put(481,"flu");
        wordEn.put(482,"bruise");
        wordEn.put(483,"event");
        wordEn.put(484,"birth");
        wordEn.put(485,"game");
        wordEn.put(486,"lesson");
        wordEn.put(487,"vacation");
        wordEn.put(488,"party");
        wordEn.put(489,"meeting");
        wordEn.put(490,"wedding");
        wordEn.put(491,"negotiation");
        wordEn.put(492,"trip");
        wordEn.put(493,"death");
        wordEn.put(494,"weather");
        wordEn.put(495,"sun");
        wordEn.put(496,"moon");
        wordEn.put(497,"wind");
        wordEn.put(498,"fog");
        wordEn.put(499,"rain");
        wordEn.put(500,"snow");
        wordEn.put(501,"sky");
        wordEn.put(502,"cloud");
        wordEn.put(503,"air");
        wordEn.put(504,"temperature");
        wordEn.put(505,"degree");
        wordEn.put(506,"art");
        wordEn.put(507,"music");
        wordEn.put(508,"song");
        wordEn.put(509,"literature");
        wordEn.put(510,"story");
        wordEn.put(511,"movie");
        wordEn.put(512,"film");
        wordEn.put(513,"sculpture");
        wordEn.put(514,"picture");
        wordEn.put(515,"photo");
        wordEn.put(516,"advertising");
        wordEn.put(517,"purchase");
        wordEn.put(518,"size");
        wordEn.put(519,"price");
        wordEn.put(520,"money");
        wordEn.put(521,"cash");
        wordEn.put(522,"discount");
        wordEn.put(523,"account");
        wordEn.put(524,"bill");
        wordEn.put(525,"tip");
        wordEn.put(526,"measure");
        wordEn.put(527,"distance");
        wordEn.put(528,"length");
        wordEn.put(529,"height");
        wordEn.put(530,"depth");
        wordEn.put(531,"strength");
        wordEn.put(532,"speed");
        wordEn.put(533,"kilometer");
        wordEn.put(534,"kilogram");
        wordEn.put(535,"pound");
        wordEn.put(536,"feeling");
        wordEn.put(537,"fun");
        wordEn.put(538,"joy");
        wordEn.put(539,"fear");
        wordEn.put(540,"sadness");
        wordEn.put(541,"passion");
        wordEn.put(542,"pleasure");
        wordEn.put(543,"happiness");
        wordEn.put(544,"peace");
        wordEn.put(545,"love");
        wordEn.put(546,"hate");
        wordEn.put(547,"world");
        wordEn.put(548,"soul");
        wordEn.put(549,"life");
        wordEn.put(550,"knowledge");
        wordEn.put(551,"task");
        wordEn.put(552,"exercise");
        wordEn.put(553,"luck");
        wordEn.put(554,"problem");
        wordEn.put(555,"opportunity");
        wordEn.put(556,"ability");
        wordEn.put(557,"beauty");
        wordEn.put(558,"danger");
        wordEn.put(559,"experience");
        wordEn.put(560,"memory");
        wordEn.put(561,"benefit");
        wordEn.put(562,"advantage");
        wordEn.put(563,"profit");
        wordEn.put(564,"habit");
        wordEn.put(565,"reason");
        wordEn.put(566,"consequence");
        wordEn.put(567,"meaning");
        wordEn.put(568,"means");
        wordEn.put(569,"effort");
        wordEn.put(570,"success");
        wordEn.put(571,"goal");
        wordEn.put(572,"miracle");
        wordEn.put(573,"science");
        wordEn.put(574,"language");
        wordEn.put(575,"word");
        wordEn.put(576,"fire");
        wordEn.put(577,"case");
        wordEn.put(578,"circumstance");
        wordEn.put(579,"thought");
        wordEn.put(580,"choice");
        wordEn.put(581,"permit");
        wordEn.put(582,"delivery");
        wordEn.put(583,"achievement");
        wordEn.put(584,"duty");
        wordEn.put(585,"delay");
        wordEn.put(586,"relationship");
        wordEn.put(587,"mark");
        wordEn.put(588,"mistake");
        wordEn.put(589,"behavior");
        wordEn.put(590,"invitation");
        wordEn.put(591,"development");
        wordEn.put(592,"decision");
        wordEn.put(593,"solution");
        wordEn.put(594,"advice");
        wordEn.put(595,"agreement");
        wordEn.put(596,"list");
        wordEn.put(597,"argument");
        wordEn.put(598,"test");
        wordEn.put(599,"step");
        wordEn.put(600,"piece");
        wordEn.put(601,"area");
        wordEn.put(602,"pair");
        wordEn.put(603,"couple");
        wordEn.put(604,"surface");
        wordEn.put(605,"mess");
        wordEn.put(606,"question");
        wordEn.put(607,"what");
        wordEn.put(608,"who");
        wordEn.put(609,"where");
        wordEn.put(610,"how");
        wordEn.put(611,"why");
        wordEn.put(612,"when");
        wordEn.put(613,"how many");
        wordEn.put(614,"how much");
        wordEn.put(615,"I");
        wordEn.put(616,"you");
        wordEn.put(617,"he");
        wordEn.put(618,"she");
        wordEn.put(619,"it");
        wordEn.put(620,"we");
        wordEn.put(621,"they");
        wordEn.put(622,"my");
        wordEn.put(623,"your");
        wordEn.put(624,"his");
        wordEn.put(625,"her");
        wordEn.put(626,"its");
        wordEn.put(627,"our");
        wordEn.put(628,"their");
        wordEn.put(629,"from");
        wordEn.put(630,"of");
        wordEn.put(631,"to");
        wordEn.put(632,"in");
        wordEn.put(633,"on");
        wordEn.put(634,"under");
        wordEn.put(635,"behind");
        wordEn.put(636,"with");
        wordEn.put(637,"without");
        wordEn.put(638,"in front of");
        wordEn.put(639,"before");
        wordEn.put(640,"after");
        wordEn.put(641,"between");
        wordEn.put(642,"near");
        wordEn.put(643,"for");
        wordEn.put(644,"since");
        wordEn.put(645,"during");
        wordEn.put(646,"around");
        wordEn.put(647,"because of");
        wordEn.put(648,"about");
        wordEn.put(649,"against");
        wordEn.put(650,"among");
        wordEn.put(651,"through");
        wordEn.put(652,"per");
        wordEn.put(653,"above");
        wordEn.put(654,"below");
        wordEn.put(655,"number");
        wordEn.put(656,"eleven");
        wordEn.put(657,"twelve ");
        wordEn.put(658,"thirteen");
        wordEn.put(659,"fourteen");
        wordEn.put(660,"fifteen");
        wordEn.put(661,"sixteen");
        wordEn.put(662,"seventeen [");
        wordEn.put(663,"eighteen");
        wordEn.put(664,"nineteen");
        wordEn.put(665,"twenty");
        wordEn.put(666,"thirty");
        wordEn.put(667,"forty");
        wordEn.put(668,"fifty");
        wordEn.put(669,"sixty");
        wordEn.put(670,"seventy");
        wordEn.put(671,"eighty");
        wordEn.put(672,"ninety");
        wordEn.put(673,"hundred");
        wordEn.put(674,"thousand");
        wordEn.put(675,"first");
        wordEn.put(676,"second");
        wordEn.put(677,"third");
        wordEn.put(678,"fourth");
        wordEn.put(679,"fifth");
        wordEn.put(680,"color");
        wordEn.put(681,"old");
        wordEn.put(682,"young");
        wordEn.put(683,"new");
        wordEn.put(684,"big");
        wordEn.put(685,"large");
        wordEn.put(686,"huge");
        wordEn.put(687,"small");
        wordEn.put(688,"fat");
        wordEn.put(689,"slim");
        wordEn.put(690,"thick");
        wordEn.put(691,"thin");
        wordEn.put(692,"hungry");
        wordEn.put(693,"full");
        wordEn.put(694,"good");
        wordEn.put(695,"excellent");
        wordEn.put(696,"amazing");
        wordEn.put(697,"fine");
        wordEn.put(698,"bad");
        wordEn.put(699,"terrible");
        wordEn.put(700,"nasty");
        wordEn.put(701,"early");
        wordEn.put(702,"late");
        wordEn.put(703,"last ");
        wordEn.put(704,"next");
        wordEn.put(705,"free");
        wordEn.put(706,"busy");
        wordEn.put(707,"hot");
        wordEn.put(708,"warm");
        wordEn.put(709,"cold");
        wordEn.put(710,"cool");
        wordEn.put(711,"spicy");
        wordEn.put(712,"sharp");
        wordEn.put(713,"blunt");
        wordEn.put(714,"stupid");
        wordEn.put(715,"clever");
        wordEn.put(716,"smart");
        wordEn.put(717,"nice");
        wordEn.put(718,"beautiful");
        wordEn.put(719,"handsome");
        wordEn.put(720,"attractive");
        wordEn.put(721,"pretty");
        wordEn.put(722,"ugly");
        wordEn.put(723,"high");
        wordEn.put(724,"tall");
        wordEn.put(725,"short");
        wordEn.put(726,"low");
        wordEn.put(727,"long");
        wordEn.put(728,"heavy");
        wordEn.put(729,"light");
        wordEn.put(730,"difficult");
        wordEn.put(731,"easy");
        wordEn.put(732,"simple");
        wordEn.put(733,"dark");
        wordEn.put(734,"expensive");
        wordEn.put(735,"dear");
        wordEn.put(736,"cheap");
        wordEn.put(737,"poor");
        wordEn.put(738,"rich");
        wordEn.put(739,"straight");
        wordEn.put(740,"left");
        wordEn.put(741,"right");
        wordEn.put(742,"wrong");
        wordEn.put(743,"fast");
        wordEn.put(744,"quick");
        wordEn.put(745,"slow");
        wordEn.put(746,"soft");
        wordEn.put(747,"hard");
        wordEn.put(748,"sad");
        wordEn.put(749,"glad");
        wordEn.put(750,"happy");
        wordEn.put(751,"merry");
        wordEn.put(752,"kind");
        wordEn.put(753,"angry");
        wordEn.put(754,"evil");
        wordEn.put(755,"polite");
        wordEn.put(756,"rude");
        wordEn.put(757,"gentle");
        wordEn.put(758,"brave");
        wordEn.put(759,"coward");
        wordEn.put(760,"shy");
        wordEn.put(761,"hard-working");
        wordEn.put(762,"lazy");
        wordEn.put(763,"useful");
        wordEn.put(764,"useless");
        wordEn.put(765,"strong");
        wordEn.put(766,"weak ");
        wordEn.put(767,"loud");
        wordEn.put(768,"noisy");
        wordEn.put(769,"quiet");
        wordEn.put(770,"calm");
        wordEn.put(771,"narrow");
        wordEn.put(772,"wide");
        wordEn.put(773,"clean");
        wordEn.put(774,"dirty");
        wordEn.put(775,"tired");
        wordEn.put(776,"honest");
        wordEn.put(777,"comfortable");
        wordEn.put(778,"strange");
        wordEn.put(779,"weird");
        wordEn.put(780,"own");
        wordEn.put(781,"tasty");
        wordEn.put(782,"delicious");
        wordEn.put(783,"bitter");
        wordEn.put(784,"sour");
        wordEn.put(785,"salty");
        wordEn.put(786,"ready");
        wordEn.put(787,"careful");
        wordEn.put(788,"main");
        wordEn.put(789,"able");
        wordEn.put(790,"necessary");
        wordEn.put(791,"important");
        wordEn.put(792,"sure");
        wordEn.put(793,"fit");
        wordEn.put(794,"better");
        wordEn.put(795,"best");
        wordEn.put(796,"worse");
        wordEn.put(797,"worst");
        wordEn.put(798,"more");
        wordEn.put(799,"most");
        wordEn.put(800,"less");
        wordEn.put(801,"least");
        wordEn.put(802,"sometimes");
        wordEn.put(803,"never");
        wordEn.put(804,"seldom");
        wordEn.put(805,"usually");
        wordEn.put(806,"often");
        wordEn.put(807,"always");
        wordEn.put(808,"soon");
        wordEn.put(809,"recently");
        wordEn.put(810,"well");
        wordEn.put(811,"far");
        wordEn.put(812,"exactly");
        wordEn.put(813,"probably");
        wordEn.put(814,"maybe");
        wordEn.put(815,"perhaps");
        wordEn.put(816,"really");
        wordEn.put(817,"of course");
        wordEn.put(818,"certainly");
        wordEn.put(819,"obviously");
        wordEn.put(820,"especially");
        wordEn.put(821,"yes");
        wordEn.put(822,"no");
        wordEn.put(823,"not");
        wordEn.put(824,"this");
        wordEn.put(825,"that");
        wordEn.put(826,"these");
        wordEn.put(827,"those");
        wordEn.put(828,"and");
        wordEn.put(829,"or");
        wordEn.put(830,"but");
        wordEn.put(831,"however");
        wordEn.put(832,"because");
        wordEn.put(833,"if");
        wordEn.put(834,"(al)though");
        wordEn.put(835,"be");
        wordEn.put(836,"do");
        wordEn.put(837,"have");
        wordEn.put(838,"can");
        wordEn.put(839,"may");
        wordEn.put(840,"go");
        wordEn.put(841,"find");
        wordEn.put(842,"hold");
        wordEn.put(843,"stand");
        wordEn.put(844,"sit");
        wordEn.put(845,"hear");
        wordEn.put(846,"win");
        wordEn.put(847,"get");
        wordEn.put(848,"make");
        wordEn.put(849,"come");
        wordEn.put(850,"become");
        wordEn.put(851,"run");
        wordEn.put(852,"see");
        wordEn.put(853,"write");
        wordEn.put(854,"fall");
        wordEn.put(855,"wear");
        wordEn.put(856,"take");
        wordEn.put(857,"give");
        wordEn.put(858,"forgive");
        wordEn.put(859,"forget");
        wordEn.put(860,"eat");
        wordEn.put(861,"lie");
        wordEn.put(862,"lead");
        wordEn.put(863,"feed");
        wordEn.put(864,"say");
        wordEn.put(865,"pay");
        wordEn.put(866,"lay");
        wordEn.put(867,"drink");
        wordEn.put(868,"swim");
        wordEn.put(869,"sing");
        wordEn.put(870,"begin");
        wordEn.put(871,"ring");
        wordEn.put(872,"sink");
        wordEn.put(873,"stink");
        wordEn.put(874,"fly");
        wordEn.put(875,"know");
        wordEn.put(876,"draw");
        wordEn.put(877,"throw");
        wordEn.put(878,"grow");
        wordEn.put(879,"blow");
        wordEn.put(880,"speak");
        wordEn.put(881,"choose");
        wordEn.put(882,"wake");
        wordEn.put(883,"break");
        wordEn.put(884,"show");
        wordEn.put(885,"cut");
        wordEn.put(886,"put");
        wordEn.put(887,"cost");
        wordEn.put(888,"let");
        wordEn.put(889,"shut");
        wordEn.put(890,"hit");
        wordEn.put(891,"read");
        wordEn.put(892,"send");
        wordEn.put(893,"spend");
        wordEn.put(894,"lend");
        wordEn.put(895,"build");
        wordEn.put(896,"feel");
        wordEn.put(897,"meet");
        wordEn.put(898,"sleep");
        wordEn.put(899,"keep");
        wordEn.put(900,"leave");
        wordEn.put(901,"buy");
        wordEn.put(902,"bring");
        wordEn.put(903,"teach");
        wordEn.put(904,"think");
        wordEn.put(905,"fight");
        wordEn.put(906,"catch");
        wordEn.put(907,"must");
        wordEn.put(908,"should");
        wordEn.put(909,"will");
        wordEn.put(910,"be afraid of");
        wordEn.put(911,"be interested in");
        wordEn.put(912,"be surprised");
        wordEn.put(913,"have to");
        wordEn.put(914,"get up");
        wordEn.put(915,"put on");
        wordEn.put(916,"take off");
        wordEn.put(917,"live");
        wordEn.put(918,"work");
        wordEn.put(919,"watch");
        wordEn.put(920,"wash");
        wordEn.put(921,"shave");
        wordEn.put(922,"try");
        wordEn.put(923,"celebrate");
        wordEn.put(924,"smile");
        wordEn.put(925,"laugh");
        wordEn.put(926,"cry");
        wordEn.put(927,"learn");
        wordEn.put(928,"study");
        wordEn.put(929,"change");
        wordEn.put(930,"listen");
        wordEn.put(931,"close");
        wordEn.put(932,"open");
        wordEn.put(933,"dance");
        wordEn.put(934,"ask");
        wordEn.put(935,"answer");
        wordEn.put(936,"collect");
        wordEn.put(937,"want");
        wordEn.put(938,"like");
        wordEn.put(939,"cook");
        wordEn.put(940,"bake");
        wordEn.put(941,"smell");
        wordEn.put(942,"wait");
        wordEn.put(943,"expect");
        wordEn.put(944,"thank");
        wordEn.put(945,"play");
        wordEn.put(946,"call");
        wordEn.put(947,"walk");
        wordEn.put(948,"smoke");
        wordEn.put(949,"wish");
        wordEn.put(950,"excuse");
        wordEn.put(951,"shout");
        wordEn.put(952,"dream");
        wordEn.put(953,"hope");
        wordEn.put(954,"remember");
        wordEn.put(955,"remind");
        wordEn.put(956,"enjoy");
        wordEn.put(957,"carry");
        wordEn.put(958,"explain");
        wordEn.put(959,"stay");
        wordEn.put(960,"rest");
        wordEn.put(961,"turn");
        wordEn.put(962,"lift");
        wordEn.put(963,"believe");
        wordEn.put(964,"receive");
        wordEn.put(965,"help");
        wordEn.put(966,"order");
        wordEn.put(967,"visit");
        wordEn.put(968,"check");
        wordEn.put(969,"jump");
        wordEn.put(970,"travel");
        wordEn.put(971,"talk");
        wordEn.put(972,"decide");
        wordEn.put(973,"solve");
        wordEn.put(974,"drop");
        wordEn.put(975,"agree");
        wordEn.put(976,"save");
        wordEn.put(977,"argue");
        wordEn.put(978,"count");
        wordEn.put(979,"surprise");
        wordEn.put(980,"worry");
        wordEn.put(981,"joke");
        wordEn.put(982,"move");
        wordEn.put(983,"match");
        wordEn.put(984,"die");
        wordEn.put(985,"influence");
        wordEn.put(986,"support ");
        wordEn.put(987,"describe");
        wordEn.put(988,"punish");
        wordEn.put(989,"intend");
        wordEn.put(990,"complain");
        wordEn.put(991,"avoid");
        wordEn.put(992,"return");
        wordEn.put(993,"disturb");
        wordEn.put(994,"provide");
        wordEn.put(995,"offer");
        wordEn.put(996,"introduce");
        wordEn.put(997,"persuade");
        wordEn.put(998,"approve");
        wordEn.put(999,"appreciate");

        return wordEn;
    }

    private Map<Integer, String> getStrWordsRu(){
        wordRu.put(0,"здравствуйте, привет");
        wordRu.put(1,"извините");
        wordRu.put(2,"пожалуйста");
        wordRu.put(3,"спасибо");
        wordRu.put(4,"как жаль");
        wordRu.put(5,"до свидания");
        wordRu.put(6,"люди");
        wordRu.put(7,"мужчина");
        wordRu.put(8,"женщина");
        wordRu.put(9,"ребенок");
        wordRu.put(10,"мальчик");
        wordRu.put(11,"девочка");
        wordRu.put(12,"парень");
        wordRu.put(13,"друг");
        wordRu.put(14,"знакомый; знакомство");
        wordRu.put(15,"сосед");
        wordRu.put(16,"гость");
        wordRu.put(17,"начальник");
        wordRu.put(18,"конкурент, соперник");
        wordRu.put(19,"клиент");
        wordRu.put(20,"коллега");
        wordRu.put(21,"семья");
        wordRu.put(22,"родители");
        wordRu.put(23,"отец");
        wordRu.put(24,"папа");
        wordRu.put(25,"мать");
        wordRu.put(26,"мама");
        wordRu.put(27,"муж");
        wordRu.put(28,"жена");
        wordRu.put(29,"сын");
        wordRu.put(30,"дочь");
        wordRu.put(31,"брат");
        wordRu.put(32,"сестра");
        wordRu.put(33,"дед");
        wordRu.put(34,"тесть, свекор");
        wordRu.put(35,"дядя");
        wordRu.put(36,"тетя");
        wordRu.put(37,"двоюродный брат, двоюродная сестра");
        wordRu.put(38,"племянник");
        wordRu.put(39,"племянница");
        wordRu.put(40,"работа");
        wordRu.put(41,"бизнесмен");
        wordRu.put(42,"учитель");
        wordRu.put(43,"водитель");
        wordRu.put(44,"рабочий");
        wordRu.put(45,"инженер");
        wordRu.put(46,"врач");
        wordRu.put(47,"адвокат, юрист");
        wordRu.put(48,"журналист");
        wordRu.put(49,"медсестра");
        wordRu.put(50,"продавец");
        wordRu.put(51,"официант");
        wordRu.put(52,"бухгалтер");
        wordRu.put(53,"художник");
        wordRu.put(54,"музыкант");
        wordRu.put(55,"актер");
        wordRu.put(56,"студент");
        wordRu.put(57,"школьник, ученик");
        wordRu.put(58,"животное");
        wordRu.put(59,"кошка");
        wordRu.put(60,"собака");
        wordRu.put(61,"птица");
        wordRu.put(62,"белка");
        wordRu.put(63,"волк");
        wordRu.put(64,"гусь");
        wordRu.put(65,"жираф");
        wordRu.put(66,"кролик; заяц");
        wordRu.put(67,"корова");
        wordRu.put(68,"крыса");
        wordRu.put(69,"лиса");
        wordRu.put(70,"лошадь");
        wordRu.put(71,"лягушка");
        wordRu.put(72,"медведь");
        wordRu.put(73,"мышь");
        wordRu.put(74,"обезьяна");
        wordRu.put(75,"свинья");
        wordRu.put(76,"слон");
        wordRu.put(77,"утка");
        wordRu.put(78,"страна; сельская местность");
        wordRu.put(79,"город");
        wordRu.put(80,"дом (здание)");
        wordRu.put(81,"дом (место проживания)");
        wordRu.put(82,"здание; строительство");
        wordRu.put(83,"место; помещать");
        wordRu.put(84,"вход");
        wordRu.put(85,"выход");
        wordRu.put(86,"центр");
        wordRu.put(87,"двор");
        wordRu.put(88,"крыша");
        wordRu.put(89,"забор");
        wordRu.put(90,"земля, участок");
        wordRu.put(91,"деревня, поселок");
        wordRu.put(92,"школа");
        wordRu.put(93,"университет");
        wordRu.put(94,"театр");
        wordRu.put(95,"церковь");
        wordRu.put(96,"ресторан");
        wordRu.put(97,"кафе");
        wordRu.put(98,"гостиница");
        wordRu.put(99,"банк");
        wordRu.put(100,"кинотеатр");
        wordRu.put(101,"больница");
        wordRu.put(102,"полиция");
        wordRu.put(103,"почта");
        wordRu.put(104,"станция, вокзал");
        wordRu.put(105,"аэропорт");
        wordRu.put(106,"магазин");
        wordRu.put(107,"аптека");
        wordRu.put(108,"рынок");
        wordRu.put(109,"офис");
        wordRu.put(110,"компания, фирма");
        wordRu.put(111,"предприятие, завод, фабрика");
        wordRu.put(112,"площадь");
        wordRu.put(113,"улица");
        wordRu.put(114,"дорога");
        wordRu.put(115,"перекрёсток");
        wordRu.put(116,"остановка; останавливаться");
        wordRu.put(117,"тротуар");
        wordRu.put(118,"тропа, тропинка");
        wordRu.put(119,"сад");
        wordRu.put(120,"парк");
        wordRu.put(121,"мост");
        wordRu.put(122,"река");
        wordRu.put(123,"лес");
        wordRu.put(124,"поле");
        wordRu.put(125,"гора");
        wordRu.put(126,"озеро");
        wordRu.put(127,"море");
        wordRu.put(128,"океан");
        wordRu.put(129,"морской берег, побережье");
        wordRu.put(130,"пляж");
        wordRu.put(131,"песок");
        wordRu.put(132,"остров");
        wordRu.put(133,"граница");
        wordRu.put(134,"таможня");
        wordRu.put(135,"мусор");
        wordRu.put(136,"отходы; тратить впустую");
        wordRu.put(137,"камень");
        wordRu.put(138,"растение; завод; сажать");
        wordRu.put(139,"дерево");
        wordRu.put(140,"трава");
        wordRu.put(141,"цветок");
        wordRu.put(142,"лист (дерева)");
        wordRu.put(143,"квартира");
        wordRu.put(144,"комната");
        wordRu.put(145,"зал");
        wordRu.put(146,"спальня");
        wordRu.put(147,"ванная");
        wordRu.put(148,"душ");
        wordRu.put(149,"туалет");
        wordRu.put(150,"кухня");
        wordRu.put(151,"коридор");
        wordRu.put(152,"балкон");
        wordRu.put(153,"пол; этаж");
        wordRu.put(154,"потолок");
        wordRu.put(155,"стена");
        wordRu.put(156,"ступеньки; лестница");
        wordRu.put(157,"дверь");
        wordRu.put(158,"окно");
        wordRu.put(159,"подоконник");
        wordRu.put(160,"занавес(ка), штора");
        wordRu.put(161,"выключатель; переключать");
        wordRu.put(162,"розетка");
        wordRu.put(163,"(водопроводный) кран");
        wordRu.put(164,"труба; трубка");
        wordRu.put(165,"дымовая труба");
        wordRu.put(166,"мебель");
        wordRu.put(167,"стол");
        wordRu.put(168,"стул");
        wordRu.put(169,"кресло");
        wordRu.put(170,"диван");
        wordRu.put(171,"кровать");
        wordRu.put(172,"(платяной) шкаф");
        wordRu.put(173,"шкаф(чик)");
        wordRu.put(174,"полка");
        wordRu.put(175,"зеркало");
        wordRu.put(176,"ковер");
        wordRu.put(177,"холодильник");
        wordRu.put(178,"микроволновка");
        wordRu.put(179,"печь, духовка");
        wordRu.put(180,"кухонная плита");
        wordRu.put(181,"еда");
        wordRu.put(182,"хлеб");
        wordRu.put(183,"масло");
        wordRu.put(184,"растительное масло; нефть");
        wordRu.put(185,"сыр");
        wordRu.put(186,"колбаса, сосиска");
        wordRu.put(187,"ветчина");
        wordRu.put(188,"мясо");
        wordRu.put(189,"говядина");
        wordRu.put(190,"свинина");
        wordRu.put(191,"баранина; ягненок");
        wordRu.put(192,"цыпленок; курица");
        wordRu.put(193,"котлета");
        wordRu.put(194,"рыба; рыбачить");
        wordRu.put(195,"яйцо");
        wordRu.put(196,"салат");
        wordRu.put(197,"гриб");
        wordRu.put(198,"кукуруза; зерно");
        wordRu.put(199,"каша");
        wordRu.put(200,"овсянка");
        wordRu.put(201,"суп");
        wordRu.put(202,"бутерброд");
        wordRu.put(203,"рис");
        wordRu.put(204,"лапша");
        wordRu.put(205,"мука");
        wordRu.put(206,"специя, пряность");
        wordRu.put(207,"перец; поперчить");
        wordRu.put(208,"соль; посолить");
        wordRu.put(209,"лук (репчатый)");
        wordRu.put(210,"чеснок");
        wordRu.put(211,"соус");
        wordRu.put(212,"овощи");
        wordRu.put(213,"картофель");
        wordRu.put(214,"морковь");
        wordRu.put(215,"свекла");
        wordRu.put(216,"помидор");
        wordRu.put(217,"огурец");
        wordRu.put(218,"капуста");
        wordRu.put(219,"кабачок");
        wordRu.put(220,"баклажан");
        wordRu.put(221,"бобы");
        wordRu.put(222,"горох");
        wordRu.put(223,"орех");
        wordRu.put(224,"фрукт");
        wordRu.put(225,"яблоко");
        wordRu.put(226,"груша");
        wordRu.put(227,"банан");
        wordRu.put(228,"ягода");
        wordRu.put(229,"клубника, земляника");
        wordRu.put(230,"малина");
        wordRu.put(231,"вишня");
        wordRu.put(232,"слива");
        wordRu.put(233,"виноград");
        wordRu.put(234,"абрикос");
        wordRu.put(235,"персик");
        wordRu.put(236,"дыня");
        wordRu.put(237,"арбуз");
        wordRu.put(238,"тыква");
        wordRu.put(239,"апельсин; оранжевый");
        wordRu.put(240,"мандарин");
        wordRu.put(241,"лимон");
        wordRu.put(242,"ананас");
        wordRu.put(243,"сахар");
        wordRu.put(244,"мёд");
        wordRu.put(245,"варенье");
        wordRu.put(246,"торт");
        wordRu.put(247,"булочка");
        wordRu.put(248,"печенье");
        wordRu.put(249,"пирог, пирожок");
        wordRu.put(250,"конфета; сладкий");
        wordRu.put(251,"мороженое");
        wordRu.put(252,"шоколад");
        wordRu.put(253,"вода; поливать");
        wordRu.put(254,"газировка");
        wordRu.put(255,"сок");
        wordRu.put(256,"вино");
        wordRu.put(257,"чай");
        wordRu.put(258,"кофе");
        wordRu.put(259,"молоко");
        wordRu.put(260,"сливки; крем");
        wordRu.put(261,"йогурт");
        wordRu.put(262,"творог");
        wordRu.put(263,"блюдо  ");
        wordRu.put(264,"чашка");
        wordRu.put(265,"стакан; стекло");
        wordRu.put(266,"кружка");
        wordRu.put(267,"тарелка");
        wordRu.put(268,"ложка");
        wordRu.put(269,"вилка");
        wordRu.put(270,"нож");
        wordRu.put(271,"блюдце");
        wordRu.put(272,"бутылка");
        wordRu.put(273,"салфетка");
        wordRu.put(274,"кастрюля");
        wordRu.put(275,"сковородка");
        wordRu.put(276,"чайник; котел");
        wordRu.put(277,"принятие пищи, еда");
        wordRu.put(278,"завтрак");
        wordRu.put(279,"обед");
        wordRu.put(280,"ужин");
        wordRu.put(281,"транспорт");
        wordRu.put(282,"самолет");
        wordRu.put(283,"автомобиль");
        wordRu.put(284,"трамвай");
        wordRu.put(285,"автобус");
        wordRu.put(286,"поезд");
        wordRu.put(287,"корабль");
        wordRu.put(288,"велосипед");
        wordRu.put(289,"время; раз");
        wordRu.put(290,"минута");
        wordRu.put(291,"час");
        wordRu.put(292,"неделя");
        wordRu.put(293,"год");
        wordRu.put(294,"век, столетие");
        wordRu.put(295,"позавчера");
        wordRu.put(296,"вчера");
        wordRu.put(297,"сегодня (днем)");
        wordRu.put(298,"сегодня вечером (ночью)");
        wordRu.put(299,"завтра");
        wordRu.put(300,"послезавтра");
        wordRu.put(301,"день");
        wordRu.put(302,"утро");
        wordRu.put(303,"день (после полудня)");
        wordRu.put(304,"вечер");
        wordRu.put(305,"ночь");
        wordRu.put(306,"понедельник");
        wordRu.put(307,"вторник");
        wordRu.put(308,"среда");
        wordRu.put(309,"четверг");
        wordRu.put(310,"пятница");
        wordRu.put(311,"суббота");
        wordRu.put(312,"воскресенье");
        wordRu.put(313,"месяц");
        wordRu.put(314,"время года; сезон");
        wordRu.put(315,"весна");
        wordRu.put(316,"лето");
        wordRu.put(317,"осень");
        wordRu.put(318,"зима");
        wordRu.put(319,"праздник; отпуск; каникулы");
        wordRu.put(320,"Рождество");
        wordRu.put(321,"Пасха");
        wordRu.put(322,"день рождения");
        wordRu.put(323,"форма; бланк");
        wordRu.put(324,"название");
        wordRu.put(325,"имя");
        wordRu.put(326,"фамилия");
        wordRu.put(327,"девичья фамилия");
        wordRu.put(328,"дата рождения");
        wordRu.put(329,"место рождения");
        wordRu.put(330,"адрес");
        wordRu.put(331,"семейное положение");
        wordRu.put(332,"холостой, незамужняя; один(окий); в один конец (о билете)");
        wordRu.put(333,"женатый/замужняя");
        wordRu.put(334,"разведенный");
        wordRu.put(335,"овдовевший");
        wordRu.put(336,"вещь");
        wordRu.put(337,"ручка");
        wordRu.put(338,"карандаш");
        wordRu.put(339,"книга");
        wordRu.put(340,"тетрадь");
        wordRu.put(341,"блокнот");
        wordRu.put(342,"записка, запись");
        wordRu.put(343,"словарь");
        wordRu.put(344,"письмо; буква");
        wordRu.put(345,"конверт");
        wordRu.put(346,"бумага");
        wordRu.put(347,"газета");
        wordRu.put(348,"журнал");
        wordRu.put(349,"телефон; разговаривать по телефону");
        wordRu.put(350,"часы");
        wordRu.put(351,"расчёска; расчесывать");
        wordRu.put(352,"телевизор");
        wordRu.put(353,"утюг; железо; гладить (утюгом)");
        wordRu.put(354,"мыло; намыливать");
        wordRu.put(355,"радио");
        wordRu.put(356,"сумка");
        wordRu.put(357,"рюкзак");
        wordRu.put(358,"карта (географическая)");
        wordRu.put(359,"открытка; карта (игральная); карточка");
        wordRu.put(360,"чемодан");
        wordRu.put(361,"подарок");
        wordRu.put(362,"фотоаппарат; видеокамера");
        wordRu.put(363,"ваза");
        wordRu.put(364,"носовой платок");
        wordRu.put(365,"мяч");
        wordRu.put(366,"воздушный шар(ик)");
        wordRu.put(367,"игрушка");
        wordRu.put(368,"билет");
        wordRu.put(369,"багаж");
        wordRu.put(370,"батарейка, аккумулятор");
        wordRu.put(371,"ведро");
        wordRu.put(372,"веревка");
        wordRu.put(373,"доска; борт; совет (правление)");
        wordRu.put(374,"календарь");
        wordRu.put(375,"ноутбук");
        wordRu.put(376,"щетка; кисть, кисточка; чистить щеткой");
        wordRu.put(377,"клавиатура");
        wordRu.put(378,"ключ; клавиша");
        wordRu.put(379,"колесо");
        wordRu.put(380,"руль");
        wordRu.put(381,"багажник; ствол; хобот");
        wordRu.put(382,"бензин");
        wordRu.put(383,"дамская сумка; кошелек");
        wordRu.put(384,"бумажник");
        wordRu.put(385,"лампа");
        wordRu.put(386,"линейка; правитель");
        wordRu.put(387,"лопата; рыть");
        wordRu.put(388,"машина; механизм; аппарат; станок");
        wordRu.put(389,"молоток; вбивать молотком");
        wordRu.put(390,"ножницы");
        wordRu.put(391,"очки");
        wordRu.put(392,"посылка; упаковка");
        wordRu.put(393,"палка; придерживаться; втыкать");
        wordRu.put(394,"клей; приклеивать");
        wordRu.put(395,"подарок; дар");
        wordRu.put(396,"полотенце");
        wordRu.put(397,"почта (корреспонденция); отправлять по почте");
        wordRu.put(398,"проволока; провод");
        wordRu.put(399,"страница");
        wordRu.put(400,"карманный фонарь; горелка; факел");
        wordRu.put(401,"коробка, ящик; боксировать");
        wordRu.put(402,"одеяло");
        wordRu.put(403,"простыня; лист(ок)");
        wordRu.put(404,"подушка");
        wordRu.put(405,"одежда");
        wordRu.put(406,"обувь");
        wordRu.put(407,"ботинок; сапог");
        wordRu.put(408,"кроссовки");
        wordRu.put(409,"пальто");
        wordRu.put(410,"платье; одевать(ся)");
        wordRu.put(411,"костюм; иск; подходить, быть к лицу, соответствовать");
        wordRu.put(412,"рубашка");
        wordRu.put(413,"блузка");
        wordRu.put(414,"юбка");
        wordRu.put(415,"перчатка");
        wordRu.put(416,"варежка");
        wordRu.put(417,"шляпа");
        wordRu.put(418,"шапка; кепка; колпачок");
        wordRu.put(419,"пиджак; куртка");
        wordRu.put(420,"кофта");
        wordRu.put(421,"шарф");
        wordRu.put(422,"носок");
        wordRu.put(423,"свитер");
        wordRu.put(424,"футболка");
        wordRu.put(425,"галстук; привязывать");
        wordRu.put(426,"брюки, штаны");
        wordRu.put(427,"шорты");
        wordRu.put(428,"колготки");
        wordRu.put(429,"чулки");
        wordRu.put(430,"джинсы");
        wordRu.put(431,"капюшон; капот");
        wordRu.put(432,"ремень, пояс");
        wordRu.put(433,"нижнее белье");
        wordRu.put(434,"трусы мужские");
        wordRu.put(435,"трусы женские");
        wordRu.put(436,"бюстгальтер");
        wordRu.put(437,"тело; кузов");
        wordRu.put(438,"голова; глава, руководитель");
        wordRu.put(439,"лицо");
        wordRu.put(440,"лоб");
        wordRu.put(441,"нос");
        wordRu.put(442,"ухо; ушко; колос");
        wordRu.put(443,"рот");
        wordRu.put(444,"горло");
        wordRu.put(445,"глаз");
        wordRu.put(446,"бровь");
        wordRu.put(447,"губы");
        wordRu.put(448,"зуб");
        wordRu.put(449,"волос(ы)");
        wordRu.put(450,"усы");
        wordRu.put(451,"щека; наглость, нахальство");
        wordRu.put(452,"подбородок");
        wordRu.put(453,"шея");
        wordRu.put(454,"плечо");
        wordRu.put(455,"грудь");
        wordRu.put(456,"сердце");
        wordRu.put(457,"желудок; живот");
        wordRu.put(458,"спина; назад");
        wordRu.put(459,"запястье");
        wordRu.put(460,"рука, кисть (руки)");
        wordRu.put(461,"палец (руки)");
        wordRu.put(462,"ноготь; гвоздь; прибивать");
        wordRu.put(463,"локоть");
        wordRu.put(464,"нога; ножка");
        wordRu.put(465,"колено");
        wordRu.put(466,"нога, ступня; подножие;");
        wordRu.put(467,"пятка; каблук");
        wordRu.put(468,"палец (ноги)");
        wordRu.put(469,"борода");
        wordRu.put(470,"кость");
        wordRu.put(471,"здоровье");
        wordRu.put(472,"здоровый");
        wordRu.put(473,"больной");
        wordRu.put(474,"болезнь");
        wordRu.put(475,"жар, (высокая) температура");
        wordRu.put(476,"кашель; кашлять");
        wordRu.put(477,"насморк");
        wordRu.put(478,"чихать");
        wordRu.put(479,"боль");
        wordRu.put(480,"головная боль");
        wordRu.put(481,"грипп");
        wordRu.put(482,"синяк, ушиб; ушибить");
        wordRu.put(483,"событие");
        wordRu.put(484,"рождение");
        wordRu.put(485,"игра");
        wordRu.put(486,"урок");
        wordRu.put(487,"отпуск, каникулы");
        wordRu.put(488,"вечеринка");
        wordRu.put(489,"встреча; собрание");
        wordRu.put(490,"свадьба");
        wordRu.put(491,"переговоры");
        wordRu.put(492,"поездка, путешествие");
        wordRu.put(493,"смерть");
        wordRu.put(494,"погода");
        wordRu.put(495,"солнце");
        wordRu.put(496,"луна");
        wordRu.put(497,"ветер");
        wordRu.put(498,"туман");
        wordRu.put(499,"дождь");
        wordRu.put(500,"снег");
        wordRu.put(501,"небо");
        wordRu.put(502,"облако");
        wordRu.put(503,"воздух");
        wordRu.put(504,"температура");
        wordRu.put(505,"градус; степень");
        wordRu.put(506,"искусство");
        wordRu.put(507,"музыка");
        wordRu.put(508,"песня");
        wordRu.put(509,"литература");
        wordRu.put(510,"рассказ, история");
        wordRu.put(511,"кино(фильм)");
        wordRu.put(512,"фильм; пленка");
        wordRu.put(513,"скульптура; статуя");
        wordRu.put(514,"картина; фотография");
        wordRu.put(515,"фото");
        wordRu.put(516,"реклама");
        wordRu.put(517,"покупка, приобретение; покупать, приобретать");
        wordRu.put(518,"размер");
        wordRu.put(519,"цена");
        wordRu.put(520,"деньги");
        wordRu.put(521,"наличные (деньги)");
        wordRu.put(522,"скидка");
        wordRu.put(523,"счет (банковский)");
        wordRu.put(524,"счёт");
        wordRu.put(525,"чаевые; кончик, верхушка; совет");
        wordRu.put(526,"измерение; мера; измерять");
        wordRu.put(527,"расстояние; дистанция");
        wordRu.put(528,"длина");
        wordRu.put(529,"высота");
        wordRu.put(530,"глубина");
        wordRu.put(531,"сила; прочность");
        wordRu.put(532,"скорость");
        wordRu.put(533,"километр");
        wordRu.put(534,"килограмм");
        wordRu.put(535,"фунт");
        wordRu.put(536,"чувство");
        wordRu.put(537,"веселье");
        wordRu.put(538,"радость");
        wordRu.put(539,"страх; бояться");
        wordRu.put(540,"печаль");
        wordRu.put(541,"страсть, страстность");
        wordRu.put(542,"удовольствие");
        wordRu.put(543,"счастье");
        wordRu.put(544,"мир (покой)");
        wordRu.put(545,"любовь; любить");
        wordRu.put(546,"ненависть; ненавидеть");
        wordRu.put(547,"мир (планета)");
        wordRu.put(548,"душа");
        wordRu.put(549,"жизнь");
        wordRu.put(550,"знание");
        wordRu.put(551,"задача, задание");
        wordRu.put(552,"упражнение; упражняться; осуществлять");
        wordRu.put(553,"удача");
        wordRu.put(554,"проблема");
        wordRu.put(555,"(благоприятная) возможность");
        wordRu.put(556,"способность");
        wordRu.put(557,"красота; красавица");
        wordRu.put(558,"опасность");
        wordRu.put(559,"опыт, переживание");
        wordRu.put(560,"память; воспоминание");
        wordRu.put(561,"польза, выгода; приносить (извлекать) пользу");
        wordRu.put(562,"преимущество");
        wordRu.put(563,"прибыль, доход; польза, выгода; извлекать пользу, выгоду");
        wordRu.put(564,"привычка");
        wordRu.put(565,"причина; размышлять");
        wordRu.put(566,"(по)следствие");
        wordRu.put(567,"значение, смысл");
        wordRu.put(568,"средство, способ");
        wordRu.put(569,"усилие");
        wordRu.put(570,"успех; успешный человек");
        wordRu.put(571,"цель; гол");
        wordRu.put(572,"чудо");
        wordRu.put(573,"наука");
        wordRu.put(574,"язык");
        wordRu.put(575,"слово");
        wordRu.put(576,"огонь; пожар; стрелять");
        wordRu.put(577,"случай; дело; чехол");
        wordRu.put(578,"обстоятельство");
        wordRu.put(579,"мысль");
        wordRu.put(580,"выбор");
        wordRu.put(581,"разрешение; разрешать");
        wordRu.put(582,"доставка; поставка");
        wordRu.put(583,"достижение");
        wordRu.put(584,"обязанность; дежурный");
        wordRu.put(585,"задержка, промедление, отсрочка; откладывать, задерживать, промедлять");
        wordRu.put(586,"отношение");
        wordRu.put(587,"оценка, отметка, знак; отметить");
        wordRu.put(588,"ошибка");
        wordRu.put(589,"поведение");
        wordRu.put(590,"приглашение");
        wordRu.put(591,"развитие");
        wordRu.put(592,"решение, принятие решения");
        wordRu.put(593,"решение; раствор");
        wordRu.put(594,"совет");
        wordRu.put(595,"соглашение; согласие; договор");
        wordRu.put(596,"список; перечислять");
        wordRu.put(597,"спор; аргумент");
        wordRu.put(598,"тест, испытание; тестировать, испытывать");
        wordRu.put(599,"шаг; ступать");
        wordRu.put(600,"кусок; часть; пьеса");
        wordRu.put(601,"область, сфера, район; площадь (фигуры)");
        wordRu.put(602,"пара");
        wordRu.put(603,"пара; чета");
        wordRu.put(604,"поверхность; всплывать");
        wordRu.put(605,"беспорядок; привести в беспорядок");
        wordRu.put(606,"вопрос");
        wordRu.put(607,"что; какой");
        wordRu.put(608,"кто");
        wordRu.put(609,"где; куда");
        wordRu.put(610,"как");
        wordRu.put(611,"почему, зачем");
        wordRu.put(612,"когда");
        wordRu.put(613,"сколько (+ слово во множественном числе)");
        wordRu.put(614,"сколько (+ слово в единственном числе)");
        wordRu.put(615,"я");
        wordRu.put(616,"ты; вы; Вы");
        wordRu.put(617,"он");
        wordRu.put(618,"она;");
        wordRu.put(619,"оно");
        wordRu.put(620,"мы");
        wordRu.put(621,"они");
        wordRu.put(622,"мой");
        wordRu.put(623,"твой; ваш");
        wordRu.put(624,"его (одуш.)");
        wordRu.put(625,"её");
        wordRu.put(626,"его (неодуш.)");
        wordRu.put(627,"наш");
        wordRu.put(628,"их");
        wordRu.put(629,"из");
        wordRu.put(630,"передает род. падеж");
        wordRu.put(631,"к; в (куда)");
        wordRu.put(632,"в (где)");
        wordRu.put(633,"на");
        wordRu.put(634,"под");
        wordRu.put(635,"позади");
        wordRu.put(636,"с");
        wordRu.put(637,"без");
        wordRu.put(638,"перед");
        wordRu.put(639,"до");
        wordRu.put(640,"после");
        wordRu.put(641,"между");
        wordRu.put(642,"возле, около; близко");
        wordRu.put(643,"для; в течение; на (такое-то время)");
        wordRu.put(644,"с (такого-то времени и поныне)");
        wordRu.put(645,"во время");
        wordRu.put(646,"вокруг");
        wordRu.put(647,"из-за");
        wordRu.put(648,"о; около, приблизительно");
        wordRu.put(649,"против");
        wordRu.put(650,"среди");
        wordRu.put(651,"через");
        wordRu.put(652,"(километров) в (час)");
        wordRu.put(653,"над, выше");
        wordRu.put(654,"под, ниже");
        wordRu.put(655,"число; количество; номер");
        wordRu.put(656,"одиннадцать");
        wordRu.put(657,"двенадцать");
        wordRu.put(658,"тринадцать");
        wordRu.put(659,"четырнадцать");
        wordRu.put(660,"пятнадцать");
        wordRu.put(661,"шестнадцать");
        wordRu.put(662,"семнадцать");
        wordRu.put(663,"восемнадцать");
        wordRu.put(664,"девятнадцать");
        wordRu.put(665,"двадцать");
        wordRu.put(666,"тридцать");
        wordRu.put(667,"сорок");
        wordRu.put(668,"пятьдесят");
        wordRu.put(669,"шестьдесят");
        wordRu.put(670,"семьдесят");
        wordRu.put(671,"восемьдесят");
        wordRu.put(672,"девяносто");
        wordRu.put(673,"сто");
        wordRu.put(674,"тысяча");
        wordRu.put(675,"первый; сначала");
        wordRu.put(676,"второй; секунда");
        wordRu.put(677,"третий");
        wordRu.put(678,"четвертый");
        wordRu.put(679,"пятый");
        wordRu.put(680,"цвет");
        wordRu.put(681,"старый");
        wordRu.put(682,"молодой");
        wordRu.put(683,"новый");
        wordRu.put(684,"большой");
        wordRu.put(685,"большой, просторный");
        wordRu.put(686,"огромный");
        wordRu.put(687,"маленький");
        wordRu.put(688,"толстый, жирный; жир");
        wordRu.put(689,"тонкий, стройный");
        wordRu.put(690,"толстый; густой");
        wordRu.put(691,"тонкий");
        wordRu.put(692,"голодный");
        wordRu.put(693,"сытый; полный");
        wordRu.put(694,"хороший; добрый");
        wordRu.put(695,"отличный, превосходный, великолепный");
        wordRu.put(696,"удивительный");
        wordRu.put(697,"прекрасный; прекрасно; утонченный; штраф; штрафовать");
        wordRu.put(698,"плохой");
        wordRu.put(699,"ужасный");
        wordRu.put(700,"противный");
        wordRu.put(701,"ранний; рано");
        wordRu.put(702,"поздний; поздно");
        wordRu.put(703,"последний, прошлый");
        wordRu.put(704,"следующий");
        wordRu.put(705,"свободный; бесплатный");
        wordRu.put(706,"занятый");
        wordRu.put(707,"жаркий; горячий; острый (по вкусу); жарко; горячо");
        wordRu.put(708,"тёплый; тепло");
        wordRu.put(709,"холодный; холодно; холод; простуда");
        wordRu.put(710,"прохладный; прохладно; круто; охлаждать(ся)");
        wordRu.put(711,"острый (по вкусу)");
        wordRu.put(712,"острый (не тупой)");
        wordRu.put(713,"тупой (нож, человек)");
        wordRu.put(714,"глупый");
        wordRu.put(715,"умный");
        wordRu.put(716,"умный; нарядный");
        wordRu.put(717,"красивый, хороший, приятный");
        wordRu.put(718,"красивая (о женщине)");
        wordRu.put(719,"красивый (о мужчине)");
        wordRu.put(720,"привлекательный");
        wordRu.put(721,"симпатичный; довольно");
        wordRu.put(722,"уродливый, безобразный");
        wordRu.put(723,"высокий");
        wordRu.put(724,"высокий (о росте)");
        wordRu.put(725,"короткий; низкий (о росте)");
        wordRu.put(726,"низкий; низко");
        wordRu.put(727,"длинный; долгий");
        wordRu.put(728,"тяжёлый");
        wordRu.put(729,"лёгкий; светлый; свет");
        wordRu.put(730,"трудный, тяжелый");
        wordRu.put(731,"легкий, нетрудный");
        wordRu.put(732,"простой");
        wordRu.put(733,"тёмный");
        wordRu.put(734,"дорогой (по цене)");
        wordRu.put(735,"дорогой, милый");
        wordRu.put(736,"дешёвый");
        wordRu.put(737,"бедный; плохой");
        wordRu.put(738,"богатый");
        wordRu.put(739,"прямой; прямо");
        wordRu.put(740,"левый; cлева; налево");
        wordRu.put(741,"правый; правильный; справа; направо; право; прямо (напр., прямо сейчас)");
        wordRu.put(742,"неправильный");
        wordRu.put(743,"быстрый, быстро");
        wordRu.put(744,"быстрый, скорый");
        wordRu.put(745,"медленный");
        wordRu.put(746,"мягкий; нежный");
        wordRu.put(747,"твёрдый; жесткий; трудный; усердно, упорно");
        wordRu.put(748,"печальный");
        wordRu.put(749,"радостный");
        wordRu.put(750,"счастливый");
        wordRu.put(751,"веселый");
        wordRu.put(752,"добрый; вид, тип");
        wordRu.put(753,"сердитый");
        wordRu.put(754,"злой; зло");
        wordRu.put(755,"вежливый");
        wordRu.put(756,"грубый");
        wordRu.put(757,"нежный");
        wordRu.put(758,"смелый");
        wordRu.put(759,"трусливый; трус");
        wordRu.put(760,"застенчивый");
        wordRu.put(761,"трудолюбивый, прилежный");
        wordRu.put(762,"ленивый");
        wordRu.put(763,"полезный");
        wordRu.put(764,"бесполезный");
        wordRu.put(765,"сильный; крепкий");
        wordRu.put(766,"слабый");
        wordRu.put(767,"громкий");
        wordRu.put(768,"шумный");
        wordRu.put(769,"тихий");
        wordRu.put(770,"спокойный; спокойствие; успокаивать");
        wordRu.put(771,"узкий");
        wordRu.put(772,"широкий");
        wordRu.put(773,"чистый; чистить, прибираться");
        wordRu.put(774,"грязный");
        wordRu.put(775,"усталый");
        wordRu.put(776,"честный");
        wordRu.put(777,"удобный, комфортабельный, уютный");
        wordRu.put(778,"странный; чужой; незнакомый");
        wordRu.put(779,"странный");
        wordRu.put(780,"собственный; владеть");
        wordRu.put(781,"вкусный");
        wordRu.put(782,"очень вкусный");
        wordRu.put(783,"горький");
        wordRu.put(784,"кислый");
        wordRu.put(785,"соленый");
        wordRu.put(786,"готовый");
        wordRu.put(787,"внимательный; осторожный");
        wordRu.put(788,"основной, главный");
        wordRu.put(789,"способный");
        wordRu.put(790,"необходимый");
        wordRu.put(791,"важный");
        wordRu.put(792,"уверенный");
        wordRu.put(793,"в хорошей форме; подходить, соответствовать");
        wordRu.put(794,"лучше; более хороший");
        wordRu.put(795,"лучший");
        wordRu.put(796,"хуже; более плохой");
        wordRu.put(797,"худший");
        wordRu.put(798,"больше (по количеству); более; еще (больше)");
        wordRu.put(799,"наибольший; больше всего; большинство");
        wordRu.put(800,"меньше (по количеству); менее");
        wordRu.put(801,"наименьший; наименее; меньше всего");
        wordRu.put(802,"иногда");
        wordRu.put(803,"никогда");
        wordRu.put(804,"редко");
        wordRu.put(805,"обычно");
        wordRu.put(806,"часто");
        wordRu.put(807,"всегда");
        wordRu.put(808,"скоро");
        wordRu.put(809,"недавно");
        wordRu.put(810,"хорошо; колодец");
        wordRu.put(811,"далеко");
        wordRu.put(812,"точно");
        wordRu.put(813,"вероятно");
        wordRu.put(814,"может быть");
        wordRu.put(815,"возможно, может быть");
        wordRu.put(816,"действительно, правда?");
        wordRu.put(817,"конечно!");
        wordRu.put(818,"конечно, безусловно");
        wordRu.put(819,"очевидно");
        wordRu.put(820,"особенно");
        wordRu.put(821,"да");
        wordRu.put(822,"нет");
        wordRu.put(823,"не");
        wordRu.put(824,"этот");
        wordRu.put(825,"тот; что (союз); который");
        wordRu.put(826,"эти");
        wordRu.put(827,"те");
        wordRu.put(828,"и");
        wordRu.put(829,"или");
        wordRu.put(830,"но");
        wordRu.put(831,"однако");
        wordRu.put(832,"потому что, так как");
        wordRu.put(833,"если; ли");
        wordRu.put(834,"хотя");
        wordRu.put(835," быть, являться");
        wordRu.put(836,"делать (действовать)");
        wordRu.put(837,"иметь");
        wordRu.put(838,"мочь (быть в состоянии)");
        wordRu.put(839,"мочь (иметь разрешение)");
        wordRu.put(840,"идти; ехать; уходить; уезжать");
        wordRu.put(841,"находить");
        wordRu.put(842,"держать");
        wordRu.put(843,"стоять; стенд  ");
        wordRu.put(844,"сидеть  ");
        wordRu.put(845,"слышать  ");
        wordRu.put(846,"побеждать  ");
        wordRu.put(847,"получать; добираться; становиться");
        wordRu.put(848,"делать (изготовлять)  ");
        wordRu.put(849,"приходить, приезжать  ");
        wordRu.put(850,"становиться  ");
        wordRu.put(851,"бежать  ");
        wordRu.put(852,"видеть  ");
        wordRu.put(853,"писать");
        wordRu.put(854,"падать");
        wordRu.put(855,"носить (одежду);");
        wordRu.put(856,"брать  ");
        wordRu.put(857,"давать; дарить");
        wordRu.put(858,"прощать  ");
        wordRu.put(859,"забывать  ");
        wordRu.put(860,"кушать");
        wordRu.put(861,"лежать; лгать; ложь");
        wordRu.put(862,"вести  ");
        wordRu.put(863,"кормить");
        wordRu.put(864,"сказать  ");
        wordRu.put(865,"платить");
        wordRu.put(866,"класть; накрывать (на стол)");
        wordRu.put(867,"пить  ");
        wordRu.put(868,"плавать");
        wordRu.put(869,"петь  ");
        wordRu.put(870,"начинать  ");
        wordRu.put(871,"звонить (в звонок), звенеть; кольцо");
        wordRu.put(872,"тонуть; опускаться; погружаться; раковина  ");
        wordRu.put(873,"вонять; вонь  ");
        wordRu.put(874,"летать; муха  ");
        wordRu.put(875,"знать  ");
        wordRu.put(876,"рисовать, чертить; тащить, тянуть  ");
        wordRu.put(877,"кидать, бросать");
        wordRu.put(878,"расти, выращивать  ");
        wordRu.put(879,"дуть; взрывать; удар");
        wordRu.put(880,"разговаривать");
        wordRu.put(881,"выбирать  ");
        wordRu.put(882,"будить  ");
        wordRu.put(883,"ломать  ");
        wordRu.put(884,"показывать  ");
        wordRu.put(885,"резать  ");
        wordRu.put(886,"помещать, ставить, класть");
        wordRu.put(887,"стоить  ");
        wordRu.put(888,"позволять");
        wordRu.put(889,"закрывать");
        wordRu.put(890,"ударять  ");
        wordRu.put(891,"читать  ");
        wordRu.put(892,"посылать  ");
        wordRu.put(893,"проводить (время); тратить");
        wordRu.put(894,"одолжить");
        wordRu.put(895,"строить  ");
        wordRu.put(896,"чувствовать  ");
        wordRu.put(897,"встречать  ");
        wordRu.put(898,"спать  ");
        wordRu.put(899,"хранить, держать");
        wordRu.put(900,"покидать; оставлять; уходить; уезжать");
        wordRu.put(901,"покупать  ");
        wordRu.put(902,"приносить, привозить  ");
        wordRu.put(903,"учить, обучать");
        wordRu.put(904,"думать  ");
        wordRu.put(905,"бороться, драться; борьба, драка  ");
        wordRu.put(906,"ловить; подхватить (болезнь)");
        wordRu.put(907,"быть должным");
        wordRu.put(908,"быть должным (следует)");
        wordRu.put(909,"для образования буд. времени");
        wordRu.put(910,"бояться");
        wordRu.put(911,"интересоваться");
        wordRu.put(912,"удивляться");
        wordRu.put(913,"быть должным, вынужденным");
        wordRu.put(914,"вставать");
        wordRu.put(915,"надевать");
        wordRu.put(916,"снимать (одежду)");
        wordRu.put(917,"жить");
        wordRu.put(918,"работать; работа");
        wordRu.put(919,"смотреть; наблюдать; наручные часы");
        wordRu.put(920,"мыть, cтирать");
        wordRu.put(921,"брить");
        wordRu.put(922,"пытаться, пробовать; попытка");
        wordRu.put(923,"праздновать");
        wordRu.put(924,"улыбаться; улыбка");
        wordRu.put(925,"смеяться");
        wordRu.put(926,"плакать, кричать; плач, крик");
        wordRu.put(927,"учить(ся)");
        wordRu.put(928,"учиться (в вузе); изучать; изучение");
        wordRu.put(929,"(из)менять; переодеваться; изменение; сдача, мелочь");
        wordRu.put(930,"слушать");
        wordRu.put(931,"закрывать");
        wordRu.put(932,"открывать; открытый");
        wordRu.put(933,"танцевать");
        wordRu.put(934,"спрашивать; просить");
        wordRu.put(935,"отвечать; ответ");
        wordRu.put(936,"собирать");
        wordRu.put(937,"хотеть");
        wordRu.put(938,"нравиться, любить; подобно, как");
        wordRu.put(939,"варить; готовить");
        wordRu.put(940,"печь");
        wordRu.put(941,"пахнуть; нюхать; запах; нюх");
        wordRu.put(942,"ждать");
        wordRu.put(943,"ожидать");
        wordRu.put(944,"благодарить");
        wordRu.put(945,"играть; спектакль, пьеса");
        wordRu.put(946,"звать; звонить");
        wordRu.put(947,"гулять; идти пешком; прогулка");
        wordRu.put(948,"курить; дым");
        wordRu.put(949,"желать; желание");
        wordRu.put(950,"извинять; извинение; отговорка");
        wordRu.put(951,"кричать; крик");
        wordRu.put(952,"мечтать; видеть сон; мечта; сон");
        wordRu.put(953,"надеяться; надежда");
        wordRu.put(954,"(за)помнить; вспомнить");
        wordRu.put(955,"напоминать");
        wordRu.put(956,"наслаждаться, нравиться");
        wordRu.put(957,"нести");
        wordRu.put(958,"объяснять");
        wordRu.put(959,"оставаться; останавливаться (в гостинице)");
        wordRu.put(960,"отдыхать; отдых; остальные/ое");
        wordRu.put(961,"повернуть; поворот; очередь, черед");
        wordRu.put(962,"поднимать(ся); лифт");
        wordRu.put(963,"верить, полагать");
        wordRu.put(964,"получать");
        wordRu.put(965,"помогать; помощь");
        wordRu.put(966,"заказывать; приказывать; заказ; приказ; порядок");
        wordRu.put(967,"посещать; посещение, визит");
        wordRu.put(968,"проверять; проверка; чек");
        wordRu.put(969,"прыгать; прыжок");
        wordRu.put(970,"путешествовать; путешествие");
        wordRu.put(971,"разговаривать; разговор");
        wordRu.put(972,"решать, принимать решение");
        wordRu.put(973,"решать (проблему); растворять");
        wordRu.put(974,"ронять; падение, снижение");
        wordRu.put(975,"соглашаться");
        wordRu.put(976,"спасать; сохранять; экономить");
        wordRu.put(977,"спорить");
        wordRu.put(978,"считать, подсчитывать");
        wordRu.put(979,"удивлять; удивление; сюрприз");
        wordRu.put(980,"беспокоить(ся); беспокойство");
        wordRu.put(981,"шутить; шутка");
        wordRu.put(982,"двигать(ся); переезжать; движение");
        wordRu.put(983,"соответствовать, подходить; матч; спичка");
        wordRu.put(984,"умирать");
        wordRu.put(985,"влиять; влияние; воздействие");
        wordRu.put(986,"поддерживать; поддержка");
        wordRu.put(987,"описывать");
        wordRu.put(988,"наказывать");
        wordRu.put(989,"намереваться");
        wordRu.put(990,"жаловаться");
        wordRu.put(991,"избегать");
        wordRu.put(992,"возвращать(ся); возврат, возвращение");
        wordRu.put(993,"беспокоить, мешать");
        wordRu.put(994,"обеспечивать");
        wordRu.put(995,"предлагать; предложение");
        wordRu.put(996,"представлять, знакомить");
        wordRu.put(997,"убеждать");
        wordRu.put(998,"одобрять");
        wordRu.put(999,"ценить; быть признательным");

        return wordRu;
    }
}